### ISSUE TITLE
Get data tests to work on dev machines

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1004]
Extract all connection string(s) into app.config and make data source same for all (i.e (local)\SQLExpress, or \\SQLExpress) so that tests can be run locally (on dev machine)

**Comment by rockfordlhotka** [comment]
@itgoran are you going to be able to do this in the near future?

**Comment by itgoran** [comment]
@rockfordlhotka 
I will my best to find time next week
