### ISSUE TITLE
any sample available for HTTPProxy implementation  .netstandard /.netcore using csla 4.8.1

### ISSUE THREAD

**Issue by Meenakshichawla** [MarimerLLC/csla#1014]
since, support of WCFProxy and WCFPortal is not anymore supported in csla 4.8.1. is there any sample available implementing HTTPProxy and its associated dataportal targeting .netcore/.netstandard ?

**Comment by rockfordlhotka** [comment]
Please direct this sort of question to the forum: https://github.com/marimerllc/cslaforum
