### ISSUE TITLE
Async DataPortal Client proxy Calls to ASPNET Core App Server Controller

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/csla#1047]
Why all Dataportal client calls to HTTPPortalController in ASPNET Core App Server async by default? All the samples shown use async Dataportal CRUD methods to interact with controller. 

Is there a way we can use synchronous calls with ASPNET Core app server ? If yes, kindly provide a pointer demonstrating the same

**Comment by rockfordlhotka** [comment]
Please direct support questions to the forum at https://github.com/marimerllc/cslaforum
