### ISSUE TITLE
Make ApplicationContext an instance type that supports dependency injection

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1068]
As of version 4.9 CSLA's config system supports both `System.Configuration` and `Microsoft.Extensions.Configuration`. The values do all funnel into a static `AppSettings` dictionary and they are still exposed by `ApplicationContext`. 

However, this was a major step toward an abstraction that could allow CSLA itself to stop using `ApplicationContext`, and instead use the new model we created to mitigate differences between the old .NET and new .NET Core config subsystems.

If the new config scheme is provider-based behind the scenes, then the runtime provider could still use a static dictionary, but for testing scenarios it could use an instance-based dictionary or object graph.

It might also be possible to make this _not_ be a breaking change by still supporting `ApplicationContext` for legacy code, even while CSLA itself would use this new model.

**Comment by rockfordlhotka** [comment]
See #2038 for how this change needs to address some SSB concerns.

**Comment by rockfordlhotka** [comment]
Spent some time last night exploring the idea of making `ApplicationContext` into an injectable instance rather than a static type. Turns out to be really hard - very likely not worth the effort.

The big problem is that there are quite a number of reflection helpers in `Csla.Reflection` that rely on configuration options, and you can't inject an instance into a static method.

**Comment by rockfordlhotka** [comment]
OK, now I'm remembering why I closed this the first time around. This is _really frickin hard_!!

Mostly because things like `BusinessBase` use `ApplicationContext.User`. Which now implies that all business types have a constructor that accepts `ApplicationContext`.

That means that _all of your types_ need to switch from a default/empty constructor to one more like this:

```c#
  public PersonEdit(ApplicationContext applicationContext)
    : base(applicationContext)
  { }
```

And that is a massive breaking change - especially for apps that have hundreds or thousands of business classes.

**Comment by rockfordlhotka** [comment]
I might have a solution for the original complexity:

> The big problem is that there are quite a number of reflection helpers in Csla.Reflection that rely on configuration options, and you can't inject an instance into a static method.

But the reality is that the `User` and context (like `LocalContext`) values need to be contained in an instance, and thus must be injected _into every type that uses them_, which would include all business types.

**Comment by ushenkodmitry** [comment]
Hello @rockfordlhotka 
What about property injection instead of constructor injection?

**Comment by rockfordlhotka** [comment]
@ushenkodmitry that's what I'm experimenting with right now. It is a big change, not least because (afaik) the standard Microsoft DI framework doesn't handle that case. But that's ok, because most objects in CSLA are created through a `CreateInstance` helper anyway, and I've made that method check for an `IUseApplicationContext` interface.

```c#
    internal object CreateInstance(Type objectType)
    {
      object result;
      if (CurrentServiceProvider != null)
        result = ActivatorUtilities.CreateInstance(CurrentServiceProvider, objectType);
      else
        result = Activator.CreateInstance(objectType);
      if (result is IUseApplicationContext tmp)
      {
        tmp.ApplicationContext = this;
      }
      return result;
    }
```

The end result is that I have a program like this (where `MainApp` was created via DI, and then its `Run` method was invoked:

```c#
  public class MainApp
  {
    public IDataPortal<PersonEdit> personPortal { get; private set; }
    public ApplicationContext ApplicationContext { get; private set; }
    public MainApp(IDataPortal<PersonEdit> dataPortal, ApplicationContext applicationContext)
    {
      personPortal = dataPortal;
      ApplicationContext = applicationContext;
    }

    public async Task Run()
    {
      try
      {
        var person = await personPortal.CreateAsync("Andrea");
        Console.WriteLine($"Name {person.Name}, IsNew {person.IsNew}");
        person = await personPortal.FetchAsync("Andrea");
        Console.WriteLine($"Name {person.Name}, IsNew {person.IsNew}");
        person = await personPortal.CreateAsync("Andrea");
        person.Name = "Ali";
        await person.SaveAndMergeAsync();
        Console.WriteLine($"Name {person.Name}, IsNew {person.IsNew}");
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.ToString());
        throw;
      }
    }
  }
```

The underlying `PersonEdit` class is normal - no modifications from CSLA 5.

It does mean that your actual app, at a minimum, looks like this:

```c#
  class Program
  {
    static async Task Main(string[] args)
    {
      ServiceCollection services = new();
      services.AddTransient<MainApp>();
      services.AddCsla();
      var provider = services.BuildServiceProvider();

      try
      {
        var app = provider.GetRequiredService<MainApp>();
        await app.Run();
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.ToString());
        throw;
      }
    }
  }
```

For aspnetcore or Blazor this is already what you do, so no big deal.

For WPF, Xamarin/Maui, WinForms, or console, it does at a slight burden - but I'd already committed to _requiring_ DI initialization in CSLA 6, so this doesn't bother me.

---

Where I'm at right now though...

I got the _local_ data portal working in the most basic configuration. I strongly suspect I've broken a whole bunch of non-simple scenarios, and I have no idea if a remote data portal works 😉

I do think it likely that the `HttpPortal` will work. The `WcfPortal` might be problematic, because I don't think I can control how the entry point is created or initialized. And maybe CSLA 6 is where we abandon WCF, which wouldn't entirely bother me.
