### ISSUE TITLE
LocalProxy doesn't flow context to async calls correctly (fix in 4.x)

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1084]
This issue is described and fixed in #1072. Ideally the fix would be back-ported to a 4.X release so people don't have to wait for the 5.0 release.

The discussion for this issue is in the forum: https://github.com/MarimerLLC/cslaforum/issues/704

**Comment by kellyethridge** [comment]
I would do this but I'm a Git illiterate. I don't know how to update a past release and all the stuff needed to create a PR for it.

**Comment by rockfordlhotka** [comment]
I appreciate that @kellyethridge - I don't either 😄

**Comment by ProDInfo** [comment]
This change cause a problem with dataportal execute locally in WPF. When I call a BeginRefresh is executed not async and IsBusy it's not refresh in UI.
I can change any configuration on the application or it's a bug?
I don't use remote proxy dataportal
