### ISSUE TITLE
Analyzer: Ensure DP methods return void or Task

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1100]
As discussed in the forum: https://github.com/MarimerLLC/cslaforum/issues/184

Create an analyzer that

1. Warns when a `DataPortal_XYZ` method returns anything other than `void` or `Task`
1. Warns when any code directly invokes a `DataPortal_XYZ` method

For the factory-based data portal models this is the rule

1. Warns when the root data portal methods in an `ObjectFactory` subclass returns anything other than the business object type or Task<botype>

**Comment by JasonBock** [comment]
Some points of clarification:
* Are you saying that the default `DiagnosticSeverity` should be `Warning`?
* The "data portal methods in an `ObjectFactory` subclass" - what are the names of these? Are they like "DataPortal_Fetch"? Or something else? I never use this approach so I don't want to assume here.

**Comment by rockfordlhotka** [comment]
Should these be warnings or errors? I suppose errors maybe?

I haven't used the factory model for so long I'd forgotten how it works. In reviewing the _Data Access_ book it actually appears that the methods must return either the business object type, or `Task<botype>` (and I suppose maybe an interface type?).

**Comment by JasonBock** [comment]
It's up to you. Warning, error, what makes the most sense?

So, for `ObjectFactory`, what are the names for the methods there? I can check that they return a business object or a `Task` of one, I just need to know what their names are.

**Comment by JasonBock** [comment]
The severity should be an error.

Note: this doesn't apply to `ObjectFactory` types as their methods need to return instances of the BO.
