### ISSUE TITLE
Support use of nameof in RegisterProperty

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1101]
As per the forum: https://github.com/MarimerLLC/cslaforum/issues/52

Enable the use of `nameof` instead of a lambda expression when calling `RegisterProperty` to register the metastate field for a property. For example:

```c#
public static readonly PropertyInfo<Guid> IdProperty =
	RegisterProperty(nameof(Id));
public Guid Id
{
	get { return this.GetProperty(IdProperty); }
	set { this.SetProperty(IdProperty, value); }
}
```

**Comment by JasonBock** [comment]
What this will really do is have an overload of `RegisterProperty` that takes just a `string`. What we probably want is some analyzer actions around this. Meaning, if we don't see `nameof` there, we probably want to give a warning of some kind as putting a literal string value isn't that safe.

**Comment by rockfordlhotka** [comment]
And very possibly an analyzer that helps refactor from the lambda scheme (today) to the `nameof` scheme (future)?
