### ISSUE TITLE
Add support for .NET Core 3.0

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1104]
.NET Core 3.0 is slated for release in 2019, and may require some changes to CSLA.

It is unlikely to require changes to CSLA _core_, because Microsoft recommends sticking at the .NET Standard 2.0 level as long as possible. But it will likely require some changes to the ASP.NET Core and EF Core projects.

We do also need to consider what to do regarding .NET Standard 2.1 - whether to add support in the short term, or hold off for a while.

**Comment by dazinator** [comment]
Are there any features / api's added in .NET Standard 2.1 that are valuable enough to warrant targeting it for a build of CSLA? (My best guess would be perhaps there are new serialisers or something you want to leverage?) If not then no need to update, just stay targeting .NET Standard 2.0.

**Comment by dazinator** [comment]
From: https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

> Given many of the API additions in .NET Standard 2.1 require runtime changes in order to be meaningful, .NET Framework 4.8 will remain on .NET Standard 2.0 rather than implement .NET Standard 2.1. .NET Core 3.0 as well as upcoming versions of Xamarin, Mono, and Unity will be updated to implement .NET Standard 2.1.

**Comment by rockfordlhotka** [comment]
Good info @dazinator. No matter what, the support for .NET Framework is stuck at NS2.0.

The big feature of NS2.1 that is interesting is `Span`, which as @JasonBock has pointed out, might be able to speed up MobileFormatter.

The thing is, serializers are pluggable, so it seems to me realistic to think about creating a newer serializer based on `Span` that only works in NS2.1 and .NET Core 3 - leaving all the existing/legacy .NET platforms running as-is.

**Comment by dazinator** [comment]
@rockfordlhotka  it's funny you mention that, I was looking at a span based json serialiser the other day, and had CSLA in mind. Opened an issue for it here: https://github.com/Tornhoof/SpanJson/issues/113

**Comment by rockfordlhotka** [comment]
At this point Microsoft's clear recommendation to stay with .NET Standard 2.0 as long as possible, and the version of CSLA targeting NS20 works with .NET Core 3.

I'm closing this vague issue in favor of actionable issues around specific needs.
