### ISSUE TITLE
Question - IDataPortalFactory injection

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1116]
Hi Rocky,

I have been away from the CSLA world for a while. I've noticed you are progressing well on the .NET Core front.

One thing I noticed was the new `IDataPortalFactory` that can be registered and then injected from an `IServiceProvider`.

Thinking about usage in a .NET Core app, the typical way I'd consume business objects is either A) via a static factory method on the business object itself, i.e `Customer.Get(1)` or..
B) via a specific factory class. I.e `var customer = (ICustomerFactory)factory).Get(1)`.

I am guessing that for scenario A) nothing changes. Static factory methods could of course be refactored to take `IDataPortal<T>` as a parameter if so inclined but then.. that passes the buck to the caller to resolve this first - making consumption less straightforward.

For B) factory classes, I am wondering if we should be injecting `IDataPortal<T>` into them now?

```
public class CustomerFactory : ICustomerFactory
{

  private readonly IDataPortal<Customer> _dataPortal;
  public CustomerFactory(IDataPortal<Customer> dataPortal)
  {
      _dataPortal = dataPortal;
  }

  public Customer GetCustomer(int id)
  {
    var customer = dataPortalFactory. Fetch(id);
    return customer ;
  }
```

I know this won't work right now until CSLA can register a generic resolver for `IDataPortal<T>` , so that we can inject this directly into factories and the like, to save injecting `IDataPortalFactory` and doing the extra `GetPortal<T>` step. Is this the direction you are heading in?

**Comment by rockfordlhotka** [comment]
There's issue #1061 already discussing this issue
