### ISSUE TITLE
"Edit level mismatch in AcceptChanges" Error When Saving BusinessListBase Directly

### ISSUE THREAD

**Issue by Hadronicus** [MarimerLLC/csla#1125]
**Describe the bug**
The changes to serialization and deserialization of edit levels in #1083 have caused a new issue when saving a **BusinessListBase** that is not a child list of another object.

**Version and Platform**
CSLA version: 4.10.0
OS: Windows 10
Platform: WPF

**Code that Fails**
In [BusinessListBase.cs](https://github.com/MarimerLLC/csla/blob/3a1a283fe204234c3a4d8586d00662d0f7715196/Source/Csla.Shared/BusinessListBase.cs#L600):
```c#
private void AcceptChanges(int parentEditLevel)
    {
      if (this.EditLevel - 1 != parentEditLevel)
        throw new UndoException(string.Format(Resources.EditLevelMismatchException, "AcceptChanges"), this.GetType().Name, _parent != null ? _parent.GetType().Name : null, this.EditLevel, parentEditLevel + 1);

      // we are coming up one edit level
      _editLevel -= 1;
      if (_editLevel < 0) _editLevel = 0;

      // cascade the call to all child objects
      foreach (C child in this)
      {
        child.AcceptChanges(_editLevel, false);
        // if item is below its point of addition, lower point of addition
        if (child.EditLevelAdded > _editLevel) child.EditLevelAdded = _editLevel;
      }

      // cascade the call to all deleted child objects
      for (int index = DeletedList.Count - 1; index >= 0; index--)
      {
        C child = DeletedList[index];
        child.AcceptChanges(_editLevel, false);
        // if item is below its point of addition, remove
        if (child.EditLevelAdded > _editLevel)
          DeletedList.RemoveAt(index);
      }
    }
```
This method sets **_editLevel** to 0 any time the current value is < 0. It then calls **AcceptChanges** on each child object in the list. Before the changes in #1083, **_editLevel**  would have typically been greater than or equal to 1 when this method is called on a cloned object when saving from **ViewModelBase**. However, with this change, it will always be 0, which then causes the argument validation on the **AcceptChanges** method for child objects to fail.

**Comment by Hadronicus** [comment]
I believe this issue can be solved by simply changing the order of operations in the **AcceptChanges** method of BusinessListBase. I'm currently looking into creating a unit test and a fix for this issue.

**Comment by pszittyay** [comment]
I am getting the same error "randomly" on a winforms app.

**Edit level mismatch in AcceptChanges**

   en Csla.Core.UndoableBase.AcceptChanges(Int32 parentEditLevel)
   en Csla.Core.UndoableBase.Csla.Core.IUndoableObject.AcceptChanges(Int32 parentEditLevel, Boolean parentBindingEdit)
   en Csla.BusinessBindingListBase`2.AcceptChanges(Int32 parentEditLevel)
   en Csla.BusinessBindingListBase`2.ApplyEdit()
   en Csla.Windows.BindingSourceNode.Apply()

![image](https://user-images.githubusercontent.com/2033373/103022926-aa6b4880-452b-11eb-83c8-00671aa848dd.png)

**Comment by KC7465128305** [comment]
I got the same error pszittyay got "Edit level mismatch in AcceptChanges" when I clone a CSLA object on a WPF application.

CSLA Version = 5.5.2
WPF
.NET 5
