### ISSUE TITLE
Investigate Serialization Refactoring and/or Restructing With Span<T> and/or Pipelines

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#1131]
As CSLA is moving towards 5.0.0, one thought I had is maybe we should look at `MobileFormatter` and see if we can do any perf improvements using either `Span<T>` and/or `System.IO.Pipelines`. I really have no other thoughts about this other than that :). But I'm thinking that some kind of gains can be made with these new approaches.

Also, the last time I dug into the `MobileFormatter` class, it felt....kind of messy. It was hard to navigate around in the methods to get to what I was really looking for. Maybe doing another dive into it, I can quantify specifics around this and go from there.

**Comment by rockfordlhotka** [comment]
Closing due to lack of interest.
