### ISSUE TITLE
Simplify get/set/read/load property helpers: eliminate IPropertyInfo param

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1148]
Using the new `CallingMemberName` attribute it should be possible to provide overloads of the get/set/load/read helper methods (such as `GetProperty`) that don't require an `IPropertyInfo` parameter.

This means (after #1101) a property declaration could look like this:

```c#
public static readonly PropertyInfo<Guid> IdProperty =
	RegisterProperty(nameof(Id));
public Guid Id
{
	get { return this.GetProperty(); }
	set { this.SetProperty(value); }
}
```

The drawback to this change is that a developer _could_ pass a string parameter to the helper methods. @JasonBock is this something that could be prevented via an analyzer?

**Also note:** This is a breaking change because there are existing methods that accept the property name as a string, and those method signatures must be changed so the method name is the last (and now optional) parameter.

I suspect these methods are mostly used _inside_ CSLA, but they are `protected` in scope, so people could be using them directly.

**Comment by ajj7060** [comment]
Don't you need the actual PropertyInfo reference in Csla though anyway to make Csla work?  I thought part of the reason for the PropertyInfos was to avoid reflection for performance reasons and unless I'm missing something you'll need to use the string from the CallingMemberName to find the PropertyInfo field anyway, right?  

What does this buy users, besides not having to specify a single parameter?

**Comment by rockfordlhotka** [comment]
You are correct, this isn't _necessary_, but it is cleanup that I believe is valuable in terms of reducing the API complexity for current and future user.

**Comment by ajj7060** [comment]
Will the existing overloads that take an IPropertyInfo remain?

**Comment by rockfordlhotka** [comment]
Yes, they remain important for scenarios where you are interacting with property values outside the property itself (such as in a rule or object factory).

**Comment by rockfordlhotka** [comment]
I've hit a bit of a snag. Two problems really.

### Problem 1
The compiler can't infer the type parameter for `GetProperty` or `ReadProperty` when a `PropertyInfo<P>` isn't a parameter. In other words
```c#
  get => GetProperty();
```
can't work because `P` is inferred as type `object`, when it needs to be the type of the property.

Two solutions

1. Don't do this whole "eliminate IPropertyInfo parameter" change at all
1. Require the code to provide a value for `P` (such as `get => GetProperty<string>();`)
   1. This would be asymmetric with `SetProperty` where `P` can be inferred

### Problem 2
There's an ambiguous overload issue between these two versions of `SetProperty` (and similar) when the property type (and therefore `P`) is `string`:
```c#
  protected void SetProperty<P>(PropertyInfo<P> propertyInfo, P newValue)
  protected void SetProperty<P>(P newValue, [CallingMemberName]string propertyName = "")
```

Three solutions:

1. Don't do this whole "eliminate IPropertyInfo parameter" change at all
1. Require all _existing_ code to specify the type of `P` (`set => SetProperty<string>(NameProperty, value)`)
1. Name the new "overloads" differently, such as `GetValue`, `SetValue`, `ReadValue`, `LoadValue` to avoid the ambiguity

**Comment by ajj7060** [comment]
For problem #1, I think solution #2 is ok provided GetProperty(PropertyInfo<P>) won't be required to now be GetProperty<string>(PropertyInfo<string>).  

For problem #2, I think solution #2 should be a non-starter TBH.  We have a pretty large codebase, and Csla 5 already contains a number of breaking changes we'll need to deal with.  Solution #2 here would require us to touch thousands of BO classes in addition.  

Solution #3 makes me thing the existing methods should also be named GetValue/SetValue, but that doesn't solve anything the, and we're back to lots of changes to update from 4.X. :-)  But adding the new methods and leaving the ones that take PropertyInfo GetProperty/SetProperty I think works against the goal of this feature, simplifying the API.

So I think that really leaves solution #1, which makes me think solution #1 for problem #1 is the right way to go, to not add confusion to the API.  I also don't think the current API is that complex; if i were to explain how to create properties for Csla business objects, I would compare them to WPF dependency properties, which would help anyone that knows WPF understand the concept Csla is using since they're pretty similar.

**Comment by JasonBock** [comment]
I understand the angst and potential pain around this feature. It's unfortunate that there are a number of overload issues, and there doesn't seem to be simple way around that.

That said, I'm hoping there's some kind of roadmap we can come up with where we *do* land on a place where these methods exist. It's not that big of a deal, but it's an elegant (to me) way to have these properties implemented. Maybe there's a more gentle way to get people that would be broken by this to have a "one-and-done" update to a project/solution so a developer doesn't have to update their code by hand in hundreds, if not thousands, of places.

**Comment by rockfordlhotka** [comment]
I'm frustrated at needing to add the generic type to Get/Read - that (to me) just changes one type of cruft for another type of cruft.

```c#
  get => GetProperty(NameProperty);
  set => SetProperty(NameProperty, value);
```
becomes
```c#
  get => GetProperty<string>();
  set => SetProperty(value);
```
and I don't see a big win, especially given that get/set are now asymmetric.

And really, given the overload issues with set/load, the new syntax would almost certainly involve a new name:
```c#
  get => GetValue<string>();
  set => SetValue(value);
```
Which means the API surface area literally doubles - especially since the versions that take an `IPropertyInfo` can't go away (needed for rules and other scenarios).

**Comment by JasonBock** [comment]
OK, I'm confused. Using a different name actually helps I think because that gets rid of the need for overloading resolution. I don't understand why you'd need a generic for `GetValue` though - is still coming down to only happening for the `string` type?

**Comment by rockfordlhotka** [comment]
The `GetProperty` or `GetValue` issue is that the compiler can't figure out the generic type, so it defaults to `object` - leaving us to either tell it the generic type or cast the resulting value. I also suspect that having `P` be type `object` would break things inside CSLA at runtime - but I haven't even tried that yet because I dislike the dev/compile time situation.

The `SetValue` issue is different. Yes, creating a whole new set of duplicate `Set` methods solves the overload problem, but it does it by doubling the number of `Set` (and `Load`) methods, making the API more complex and confusing that seems wise.

**Comment by rockfordlhotka** [comment]
I'm largely decided on NOT doing this change at this point. I don't see the necessary value to overcome the cost of the change (to me and everyone else).

Speak now or forever hold your peace. ⌚️

**Comment by rockfordlhotka** [comment]
I am choosing to not make this change.
