### ISSUE TITLE
Blazor get server response content-length only 1024 bytes

### ISSUE THREAD

**Issue by kenny2061** [MarimerLLC/csla#1152]
**Describe the bug**
Blazor sample set UseTextSerialization from HttpPortalController, I use fiddler got server response content-length only have 1024 bytes, and the blazor app throw an exception "System.IO.EndOfStreamException: Unable to read beyond the end of the stream. at Csla.DataPortalClient.HttpProxy.Update ...".

I download csla source trace code, I found InvokeTextPortal write response stream have not flush buffer, I add "writer.AutoFlush = true;" before "await writer.WriteAsync( ... );", it work fine.

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: .NET Core

**Code that Fails**

      private async Task InvokeTextPortal(string operation, Stream requestStream, Stream responseStream)
      {
          string requestString;
          using (var reader = new StreamReader(requestStream))
          requestString = await reader.ReadToEndAsync();
          var requestArray = System.Convert.FromBase64String(requestString);
          var requestBuffer = new MemoryStream(requestArray);

          var serializer = new MobileFormatter();
          var result = new HttpResponse();
          HttpErrorInfo errorData = null;
          try
          {
            var request = serializer.Deserialize(requestBuffer);
            result = await CallPortal(operation, request);
          }
          catch (Exception ex)
          {
            errorData = new HttpErrorInfo(ex);
          }
          var portalResult = new HttpResponse { ErrorData = errorData, GlobalContext =  result.GlobalContext, ObjectData = result.ObjectData };

          var responseBuffer = new MemoryStream();
          serializer.Serialize(responseBuffer, portalResult);
          responseBuffer.Position = 0;
          using (var writer = new StreamWriter(responseStream))
          {
            await writer.WriteAsync(System.Convert.ToBase64String(responseBuffer.ToArray()));
          }
       }

**Stack Trace or Exception Detail**
System.IO.EndOfStreamException: Unable to read beyond the end of the stream. at Csla.DataPortalClient.HttpProxy.Update (System.Object obj, Csla.Server.DataPortalContext context, System.Boolean isSync) <0x2fc4ed8 + 0x002b4> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.DataPortal`1[T].DoUpdateAsync (T obj, System.Boolean isSync) <0x2fc37b8 + 0x0091a> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.DataPortal`1[T].UpdateAsync (T obj) <0x2fb2600 + 0x00100> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.DataPortal.UpdateAsync[T] (T obj) <0x2fb1fe8 + 0x000f6> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.BusinessBase`1[T].SaveAsync (System.Boolean forceUpdate, System.Object userState, System.Boolean isSync) <0x2fa3e78 + 0x0021e> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.BusinessBase`1[T].SaveAsync (System.Boolean forceUpdate) <0x2fa3160 + 0x00108> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at Csla.BusinessBase`1[T].SaveAsync () <0x2fa2b48 + 0x000f8> in <6a4c6a28b2e74ee4ba47e4b0a71d39b5>:0 at BlazorApp.Client.Pages.PersonEdit.doupdate () <0x2f41458 + 0x00176> in <f960fcc9afdf424d863ca735ed30a9e2>:0 

**Additional context**

**Comment by rockfordlhotka** [comment]
Thank you @kenny2061 - any chance you can submit a PR with the fix?

**Comment by kenny2061** [comment]
@rockfordlhotka I was download source as zip file, so I has not fork this project can not to send pull request, thank you understand.

**Comment by rockfordlhotka** [comment]
No problem @kenny2061 - as you can see, I applied the suggested code change. For both version 5.0.0 and also 4.10.1 (so it is online now).
