### ISSUE TITLE
Mark all BeginFetch-style methods as obsolete

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1160]
The `BeginFetch` style methods (with associated callback events) came into existence to support Silverlight and other async scenarios back in the 00's before async/await became available.

Nobody should be using that model anymore - they should be using async/await, and therefore methods like `FetchAsync`.

Of course we need to phase out those old methods, so for now they should get the `Obsolete` attribute.

**Comment by GillesBer** [comment]
Hi @rockfordlhotka ,
For the few of us that are still using legacy ViewModel methods, does this issue also marks them as obsolete?
ex: OnRefreshed, OnSaved on addition to BeginRefreh?
I believe those are only useful when used by the obsolete dataportal method.

**Comment by rockfordlhotka** [comment]
@GillesBer just at the moment I have only marked `BeginSave` as obsolete in the viewmodel base class.

You have me thinking though, maybe `BeginRefresh` should be marked obsolete too, and a replacement `RefreshAsync` method added?

**Comment by GillesBer** [comment]
Yes , this would be great to have an upgrade path for our legacy code.


-------- Message d'origine --------
De : Rockford Lhotka <notifications@github.com>
Date : 30/05/2019 22:11 (GMT+01:00)
À : MarimerLLC/csla <csla@noreply.github.com>
Cc : Gilles Beraudo <g.beraudo@castsoftware.com>, Mention <mention@noreply.github.com>
Objet : Re: [MarimerLLC/csla] Mark all BeginFetch-style methods as obsolete (#1160)


@GillesBer<https://github.com/GillesBer> just at the moment I have only marked BeginSave as obsolete in the viewmodel base class.

You have me thinking though, maybe BeginRefresh should be marked obsolete too, and a replacement RefreshAsync method added?
