### ISSUE TITLE
Add option to allow FieldManager.UpdateChildren to ignore IsDirty

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1167]
As per https://github.com/MarimerLLC/cslaforum/issues/755 from @j055

1. Add public `UpdateAll` methods to `ChildDataPortal` to match the existing public `Update` methods
1. Add a parameter to the private `Update` method in `ChildDataPortal` to override the `IsDirty` check as you suggest
1. Add an `UpdateAllChildren` method to `FieldManager` that calls the new `UpdateAll` method in the data portal

**Comment by rockfordlhotka** [comment]
@j055 do you want to add this change to the v4.x branch as well so it goes into 4.11? If not that's fine, but if your need is pressing that would get you the change faster.

**Comment by j055** [comment]
Sorry, I need to fork from 4.x first. Please delete the PR. My head hurts!

**Comment by rockfordlhotka** [comment]
Yeah, this git stuff can be confusing... I only figured out the whole PR-against-a-branch thing recently, but I did add it to the [contributor instructions doc](https://github.com/MarimerLLC/csla/blob/master/docs/csla-github-flow.md).
