### ISSUE TITLE
Consider allowing multiple criteria params to create/fetch/delete methods

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1176]
As per @JasonBock's comment here: https://github.com/MarimerLLC/csla/issues/1102#issuecomment-498063837

It should be realistic to enhance the create/fetch/delete data portal methods to accept a params array instead of a single criteria parameter. This array can be placed in a `MobileList` and transferred to the logical server.

On the server, the [algorithm described here](https://github.com/MarimerLLC/csla/issues/787#issuecomment-498075922) should accommodate multiple criteria members.

What I envision is this.

The client-side data portal will change from having methods like `Create()` and `Create(object criteria)` to `Create(params object[] criteria)`.

1. If no params are provided it is the same as today's "empty" criteria
1. If a `null` or any other value(s) are provided they'll flow to the server, much like a single value flows today

The server-side data portal will change such that it'll attempt to match the server-side data portal methods (old-style or attributed as per #1102) to the list of criteria parameter values (if any). Also, (based on #787) the server-side data portal will use `ServiceProvider` to supply any values attributed for injection.
```c#
  // client-side call
  var obj = await DataPortal.FetchAsync<PersonEdit>(123, "Yu");

  [Serializable]
  public class PersonEdit : BusinessBase<PersonEdit>
  {
    [Fetch]
    private async Task FetchAsync(int id, string name, [FromService]IDalProvider dal)
    { }
  }

**Comment by ajj7060** [comment]
Would this enable a DP method to look something like this?

`private void Create(int customerId, string description, Guid guidForSomeReason) { }`

**Comment by rockfordlhotka** [comment]
Yes. And also
```c#
  var obj = await DataPortal.CreateAsync<CustomerEdit>(123, "description", Guid.NewGuid());
```

**Comment by dazinator** [comment]
More thoughts not saying any of the following is good or bad just exploring. Suppose if no methods can be found with signatures matching the contents of the list then could the following be invoked as a fallback:

```
 void DataPortal_Fetch(MobileList list) { 

}

```

This method could be baked in to csla business objects, and throw a not implemented exception by default - but the developer could override it in derived classes.

It's even feasible you could plugin your own resolver logic?

```
void DataPortal_Fetch(MobileList list)
{
 var loadDelegate = ResolveDelegate(list); // uses your own logic to find a method to invoke with these params..
 loadDelegate.Invoke();
}

**Comment by rockfordlhotka** [comment]
In my [current prototype](https://github.com/rockfordlhotka/csla/blob/1102-dataportal/Source/csla.netcore.test/DataPortal/ServiceProviderMethodCallerTests.cs) I'm able to resolve multiple criteria parameters from a params array, plus DI parameters.

I might end up using a `MobileList` under the covers to transport the client-side params array to the server-side logic. Somehow that arbitrary list of values needs to get serialized/deserialized.

So yeah, I could NOT do all the stuff I'm currently doing, and just support

1. No criteria (as today)
1. Simple/single criteria value (as today)

You can already (today) just pass a `MobileList` as a criteria parameter. The existing implementation in CSLA allows your criteria value to be any serializable type, so `MobileList` is perfectly acceptable. As is `MobileDictionary`, etc.

**Comment by rockfordlhotka** [comment]
What I envision is this.

The client-side data portal will change from having methods like `Create()` and `Create(object criteria)` to `Create(params object[] criteria)`.

1. If no params are provided it is the same as today's "empty" criteria
1. If a 'null' or any other value(s) are provided they'll flow to the server, much like a single value flows today

The server-side data portal will change such that it'll attempt to match the server-side data portal methods (old-style or attributed as per #1102) to the list of criteria parameter values (if any). Also, (based on #787) the server-side data portal will use `ServiceProvider` to supply any values attributed for injection.
```c#
  // client-side call
  var obj = await DataPortal.FetchAsync<PersonEdit>(123, "Yuan");

  [Serializable]
  public class PersonEdit : BusinessBase<PersonEdit>
  {
    [Fetch]
    private async Task FetchAsync(int id, string name, [FromService]IDalProvider dal)
    { }
  }

**Comment by ajj7060** [comment]
Given the discussion in the other thread about supporting DI and flexible data portal method names, I think I like this idea less 😸
