### ISSUE TITLE
Implement Core WCF data portal channel

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1183]
This may be a longer term goal, but over time it appears that [Core WCF](https://github.com/CoreWCF/CoreWCF) will become a viable technology that'll allow .NET Core (and .NET Standard?) code to support a subset of the WCF protocol.

When Code WCF is stable enough, we should create a project/package (`Csla.Channels.Wcf`) that implements a data portal proxy and host.

**Comment by rockfordlhotka** [comment]
They are making progress, so that's good news!

https://corewcf.github.io/blog/2021/07/29/corewcf-0_2_0_release

**Comment by DavidRMaltby** [comment]
I have a need, so if anyone hasn't already begun this work, I will likely take a crack at it.

**Comment by rockfordlhotka** [comment]
@DavidRMaltby sounds great!

You can use the grpc and rabbitmq projects as a template.

**Comment by DavidRMaltby** [comment]
Currently have a blocker for the [NetDataContractSerializer class](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.netdatacontractserializer?view=netframework-4.8&viewFallbackFrom=net-6.0) as there is no .NET Core version of it.  CoreWCF doesn't provide one and the discussion at https://github.com/dotnet/runtime/issues/27763 indicates that they won't persue it either.  I've found is a port of most of it from .NET Framework source at https://github.com/dmitrykolchev/NetDataContractSerializer and it was extended in https://github.com/cklutz/Compat.Runtime.Serialization.  The later even does publish a NuGet package from the work.  Would using that be a non-starter for PR approval here?

**Comment by rockfordlhotka** [comment]
My recommendation would be to use `MobileFormatter` to create a byte array, and have the WCF contract accept/return a byte array - exactly like the `HttpProxy` does.

No need for any WCF specifics _inside_ CSLA or within the byte stream, but enabling the use of WCF features at higher levels (assuming they support WS-* capabilities that you need to use).

**Comment by DavidRMaltby** [comment]
Wonderful.  Thank you sir.  My WCF background is weak and that was exactly the insight that I needed.

**Comment by rockfordlhotka** [comment]
There are some thoughts on implementation in this discussion thread: https://github.com/MarimerLLC/csla/discussions/3448

**Comment by rockfordlhotka** [comment]
Closing due to lack of interest.

**Comment by rockfordlhotka** [comment]
@b-higginbotham - use this issue please
