### ISSUE TITLE
RegisterProperty - Change from string friendlyName to Func<string>

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/csla#1186]
**Is your feature request related to a problem? Please describe.**
With the changes to `RegisterProperty` in #1101, it might be a good time to change from using a string for the `friendlyName` parameter to a `Func<string>`.  This will allow friendly names to be localizable.

This would also allow for an overload which is just `RegisterProperty(string propertyName, string defaultValue)`

**Describe the solution you'd like**
Make the `string friendlyName` parameters in `RegisterProperty` a `Func<string>` instead.

**Describe alternatives you've considered**
I can't think of other ways to do this that would localize the friendly name into rules that are built into Csla.

**Additional context**

**Comment by ajj7060** [comment]
@rockfordlhotka I think this was discussed on the forum sometime back, but I didn't find an issue for it.  Hopefully it was ok to add this; just seems like a good time given the other changes to Registerproperty.

**Comment by rockfordlhotka** [comment]
I'm undecided on this idea. I recommend people use the attributes from `System.ComponentModel.DataAnnotations` to set the friendly name, and there's already an integrated way for the attribute to access resource files for localization.

We absolutely _could_ have overloads like you suggest, but that'd force you to write the code to access the resource file - code that already exists for us all in the attribute.

**Comment by ajj7060** [comment]
Ah, I didn't realize that Csla would pick up the DisplayName attribute already.  So is there any need to have friendlyName in the overload at all then?
