### ISSUE TITLE
'Clear' button on a winform and CslaActionExtender

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/csla#1187]
**Is your feature request related to a problem? Please describe.**
CslaActionExtender provides action types Save, Cancel, Validate  and close for buttons. Recently I needed 'Clear' and 'Refresh' functionality, where 'Clear' clears out the form and Refresh get the object back from DB.
I ended up setting the Clear and Refresh buttons to action type None and providing custom code
For Refresh I used the following pseudo code in the click event.
  myobject = Factorymethodforexistingobject();
   MyActionExtender.ResetActionBehaviors(myobject );
this.Refresh();

For Clear I used the following
   myobject = Factorymethodfornewobject();
MyActionExtender.ResetActionBehaviors(myobject );
this.Refresh();
   
  

**Describe the solution you'd like**
I would like for us to add ActionTypes of 'Clear' and 'Refresh' in the cslaActionExtender Control.

**Describe alternatives you've considered**
  The atlernatives is the code I have mentioned above.

**Additional context**

**Comment by rockfordlhotka** [comment]
That's wonderful @Chicagoan2016!! Yes, that is the file.

I've moved this issue to the csla repo and assigned you, so you should be able to associate any commits with this new issue number as per the [contribution process](https://github.com/MarimerLLC/csla/blob/master/CONTRIBUTING.md).

**Comment by rockfordlhotka** [comment]
@Chicagoan2016 it has been a long time since we chatted - were you able to move forward with this, or is it something you aren't able to work on any longer?

**Comment by rockfordlhotka** [comment]
Closing due to lack of interest.
