### ISSUE TITLE
EditLevel mismatch in BusinessRules class (NS2 only)

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/csla#1191]
Question. I noticed that when using `ViewModelBase.SaveAsync()`, my object is first cloned, and then `ApplyEdit` is called. During `ApplyEdit`, `AcceptChanges` on my root `BusinessListBase` cascades the call to the children.

However, during the cascading `AcceptChanges` call, one of the list `BusinessBase` child object's `BusinessRules` object also gets `AcceptChanges` called on it, which causes "Edit Level mismatch in AcceptChanges." It appears to be because during cloning, `BusinessRules` does not serialize `_stackStack`, causing it to be 0 instead of 1 during `AcceptChanges`.

Line 940 of `BusinessRules` indicates that `OnGetState` can serialize `_stateStack` `#if ANDROID || IOS || NETFX_CORE`, but according to the link [here](https://github.com/MarimerLLC/cslaforum/issues/740), Lhotka indicates that "the only valid compile targets are now .NET Standard 2.0, .NET Framework 4.6.1, 4.5, and 4.0," so i assume that shouldn't be used, but if not, then how will _stateStack be serialized and usable for AcceptChanges after cloning? Should that possibly be `#if (ANDROID || IOS) || NETFX_CORE || NETSTANDARD2_0` instead?

Any help would be appreciated.

Thanks,
Jason

**Comment by rockfordlhotka** [comment]
I'm fixing this in 4.11.1 and 5.0.0

**Comment by GreatBarrier86** [comment]
Great news. Thanks!
