### ISSUE TITLE
Create IAuthorizationContext

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/csla#1194]
**Is your feature request related to a problem? Please describe.**
Simplify unit testing of AuthorizationRule subclasses.  Currently the use of AuthorizationContext means that you need to create the auth rule instance, then create the AuthorizationContext to execute the rule; this makes is more challenging to alter the inputs provided by the context for various scenarios.

**Describe the solution you'd like**
Create an IAuthorizationContext, like the IRuleContext created in #948 to allow for mocking of the instance used in the rule's Execute.

**Describe alternatives you've considered**
As described in the problem description, this can be worked around by writing more testing code and use of `Lazy<T>` to delay building of the AuthorizationContext, but this requires extra code to be written and maintained in the unit tests.

**Comment by ajj7060** [comment]
@rockfordlhotka You can assign this to me; I'm working on a PR now.

**Comment by rockfordlhotka** [comment]
Will this be a breaking change like it was with IRuleContext?

**Comment by rockfordlhotka** [comment]
Hi @ajj7060 - thank you for the PR on this issue, I appreciate it!

I did a code review on the PR and have one requested change - you can see the details in the PR issue itself.

**Comment by ajj7060** [comment]
@rockfordlhotka Yes, it will be a breaking change like IRuleContext.  I'll get the PR fixed, I had been on vacation.
