### ISSUE TITLE
Eliminate use of hardcoded AddObjectAuthorizationRules

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/csla#1209]
**Is your feature request related to a problem? Please describe.**
Adding type-level authorization rules is done by creating a public static void method with the magic name of `AddObjectAuthorizationRules`.  Related to #1102, an attribute could be used mark the method and eliminate the need for a magic name.

**Describe the solution you'd like**
Add an attribute (`ConfigureAuthorizationRules`?) which can mark the method Csla should call to configure per-type auth rules.

If `AddObjectAuthorizationRules` exists, but another method has the attribute, an AmbiguousMatchException could be thrown.  Likewise if more than one method has the attribute.

An analyzer could warn about existing `AddObjectAuthorizationRules` which do not have the attribute, and fix them by adding it.

**Comment by ajj7060** [comment]
Discussing #1102 with a coworker, and she was excited about the feature, and said it'd be nice of `AddObjectAuthorizationRules` could be handled the same way.  Seems like it might be relatively low-hanging fruit, especially once the data portal attributes feature is complete.

**Comment by JasonBock** [comment]
FYI this is something discussed with the Ystari project: https://github.com/MarimerLLC/Ystari/blob/master/docs/rules.md. May want to read that as well.
