### ISSUE TITLE
Add support for Windows Forms in .NET Core 3

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1234]
The `Csla.Windows` project needs a version that supports .NET Core 3 in addition to the existing .NET Framework version.

* Create `Csla.Windows.Core` project (using existing `Csla.Windows` namespace)
* Use a Shared Project to get code into both existing and new projects
* Update NuGet definitions for new package

**Comment by GillesBer** [comment]
Hi @rockfordlhotka , I propose to contribute to this issue.
I have a 2 questions to keep consistency with the existing code.

1. I would propose to name the project: Csla.Windows.NetCoreApp3.0 instead.

The reason behind my proposition is to keep consistency with other .NET Core projects, sur cas CSLA.NetStandard2.0

In the exisinting CSLA.NetStandard2.0, I guess that `NetStandard2.0` was choosen to match the build directory:
`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">`
`    <OutputPath>..\..\Bin\Release\netstandard\</OutputPath>`
`    <DocumentationFile>..\..\Bin\Release\netstandard\netstandard2.0\Csla.xml</DocumentationFile>`
`  </PropertyGroup>`

I noticed that, when using .NET Core:
`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">`
`    <OutputPath>..\..\Bin\Release\netstandard\</OutputPath>`
`    ...`
`  </PropertyGroup>`

Then DLLs are generated in `..\..\Bin\Release\netstandard\netcoreapp3.0`.

2. Regarding the AssemblyInfo.cs
On my local, I used the Csla.NetStandard2.0 as a template:
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.NetStandard2.0/Properties/AssemblyInfo.cs
but I identified it is not consistent with other projects, ex .Net full:
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Net4.6/Properties/AssemblyInfo.cs

Can I push my PR and let you clean the copyrights in another PR?

**Comment by rockfordlhotka** [comment]
@GillesBer 

I agree with your naming, that is correct.

Please go ahead and push your PR and we can discuss specifics once I see what you are proposing.

**Comment by GillesBer** [comment]
I used https://github.com/MarimerLLC/csla/issues/1187#issuecomment-525535344
as a reference to package the NuSpec
