### ISSUE TITLE
Add support for WPF on .NET Core 3

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1235]
The `Csla.Xaml` project needs a version that supports .NET Core 3 in addition to the existing .NET Framework version.

* Create `Csla.Xaml.Core` project (using existing `Csla.Xaml` namespace)
* Use exiting Shared Project to get code into the new project
* Update NuGet definitions for new package

**Comment by GillesBer** [comment]
Hi @rockfordlhotka , I propose to contribute to this issue.
I have a few questions that I put on https://github.com/MarimerLLC/csla/issues/1234 as both issues are very similar;
