### ISSUE TITLE
Review use of service provider in ApplicationContext

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1246]
The `ApplicationContext` can capture a reference to the `IServiceCollection` and/or the resulting `ServiceProvider` instance.

Review how this is done and make sure we aren't leaking that value to the rest of the app. In other words, it should probably be `internal` to CSLA if at all possible.

**Comment by JasonBock** [comment]
As a thought, maybe we don't make this `internal` right away, but write an analyzer to inform/warn/error if developers are using it. There's no code fix for this, but it'll give developers time to get away from using it before it becomes `internal`.

**Comment by rockfordlhotka** [comment]
I'm not worried about backward compat with this, as it is a new feature in CSLA 5.
