### ISSUE TITLE
An instance of analyzer Csla.Analyzers.NNN cannot be created from Csla.Analyzers.dll [5.0.0-r19082803]

### ISSUE THREAD

**Issue by itgoran** [MarimerLLC/csla#1265]
**Describe the bug**
Lots of warning when compiling with CSLA 5.0.0-r1908283

![image](https://user-images.githubusercontent.com/3634279/63951566-455e2a80-ca7e-11e9-95f0-316379a78175.png)

**Version and Platform**
CSLA version: 5.0.0-r1908283
OS: Windows
Platform: WPF, ASP.NET Core

**Code that Fails**
Image attached.

**Stack Trace or Exception Detail**

Csla.Analyzers.FindOperationsWithIncorrectReturnTypesAnalyzer cannot be created from C:\Users\NNN\.nuget\packages\csla\5.0.0-r19082803\analyzers\c#\Csla.Analyzers.dll: Could not load type 'Csla.Analyzers.FindOperationsWithIncorrectReturnTypesAnalyzer' from assembly 'Csla.Analyzers, Version=4.11.2.0, Culture=neutral, PublicKeyToken=null'

**Comment by rockfordlhotka** [comment]
What version of Visual Studio?

**Comment by JasonBock** [comment]
I just tried creating a .NET Core app in VS2019 16.2.3:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Csla" Version="5.0.0-R19082803" />
  </ItemGroup>

</Project>
```
Added a simple business object:
```
[Serializable]
public sealed class Customer
	: BusinessBase<Customer> { }
```
And it built just fine. So....not sure how that issue is occuring

**Comment by rockfordlhotka** [comment]
One thing I found when updating an existing solution to the new NuGet packages is that Visual Studio didn't (at least reliably) unload the old analyzer and load the new one.

In other words, as a solution:

1. I removed all the old NuGet packages
1. Added all the new v5 packages
1. Closed VS
1. Reopened the solution
1. Did a Rebuild All

That seemed to get the new analyzers working.

**Comment by itgoran** [comment]
@rockfordlhotka 
Yes, re-adding new packages and close/open resolved issue.

I'm using VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152
