### ISSUE TITLE
Update Blazor unit tests to use latest CSLA syntax

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#1292]
As detailed in review of PR #1284, update the code in the unit tests project to use the latest CSLA syntax:

Replace use of c=>c.Name lambda with nameof(Name) in RegisterProperty

Use [create] attribute to allow simplification of data portal method names

**Comment by rockfordlhotka** [comment]
@TheCakeMonster are you likely to get to this within the next week?

**Comment by TheCakeMonster** [comment]
Yep, sorry, all done.

I found the other locations in which this older RegisterProperty syntax was used and I think they are intended to be that way - they are in the Basic folder of csla.netcore.test, but use the new syntax in the BasicModern folder. As a result, I left those unchanged.

**Comment by rockfordlhotka** [comment]
Thank you!

Yes, some of the tests intentionally use old syntax or APIs to test for backward compat. @JasonBock has been writing more and more analyzers to encourage folks to modernize their code, so over time it should be possible to get rid of some of those older options.
