### ISSUE TITLE
Enhanced DataPortalT

### ISSUE THREAD

**Issue by dojason** [MarimerLLC/csla#1298]
I think DataPortalT can return other generic types
Like this 
 ` public static PageResult<ProjectList> GetProjectList(GetProjectListInput input)`
`{`
` return DataPortal.Fetch<PageResult<ProjectList>, ProjectList>(input);`
`}`

`public static int DeleteProjectList(string projectIds)`
`{`
`return DataPortal.Delete<int, ProjectList>(projectIds);`
` }`

**Comment by rockfordlhotka** [comment]
Right now the data portal returns a single value from the server to the client, so there is nothing for `DataPortalT` to return except for that single value.

What is the scenario where you would want the data portal to return multiple values?

**Comment by dojason** [comment]
Sometimes the server may return an basic data type，like int、bool、string......
I thkink DataPortal<R,T> can be flexibility.

**Comment by rockfordlhotka** [comment]
The data portal does not have the capability to return simple types. It works against business domain objects only.

I need to understand a business scenario where this would make sense. _Technically_ it is possible of course, but that doesn't mean it has value.

**Comment by dojason** [comment]
Client side
`namespace Com.WlTms.FrameWork.Biz.MinXin`
`{`
` [Csla.Server.ObjectFactory("Com.WlTms.FrameWork.DataAccess.DemoFactory,Com.WlTms.FrameWork.DataAccess")]`
`[Serializable]`
     `public class DemoBusiness : BaseBusiness<DemoBusiness, int>`
`{`
`public static DemoBusiness FindById(int id)`
`{`
     `return DataPortal.Fetch<DemoBusiness>(id);`
` }`

`public static bool ExistsByName(string name)`
`{`
     `return DataPortal.Fetch<bool, DemoBusiness>(name);`
`}`

`public static int FindIdByName(string name)`
`{`
     `var  singleCriteria= new SingleCriteria<string>(name);`
     `return DataPortal.Fetch<int, DemoBusiness>(singleCriteria);`
`}`

`public static PagerInfo<DemoListBusiness> FindByPager(PagerInfo pagerInfo)`
`{`
     `return DataPortal.Fetch<PagerInfo<DemoListBusiness>, DemoBusiness>(pagerInfo);`
`}`
` }`

` [Csla.Server.ObjectFactory("Com.WlTms.FrameWork.DataAccess.DemoListFactory, Com.WlTms.FrameWork.DataAccess")]`
`[Serializable]`
`public class DemoListBusiness : BusinessBindingListBase<DemoListBusiness, DemoBusiness>`
`{`

`}`
`}`

Serve side
`namespace Com.WlTms.FrameWork.DataAccess`
`{`
`public class DemoFactory : BaseObjectFactory`
`{`
` //FindById `
`public DemoBusiness Fetch(int id)`
`{`
`var biz = (DemoBusiness)MethodCaller.CreateInstance(typeof(DemoBusiness));`
`using (BypassPropertyChecks(biz))`
`{`
`biz.id = 100;`
`}`
`MarkOld(biz);`
`return biz;`
` }`

`//ExistsByName`
`public bool Fetch(string name)`
`{`
`return true;`
`}`

`//FindIdByName`
`public int Fetch(SingleCriteria<string> criteria)`
`{`
`return 100;`
`}`

`//FindByPager`
`public PagerInfo<DemoListBusiness> Fetch(PagerInfo pagerInfo)`
`{`
`var records= new PagerInfo<DemoListBusiness>()`
`records.Pager.RecordCount = 500;   //Total 500 records`
`var list = (DemoListBusiness)MethodCaller.CreateInstance(typeof(DemoListBusiness));`
`records.Data = list;   //BusinessData`
` //Todo:Add record to list`
`return records;`
`}`
`}`

`public class DemoListFactory : BaseObjectFactory`
`{`

`}`
`}`

I think it makes the code more flexible.Do you feel it too?

**Comment by ajj7060** [comment]
We usually create command objects for stuff like this, and just have the static factory method return the value which the clients is interested in:

``
public static bool Exists(int id) => DataPortal.Execute(new ExistsCommand(id)).Result;
``

**Comment by dojason** [comment]
In DataPortal.cs
`public static T Fetch<T>()`
`{`
`return (T)Fetch(typeof(T), EmptyCriteria);`
`}`

`public static R Fetch<R, T>()`
`{`
`return (R)Fetch(typeof(T), EmptyCriteria);`
`}`

`public static R Fetch<R,T>(object criteria)`
`{`
`return (R)Fetch(typeof(T), criteria);`
`}`

`public static R Delete<R,T>(object criteria)`
`{`
`return (R)Delete<R>(typeof(T), criteria);`
`}`

**Comment by rockfordlhotka** [comment]
Thank you @dojason - what I can't figure out is what the operations would look like in your business class.

For example, today you have

```c#
  [Fetch]
  private void Fetch(int criteria, IDal dataAccess)
  {
    var data = dataAccess.Get(criteria);
    // load properties from data
  }
```

What would that look like to a business developer?
