### ISSUE TITLE
Should we rename Blazor CslaValidator to BusinessRulesValidator

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#1309]
Should the Csla.Blazor.CslaValidator component be renamed to Csla.Blazor.BusinessRulesValidator?

My thoughts behind the suggestion:

1) Slightly more descriptive
2) It's already within the Csla.Blazor namespace, so Csla is a repeat
3) The new name leaves room for another implementation; my original name suggests this is the only one there will ever be, whereas we might find a need for a different implementation as Blazor matures
4) I have named the Blazor ValidationMessage replacement component BusinessRulesValidationMessages, so it would better fit with that other, related component
5) Somehow feels more professional, although I can't explain why!

Suggestions welcomed.

**Comment by rockfordlhotka** [comment]
Should it just be called `Validator`?

**Comment by TheCakeMonster** [comment]
Oh wow! I didn't even think of that!

It could be, I suppose. Blazor components can be referenced by namespace, so if it ever clashed, people could use the more complex

`<Csla.Blazor.Validator />`

However, is the chance of a clash with another framework sufficient enough that we go for something more specific?

**Comment by TheCakeMonster** [comment]
I mean, I know that the idea that people might use another framework is shocking, but I suppose there's a chance that someone _might_.

Hehehe; tongue definitely in cheek!

**Comment by rockfordlhotka** [comment]
I think relying on the namespace is the best option.

However, another naming option is to follow what we did in XAML and name this thing `PropertyStatus` since it displays status information about a single property.

**Comment by TheCakeMonster** [comment]
Yeah, that's interesting. DataAnnotationsValidator, the one I am replacing, doesn't validate anything either, as such, but simply wires up the validation. The events it wires up are then triggered by the requirement to validate - events from EditContext - and makes use of the DataAnnotations validation system to write the messages to the context, for ValidationMessage to output.

In this case, my initial reaction is that PropertyStatus doesn't feel entirely right either, based on your description. This component isn't associated with a single property. There is one - and only one - instance of this component, and it is used to hook the validation code to the EditContext that is flowed from the parent EditForm component.

**Comment by rockfordlhotka** [comment]
Oh, I misunderstood the purpose of this control then. I thought it was a per-property widget, but it summarizes the info/warn/error info for _all properties_ from the model?

That's sort of what `ObjectStatus` does (or was intended to do) - but I don't know that anyone ever used it, because that's such a poor user experience to have a laundry list of problems that's not displayed near the individual properties that have issues.

**Comment by rockfordlhotka** [comment]
No, it is per-property, right? Now I'm confused...

![image](https://user-images.githubusercontent.com/2333134/65078895-a41f1180-d963-11e9-8568-900f770a155d.png)

**Comment by TheCakeMonster** [comment]
Ah, sorry. Two different components. The per-property one is the latest PR, which I'm still working on. That's about displaying messages - outputting HTML. That's not what this issue is about.

This issue refers to the first component I built. This first component is an entirely non-visible element which is used solely during the initialisation of a page. Its sole responsibility is to link the outermost edit context with the code that will be used to perform validation. This structure is what allows us to swap out the validation code based on the type of validation system in use, be it DataAnnotations, FluentValidation or CSLA BusinessRules whilst still fitting within the overall system of editing that the ASP.NET team have provided.

CslaValidator - the thing I'm questioning - accepts a cascading parameter from the outermost EditForm component and calls an extension method of our own choosing, to wire up some event handlers for the following methods:

ValidateField
ValidateModel

CslaValidator is just involved in _initiating_ the conversation between the topmost EditForm and something else.

In our case, the _extension_ method that CslaValidator calls is in a class which takes responsibility for extracting messages from the CSLA object and placing them into an intermediary message store. This message store is the source from which other components take messages for display, in whatever way they see fit.

In the original DataAnnotations example, the external validation code runs the rules on the model in event handlers for the two methods mentioned above.

To a large extent, this makes less sense in CSLA. CSLA knows the state of all of its rules all of the time - they don't need rerunning - so the external code isn't strictly necessary. However, the (quite big, imo) benefit of of having it anyway, is that we are able to mix and match with other components that people write. This structure allows the built-in ValidationMessage component (which displays errors) to play nicely with CSLA, as well as the EditForm component. EditForm uses the presence of validation messages in the message store to determine that the form is not valid, and run a delegate called OnInvalidSubmit. No messages present and OnValidSubmit runs instead.

We could choose to completely ignore all of the existing infrastructure and do something simpler. However, the danger of that approach, is that third-party vendors seem likely to fit in with it, so we might lose the ability to make use of a wealth of third-party components.

**Comment by rockfordlhotka** [comment]
I rather think it should be called `CslaValidator` and that the other control should be called `CslaValidationMessages`. I think that looks and reads very clearly and avoids ambiguity with existing types and other possible frameworks.

**Comment by TheCakeMonster** [comment]
OK, that makes sense.

There's no change required here then, so I suppose I close this issue and make the changes as part of the other one.
