### ISSUE TITLE
Remove support for .NET 4.0/4.5/4.6, add 4.8

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1313]

**Comment by ajj7060** [comment]
Will you be leaving support for .net 4.7.2?

**Comment by rockfordlhotka** [comment]
@ajj7060 that is up for discussion. My _plan_ was to switch fully to 4.8 and not worry about anything older, but it is true that (as far as I know) it should still be possible to go to 4.7.2 and cover 4.8.

Are you unable to go to 4.8?

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka It's not that we can't go to 4.8, just that it is challenging.  We offer SaaS which is a WinForms client, so before we can move to .net 4.8, we have to get all our customers to install that on all their work stations.  Ideally we're moving to .Net core 3 so we no longer have that concern, but there's a ton of work for us before we can move to .net core as well. 

Not saying that supporting 4.7.2 is necessary in csla 6, I'm just more curious what the plan is so we can figure out our roadmap (we're just updating to Csla 5 now).

**Comment by rockfordlhotka** [comment]
Still need to update from 4.6 to 4.8 (or 4.7.2?)
