### ISSUE TITLE
Csla.Wpf 5.0 not work with net core 3.0

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#1337]
I create anew wpf project with netcoreapp3.0
When I try to instal Csla.Wpf nuget package always show this error:

NU1101: No se encuentra el paquete Microsoft.WindowsDesktop.App.WPF. No existe ningún paquete con este id. en los orígenes: nuget.org
NU1102: No se encuentra el paquete Microsoft.NETCore.App con la versión (>= 3.0.0)
  - Versiones encontradas en nuget.org: 76 [ versión más cercana: 3.0.0-preview8-28405-07 ]
Error al restaurar el paquete. Revirtiendo los cambios del paquete para 'WpfApp1'.

How I install the Csla.Wpf 5.0 in a net core 3.0 project?

Very thanks

**Comment by GillesBer** [comment]
Yes, I reproduce the issue on my side with Csla.Wpf (it works well on Csla.Windows.Forms).
@rockfordlhotka : I can do a PR to fix it with https://github.com/GillesBer/csla/pull/new/pr/wpf_nuget

**Comment by rockfordlhotka** [comment]
For my reference, here's the English translation of the errors:

```
NU1101: Microsoft.WindowsDesktop.App.WPF package not found. There is no package with this ID. in the origins: nuget.org
NU1102: Unable to find the Microsoft.NETCore.App package with version (> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

Versions found in nuget.org: 76 [ nearest version: 3.0.0-preview8-28405-07 ]
Failed to restore the package. Reverting package changes to 'WpfApp1'.
```

**Comment by rockfordlhotka** [comment]
It looks like maybe Microsoft has not yet released a 3.0 version of the WPF library, and they are still on a preview?
