### ISSUE TITLE
Csla Blazor Example is including DataAccess.dll on the client

### ISSUE THREAD

**Issue by drakeforte5** [MarimerLLC/csla#1350]
Not sure if this is a known issue but the Csla Blazor Example is including DataAccess.dll on the client.  Run the sample and watch Network tab of the browser.  DataAccess.dll is listed as a file that was downloaded on the client.

Any database-related libraries should not be shipped to the client as was the convention when deploying thick client applications.

**Comment by drakeforte5** [comment]
I suppose the solution to this is create partial classes and create two BlazorExample.Shared libraries with the same namespace.  One for the BlazorExample.Server with the DataPortal.XXX methods and one for BlazorExample.Client.

**Comment by rockfordlhotka** [comment]
Thanks for reporting this.

I too often use the samples as demos, and one of the demos I frequently do is showing how easy it is to switch between local and remote data portal configurations.

A side-effect is that I sometimes accidentally commit things like this, where the DAL is referenced by the client - something (as you note) you'd never do in production with the data portal configured as remote.

There should be no code changes required, just remove the reference on the client and make sure the data portal is configured for remote use.

**Comment by drakeforte5** [comment]
I can't seem to make what you suggested work.  It seems .NET core projects copies dependent libraries in the output.  In the case of BlazorExample.Client it has dependency on BlazorExample.Shared which in turn has a dependency on DataAccess.  When building the projects the BlazorExample.Client automatically generates the DataAccess.dll which is then shipped to the user's browser.  

I was looking if Visual Studio somehow has a way to exclude dependent libraries (DataAccess.dll) in the BlazorExampleClient project but there doesn't seem to be one.
![blazorclient](https://user-images.githubusercontent.com/46607604/65891396-47572a00-e359-11e9-9176-b12810f625b3.PNG)

**Comment by rockfordlhotka** [comment]
Oh, that is interesting! And certainly not ideal.

Though "in real life" your "data access" project is normally just a bunch of interfaces and DTO types, and the real data access implementation is dynamically loaded at runtime on the server (like an EF or Dapper implementation).

So downloading the interface/DTO assembly doesn't seem like a horrible thing. It'll be very small and reveal nothing of value from a security perspective.

**Comment by drakeforte5** [comment]
I suppose it is okay to ship the DAL but this is why I was hinting on having partial classes/libraries.  And then again, I could not make the partials work either because of the .net core project dependencies I mentioned.   I'll keep on stabbing it until I can satisfy my curiosity of not shipping DAL or any servers-side libraries.

**Comment by rockfordlhotka** [comment]
The most direct solution is to do the same thing I've recommended folks do for the past several years - use Shared Projects.

1. Create a Shared Project and put all your business library code in that project
1. Create an ns2 class library _with no code_ and reference the shared project - then reference this from the Blazor.Client project
1. Create a second ns2 class library _with no code_ but _with the exact same assembly name as #2_ - then reference the shared project and reference the DAL - then reference this from the Blazor.Server project

This should solve the issue because two different `BusinessLibrary.dll` assemblies are created _with the exact same code_ but different references.

**Comment by rockfordlhotka** [comment]
Or, if your server is ASP.NET Core 3 you could do the same thing with multitargeting - where your business library project multitargets ns2 and nc3 - resulting in the code being compiled twice, into two different assemblies. And each target can have its own references.

**EITHER WAY** the data portal methods in the business classes need access to the interface/DTO types, or they can't compile.

**Comment by rockfordlhotka** [comment]
Ahh, so that's the final part (I'm distracted, sorry) - you can use _compiler directives_ in either the shared project or multitargeting approach. So you can 

```c#
#if !CLIENT_CODE
  [Create]
  private void Create(int id, IDal dal)
  {
  }
#endif
```

This is how you make the code that interacts with the DAL not even compile into the client-side code.

**Comment by drakeforte5** [comment]
Aaah! I got to try the compiler directives.

I made the shared/partials  work by the way:
![blazorshared](https://user-images.githubusercontent.com/46607604/65895133-cc454200-e35f-11e9-9eae-bed6387625b8.PNG)
