### ISSUE TITLE
Text in analyzers should be localizable

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1352]
Right now the analyzers have hard-coded US English text in them as error messages that are displayed to developers.

That text should be moved to a resource file so it can be localized. At least that is what we _think_ should happen. Some research is required to figure out if that's the right approach to localize analyzers that are running inside of Visual Studio.

**Comment by kant2002** [comment]
Would like to follow this guide.
https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Localizing%20Analyzers.md
