### ISSUE TITLE
Blazor - Extend ApplicationContextManager to leverage AuthenticationStateProvider

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1370]
**Is your feature request related to a problem? Please describe.**
As discussed in https://github.com/MarimerLLC/csla/issues/1142 several options were proposed. The issue was closed however before any were implemented.

I propose this feature will show how CSLA's blazor ContextManager.User and blazor's AuthenticationStateProvider can work together. Propose we extend the blazor sample to have an authenticated view, with a simple login / logout mechanism. This would show the pure mechanics of what needs to happen when you login and logout. Then from that we can work out how we refactor that into Csla's blazor support packages (or not) - i.e by extending ContextManager, or some other means.

**Describe alternatives you've considered**
As discussed on linked issue.

**Additional context**

**Comment by rockfordlhotka** [comment]
I like this idea a lot.

I am working through a bunch of issues with aspnetcore, HttpContext, and user principal things right now for v5.1. Tricky stuff given how they've changed things - like HttpContext isn't automatically available or even initialized at certain points.

Working through these details in Blazor would be very beneficial.

@dazinator is this something you are interested in figuring out?

**Comment by dazinator** [comment]
@rockfordlhotka  PR submitted! To be honest I am not sure there would be that much to pull into CSLA's blazor support library. See what you think. One question that does crop up (as per my notes on the PR) - is the issue of ClaimsPrincipal and MobileFormatter not playing together and whether that could possibly be improved.
