### ISSUE TITLE
MobileFormatter and its reader/writer should be async

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1376]
A breaking change in ASP.NET Core 3 means that extra config is required if any dependent libraries use synchronous operations for IO or serialization. Right now `MobileFormatter` (more accurately its reader/writer pair) are synchronous.

These should be updated to be async to avoid the extra config, and to potentially improve throughput.

**Comment by rockfordlhotka** [comment]
I did some research/testing around this. It turns out to be a harder problem to solve than one might think, since Microsoft hasn't provided an async `BinaryWriter` or `BinaryReader`. The stated reason is that making them async reduces performance, since these types are working on in-memory streams.

I'm not sure where to go with this right now, so I'm going to put it back into the backlog in the hopes that someone has a good solution.

**Comment by StefanOssendorf** [comment]
What about creating the async-versions and use async-over-sync in this case? Other cases could benefit from the available async-methods? I didn't check the current implementations if it's even feasable.

**Comment by rockfordlhotka** [comment]
The issue we need to address is that right now we need to add extra configuration for IIS and Kestrel to allow the use of a syncronous IO service on the web server - specifically MobileFormatter because it uses the sync reader/writer API.

I don't believe changing to the async API will actually matter in terms of performance or behavior, but it is necessary to address the web server issue.

Behind the scenes, MobileFormatter ultimately uses the `BinaryWriter` and `BinaryReader` - and I think you (@StefanOssendorf) are right - the answer is probably to try an async-over-sync solution.

**Comment by StefanOssendorf** [comment]
I think I fixed it - at least for the `HttpPortalController`. So I didn't touch the `MobileFormatter` API which would cause a _huge_ async/await wave throughout the code.
Is there any other Code which provides an endpoint to Kestrel/IIS which I'm not aware of? The new BlazorStateController is fine.

**Comment by rockfordlhotka** [comment]
Probably the GrpcProxy

**Comment by StefanOssendorf** [comment]
As far as I can tell the gRPC implementation does not have any way of async-read in the `RequestMessage`.
The fix is in my branch but I'll try to create an integration test to verify it's fixed - for the future too :)
