### ISSUE TITLE
DataPortal DbContextManager EF.Core context disposed

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#1383]
**Describe the bug**
When load application call the DbContextManager(Of T).GetManager work well.
Some time after calls the DataPortal the context object is disposed and can't call anymore until close and reopen the application.
I have a EF Context with Net Framework 4.7.2. The configuration is LocalProxy, the WPF application have the DataPortal that call a EF Core

**Version and Platform**
CSLA version: 4.9.0 , 4.11.2
OS: Windows
Platform: WPF

**Code that Fails**
      Using ctx = DbContextManager(Of EuroSQLContext).GetManager(Database.ConexionSQL)
                Dim hr = (From h In ctx.DbContext.HrHojasDeRuta
                          Where h.Orden = Me.HojaRuta
                          Select h).Single
                hr.Bloqueo = Me.Bloqueo
                ctx.DbContext.SaveChanges()
     End Using

**Stack Trace or Exception Detail**

DataPortal.Update falló (Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.

**Additional context**
I have a EF Context with Net Framework 4.7.2

app.config:

  &lt;connectionStrings&gt;
   &lt;add name="Conexion" connectionString="..." providerName="System.Data.SqlClient" /&gt; 
   &lt;/connectionStrings&gt;
  &lt;appSettings file=""&gt;
 &lt;clear /&gt;
    &lt;add key="CslaDataPortalProxy" value="Csla.DataPortalClient.LocalProxy,Csla" /&gt;
  &lt;/appSettings&gt;

Context:

`

    public class EuroSQLContext :DbContext
    {
        public EuroSQLContext() { }
        private string _cnn;
        public EuroSQLContext(string cnn)
        {
            this._cnn = cnn;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                 optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings[_cnn].ConnectionString);
            }
        }
	}
`

**Comment by ProDInfo** [comment]
Probably if this error??:

https://github.com/aspnet/EntityFrameworkCore/issues/9901

More Details:

Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Nombre del objeto: 'EuroSQLContext'.

StackTrace:


   en Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   en Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   en Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_QueryProvider()
   en Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor..ctor(IEvaluatableExpressionFilter evaluatableExpressionFilter, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, DbContext context, Boolean parameterize, Boolean generateContextAccessors)
   en Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ExtractParameters(IDiagnosticsLogger`1 logger, Expression query, IParameterValues parameterValues, Boolean parameterize, Boolean generateContextAccessors)
   en Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   en Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   en Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   en Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SumAsync(IQueryable`1 source, CancellationToken cancellationToken)
   en Business.Ef.Models.ContextExtensions.<GetStockTeorico>d__0.MoveNext() en ..\ContextExtensions.cs:línea 15
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Business.Data.Programas.Preparacion.DocumentoPreparacionLinea.<Child_Fetch>d__32.MoveNext() en ..\PreparacionLinea.cs:línea 85
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__7.MoveNext()
   en Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Reflection.LateBoundObject.<CallMethodTryAsyncDI>d__12`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Server.DataPortalTarget.<FetchChildAsync>d__18.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Server.ChildDataPortal.<Fetch>d__9.MoveNext()
   en Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Reflection.LateBoundObject.<CallMethodTryAsyncDI>d__12`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Server.DataPortalTarget.<InvokeOperationAsync>d__14`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Server.DataPortalTarget.<FetchAsync>d__17.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   en Csla.DataPortal`1.HandleDataPortalException(String operation, DataPortalException ex, Boolean isSync, IDataPortalProxy proxy)
   en Csla.DataPortal`1.<DoFetchAsync>d__18.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.DataPortal`1.<FetchAsync>d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Csla.DataPortal.<FetchAsync>d__29`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Business.Data.Programas.Preparacion.DocumentoPreparacion.<DataPortal_Fetch>d__14.MoveNext() en ..\Preparacion.cs:línea 73
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   en System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   en System.Threading.ThreadPoolWorkQueue.Dispatch()
   en System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by rockfordlhotka** [comment]
It is true that when the last `using` block closes on the `DbContextManager` it calls `Dispose` on the context.

https://github.com/MarimerLLC/csla/blob/v4.x/Source/Csla.Data.EF6.Shared/DbContextManager.cs

Is this not the correct behavior? Should the context not be disposed when the work is complete?

**Comment by rockfordlhotka** [comment]
@ProDInfo I'm reviewing the backlog, and see that this went silent a long time ago. Did you find a workaround or solution, or is this still a problem (I hope not!!!)?

**Comment by ProDInfo** [comment]
The problem continue.
I need to instanciate manually a DataContext because with DbContextManager dispose the object but continue in memory

De: Rockford Lhotka <notifications@github.com>
Enviado el: jueves, 30 de julio de 2020 19:25
Para: MarimerLLC/csla <csla@noreply.github.com>
CC: Javier <programador_jg@yahoo.es>; Mention <mention@noreply.github.com>
Asunto: Re: [MarimerLLC/csla] DataPortal DbContextManager EF.Core context disposed (#1383)


@ProDInfo<https://github.com/ProDInfo> I'm reviewing the backlog, and see that this went silent a long time ago. Did you find a workaround or solution, or is this still a problem (I hope not!!!)?

**Comment by rockfordlhotka** [comment]
Thank you for confirming.

How do you close or dispose of your `DataContext` so it doesn't continue in memory?

**Comment by rockfordlhotka** [comment]
@ProDInfo How do you close or dispose of your `DataContext` so it doesn't continue in memory?

**Comment by ProDInfo** [comment]
Because I have problems with DbContextManager I don't use it for Ef.Core.
On each call I create a new DbContext inside of using statement aftar that it's dispose.

I think that the DbContextManager would work in the same form: create and dispose the DBContext.

**Comment by rockfordlhotka** [comment]
You don't call `Close`, you just call `Dispose`? Or you rely on your `using` statement to do the `Dispose`?

Perhaps the big thing is that you don't `Close`?

**Comment by rockfordlhotka** [comment]
I am looking at the code, and there's no obvious reason why it would fail for efcore when it works for previous versions of EF.

I wonder, @ProDInfo, if your data access code is maybe multi-threaded? Maybe there are two concurrent data portal calls running on different threads, using the same context?

The dbcontextmanager is not threadsafe, and so that could lead to issues.

**Comment by rockfordlhotka** [comment]
I am going to close this issue, in favor of #1385 - which will mark the context manager types as obsolete, because people should now be using DI to get and manage data access types.
