### ISSUE TITLE
ConnectionManager<T> does not support access tokens

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/csla#1384]
**Is your feature request related to a problem? Please describe.**
Ideally, we would like the ConnectionManager<T> class to support .NET 4.6's `SqlConnection.AccessToken` property. We're about to start using Azure MFA authentication, so we aren't going to be passing a User/PW but instead an Access Token. However, because ConnectionManager<T> calls `new C()` followed by `C.Open()`, there is no time to set the `AccessToken` property.

**Describe the solution you'd like**
Recognizing that this would probably break pre-4.6 apps, i could imagine three options.

1. Change ConnectionManager<T> to offer a virtual function we could override and set properties to prior to calling `Open` within an inherited class. For example, on Line 148 [here](https://github.com/MarimerLLC/csla/blob/9037cfee81f7fe98b1d8dec2150bc9962571f7e2/Source/Csla.Shared/Data/ConnectionManagerT.cs#L147), make a virtual function called `OnBeforeOpen`, where we could set it similar to how you do it in GetHttpClient [here](https://github.com/MarimerLLC/csla/blob/dc44e4d952049f4172b64a197799d7d259c5badd/Source/Csla.Shared/DataPortalClient/HttpProxy.cs)
1. Add a static event we'd listen for to set the connection's properties prior to calling `Open`.
2. Add a static dictionary of properties `<string PropertyName, object PropertyValue>` to set with reflection prior to calling `Open`.

**Describe alternatives you've considered**
The only other option would be to handle the sql references ourselves, which is basically reinventing the wheel since you already offer an excellent solution.

**Comment by JasonBock** [comment]
I realize you probably have a lot of code reliant upon `ConnectionManager`, but I would suggest not using `ConnectionManager` at all. I've only used it on one project and it was a PITA because IoC is a much better choice, and CSLA 5 has better support for injecting dependencies. I'd go that route if you can (and as a side note, I'd really like to see `ConnectionManager` deprecated and eventually obsoleted if possible :) ).

**Comment by rockfordlhotka** [comment]
I agree with @JasonBock - CSLA 5 and DI is a better solution overall.

That said, I understand the need for such a feature to ease an update of large existing codebases. @GreatBarrier86 is that your scenario? Or would moving to DI be realistic?

**Comment by GreatBarrier86** [comment]
@rockfordlhotka, for right now, it's not feasible to restructure that. I don't dispute it would be better, and we most likely will do so, but that's a bigger change than we're comfortable doing NOW since we're already overhauling a ton of stuff for Azure.

**Comment by GreatBarrier86** [comment]
One solution we could use for now is to copy/paste your `ConnectionManager<T>` class, make our own `MyConnectionManager<T>`, and then just use that until we're ready to move to CSLA 5/DI.

Since you've both basically implied that `ConnectionManager<T>` is depreciated-ish, this is a tolerable solution assuming you have no plans for big changes to `ConnectionManager<T>`.

Opinons?

**Comment by JasonBock** [comment]
@GreatBarrier86 I did something similar about 10 years ago on a project. I wanted more control over `ConnectionManager` so we just grabbed the code and rolled our own.

I completely understand your point about moving to a DI approach is a big change to do. And to be clear, I'm not saying these manager types **are** going to be deprecated. I made an issue to discuss that, but there are **no** plans AFAIK to do that :).

**Comment by rockfordlhotka** [comment]
@GreatBarrier86 I like option 1 best, as I think it provides the most maintainable/clear overall solution.

Do you want to create a PR?

**Comment by GreatBarrier86** [comment]
@rockfordlhotka, I've never done one with Git before. I'm used to using TFVC. Mind explaining what you're asking for? :)

**Comment by rockfordlhotka** [comment]
@GreatBarrier86 From a solution perspective I think your idea of adding a virtual method as an extensibility point is the way to go.

From a PR perspective there are [developer docs](https://github.com/MarimerLLC/csla/tree/master/docs/dev) available on how to contribute. Probably start with [contributing.md](https://github.com/MarimerLLC/csla/blob/master/CONTRIBUTING.md). There's a doc that walks through the specific git commands necessary to submit a PR via GitHub.

**Comment by GreatBarrier86** [comment]
Thanks @rockfordlhotka, I'll do so now. I've never worked with a GitHub project so there's a little for me to learn first.

**Comment by GreatBarrier86** [comment]
@rockfordlhotka, i'm not sure about this now. `ConnectionManager<C>` does not expose a non-private constructor so the `MyConnectionManager<C>` class that overrides my suggested `OnConnectionOpen` function isn't compilable.

Making the constructor `protected` instead of `private` seems like it could be an answer, but it feels outside the scope of my particular change. Thoughts?

```
    public class MyConnectionManager<C> : ConnectionManager<C>, IDisposable where C : IDbConnection, new()
    {
        public MyConnectionManager()
            : base() 
        {
        }
    }
```
will yield this error

**Error	CS1729	'ConnectionManager<C>' does not contain a constructor that takes 0 arguments**

**Comment by GreatBarrier86** [comment]
Hi @rockfordlhotka, any opinion on this? It definitely seems weird for me to make a scope change.

**Comment by rockfordlhotka** [comment]
I'd think making the constructor `protected` is the right answer. We're basically taking a class that was not intended for subclassing (probably should have been `sealed` really) and allowing subclassing. So changing ctor scope seems like it fits with the change you are making.

**Comment by GreatBarrier86** [comment]
Would you say as a general principle, you would discourage people from making reasonable scope changes to your code? Maybe in open-source development, such a thing is considered ok, but i'd think it would be seen a second-guessing the original developer.

**Comment by rockfordlhotka** [comment]
I think it all comes down to achieving a specific goal. In this case the goal is to add an extensibility point, and the original code design blocks that, so a change needs to be made.

So yeah, I'd discourage such changes in a flagrant manner, but within the context of making an enhancement sometimes things have to change.

I have no problem with people second-guessing or suggesting changes to the code. Sometimes I don't agree with such a suggestion, but more often people have good ideas and things get better.

**Comment by GreatBarrier86** [comment]
We've run into another problem. Overriding CpsConnectionManager worked fine for a single user app, but for a web service, where each caller will have their own Azure AccessToken, this whole thing falls apart. In my example below, i'm using a static string property to hold the AccessToken, which again, works great for a single user scenario. This obviously won't work for any multi-user implementation. Is this where Dependency Injection could come back into play? Each app/instance could provide its own SqlConnection, so the business layer doesn't need to worry about it at all?

Given this scenario, what's the "best-practice" implementation? I'm having trouble finding good examples that come close to what we presently have, so i'm getting suspicious that @JasonBock's mention of DI may have been the appropriate solution early on.

![image](https://user-images.githubusercontent.com/29482393/71896242-36207500-3121-11ea-80ca-4eff363ff49e.png)

**Comment by GreatBarrier86** [comment]
Btw, my initial thought was to use the `ApplicationContext.DataPortalActivator` property, but it's static, so really, i don't think a per-use property like `AccessToken` could be applied this way, if i understand it correctly.

**Comment by rockfordlhotka** [comment]
In CSLA 6 all the database/transaction/context manager types are removed.
