### ISSUE TITLE
Useful exceptions on non success status codes. When using HttpProxy async

### ISSUE THREAD

**Issue by MTantos1** [MarimerLLC/csla#1387]
**Is your feature request related to a problem? Please describe.**
Recently we had an application which appeared to be not working randomly, it in fact was the server rejecting requests over a certain size. Detecting this problem required using a traffic monitoring tool (fiddler) and looking at the server response body which was:
```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Maximum request length exceeded.",
  "ExceptionType": "System.Web.HttpException"
}
```
When making an async call via the HttpProxy, if the response code from the server is not one of success (200-299) then an HttpRequestException is thrown by `httpResponse.EnsureSuccessStatusCode();` which is (at the time of writing this) on line 420 of `Source/Csla.Shared/DataPortalClient/HttpProxy.cs`

**Describe the solution you'd like**
Throw a `DataPortalException` or any other which has the response body included in the exception. This would make debugging certain server errors much easier as the behaviour of `EnsureSuccessStatusCode` is frankly next to useless.

**Describe alternatives you've considered**
Replace `httpResponse.EnsureSuccessStatusCode();` with `if (!response.IsSuccessStatusCode) { ... }` this way you can include a little more context in the exception, particularly the response body as this would be where the server would include any extra information regarding why a non success status code was returned.

**Additional context**

**Comment by rockfordlhotka** [comment]
Great suggestion
