### ISSUE TITLE
ClientContext lost in async DataPortal_Fetch after upgrade from 4.6 to 4.7 and above

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#1400]
**Describe the bug**
In ASP.NET targeting .NET Framework v4.8, the ClientContext is empty inside async DataPortal_Fetch

**Version and Platform**
CSLA version: 4.7.100 and up to 4.11.2
OS: Windows
Platform: ASP.NET MVC 5 .NET Framework v4.8

**Code that Fails**
```
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            ApplicationContext.ClientContext.Add("MyContext","Stuff");
            TestBoSync.Get(); // WORKS
            await TestBo.GetAsync(); // FAILS

            return View();
        }
    }

    public class TestBo : NameValueListBase<string, string>
    {
        public static async Task<TestBo> GetAsync()
        {
            Debug.WriteLine(ApplicationContext.ClientContext.Contains("MyContext"), "TestBoAsync:Before");  // TRUE

            return await DataPortal.FetchAsync<TestBo>();
        }

        private async Task DataPortal_Fetch()
        {
            Debug.WriteLine(ApplicationContext.ClientContext.Contains("MyContext"), "TestBoAsync:After"); // FALSE
        }
    }

```

**Stack Trace or Exception Detail**
See above

**Additional context**
This works as expected in v4.6. I know the default ApplicationContext changed to AsyncLocal from v4.7 but assumed it would work the same in an ASP.NET website, i.e. no breaking changes from 4.6 to 4.7?

**Comment by rockfordlhotka** [comment]
In ASP.NET the context manager did not change to `AsyncLocal` - so if this is the code you are seeing run, then you aren't using the correct context manager.

Does your web project have the right NuGet reference? Specifically (for .NET Framework) the ASPNET package?

**Comment by j055** [comment]
Hi Rocky

It looks like ```HttpContext.Current``` is lost in the ```async DataPortal_Fetch``` method in all versions of CSLA.

In 4.6 the default implementation is different than 4.7 and carries the contents of the ```ClientContext``` over.
```
  <package id="CSLA-ASP.NET" version="4.6.603" targetFramework="net48" />
  <package id="CSLA-Core" version="4.6.603" targetFramework="net48" />
```

4.11 Packages
```
  <package id="CSLA-ASP.NET" version="4.11.2" targetFramework="net48" />
  <package id="CSLA-Core" version="4.11.2" targetFramework="net48" />
```

All versions from 4.6 to 4.11 behave as below:
```
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            await TestBo.GetAsync();
/*

ContextManager.IsValid: True
WebContextManager.IsValid: True
ContextManager.Type: Csla.Web.ApplicationContextManager
ContextManager.IsValid: True
WebContextManager.IsValid: False
ContextManager.Type: Csla.ApplicationContext+ApplicationContextManager

*/
            return View();
        }
    }

    [Serializable]
    public class TestBo : NameValueListBase<string, string>
    {
        public static async Task<TestBo> GetAsync()
        {
            Debug.WriteLine(Csla.ApplicationContext.ContextManager.IsValid, "ContextManager.IsValid");
            Debug.WriteLine(Csla.ApplicationContext.WebContextManager.IsValid, "WebContextManager.IsValid");
            Debug.WriteLine(Csla.ApplicationContext.ContextManager.GetType(), "ContextManager.Type");

            return await DataPortal.FetchAsync<TestBo>();
        }

        private async Task DataPortal_Fetch()
        {
            Debug.WriteLine(Csla.ApplicationContext.ContextManager.IsValid, "ContextManager.IsValid");
            Debug.WriteLine(Csla.ApplicationContext.WebContextManager.IsValid, "WebContextManager.IsValid");            
            Debug.WriteLine(Csla.ApplicationContext.ContextManager.GetType(), "ContextManager.Type");
        }
    }
```

**Comment by rockfordlhotka** [comment]
And you have NOT upgraded the version of ASP.NET MVC you are using?

I ask, because the web context manager has not changed recently - to say the least...

![image](https://user-images.githubusercontent.com/2333134/68224475-4ea2d080-ffb4-11e9-8eac-5c3aca88605c.png)

**Comment by j055** [comment]
The last package update for Microsoft.AspNet.Mvc (Version 5.2.7) was 29/11/2018 (UK). I have tried reverting to some older versions but the results are the same. We updated our app from .NET Framework 4.7.2 to 4.8 recently but I've tested the behaviour in both and it's the same.

Is it possible that in CSLA 4.6 we were just accessing the ```ClientContext``` on the default context in ```async DataPortal_Fetch``` instead of the ```HttpContext``` and that the data is saved to both context's client-side? And switching to ```AsyncLocal``` reveals the original setup?

**Comment by rockfordlhotka** [comment]
There have been some changes in `ApplicationContext` in the past year, but nothing I can see which would impact how it selects between the web and non-web context manager.

Here's the 4.11 file with latest changes flagged for each line (or block of lines) of code.

https://github.com/MarimerLLC/csla/blame/v4.x/Source/Csla.Shared/ApplicationContext.cs

**Comment by rockfordlhotka** [comment]
It is true though, that if `HttpContext` is `null` that you'll get the default context manager - and that has always been true.

If we assume background threads have _never_ had `HttpContext`, then they've always been using the default context manager instead of the web context manager.

The thing is, the `AsyncLocal` code isn't in CSLA 4.x, it is in 5.x.

In 4.x the default `IContextManager` implementation is still a nested class in the `ApplicationContext` class. In 5.x (in August 2019) the default implementation moved to `Csla.Core` into its own file.

**Comment by rockfordlhotka** [comment]
Here's the [4.7.200 history of `ApplicationContext`](https://github.com/MarimerLLC/csla/commits/v4.7.200/Source/Csla.Shared/ApplicationContext.cs) - no changes from 4.6 to 4.7.


**NOTE:** I'm not saying you aren't seeing an issue!! I'm trying to help figure out what might have changed!

**Comment by rockfordlhotka** [comment]
You know - is it possible that there's a change in the _data portal_ and how it invokes async DP_XYZ methods? I don't know if that's true - just another possible angle to explore?

I know in CSLA 5.x the way the data portal works is _very_ different, but I don't _think_ any changes were made in 4.6 or later.

**Comment by j055** [comment]
Just tried CSLA v5 and it looks the same, i.e. the ```HttpContext``` is passed to the sync method but not the ```async``` method. 

```
        [Fetch, RunLocal]
        private async Task FetchAsync()
        {
            Debug.WriteLine(Csla.ApplicationContext.WebContextManager.IsValid, "WebContextManager.IsValid"); 
            
            // False
        }

        [Fetch, RunLocal]
        private void Fetch()
        {
            Debug.WriteLine(Csla.ApplicationContext.WebContextManager.IsValid, "WebContextManager.IsValid"); 
            
            // True
        }
```

**Comment by rockfordlhotka** [comment]
fwiw, CSLA doesn't manage or do anything with `HttpContext`, so what you are seeing is a behavior of ASP.NET itself.

**Comment by j055** [comment]
But ASP.NET doesn't know anything about the way the DataPortal works and the ```HttpContext``` is only lost in the DataPortal communication channel. Obviously I'm only talking about when using the local Data Portal channel/proxy.

If we call ```await FetchAsync();``` directly from the BO factory method then the ```HttpContext``` is maintained.

**Comment by rockfordlhotka** [comment]
I am finding that `HttpContext` is not available in _any_ DP_XYZ method, sync or async.

To test this I created a simple MVC5 project that checks `Csla.ApplicationContext.WebContextManager.IsValid` in the controller and in a DP_Fetch method.

That `IsValid` property returns `true` if `HttpContext` is available, so it is an easy check.

It is valid in the controller, but not in _any_ DP_Fetch method.

This makes sense to me. This is, in fact, the reason that `ApplicationContext` maintains two context managers - one web and the other for everything else - because ASP.NET has never exposed `HttpContext` to code outside the UI itself.

**Comment by rockfordlhotka** [comment]
However, I can confirm exactly what you are seeing - CSLA 4.6 makes `ClientContext` available in the data portal.

However, in 4.6 it is also the case that the web context manager is invalid.

So something changed, I think, in the data portal, not in `ApplicationContext`.

**Comment by rockfordlhotka** [comment]
@j055 you'll be "happy" to know that the issue _is absolutely_ due to `AsyncLocal` as you thought originally. 😮

**Comment by rockfordlhotka** [comment]
I'm using this thread as a running monologue to keep my thoughts straight - this is complex stuff!

I begin to suspect that the issue isn't actually `AsyncLocal`, but rather that `LocalProxy` is using a custom task scheduler (`CslaTaskScheduler`), but as a general rule all tasks in CSLA also use `ConfigureAwait(false)` and the [two concepts aren't compatible](https://dotnet.github.io/orleans/1.5/Documentation/Advanced-Concepts/External-Tasks-and-Grains.html).

I'm not 100% sure why we're using a custom task scheduler. The task scheduler exists to flow context from the caller to the new task, but the data portal _also_ does that all by itself. So I'm kind of thinking that eliminating the use of the custom scheduler in `LocalProxy` is a good plan.

**Comment by rockfordlhotka** [comment]
@j055 I'll fix this in 5.1.0. Are you able to upgrade to v5?

**Comment by j055** [comment]
@rockfordlhotka I've had a quick look at the breaking changes and it looks doable. Thank you.

**Comment by j055** [comment]
Sorry!

**Comment by j055** [comment]
I've tried ```5.1.0-R19122302``` but the reported behaviour is still the same, i.e. the context is lost after an async call.

**Comment by rockfordlhotka** [comment]
@j055 I need to understand the specific code you are using to cause the issue.

**Comment by j055** [comment]
I think I've invited you to be a collaborator of my test repo. It's a pared-back ASP.NET project. Running it should show you the behaviour I'm taking about.

**Comment by rockfordlhotka** [comment]
This is stream of consciousness as I try to figure this out - I don't think I've encountered anything so complex and hard to debug in many, many years.

I've been doing my testing in ASP.NET Core, not MVC5. I'm not entirely sure that is what's going on, but in aspnetcore the `HttpContext` is an injected value, while in MVC5 is is ambient (afaik).

From what I'm seeing, as soon as I do a `Task.Run` to get the work onto a background thread, the `HttpContext` is lost. This can (and is) overcome in aspnetcore because CSLA gets `HttpContext` via injection, so it remains available. In MVC5 I'm not sure (at least yet) how to get the value onto a thread in the worker pool.

**Comment by rockfordlhotka** [comment]
I might have a solution - just pushed it to my PR - but @j055 your test will continue to fail.

The goal isn't to get `WebContextManager` working, it is to ensure that `ApplicationContext.ClientContext` and `GlobalContext` flow through the data portal.

I don't see an obvious/safe way to get `HttpContext` to flow, but the data portal already has a way to flow context - it is just optimized out of the way for `LocalProxy`. 

However, in the case where the client and server both DO have a `WebContextManager` and the data portal call is NOT remote, I can flow those context values through the data portal. Then on the server I can ignore them (for aspnetcore), or use them (for MVC5).

There's a little wasted overhead for aspnetcore, because those values get serialized onto the background thread for nothing. When MVC5 is truly obsolete I can get rid of this code in any case, so this is all temporary until folks move to aspnetcore.

**Comment by rockfordlhotka** [comment]
@j055 try the new 20012001 prerelease and see if it helps.

**NOTE** it won't help your test project, because I am NOT carrying `HttpClient` to the background thread, but I am carrying local/global context.

**Comment by j055** [comment]
I'm in the process of moving MVC5 to ASP.NET Core. The only thing is I must target .NET FX and not .NET Core for the time being. I assume you are only testing ASP.NET Core with .NET Core because it looks like there may be a bug in the Csla.AspNetCore when using .NET FX when configuring the services in the startup.

I will have another look and report in another ticket.

**Comment by j055** [comment]
> There's a little wasted overhead for aspnetcore

Is that neccessary if you have different assemblies for aspnetcore and MVC5? I guess I'm missing something!

**Comment by rockfordlhotka** [comment]
This is all in the core of Csla - not in any satellite assemblies - so it is the same for .NET 4.6.1+ and Core (but not .NET 4.0).

I _current_ testing is all in .NET 4.8 with MVC5, not .NET Core, because I want to match your scenario.

**Comment by rockfordlhotka** [comment]
@j055 have you had time to see if the changes meet your needs?

**Comment by j055** [comment]
I'm not entirely sure. Isn't the ```WebContextManager``` important in a web app? It doesn't seem to be available in NET Core or Framework.

I was getting Type loading exceptions with ```Microsoft.Extensions.DependencyInjection.Abstractions``` at first. I would be nice if the package version could align with the AspNetCore framework. Stops you having to create explicit references. Don't care about MVC5 because you always have to add explicit refs these days.

I've updated my repo with a .NET core version too with the same code.

I realize that I can't migrate to ASP Core using .NET Framework because >= 3.0 doesn't support it anymore. 

Looks like the ```ClientContext``` is coming through server-side. So do we need ```WebContextManager``` anymore? I don't know!

**Comment by rockfordlhotka** [comment]
`WebContextManager` is not important. Is is purely a solution to a problem with pre-aspnetcore `HttpContext` and how it did and didn't interact with `System.Threading.Thread.Current`, from .NET 2 through (I think) 4.8. Or maybe just 4.5.

In any case, it looks like I'll be able to eliminate the whole thing in a few years, once people stop using the legacy .NET Framework.

**Comment by rockfordlhotka** [comment]
Regarding the DependencyInjection package, that's a bug and I've [opened an issue](https://github.com/MarimerLLC/csla/issues/1469).
