### ISSUE TITLE
Review Repo for Code Duplication

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#1412]
**Is your feature request related to a problem? Please describe.**
No problem, just a code cleanup issue.

**Describe the solution you'd like**
I went through CSLA's code base using the VS Code Clones tool. There are a couple of areas where there are exact copies. Here are some examples:

- `BusinessBase.LoadProperty<P>(PropertyInfo<P> propertyInfo, P newValue)` - the code in the `try` block is duplicated in 6 other places.
- A lot of the portal classes - `GrpcPortal`, `HttpPortal`, and `RabbitMqPortal` - are copies.
- `CslaActionExtender.ExecuteSaveAction(ISavable savableObject, ITrackStatus trackableObject, CslaActionExtenderProperties props)` - this is duplicated in 3 other places.
- `GrpcProxy` and `HttpProxy` have duplication.
- `BusinessBase.InitializeBusinessRules()` is duplicated in `ReadOnlyBase`.

I realize that code duplication isn't always a "bad" thing in code, and sometimes trying to share code can actually be a detriment. That said, it may be worth seeing if some of these duplications can be eliminated.

**Describe alternatives you've considered**
Just leave it as-is :)

**Comment by rockfordlhotka** [comment]
I am going for leave as-is
