### ISSUE TITLE
Add localized resources to Csla NuGet package

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1413]
As of version 5.0 the `Csla` NuGet package only contains the default (en-us) language.

There's a doc that [describes two options for including localized resources via NuGet](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages).

It sounds like the most direct approach is for the Csla nuspec to include the localized resources in the primary package.

**Comment by ossendorf-at-hoelscher** [comment]
@rockfordlhotka  Isn't this issue done? At least there are a lot of localization files in Source/Csla/Properties.

**Comment by rockfordlhotka** [comment]
@ossendorf-at-hoelscher this issue is about how the resources are packaged into the NuGet packages.

**Comment by StefanOssendorf** [comment]
Yeah. And the current nuget contains the language resources as described by the link.
