### ISSUE TITLE
Sync context disappears after async call causing DataPortal.Complete method to fail.

### ISSUE THREAD

**Issue by kellyethridge** [MarimerLLC/csla#1417]
When using the `LocalProxy` synchronization fix and we flow the context everything works fine until the `Csla.Server.DataPortal.Complete` method call. This is because the `ApplicationContext.ClientContext` has been cleared from the `ConfigureWait(false)` methods used in the calling code in `Csla.Server.DataPortal`.

I'm using version 5.0.1 in VS2019, though this issue existed in the 4.x version as well. I'm using ASP.NET and I haven't heard about this issue from others, so I might be using CSLA completely wrong. In which case, I would like to correct my usage. I've been able to use CSLA because I use a custom built version.

I've created a repo that shows the error. If you were to compile a version of CSLA that does not use `ConfigureWait(false)` or does not call the `ApplicationContext.ClientContext` in the `DataPortal.Complete` method, the repo works correctly. When the project is run, the failure is shown in the browser developer tools network tab. I use Chrome for this.

Repo: https://github.com/kellyethridge/CslaApplicationContextTest

Thank you.

**Comment by kellyethridge** [comment]
Hi Rocky,

I saw your commit and wanted to compile and try it out. Unfortunately, it seems this issue was not resolved. I saw how you changed to `Task.Factory.StartNew`, but that didn't seem to address this issue. It still all stems back to the `.ConfigureAwait(false)` calls in `Server.DataPortal`. I am wondering if a possible fix is to use the `CslaFlowSynchronizationContext` `appsetting` as a parameter to the `ConfigureAwait` calls? That way by default it would be configured with `false` as it is now and when set to `true` it will align with the `LocalProxy` usage of `TaskScheduler.FromCurrentSynchronizationContext`.

What are  your thoughts?

Thank You!

**Comment by kellyethridge** [comment]
Hi Rocky,

I tried your 5.1.0 pre-release and as I feared, the issue still persists. I was wondering if you're uninterested in my possible fix or if I could create the fix and pull-request? Or if you have other ideas in mind.

Thanks, Rocky!

**Comment by rockfordlhotka** [comment]
You tried it in the one I released today?

I did a bunch of work around that, and solve the issue in my test cases. I wonder what is different in your test cases?

**Comment by rockfordlhotka** [comment]
I suspect the issue might be more complex than just changing the `ConfigureAwait` parameter.

An issue I had to overcome in this most recent release is that the data portal, when using local proxy, doesn't send/restore context values to the "server" because there is no server. I'd been playing with having the local proxy copy the context to the "server" just like a remote proxy, but that caused other complex issues, especially outside a web server where context values are often maintained in a static.

The end of one data portal call would overwrite the static values, even if other data portal calls were outstanding, etc. It was a mess!

**Comment by kellyethridge** [comment]
Hi Rocky,

Thanks for responding. OK, so from what I can tell with my limited knowledge, there is no way to solve the issue without some custom code. And by that, I mean a new `ApplicationContextManager`. So what I did was take the `ApplicationContextManager` in the `Csla.Web` project and extend it to use `AsyncLocal<HttpContext>` for the backing. When setting the `ApplicationContext.WebContextManager` to an instance in `Start` and setting the `HttpContext.Current` on each `BeginRequest` event, I was able to solve my specific issue without even needing to use the `CslaFlowSynchronizationContext` code you added. I'm unsure how robust this method is though.

If you browse the [CslaApplicationContextTest](https://github.com/kellyethridge/CslaApplicationContextTest) repository you can at least check out the `AsyncLocalWebContextManager` class and usage in `Global.asax`

**Comment by kellyethridge** [comment]
It sounds like if you're trying to serialize/deserialize the context for local proxy, you'd need to maintain two internal context references in the `ApplicationContextManager`, a client and server and access each one based on logical execution location. You'd need to set the server reference on the initial data portal call only. Sounds like a mess as well. I prefer the idea that the local proxy has much less overhead because of not serializing things.

**Comment by rockfordlhotka** [comment]
I looked at the context manager you created, and from a CSLA perspective that seems fine. I agree with you, I wonder, over time, if wrapping the `HttpContext` type in an `AsyncLocal` is a recommended practice.

On the other hand, if it works then that's a good thing right?
