### ISSUE TITLE
Csla version 2.1.1.0 NuGet

### ISSUE THREAD

**Issue by gojanpaolo** [MarimerLLC/csla#1451]
Hello, we're currently using an old version of Csla.dll (v2.1.1.0). We're trying to move from directly referencing the file to using NuGet. But we couldn't find the said version of Csla in NuGet. We would just like to verify if v2.1.1.0 is not published in NuGet and is there a recommended way of consuming this version of Csla? Thanks!

**Comment by JasonBock** [comment]
The earliest version of Csla on NuGet is 4.1.0. So there's no way to do what you want from NuGet. You could create a private NuGet server yourself, make a NuGet package for that version, and reference it that way.

@rockfordlhotka may have better ideas.

**Comment by gojanpaolo** [comment]
@JasonBock thank you for the confirmation.
