### ISSUE TITLE
WPF PropertyStatus not working on .Net Core 3.1

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/csla#1454]
**Describe the bug**
The PropertyStatus control is not showing on any broken rules when using a .Net Core 3 WPF project. Both for .net core 3.0 and 3.1.

I have created a simple project in both WPF .Net project and WPF .Net Core 3.1 project with the same code. In WPF .Net the brokenrule triggers the error display of the PropertyStatus control. In the WPF .Net Core 3.1 project nothing happens.

**Version and Platform**
CSLA version: 5.0.1
OS: Windows
Platform:  WPF .Net Core 3.1

**Comment by JacoJordaan** [comment]
I have found this error on rendering the XAML, if it would help:

Could not find the resource "Csla.Xaml.g.resources" among the resources "" embedded in the assembly "Csla.Xaml", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

**Comment by rockfordlhotka** [comment]
Possibly the wrong name, or path, or something with resx vs resw files - I haven't looked at how WPF works in .NET Core 3 at all, the porting was a contribution by @GillesBer.

**Comment by JacoJordaan** [comment]
I have upgrade to version 5.1.0 and this is still an issue. Did not expect this to be resolved with latest version, just hopeful.
I am willing to help, but I have no idea where to even start looking at this issue.

**Comment by rockfordlhotka** [comment]
I have had no time to look at this, and welcome anyone's help.

**Comment by JacoJordaan** [comment]
@rockfordlhotka , I have downloaded csla and add the following to the Csla.Xaml.NetCoreApp3.0 project file:
```
  <ItemGroup>
    <Page Include="..\Csla.Xaml.Resources\Themes\Generic.xaml">
      <Link>Themes\Generic.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\Csla.Xaml.Resources\Resources\Error.png">
      <Link>Resources\Error.png</Link>
    </Resource>
    <Resource Include="..\Csla.Xaml.Resources\Resources\Information.png">
      <Link>Resources\Information.png</Link>
    </Resource>
    <Resource Include="..\Csla.Xaml.Resources\Resources\Warning.png">
      <Link>Resources\Warning.png</Link>
    </Resource>
  </ItemGroup>
```
This did the trick to show the PropertyInfo control in my test project.

Will you please check this out when you have a gap and let know if you need more info.

**Comment by rockfordlhotka** [comment]
That seems like the right solution to me - please proceed with a PR if you would. Thank you @JacoJordaan
