### ISSUE TITLE
Add support for general purpose CSLA Web API endpoint

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#147]
Create a CslaApiController (or similar) that can be used to expose a general purpose Web API endpoint that exposes a CSLA object graph to the service caller.

This endpoint should support GET and PUT operations (insert/update).

To make this meet common requirements, a visitor pattern should probably be used so each object in the graph can choose whether to expose itself via the service, and can also choose which of its property/field values it wants to expose.

**Comment by oatsoda** [comment]
Are there any plans to add this add this back into the roadmap?

Thanks!

**Comment by rockfordlhotka** [comment]
Probably, it just hasn't been a high enough priority for me to work on it given all my health issues. Supporting UWP and .NET 4.6 seemed more important.

**Comment by oatsoda** [comment]
Thanks - not chasing! Just interested to know if it is likely to happen so I can plan our product direction accordingly.

**Comment by rockfordlhotka** [comment]
A couple years ago this seemed like a good idea. I don't have a clear vision for the concept in my mind at this time, so I'm closing the issue.
