### ISSUE TITLE
Data Portal not found when using arrays

### ISSUE THREAD

**Issue by Eduardo-Micromust** [MarimerLLC/csla#1470]
**Describe the bug**
Fetch is not found when it is receiving an array.

**Version and Platform**
CSLA version: 5.1.0-R20012201
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Code that Fails**
```
    public static MultipleDataAccess GetMultiple(int[] ids)
    {
      return Csla.DataPortal.Fetch<MultipleDataAccess>(ids);
    }

    [Fetch]
    private void Fetch(int[] ids)
    {
    }
```

**Additional context**
ServiceProviderMethodCaller.FindDataPortalMethod looks for a method whose number of parameters is equal to the array size.

**Comment by rockfordlhotka** [comment]
@Eduardo-Micromust if you can find a solution to this I'd be very grateful (and impressed!).

I never did find a way to disambiguate between the params array and a regular array.

**Comment by Eduardo-Micromust** [comment]
The problem is harder to solve than I thought. 
SingleCriteria could be useful for situations like that but it is marked as Obsolete.

**Comment by rockfordlhotka** [comment]
`ToList` is your friend 😄

**Comment by Eduardo-Micromust** [comment]
Could an analyzer be created to warn developers when Data Portal is receiving an array?

**Comment by Eduardo-Micromust** [comment]
I wrote a small test to see if it is possible to differ a params array and a regular array:

```
using System;

namespace ArrayTests
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("PrintParameters()");
            PrintParameters();

            Console.WriteLine("PrintParameters(null)");
            PrintParameters(null);

            Console.WriteLine("PrintParameters(new int[] { 1, 2, 3 })");
            PrintParameters(new int[] { 1, 2, 3 });

            Console.WriteLine("PrintParameters(new string[] { \"a\", \"b\", \"c\" })");
            PrintParameters(new string[] { "a", "b", "c" });

            Console.WriteLine("PrintParameters(new object[] { \"a\", \"b\", \"c\" })");
            PrintParameters(new object[] { "a", "b", "c" });
        }

        private static void PrintParameters(params object[] args)
        {
            Console.WriteLine($"Parameters type: {(args == null ? "null" : $"{args.GetType().Name}({args.Length})")}");
            Console.WriteLine();
        }
    }
}
```

And this is the output I got:

PrintParameters()
Parameters type: Object[](0)

**PrintParameters(null)
Parameters type: null**

PrintParameters(new int[] { 1, 2, 3 })
Parameters type: Object[](1)

**PrintParameters(new string[] { "a", "b", "c" })
Parameters type: String[](3)**

PrintParameters(new object[] { "a", "b", "c" })
Parameters type: Object[](3)

According to the C# language specification, the output in bold are wrong (a bug in C#). Look what the specification (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction) says about params: 

Within a method that uses a parameter array, the parameter array behaves exactly like a regular parameter of an array type. However, in an invocation of a method with a parameter array, it is possible to pass either a single argument of the parameter array type or any number of arguments of the element type of the parameter array. **In the latter case, an array instance is automatically created and initialized with the given arguments.** 

So, according to the documentation, we should always have an object[] but it is not happening.

As Csla.Server.DataPortal.GetCriteriaFromArray is always used to serialize the criteria, I can write a fix using the criteria type and correct it, if necessary.

@rockfordlhotka, what do you think?

**Comment by rockfordlhotka** [comment]
I _love_ your attention to detail @Eduardo-Micromust !
