### ISSUE TITLE
IServiceScope (in ApplicationContext.ServiceProviderScope) is disposed if a DataPortal method is called inside another DataPortal.

### ISSUE THREAD

**Issue by Eduardo-Micromust** [MarimerLLC/csla#1481]
Csla.Server.DataPortal.Complete disposes scope without checking if it is being used.

```
  [TestClass]
  public class DisposeScopeTest
  {
    [TestMethod]
    public void Test_Scope_Dispose()
    {
      var serviceCollection = new ServiceCollection();
      serviceCollection.AddScoped<DisposableClass>();

      ApplicationContext.DefaultServiceProvider = serviceCollection.BuildServiceProvider();

      _ = ClassA.GetClassA();
    }

  }

  public class DisposableClass
  : IDisposable
  {
    public bool IsDisposed { get; private set; } = false;
    public void Dispose()
    {
      IsDisposed = true;
    }
  }

  public class ClassA : BusinessBase<ClassA>
  {
    public static ClassA GetClassA()
    {
      return Csla.DataPortal.Fetch<ClassA>();
    }

    [Fetch]
    private void Fetch([Inject]DisposableClass disposable)
    {
      if (disposable.IsDisposed)
      {
        throw new ObjectDisposedException(nameof(disposable)); //No Exception here
      }

      _ = ClassB.GetClassB();
      if (disposable.IsDisposed)
      {
        throw new ObjectDisposedException(nameof(disposable)); //ObjectDisposedException is thrown
      }
    }
  }

  public class ClassB : BusinessBase<ClassB>
  {
    public static ClassB GetClassB()
    {
      return Csla.DataPortal.Fetch<ClassB>();
    }

    [Fetch]
    private void Fetch([Inject]DisposableClass disposable)
    {
    }
  }
```

**Comment by Eduardo-Micromust** [comment]
I couldn't find where the IServiceScope is disposed in Csla.DataPortalClient.DataPortalProxyFactory.Create and Csla.Server.ObjectFactoryLoader.GetFactory. Is it ok to keep the IServiceScope in memory?

**Comment by rockfordlhotka** [comment]
I don't know.

I suspect the reason you'd need to dispose the scope is so it can dispose any singleton or other instances it is referencing? Not like the scope itself holds any expensive resources (like a file handle, etc).

However, I do think that the data portal needs to dispose the scope before returning the call to the local client (so at the end of the logical server-side call).

**Comment by Eduardo-Micromust** [comment]
> I don't know.
> 
> I suspect the reason you'd need to dispose the scope is so it can dispose any singleton or other instances it is referencing? Not like the scope itself holds any expensive resources (like a file handle, etc).
> 
> However, I do think that the data portal needs to dispose the scope before returning the call to the local client (so at the end of the logical server-side call).

It is hard to define what is a scope in the client:
- a scope per call;
- a scope for all calls running simultaneously;
- a single scope for all the client's lifetime (actual);
I can´t see any problem in using a single scope but the recommend approach to use HttpClient is using HttpClientFactory (https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests). Maybe it can be listed as an improvement for some future version.

**Comment by rockfordlhotka** [comment]
The data portal creates a scope in the logical server-side code, so it shouldn't matter if it is on the client or a physical server. The idea is that each data portal request that hits the "server" gets its own scope.

The `HttpProxy` (on the client) should rely on DI to get its `HttpClient`, and so it all depends on how the `HttpClient` is resolved based on app startup config. But that is _not affected_ by the scope created and used by the data portal on the logical server-side code.
