### ISSUE TITLE
ASP.Net Core MVC - Required Business Rule

### ISSUE THREAD

**Issue by tjscurr** [MarimerLLC/csla#1490]
**Describe the bug**
Using the latest code for MVCExample sample project.
After replacing the [Required] DataAnnotation with a Required BusinessRule in PersonEdit for the NameProperty, the Required rule does not appear to be executed on creation of a new PersonEdit record via the MVC UI, allowing records to save with no name property.

**Version and Platform**
CSLA version: 5.0.0
OS: Windows 10
Platform: ASP.NET Core 3.0, MVC, Visual Studio 2019 16.4.3

**Code that Fails**
Maybe somewhere in the Csla MVC model binder? After calling SaveObjectAsync method in PersonController.Create.

**Stack Trace or Exception Detail**
No exception thrown, PersonEdit object saves with no NameProperty despite the presence of the business rule.

**Additional context**
Found the following related info for ASP.Net Core MVC 2.2:
https://github.com/MarimerLLC/csla/issues/905 and
https://github.com/MarimerLLC/csla/pull/1280

To reproduce the issue:
Using the latest code for MVCExample sample project.

1. Comment out the `[Required]` DataAnnotation (MvcExample.BusinessLibrary.PersonEdit.cs line 21)
2. Add the following Rule (MvcExample.BusinessLibrary.PersonEdit.cs line 32):

`BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(NameProperty));`

3. Set the MVCExample project as Start-up project, build and run.
4. Click on 'People' in the webpage menu.
5. Click on the 'Create New' link.
6. Without entering anything as the Name, just click the 'Create' button.
7. Note the new record with no name despite the Required Business Rule.

Some custom rules of the project appear to be executed as expected, but the Required rule is not.

**Comment by rockfordlhotka** [comment]
I suspect the method with the `Create` attribute isn't calling `BusinessRules.CheckRules()`, so no rules are actually running as the object is created.

The `Required` attribute would still trigger the MVC UI framework, but probably isn't running in CSLA at all.

**Comment by rockfordlhotka** [comment]
You know what's really odd? The `NoZAllowed` rule works as expected in all cases.

So I actually wonder if there isn't some bug in the `Required` common rule?

**Comment by tjscurr** [comment]
Yes, NoZAllowed seems to be working.

Is the CheckCase rule working for you?

I just tried the following Name values but got no validation responses.
"no upper case"
"Mr.Green"

**Comment by tjscurr** [comment]
It might be a .Net Core 3.0 thing, I found your blog post showing these rules working back in Sept last year.
https://blog.lhotka.net/2019/09/12/AspCore-Csla5

I've tried updating Csla packages to 5.0.1 and latest pre-release, they all exhibit the same issue.

**Comment by rockfordlhotka** [comment]
I think the issue is that there's no code that actually configures the use of `CslaModelBinder`.

**Comment by tjscurr** [comment]
How does `NoZAllowed` work at all without it?

I just tried putting the CslaModelBinder in the Startup.cs , the issue still exists.

```
public void ConfigureServices(IServiceCollection services)
    {
      services.AddControllersWithViews();
            services.AddMvc(options =>
            {
                options.ModelBinderProviders.Insert(0, new Csla.Web.Mvc.CslaModelBinderProvider());
            });

      services.AddCsla();
      services.AddTransient(typeof(DataAccess.IPersonDal), typeof(DataAccess.PersonDal));
    }
```

**Comment by rockfordlhotka** [comment]
Yes, there's a bug in `CslaModelBinder`, in that it doesn't call `CheckRules` after the form data has been loaded into the object.

**Comment by tjscurr** [comment]
Thank you for your help Rocky, it is greatly appreciated!

**Comment by rockfordlhotka** [comment]
As a workaround until 5.1 is updated you can add this line in the controller right before the create/edit calls to `SaveObjectAsync`:

```c#
        ((Csla.Core.ICheckRules)person).CheckRules();
```

**Comment by tjscurr** [comment]
Thanks for the workaround!

Ah, CheckCase is not showing because the MvcExample.Views.Person.Create.cshtml is missing:
`@using Csla.Web.Mvc` at the top (which could really be put in MvcExample.Views.Shared._ViewImports.cshtml for all views in project), and
the ErrorFor calls in the view at line 20:

```
<span class="text-danger">@Html.ErrorFor(model => model.Name)</span>
<span class="text-warning">@Html.WarningFor(model => model.Name)</span>
<span class="text-info">@Html.InformationFor(model => model.Name)</span>

```

**Comment by tjscurr** [comment]
Hmm, after making the changes above, and your suggested workaround, CheckCase is still not working in the Create View, but appears to be working in the Edit View.

**Comment by tjscurr** [comment]
Nevermind, I see now that the CheckCase rule returns a warning result, which I assume does not prevent a create operation, as it is more of a suggestion than a validation error.

This means that the CheckCase rule message is never going to appear on the Create view UI if it is the only broken rule, but does appear if there is another rule returning an error result.

For example, a Name value of 'george' will not show the CheckCase rule message on the Create view, but a Name value of 'georgez' will display the CheckCase rule message on the Create view because the create operation is blocked by the NoZAllowed rule.

It is just an example after all, however this kind of warning or suggestion might be better suited to client side validation for value changes or keystrokes for immediate user feedback.

**Comment by tjscurr** [comment]
Thanks again for your help Rocky!
