### ISSUE TITLE
ClientContext missing server-side in netcoreapp3.1 and AspNetCore 

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#1492]
**Describe the bug**
Similar behaviour as this:
https://github.com/MarimerLLC/csla/issues/1400

But this time using a ```ASP.NET Core 3.0```, ```netcoreapp3.1``` and ```Csla.AspNetCore 5.1.0-R20020701``` project, everything is the latest.

if you comment out:

```
    app.UseCsla();
```
in ```Startup.Configure``` it works

**Code that Fails**
```ApplicationContext.ClientContext``` values lost in ```DataPortal_XYZ``` method after setting in middleware or controller action.

**Comment by rockfordlhotka** [comment]
@j055 I am not seeing this behavior.

In the `MvcExample` project, in the `PersonController` class in the `Edit` method (the setup one, not the postback) I added this:

```c#
      ApplicationContext.ClientContext["test"] = "123";
      var ctx = ApplicationContext.ContextManager;
      var ctw = ApplicationContext.WebContextManager;
```

and set a breakpoint on the next line (the data portal call) so I can confirm that `ctw` is null and `ctx` is there, and that `ApplicationContext.ClientContext["test"]` has the correct value.

Then in the `PersonEdit` class, in the `Fetch` method, I added this:

```c#
      var ctx = ApplicationContext.ContextManager;
      var ctw = ApplicationContext.WebContextManager;
      var test = ApplicationContext.ClientContext["test"];
```

with a breakpoint so I can confirm `ctx` is valid, `ctw` is null, and there is a value for `test` as expected.

**Comment by j055** [comment]
For me it's this line the causes the behaviour:
https://github.com/MarimerLLC/csla/blob/173245b2e37e8623c1099eb75f55e479535db16a/Samples/MvcExample/MvcExample/Startup.cs#L57

If I comment it out it works as you describe.

![controller](https://user-images.githubusercontent.com/6011428/74588654-4cf69900-4ff6-11ea-986e-58a76f1d0a34.png)

![fetch](https://user-images.githubusercontent.com/6011428/74588612-d5c10500-4ff5-11ea-837d-5e86dac39744.png)

**Comment by rockfordlhotka** [comment]
I wonder what is different on your machine to mine, as I absolutely don't see that behavior.

**Comment by rockfordlhotka** [comment]
@j055 I am still unable to replicate this issue. Do you have a repro I can run?

**Comment by j055** [comment]
Sorry for the slow reply. I going through migration hell at the moment - moving from NETFX to NETCORE and the ```MobileFormatter```. I guess when I've resolved some of these issues I will be in a better place to assess whether this is still a problem. Happy for you to shelve it for the time being though.

**Comment by rockfordlhotka** [comment]
Thanks for the follow-up @j055, I appreciate it. I'll close the issue and if you encounter something in the future you can open a new issue.

Hopefully the forum is providing a good venue for you to get help dealing with the migration?
