### ISSUE TITLE
Error on save when using interface for BusinessListBase child type

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#1494]
**Describe the bug**

In the latest version of CSLA I can no longer use an interface for the child type of a ```BusinessListBase```

```
    public class Blb : BusinessListBase<Blb, IChild>
```

On save i get misleading error:

```
System.InvalidOperationException: Cannot serialize collections not of type IMobileObject
   at Csla.BusinessBase`1.Save()
```

There are no collections.

**Version and Platform**
CSLA version: 5.1.0-R20020701
OS: Windows
Platform: ASP.NET Core, MVC

**Code that Fails**
https://github.com/j055/CslaWeb5

**Comment by rockfordlhotka** [comment]
@JasonBock is this something I overlooked in describing how that analyzer should work?

**Comment by rockfordlhotka** [comment]
@j055  This isn't a bug - your interface needs to derive from the `IMobileObject` interface.

**Comment by j055** [comment]
Ah OK. It's not a misleading error! I was previously deriving only from ```IEditableBusinessObject``` in a previous version of CSLA. Thank you.
