### ISSUE TITLE
Applying Authorization rules to properties from a UI

### ISSUE THREAD

**Issue by Brannos1970** [MarimerLLC/csla#1511]
I am building a new Blazor project. I need to hide sections in the UI that the user does not have permission to read the property that is being displayed. For example, we have a property name ConfidentialNotes. Not all users can view this so I need to hide the sections that display the information in the UI.

Is there a clean way to check if the user has permission to read or write to a property in the business object to change the visible or the disable properties in a UI element? If not is this something we can add and can someone guide me where it should be added?

I did notice that authorization helpers were added to Csla Blazor but I did not see any way to check property authorization.

**Comment by rockfordlhotka** [comment]
Have you read the [Using CSLA 5: Blazor and WebAssembly](https://store.lhotka.net/using-csla-5-blazor-and-webassembly) book? Or looked at the ProjectTracker code (discussed in the book)?

**Comment by Brannos1970** [comment]
Actually I am re-reading it now. I thought about it after I posted this.

**Comment by Brannos1970** [comment]
I found the answer on page 152. It makes sense it is part of the view model.
