### ISSUE TITLE
Duplicate base paths error in 3.2.0-preview2.20160.5

### ISSUE THREAD

**Issue by uwefms** [MarimerLLC/csla#1515]
Hi everybody,

trying to shift the MultiHead sample from 3.2.0-preview1.20073.1 to 3.2.0-preview2.20160.5 I get the following error:

Severity Code Description Project File Line Suppression State
Error Duplicate base paths '/' for content root paths 'j:__Blazor_Core_3.2_SP2_RTM\testing\MultiHead32\MultiHead32\MultiHead32.UI\bin\Debug\netstandard2.1\wwwroot' and 'j:__Blazor_Core_3.2_SP2_RTM\testing\MultiHead32\MultiHead32\Client\bin\Debug\netstandard2.1\wwwroot'. ('j:__Blazor_Core_3.2_SP2_RTM\testing\MultiHead32\MultiHead32\MultiHead32.UI\obj\Debug\netstandard2.1\MultiHead32.UI.dll', 'j:__Blazor_Core_3.2_SP2_RTM\testing\MultiHead32\MultiHead32\Client\obj\Debug\netstandard2.1\MultiHead32.Client.dll') MultiHead32.Client C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets 195

To avoid any trouble I followed Rocky's steps in the book based on a brand new Core hosted app in preview 2.
Before that I applied the update steps to preview2 with the same error on a perfectly running preview1 version, I updated from Rocky's original github version.

**Comment by rockfordlhotka** [comment]
Should be addressed by #1514

**Comment by uwefms** [comment]
> Should be addressed by #1514

Hi Rocky,

   I do not think so, as the error is not related to CSLA. The MultiHead Example is a Dual Mode Blazor app without any CSLA. I also tried with 3.2.0-preview3.20168.3 hoping for a change but no success either. This is not a great problem for me at the moment, because I am using a different Dual Mode approach, but Project Tracker will break as well after integrating the #1514 fixes because of this and some samples in your book as well.

Another thing I noticed at changing from preview2 to preview3:

in program.cs on client side

`builder.Services.AddSingleton<IWeatherForecastService, WeatherForecastService>();`
is not working any more
you have to change it to
`builder.Services.AddScoped<IWeatherForecastService, WeatherForecastService>();`

when consuming this service together with other scoped services. 
This worked with preview2.

   Uwe
