### ISSUE TITLE
LocalProxy won't initialize with HttpClient added as service

### ISSUE THREAD

**Issue by ashishsinha24** [MarimerLLC/csla#1541]
Hi,

I am able to run the projecttracker blazor server successfully. But as soon as I try to add syncfusion Services, I start getting runtime errors in CSLA.

   `services.AddSyncfusionBlazor();`

Comment out this line, and projecttracker starts working again.
I am pasting some part of the error

`MissingMethodException: Constructor on type 'Csla.DataPortalClient.LocalProxy' not found.
System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture)
System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes)
System.Activator.CreateInstance(Type type, object[] args)
Csla.Reflection.MethodCaller.CreateInstance(Type objectType, object[] parameters)
Csla.DataPortalClient.DataPortalProxyFactory.Create(Type objectType)
Csla.DataPortal<T>.GetDataPortalProxy(Type objectType, bool forceLocal)
Csla.DataPortal<T>.GetDataPortalProxy(Type objectType, ServiceProviderMethodInfo method)
Csla.DataPortal<T>.DoFetchAsync(Type objectType, object criteria, bool isSync)
Csla.DataPortal<T>.FetchAsync(object[] criteria)
Csla.DataPortal.FetchAsync<T>()
ProjectTracker.BusinessLibrary.RoleList.CacheListAsync() in RoleList.cs
+
                SetCache(await DataPortal.FetchAsync<RoleList>());
ProjectTracker.Ui.Blazor.App.OnInitializedAsync() in App.razor
+
        roleList = await RoleList.CacheListAsync();
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

**Comment by rockfordlhotka** [comment]
Thank you @Madhust - I've moved this to the backlog and marked it as a bug - I appreciate the research!

**Comment by ashishsinha24** [comment]
> Hi @ashishsinha24 ,
> 
> I did some analysis and able to narrow down this problem. This happens when the `HttpClient` is registered in the services.
> 
> ```cs
> services.AddScoped<HttpClient>();
> services.AddCsla().WithBlazorServerSupport();
> ```
> 
> During LocalProxy instance creation, the `DataPortalProxyFactory` is trying to inject `HttpClient` service into the `LocalProxy`(which has no constructor) thus throws the Missing constructor exception. @rockfordlhotka I hopes this helps.
> 
> @ashishsinha24 For now you could workaround this issue by creating a custom data portal proxy to create `LocalProxy` instance without `HttpClient` injection and registered it like shown below.
> 
> **CustomDataPortalProxyFactory.cs**
> 
> > _Note:  Source copied from DataPortalProxyFactory.cs file and modified the create method alone. Not fully tested._
> 
> ```cs
> public class CustomDataPortalProxyFactory : IDataPortalProxyFactory
>     {
>         private static Type _proxyType;
> 
>        . . . . . 
>         public IDataPortalProxy Create(Type objectType)
>         {
> 
>             if (_proxyType == null)
>             {
>                 string proxyTypeName = ApplicationContext.DataPortalProxy;
>                 if (proxyTypeName == "Local")
>                     _proxyType = typeof(LocalProxy);
>                 else
>                     _proxyType = Type.GetType(proxyTypeName, true, true);
>             }
> 
>             return (IDataPortalProxy)MethodCaller.CreateInstance(_proxyType);
>         }
> 
>      . . . .  .. . . .
> }
> ```
> 
> Register the ProxyFactory as below.
> 
> ```cs
>         public void ConfigureServices(IServiceCollection services)
>         {
>             . . . . . . .
> 
>             Csla.DataPortal.ProxyFactory = new CustomDataPortalProxyFactory(); //Registered custom data proxy.
>             services.AddSyncfusionBlazor();
>             services.AddCsla().WithBlazorServerSupport();
>         }
> ```

You are absolutely right in your research. It works perfectly. Thanks for your effort.
