### ISSUE TITLE
Refreshing Blazor ProjectTracker app - logs off user

### ISSUE THREAD

**Issue by BlagoCuljak** [MarimerLLC/csla#1550]
I'm experimenting with CSLA and Blazor, and when ever I refresh page, I get logged off, and need to log in again. 

I'm not sure if its #1377 has any connection to this. 

**Version and Platform**
CSLA version: 5.1 
OS: Windows, 
Platform: Blazor

**Comment by rockfordlhotka** [comment]
Is this true for both the client-side and server-side deployments?

**Comment by BlagoCuljak** [comment]
Hi Rocky, I'm sorry that I missed your question. 

I have tried to reproduce this again, and I just can't, works like it should. A don't think it's bug/issue (anymore).
