### ISSUE TITLE
Create analyzer for AddObjectAuthorizationRules methods

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1561]
In the past people would use the "well-known" `AddObjectAuthorizationRules` name for the `static` method that established per-type rules.

Now people should be using the `ObjectAuthorizationRules` attribute to identify the `static` method that establishes per-type rules. They can name the method as they choose.

It would be ideal to have an analyzer that identifies the old-style approach, and offers a fix to add the new attribute.

**Comment by JasonBock** [comment]
Should be very similar to what DoesOperationHaveAttributeAnalyzer and DoesOperationHaveAttributeAddAttributeCodeFix does.

**Comment by kant2002** [comment]
working on this.
