### ISSUE TITLE
Xamarin PropertyInfo ErrorText, WarningText and InformationText not updating

### ISSUE THREAD

**Issue by russblair** [MarimerLLC/csla#1570]
**Describe the bug**
The Xamarin PropertyInfo control is not updating the ErrorText, WarningText and InformationText properties when the property becomes valid.

**Version and Platform**
CSLA version: 5.1
OS: Windows 10, Android
Platform: ASP.NET Core, Xamarin

**Code that Fails**
```xaml
<csla:PropertyInfo x:Name="JobNoInfo" Path="Model.JobNo"/>
<Label x:Name="ErrorText" BindingContext="{x:Reference JobNoInfo}" Text="{Binding ErrorText, Mode=OneWay}" TextColor="White" BackgroundColor="Red" />
<Label x:Name="WarnText" BindingContext="{x:Reference JobNoInfo}" Text="{Binding WarningText}" TextColor="Black" BackgroundColor="Yellow" />
<Label x:Name="InfoText" BindingContext="{x:Reference JobNoInfo}" Text="{Binding InformationText}" TextColor="White" BackgroundColor="Blue" />
```

**Stack Trace or Exception Detail**
The same issue is described in https://github.com/MarimerLLC/cslaforum/issues/718. I did notice that the PropertyInfo RuleDescription property is correctly updated so I investigated.

**Proposed Solution**
I looked into the CSLA source code and found the reason in [Csla.Xaml.Shared.PropertyInfo.cs on line 848 to 850](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Xaml.Shared/PropertyInfo.cs#L848). The OnPropertyChanged statements are only within the not isvalid branch.
```cs
if (!IsValid)
{
  ...
  OnPropertyChanged(nameof(ErrorText));
  OnPropertyChanged(nameof(WarningText));
  OnPropertyChanged(nameof(InformationText));
}
else
{
  ...
}
```
I suspect moving these three OnPropertyChanged statements after the if (!IsValid) would solve the problem.

I wasn't sure if this behaviour was by design so I thought I would bring it to the group's attention.

**Comment by rockfordlhotka** [comment]
@russblair I agree, those lines of code appear to be in the wrong place. That was a recently added capability and clearly there's a bug.
