### ISSUE TITLE
Analyzer: ReadOnlyListBase subclass must be serializable

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1588]
**Describe the bug**
There's an analyzer to make sure business types are marked as `Serializable`. I would expect that a `ReadOnlyListBase` subclass would trigger this rule.

**Version and Platform**
CSLA version: 5.2.0
OS: n/a
Platform: n/a

**Code that Fails**

```c#
namespace GameMechanics
{
  public class SkillList : ReadOnlyListBase<SkillList, SkillInfo>
  {
  }
}
```

I declared this code, and even compiled it, and there was no warning or error that this type isn't `Serializable`.

**Comment by JasonBock** [comment]
`ReadOnlyListBase` implements `IReadOnlyListBase`, which derives from `IMobileObject`. The `IsMobileObject()` **should** pick this up, but obviously it's not. That's probably where the problem lies.

**Comment by rockfordlhotka** [comment]
@StefanOssendorf I appreciate you picking up this issue.

My one observation is that #3687 will probably entirely remove the `Serializable` attribute analyzer entirely 🫢

**Comment by StefanOssendorf** [comment]
That's okay and I saw that. I think for people who will be using 8/7.x this
will be okay. (I plan on porting it to 7.x if there's nothing against
that). Furthermore I'm learning source gen/analyzer stuff so this is a nice
practice :)

Rockford Lhotka ***@***.***> schrieb am So., 3. März 2024,
20:33:
