### ISSUE TITLE
Csla.Blazor package includes Csla.Blazor.WebAssembly reference which breaks app.UseCsla on server side blazor applications

### ISSUE THREAD

**Issue by heloraptr** [MarimerLLC/csla#1597]
**Describe the bug**
When creating a Blazor server application and adding the Csla.AspnetCore and Csla.Blazor packaged, adding app.UseCsla() to the startup throws an error due to the type "WebAssemblyHostBuilder" not being referenced.   I believe this is because the Csla.Blazor nuget package definition is also including the Csla.Blazor.WebAssembly library due to file name wildcard matching in the nuspec

**Version and Platform**
CSLA version: 5.2.0-R20042901
OS: Windows, 
Platform: ASP.NET Core, Blazor Server Side

**Code that Fails**
```c#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
  //Additional configuration removed for brevity

  app.UseCsla();
}
```
```
Error CS0012 The type 'WebAssemblyHostBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Components.WebAssembly, Version=3.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.	
```
The files section of the Nuspec definition for the Csla.Blazor package ha Csla.Blazor.* which bring in the webassembly dll as well as it matches the wildcard.

```xml
 <files>
    <!-- NetStandard Assembly -->
    <file src="..\..\bin\Release\netstandard\netstandard2.1\**\Csla.Blazor.*" target="lib\netstandard2.1" />
    <!-- icon -->
    <file src="..\..\Support\Logos\csla.png" target="images\" />
  </files>
```

**Comment by rockfordlhotka** [comment]
Thank you @heloraptr 

I am pretty sure this is addressed here: https://github.com/MarimerLLC/csla/issues/1586

**Comment by heloraptr** [comment]
@rockfordlhotka  Thanks for the quick response.   I'm seeing this in the latest 5.2.0-R20042901 Csla.Blazor package.  The separate Csla.Blazor.WebAssembly assembly is also being included in the Csla.Blazor package because it also meets the wildcard criteria (Csla,Blazor.*) in the files definition.

**Comment by rockfordlhotka** [comment]
Oh, arg!

**Comment by rockfordlhotka** [comment]
Thanks for finding this @heloraptr !!
