### ISSUE TITLE
Add NonSerialized feature for managed backing fields

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1628]
It should be possible to have a `RegisterNonSerializedProperty` method for each `RegisterProperty` method in `BusinessBase` and `ReadOnlyBase` to indicate that the property should not be serialized by `MobileFormatter`.

**Comment by JacoJordaan** [comment]
@rockfordlhotka , will this change mean that you can declare an using reference property as a normal managed property without the requirement to create a private backing field for it?

I am just thinking in the lines of existing properties where I need to create the property as a private field only because I do not want to serialize it.

**Comment by JacoJordaan** [comment]
@rockfordlhotka . I probably misinterpreted this. This is probably then for replacing the [NonSerialized] attribute that we had with the binary formatter. You will still need the private backing field and still have the [NotUndoable] attribute for an using reference property.

**Comment by rockfordlhotka** [comment]
The _intent_ is that you should be able to use a managed property (no private field) and indicate that it is nonserialized. And notundoable would make sense too.

Perhaps the overload method idea isn't a good one. Perhaps this is better done using the same relationships parameter used for PrivateField - make that a Flags enum

* PrivateField
* NonSerialized
* NotUndoable

**Comment by JacoJordaan** [comment]
This will be great - to have a managed property for both nonserialized and notundoable properties. Flag enums sounds good.

I can already see that I can use things like LazyGetPropertyAsync for using reference property that already handles checking to only run once.
I have also picked up that the PropertyHasChanged method is not called for private field properties and this should also resolve this.

**Comment by BaHXeLiSiHg** [comment]
We used this notation in version 4.X to handle backing fields value:
```csharp
[NonSerialized]
[NotUndoable]
private SomeType _originalObject;
```
It was helping to "save" field value between ```DataPortal``` operations.

@rockfordlhotka, there was any changes with such logic up to version 5.2?

Cause, as i have noticed, value of field ```_originalObject``` is not defined at ```DataPortal_Insert``` method but was set, for example, at ```DataPortal_Create``` method. Before calling ```.Save``` i still have value for field ```_originalObject``` in business object.

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg there are several things going on here.

1. `NotUndoable` only affects n-level undo, not serialization
2. The MobileFormatter doesn't work exactly like the old BinaryFormatter; BinaryFormatter is being slowly deprecated by Microsoft, so eventually it won't matter anymore
3. Properties with managed backing fields work differently than those with private backing fields (in MobileFormatter)

Your example has a private backing field, marked so it won't participate in n-level undo. It also is *not* automatically serialized by MobileFormatter, so if it you want it to flow over the network, you need to implement the get/set state methods.

I recommend against using private backing fields because they require manual work, and are therefore error-prone.

**Comment by BaHXeLiSiHg** [comment]
I see, but we have to use such backing fields because they have links to required sources (objects).

Have implemented something like this and it works:
```csharp
protected override void OnGetState(SerializationInfo info, StateMode mode)
{
    base.OnGetState(info, mode);

    info.AddValue("OriginalObject", ReflectionHelper.GetPropertyValue<object>(this, "OriginalObject"));
}

protected override void OnSetState(SerializationInfo info, StateMode mode)
{
    base.OnSetState(info, mode);

    var originalObject = info.GetValue<object>("OriginalObject");

    ReflectionHelper.SetPropertyValue(this, "OriginalObject", originalObject);
}
```

But it requires to declare ```OriginalObject``` as public property, to access it via reflection :(

Is there any other way to access private property on get/set state?

**Comment by rockfordlhotka** [comment]
Since the field is in your same class, why can't you just access it directly without using reflection?

Or if you _must_ use reflection for some reason, use a helper library that doesn't limit you to public fields. Reflection itself can access non-public fields just fine, and CSLA actually has helpers for that purpose.

Also, why would you go through the _property_ to get at the _field_? It would be more efficient to just get/set the field itself.

**Comment by BaHXeLiSiHg** [comment]
Updated answer, methods was inside base class, but i think i will move them inside target classes to avoid reflection. Thx for tips, going to change classes in this direction.

**Comment by ossendorf-at-hoelscher** [comment]
How would this be used? I can only vaguely guess what's wanted here.
Do you want:
```csharp
public string NonSerializedProp { get; set; }

// Somewhere in your Code
RegisterNonSerializedProperty(NonSerializedProp);
```
or

```csharp
public static readonly PropertyInfo<Guid> IDProperty = RegisterNonSerializedProperty<Guid>(nameof(ID));
public Guid ID
{
    get => GetProperty(IDProperty);
    set => SetProperty(IDProperty, value);
}
```

If it's for plain old C# propeties. Maybe the notation
```csharp
[field: NonSerialized]
public int Id { get; set; }
```

**Comment by rockfordlhotka** [comment]
This is for the `MobileFormatter` with managed backing fields. Right now, all properties with managed backing fields are serialized by `MobileFormatter`. Sometimes people have properties that are calculated by rules (for example), and don't need to be serialized.

**Comment by luizfbicalho** [comment]
I think that you are takling about this option right?

```cs
public static readonly PropertyInfo<Guid> IDProperty = RegisterNonSerializedProperty<Guid>(nameof(ID));
public Guid ID
{
    get => GetProperty(IDProperty);
    set => SetProperty(IDProperty, value);
}
```

What would this do that a `public Guid ID{ get; set; }` woudn't do?

**Comment by JacoJordaan** [comment]
A public property will loose all the functionality a csla property has like property change notifications, authorisation checks, use in business rules etc.

**Comment by rockfordlhotka** [comment]
The workaround today for `NonSerialized` is to use a private backing field and to not add the field value to serialization in the Get/Set state methods.

The idea of this backlog issue is to somehow tell `MobileFormatter` to ignore a _managed property_. Possibly via a flag in `RegisterProperty` or an attribute.

From a performance perspective, I rather like the `RegisterProperty` approach. Though the two could be merged, in that `RegisterProperty` could reflect against the property, find the attribute, and set a flag on the property metadata. This would only happen once during static initialization, so would be very efficient.

**Comment by luizfbicalho** [comment]
I can see this in more detail. Can you assign that to me too?

**Comment by luizfbicalho** [comment]
I'm looking at some different approaches here, for example in the generator we have this solution

```cs
[AutoSerializable]
public partial class AddressPOCO
{

  [AutoNonSerialized]
  public string? AddressLine1 { get; set; }

  public string AddressLine2 { get; set; } = string.Empty;

  public string Town { get; set; } = string.Empty;

  public string County { get; set; } = string.Empty;

  public string Postcode { get; set; } = string.Empty;

}
```

that generates this

```cs
	[Serializable]
	public partial class AddressPOCO : IMobileObject
	{
		void IMobileObject.GetChildren(SerializationInfo info, MobileFormatter formatter)
		{
		}
		
		void IMobileObject.GetState(SerializationInfo info)
		{
			info.AddValue(nameof(AddressLine2), AddressLine2);
			info.AddValue(nameof(Town), Town);
			info.AddValue(nameof(County), County);
			info.AddValue(nameof(Postcode), Postcode);
		}
		
		void IMobileObject.SetChildren(SerializationInfo info, MobileFormatter formatter)
		{
		}
		
		void IMobileObject.SetState(SerializationInfo info)
		{
			AddressLine2 = info.GetValue<string>(nameof(AddressLine2));
			Town = info.GetValue<string>(nameof(Town));
			County = info.GetValue<string>(nameof(County));
			Postcode = info.GetValue<string>(nameof(Postcode));
		}
		
	}
```

One other solution is to add another property to `IPropertyInfo` to set it as serializable 
then we could have two ways to go

One is to add an optional property to the `RegisterProperty` to force the serialized or not

The other is to get this by atributes as this one  `[AutoNonSerialized]` or the `[field: NonSerialized]`, but I think that the second one is complicated by the field: and if you change to the source generator later then it would require change in the attribute.
Could be a refactor in this attribute to be used as one only option?


Another point that it's not clear to me is the depth of the implementation here, if we add more information to `IPropertyInfo` it's not clear if we need to change the `IFieldData` also.

**Comment by rockfordlhotka** [comment]
The solution needs to work with existing code as well as any generators. I think it should rely on the existing `NonSerialized` attribute that is part of .NET.

To make this work, I do think it needs to be part of `IPropertyInfo`, probably a property called `IsSerializable` that defaults to `true`. During type initialization, like we do with the `DisplayName` attribute, the code should check for `NonSerialized` and set the `IsSerializable` value to `false` if appropriate.

The `FieldDataManager` class has `OnGetState` and `OnGetChildren` methods that need to honor the `IsSerializable` property on `IPropertyInfo`.

As you note, the `AutoSerializable` generator should also honor the `NonSerialized` attribute by not adding the property to the get/set state implementations.

**Comment by luizfbicalho** [comment]
The problem here with the `NonSerialized ` is that it is an attribute added to the field, but those properties don't have any field

```cs
public static readonly PropertyInfo<Guid> IDProperty = RegisterProperty<Guid>(nameof(ID));
[field:NonSerialized]
public Guid ID
{
  get => GetProperty(IDProperty);
  set => SetProperty(IDProperty, value);
}
```

'field' is not a valid attribute location for this declaration. Valid attribute locations for this declaration are 'property'. All attributes in this block will be ignored.

this is because this property doesn't have a field associated with it
```cs

    [field:NonSerialized]
    public string? AddressLine1 { get; set; }
```

this works fine

I think that we need `Csla.Serialization.NonSerialized` to make this work

**Comment by rockfordlhotka** [comment]
I see, you are correct. 

What I _want_ is this:

```csharp
public static readonly PropertyInfo<Guid> IDProperty = RegisterProperty<Guid>(nameof(ID));
[NonSerialized]
public Guid ID
{
  get => GetProperty(IDProperty);
  set => SetProperty(IDProperty, value);
}
```

To do that, as you say, we'd need a `Csla.NonSerialized` attribute. I think I'm good with that plan though, as it wouldn't be ambiguous (I just checked).

```csharp
namespace Csla;

[AttributeUsage(AttributeTargets.Property)]
public class NonSerializedAttribute : Attribute { }
```

**Comment by luizfbicalho** [comment]
> To do that, as you say, we'd need a `Csla.NonSerialized` attribute. I think I'm good with that plan though, as it wouldn't be ambiguous (I just checked).

I tink that we should rename `Csla.Serialization.AutoNonSerializedAttribute` to `Csla.NonSerializedAttribute` ok?

Or do you think that we should need two attributes?

**Comment by StefanOssendorf** [comment]
I'm late. But isn't a `[NonSerialized]` a really confusing concept here? I declare a property which _does not_ get transferred between client and server. _But_  it participates in changetracking etc and could mark my BO dirty even though the transition the other side will get a non dirty object? Or are objects using that _always_ dirty because we have a rule which changes this - which triggers dirtyness - at any point in time 🤔

#4197

**Comment by luizfbicalho** [comment]
> I'm late. But isn't a `[NonSerialized]` a really confusing concept here? I declare a property which _does not_ get transferred between client and server. _But_ it participates in changetracking etc and could mark my BO dirty even though the transition the other side will get a non dirty object? Or are objects using that _always_ dirty because we have a rule which changes this - which triggers dirtyness - at any point in time 🤔
> 
> #4197

I can't answer that

**Comment by rockfordlhotka** [comment]
The primary scenario that I'm aware of, is where there's a calculated property. There's no benefit to serializing the value across the network because it is calculated.

There may be other scenarios too, but that's the one that comes up frequently regarding serialization.

**Comment by StefanOssendorf** [comment]
I understand that. But shouldn't such a property _not_ change the dirty state?
A possible use case: Summary of X other properties.
Sending that over the wire is unnecessary due to the sum nature, but I do want to participate in changes of that value to simplify other stuff (Instead of having X input variables I only have to care about 1 in other rules).
In the new form this recalculation would _always_ mark the BO as dirty on it's first (re)calculation. That's for a brand new object probably not a problem. X * 0 = 0 (to go with my sum example).
But as soon as you _load_ existing data you have the following scenario.
All data loaded and because people might do a `CheckRules` before returning from the server to the client the BO is _now_ dirty. The newly calculated value wasn't loaded. Now on the client I recalculate the value and my BO is dirty _again_. Without doing anything. That seems really weird to me.
To prevent that with currently available tools, a developer _must_ use `LoadProperty` in it's rules or property defintion. (I'm unsure here if an `AddOutValue()` of a rule uses the property set or Set/LoadProperty internally).

Or maybe I miss something crucial here? I personally would _love_ to have a property declaration where I can _mark_ the property as "not dirty relevant" so I can use it in rules etc. _without_ interfering in changes made by users.

**Comment by rockfordlhotka** [comment]
@StefanOssendorf I'm going to spin off a new discussion based on your last comment.

I think you are on to something - and perhaps we need a new feature for that behavior.
