### ISSUE TITLE
DefaultProxy method in config should accept generic type param

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1631]
Right now to configure the data portal, code looks like this:

```c#
  app.UseCsla((config) => config
    .DataPortal()
      .DefaultProxy(typeof(Csla.DataPortalClient.HttpProxy), "https://myserver/api/dataportal")
  );
```

As a convenience, it would be cleaner with an overload like this:

```c#
  app.UseCsla((config) => config
    .DataPortal()
      .DefaultProxy<Csla.DataPortalClient.HttpProxy>("https://myserver/api/dataportal")
  );
```

**Comment by StefanOssendorf** [comment]
I think this issue is obsolete. The configuration structure has changed and e.g. `DefaultProxy` now has it's own extension method with more configurability.
