### ISSUE TITLE
PropertyChanged being invoked in a background thread

### ISSUE THREAD

**Issue by Eduardo-Micromust** [MarimerLLC/csla#1635]
If we have a business object with a async rule, when the rule is finished the PropertyChanged event is called in a background thread. In WinForms and WPF only the main thread can manipulate the UI and this behavior causes error in data binding.

**Version and Platform**
CSLA version: 5.1.0
OS: Windows
Platform: WinForms, WPF

Analyzing the code I found that PropertyChanged is fired Csla.Rules.BusinessRules.RunRules, line 788:
`asyncRule.ExecuteAsync(context).ContinueWith((t) => { context.Complete(); });`

I tried the following modification but it didn't work:
```
var uiSyncContext = System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext();
asyncRule.ExecuteAsync(context).ContinueWith((t) => { context.Complete(); }, uiSyncContext);
```

**Comment by rockfordlhotka** [comment]
I just tried to create this problem in Windows Forms 4.8 and it works fine.

Do you have a repro?

**Comment by Eduardo-Micromust** [comment]
I wrote a small test program with two rules: one async and one sync. 
Using the sync rule the program works perfectly: when the user inserts the birth's year the age is updated and OnPropertyChanged is fired on the main thread.
Using the async rule the program do not work: the age is not updated when the user inserts the birth's year and OnPropertyChanged is fired on a background thread.
[AsyncRuleTest.zip](https://github.com/MarimerLLC/csla/files/4647750/AsyncRuleTest.zip)

**Comment by JacoJordaan** [comment]
@Eduardo-Micromust . Just a quick observation regarding you test program.
I believe you should pass the AgeProperty to your business rule:
`
BusinessRules.AddRule(new CalculateAgeAsync(BirthYearProperty, AgeProperty));
`
And in rule use the age property as affected property something like this:
```
        private class CalculateAgeAsync :
            PropertyRuleAsync
        {
            private IPropertyInfo AgeProperty{ get; set; }

            public CalculateAgeAsync(IPropertyInfo primaryProperty, IPropertyInfo ageProperty)
                : base(BirthYearProperty)
            {
                AgeProperty= ageProperty;
                InputProperties = new List<Csla.Core.IPropertyInfo> { BirthYearProperty };

                AffectedProperties.Add(ageProperty);
            }

            protected override async Task ExecuteAsync(IRuleContext context)
            {
                var birthYear = Convert.ToInt32(context.InputPropertyValues[BirthYearProperty]);

                await Task.Delay(10).ConfigureAwait(false);

                var age = DateTime.Today.Year - birthYear;
                context.AddOutValue(AgeProperty, age);
            }
        }

```

Not sure if this will make a difference, but this is how I understand how to create the business rules and this is working fine on my side for both sync and async rules.

**Comment by Eduardo-Micromust** [comment]
@JacoJordaan I made the changes but the behavior is the same:

```
private class CalculateAgeAsync :
            PropertyRuleAsync
        {
            public CalculateAgeAsync(IPropertyInfo birthYearProperty, IPropertyInfo ageProperty)
                : base(birthYearProperty)
            {
                AgeProperty = ageProperty;

                InputProperties = new List<IPropertyInfo> { birthYearProperty };

                AffectedProperties.Add(AgeProperty);
            }

            public IPropertyInfo AgeProperty { get; }

            protected override async Task ExecuteAsync(IRuleContext context)
            {
                var birthYear = Convert.ToInt32(context.InputPropertyValues[PrimaryProperty]);

                await Task.Delay(10).ConfigureAwait(true);

                var age = DateTime.Today.Year - birthYear;
                context.AddOutValue(AgeProperty, age);
            }
        } 
```

As PropertyInfos are static, its value can be accessed by nested classes.

**Comment by JacoJordaan** [comment]
Ok, its a nested class.
I have run the project on Framework 4.7.2 and also get inconsistent behaviour.
The behaviour I see is that with the async rule, the textbox is updated with the value of the previous calculation.

**Comment by Eduardo-Micromust** [comment]
I tried to fix it but calling OnPropertyChanged in the thread that updated the property can cause a deadlock in a non-WinForm / non-WPF and the thread is busy. 
Csla should fire OnPropertyChanged on WinForm / WPF main thread if this thread updated the property.

**Comment by rockfordlhotka** [comment]
I agree that this is a problem.

I am not yet sure how to fix it. Remember that this code needs to work in scenarios where there is no sync context too (like console apps, services, etc.).

**Comment by rockfordlhotka** [comment]
This appears to fix the issue.

https://github.com/MarimerLLC/csla/pull/1643/commits/5e370500649ed339d6af3ef2ebd89a83b5e18887

**Comment by Eduardo-Micromust** [comment]
@rockfordlhotka Your change fixes the issue but I'm not sure if it can cause a deadlock in a non-WPF/non-WinForm thread. In Csla 4.x I had a bug with some async rules that never finished and I believe it was caused by a deadlock issue as described in https://devblogs.microsoft.com/dotnet/configureawait-faq/

I suggest the following:

```
    private async void RunAsyncRule(IBusinessRuleAsync asyncRule, IRuleContext context)
    {
      // Somehow detect if the current thread is a UI Thread
      if (System.Threading.Thread.CurrentThread.ManagedThreadId != 1)
      {
        //Non UI Thread
        await asyncRule.ExecuteAsync(context).ContinueWith(t => context.Complete());
      }
      else
      {
        // UI Thread
        await asyncRule.ExecuteAsync(context);
        context.Complete();
      }
    }

```

**Comment by rockfordlhotka** [comment]
I'd like to prove that it is a problem before adding complexity to the code.

**Comment by Eduardo-Micromust** [comment]
I wrote a test to prove my theory but the rule finished as expected. I think your fix closes this issue.

**Comment by Eduardo-Micromust** [comment]
One last suggestion: a try finally block to garantee that context.Complete
will always be called.

Em sex, 22 de mai de 2020 00:07, Rockford Lhotka <notifications@github.com>
escreveu:

**Comment by rockfordlhotka** [comment]
Good idea @Eduardo-Micromust - done!
