### ISSUE TITLE
New SaveAndMergeAsync methods not exposed via ISavable and ISavable<T>

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#1655]
We interact with our CSLA objects via interfaces defined in CSLA, as that allows the code that consumes the classes to be more easily targeted using automated unit tests. Recently the SaveAndMergeAsync methods were added to support merging changes back into the original object. We'd now like to make use of these methods to simplify some of our consumers, but the methods are not accessible via the ISavable and ISavable<T> interfaces, so they are not available to us.

Adding these new methods onto an interface would probably be considered a breaking change, because custom fake objects that do not implement these members would not compile, although real objects inheriting from CSLA base classes would be unaffected. C# 8 now supports the addition of interface members with default implementations, so this could be used to help overcome the compile-time failure. However, it might be that we are trying to avoid the need to use the most modern language features. If that's the case, then should we consider adding another interface for the new methods?

Solutions could be based around the C# 8 feature of interface methods with default implementations if use of C# 8 is acceptable. The alternative is the addition of a new, separate interface through which this new functionality can be accessed.

**Comment by Chicagoan2016** [comment]
@TheCakeMonster, Years ago I looked into something similar to DiffGram Sample. Is SaveandMerge serve same purpose? Any suggestions on how we could use SaveandMerge?
Thank you for your help.

**Comment by TheCakeMonster** [comment]
I've not looked at the DiffGram sample to which you refer, but I've read a thread on the old forum and it looks like that might have been about sending subsets of changes from client to server. I don;t think that is the same thing.

SaveAndMergeAsync() is a new(ish) alternative to the SaveAsync() method, Normally when you send an object through the dataportal as part of a save, the object returned from the SaveAsync() method is a _different_ object from the one you sent in. That forces you to update all of your references to the object, including rewiring any event handlers you might have in your application. In short, the SaveAsync() method returns an entirely new object instance.

SaveAndMergeAsync() attempts to overcome this by merging the changes from the object returned by the server-side dataportal back into the _original_ object instance. This saves you having to update any references to the object, or needing to rewire any event handlers.

I'm still learning about SaveAndMergeAsync, such as if there might be any scenarios when it won't work, but so far I can see significant advantages in user interfaces that are using binding to update themselves.

**Comment by TheCakeMonster** [comment]
The new method is mentioned at http://www.lhotka.net/weblog/CSLANETVersion49NewFeatures.aspx although this post largely explains that it is based upon a class that already existed, so there isn't all that much detail.
