### ISSUE TITLE
Enable gRPC data portal channel in Blazor

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1699]
https://devblogs.microsoft.com/aspnet/grpc-web-for-net-now-available/

**Comment by rockfordlhotka** [comment]
https://medium.com/@waelkdouh/how-to-utilize-grpc-web-from-a-blazor-webassembly-application-e8313444f75b

**Comment by rfcdejong** [comment]
Looks good

**Comment by rockfordlhotka** [comment]
Closing due to lack of interest.
