### ISSUE TITLE
Operation Arguments Should be Serializable....AGAIN

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#1732]
**Describe the bug**
Apparently I can't create an analyzer to check for serialization :(

**Version and Platform**
CSLA version: 5.2.0
OS: Windows (but probably exists everywhere).
Platform: doesn't matter

**Code that Fails**
```
[Fetch]
private async Task FetchAsync(Guid id, [Inject] IContext context)
```

I'm getting the analyzer error CSLA0010 that says `id` should be serializable. And since I wrote the analyzer, it's my fault :(. I'm guessing I'm not looking for `Guid` as a "known" type that is serializable, but I don't know for sure.

**Stack Trace or Exception Detail**
None

**Additional context**
Sorry

**Comment by JasonBock** [comment]
Just to check, I changed the parameter type to `int`, and that's fine, so again, I think it's an issue for specific types like `Guid`.

**Comment by JasonBock** [comment]
Sure enough, `Guid` isn't in the list: https://github.com/MarimerLLC/csla/blob/b1f49e7d794761cf1e3b5fe11ee0d30b2aca48ec/Source/Csla.Analyzers/Csla.Analyzers/Extensions/ITypeSymbolExtensions.cs#L71. I guess the other checks for a `Guid` type don't work here either. Sad :(

I don't want to assume all value types are serializable, but I don't want to create a long-running list of types here that we think *should* be serializable either. @rockfordlhotka, thoughts?

**Comment by rockfordlhotka** [comment]
I think we have (in `MobileFormatter`?) a method that does list all the "serializable" types we consider primitive. Can you use that?

**Comment by JasonBock** [comment]
I'm guessing you're referring to the types in `CslaBinaryWriter.Write()`. Even if there was a helper method that gave me a list of all the "special" types, the analyzers project doesn't reference `Csla`, so the best I can do is to duplicate the list in the analyzer.

**Comment by rockfordlhotka** [comment]
Although not ideal, we could separate that code into its own function and _physical file_, thus allowing us to link the file into the analyzer project. A little weird, but at least changing the code would only be done in one place.

**Comment by JasonBock** [comment]
I don't think that would help. The serializer is switching on different types to incorporate different serialization strategies; I'm in the Compiler API where you really don't deal too much with a `Type` per-se, plus I just need a list. I think it'll be easier to keep the two worlds separate.
