### ISSUE TITLE
ViewModelBase always raises PropertyChanged for IsBusy & Model, even if they are set to the same values

### ISSUE THREAD

**Issue by ajohnstone-ks** [MarimerLLC/csla#1767]
**Describe the bug**
If savable.SaveAsync finishes fine, IsBusy is set to false; but there's also an IsBusy = false in the finally block, resulting in the property being set false twice.

Model also raises PropertyChanged even if set back to the exact same instance.

Also, the IsBusy setter does not check that the value of IsBusy is actually changing, and so setting it to the value it already contains causes a PropertyChanged event to be raised as well as the logic on OnSetProperties.

**Version and Platform**
CSLA version: 5.3.0
OS: All
Platform: All

**Code that Fails**
https://github.com/ajohnstone-ks/ViewModelBaseIsBusyBug

**Stack Trace or Exception Detail**
n/a

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka Hopefully it was ok to create this; this actually causes an issue for us, because when IsBusy changes on the VM, we publish a message which the app picks on and can cause other behaviors to trigger, plus any bindings to the VMs IsBusy will be triggered too.

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka I just noticed the same thing with Model; if you set it to the same instance it already has, it redoes all the work.  Should I update this issue to reflect that or create a new one?

**Comment by rockfordlhotka** [comment]
Probably update this issue is fine - it seems like the same basic problem.

**Comment by ajj7060** [comment]
I'll take this up, please assign to me.

**Comment by ajj7060** [comment]
I think I have this ready, but I'm not sure where to put the pull request.

**Comment by rockfordlhotka** [comment]
Please pull into master. I was going to make that v6, but work has been crazy, so it can be for a couple bug fixes right now.
