### ISSUE TITLE
Propertyrule not executed

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#1796]
**Describe the bug**
After some period of time, normally detect more than a day of executing desktop app, the propertyrules not working.
SetProperty execute but not execute a PropertyRule

**Version and Platform**
CSLA version: 5.2.0
OS: Windows
Platform: WPF

**Code that Fails**

The object has a property

        Public Shared ReadOnly FechaTProperty As PropertyInfo(Of DateTime?) = RegisterProperty(Of DateTime?)(Function(c) c.FechaT)
        Public Property FechaT() As DateTime?
            Get
                Return GetProperty(FechaTProperty)
            End Get
            Set(ByVal value As DateTime?)
                SetProperty(FechaTProperty, value)
            End Set
        End Property

        Protected Overrides Sub AddBusinessRules()
            MyBase.AddBusinessRules()
            BusinessRules.AddRule(New TerminadoRule())
            BusinessRules.AddRule(New TerminadoFechaRule())
        End Sub

       <Serializable()>
        Public Class TerminadoRule
            Inherits PropertyRule

            Public Sub New()
                MyBase.New(TerminadoProperty)

                If InputProperties Is Nothing Then
                    InputProperties = New List(Of IPropertyInfo)()
                End If
                InputProperties.Add(TerminadoProperty)
                InputProperties.Add(FechaTProperty)
                AffectedProperties.Add(FechaTProperty)

                IsAsync = False

                CanRunAsAffectedProperty = False ' only run when this property is changed 
                CanRunInCheckRules = False ' when true will also run in CheckRules
                CanRunOnServer = False ' when true will also run on logical serverside (Data Access)
            End Sub

            Protected Overrides Sub Execute(context As IRuleContext)
                Dim terminado As Boolean = context.InputPropertyValues(TerminadoProperty)
                Dim fechat As DateTime? = context.InputPropertyValues(FechaTProperty)
                Try
                    If terminado = True Then
                        If fechat.HasValue = False Then
                            context.AddOutValue(FechaTProperty, Date.Today)
                        End If
                    End If
                Catch ex As Exception
                    context.AddErrorResult("Error al validar la fecha terminado")
                End Try
            End Sub
        End Class

**Stack Trace or Exception Detail**
Not exception, all bussiness object suffer same situation, not validate any rule on application business

**Additional context**
This error I observe from latest versions from upper 4.7.200.
I don't know why dont launch the rules but client applicatons need to close and reopen application for work properly

**Comment by rockfordlhotka** [comment]
There was a discussion about this in the Discussions tab in this repo, about 2 weeks ago. The problem turned out to be a rule that was throwing an unhandled exception (I think it was an async rule maybe?).

**Comment by rockfordlhotka** [comment]
@ProDInfo did that discussion thread help resolve your issue?
