### ISSUE TITLE
Fix Analyzer build warnings

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1897]
The new version of VS and .NET 5 is causing a set of build warnings for the analyzer project.

```text
Severity	Code	Description	Project	File	Line	Suppression State
Warning	RS1032	The diagnostic message should not contain any line return character nor any leading or trailing whitespaces and should either be a single sentence without a trailing period or a multi-sentences with a trailing period	Csla.Analyzers	E:\src\rdl\csla\Source\Csla.Analyzers\Csla.Analyzers\AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzer.cs	18	Active
```

I'm not sure what this means, and am hoping @JasonBock has some insight.

**Comment by JasonBock** [comment]
I'm guessing it's saying that the diagnostic message shouldn't have line return characters or leading/trailing whitespace and it should be a single sentence.

:P

Probably a new analyzer they added for .NET 5.0. You can change the diagnostic messages to fit the expected pattern, or ignore RS1032 in your .editorconfig.

**Comment by JasonBock** [comment]
Look at `AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerConstants.Message`. The string ends with a period. That's the "issue". Your call on how you want to fix it.
