### ISSUE TITLE
Error in Blazor ProjectTracker 5.3.1 -> 5.3.2

### ISSUE THREAD

**Issue by uwefms** [MarimerLLC/csla#1911]
Hi everybody,

  when trying to upgrade ProjectTracker to 5.3.2, I get the following error in serverside Blazor at login.

![image](https://user-images.githubusercontent.com/13874580/99183831-1b565e00-273f-11eb-82f4-a1dee3b119ee.png)

There was no problem in 5.3.1. Is there anything that has to be changed in the source ?

   regards

       Uwe

**Comment by rockfordlhotka** [comment]
Thank you for the report, I hope to have time to spend working on CSLA tomorrow.

**Comment by rockfordlhotka** [comment]
I strongly suspect it is due to dependency conflicts. Keeping all the dependencies in sync turns out to be quite challenging! I just today finally (🤞🤞🤞) got them all sorted for the upcoming 5.4.0 release, and I'm updating ProjectTracker to target that version to double-check.

**Comment by uwefms** [comment]
Rocky,

  thanks a lot for your work. will keep testing after the 5.4.0 release.

   Uwe
