### ISSUE TITLE
Consider returning list of string from Blazor.PropertyInfo.ErrorText

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1975]
As per https://github.com/MarimerLLC/csla/discussions/1972

> Having said that I would prefer if Csla.Blazor.IPropertyInfo.ErrorText and it's siblings returned a collection of strings. An implicit ToString could join them with a comma/space.
> It would be nice to have a Name property in IPropertyInfo so it can easily be used as an id in HTML elements.

**Comment by j055** [comment]
What about adding 3 extra properties:

```
ErrorCollection
WarningCollection
InformationCollection
```
Or
```
ErrorList
WarningList
InformationList
```
Or (but horrible)
```
Errors
Warnings
Informations
```
Potentially deprecate the others?

**Comment by rockfordlhotka** [comment]
Really, we could just return the `BrokenRules` collection and the UI can filter and manipulate it as desired.
