### ISSUE TITLE
AuthorizationRule authorization specification changes

### ISSUE THREAD

**Issue by angtianqiang** [MarimerLLC/csla#1982]
**Version and Platform5.3.2
OS: Windows
Platform:  WPF,

  BusinessRules.AddRule(new ZtxFrameWork.Business.Security.CostAuthorizationRule(Csla.Rules.AuthorizationActions.ReadProperty, PriceProperty, “saleOrder"));

After the CSLA version was upgraded, the Price attribute of the business class was read and an exception was thrown. The previous version would return the default value. Has the logic here been changed?

**Comment by rockfordlhotka** [comment]
What exception?

**Comment by angtianqiang** [comment]
Oh, finally find out the problem is my business code, thank you Rockfordlhotka
