### ISSUE TITLE
ApplicationContext.User lost inside razor component when switching to Azure SignalR Service

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#2007]
**Describe the bug**
A `Csla.Security.SecurityException` is thrown when calling a BO factory method from inside a Server-side Blazor Razor Component after switching to use a Azure SignalR Service. 

**Version and Platform**
CSLA version: 5.4
.NET 3.1

**Code that Fails**

If the BO contains an auth rule:
```
private static void AddObjectAuthorizationRules()
{
    BusinessRules.AddRule(typeof(Bo), new IsInRole(AuthorizationActions.CreateObject, "Admin"));
}
```

```   
protected override async Task OnParametersSetAsync()
{
    await Vm.RefreshAsync(Bo.NewAsync);  // Csla.Security.SecurityException thrown
}
```

**Stack Trace or Exception Detail**
`Exception thrown: 'Csla.Security.SecurityException' in System.Private.CoreLib.dll`

**Additional context**

It looks like CSLA is trying to get the User context from the HttpContext via:

https://github.com/MarimerLLC/csla/blob/6b84de769f085deacbb3ffa9f752252735ddd766/Source/Csla.AspNetCore.Shared/ApplicationContextManager.cs#L50

`HttpContext` is not supposed to be used over a SignalR connection, see article: 

* https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#blazor-and-shared-state

**Comment by j055** [comment]
Moving to discussions because I'm not convinced it's a bug with CSLA

**Comment by rockfordlhotka** [comment]
I haven't ever tried this @j055.

How does the server get the user principal/identity when using SignalR?

**Comment by j055** [comment]
I think the article is suggesting you grab what state you need from `HttpContext` on initial page render and pass a custom class to the root razor component which will look after it while the client is connected to the SignalR service, wherever it may be. 

I'm wondering if we can keep this state in memory and reference it using the `Circuit` `Id` by implementing a custom `CircuitHandler`?

https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-5.0

I haven't really got my head round it yet though - still at the 'bouncing ideas around' stage. Questions so far:

* Would we need a new `IContextManager` - what does implementation look like? 
* Can we avoid creating a custom `ComponentBase` to set `ApplicationContext` properties?
* Does `AuthenticationStateProvider` help -  https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#implement-a-custom-authenticationstateprovider
* What about `LocalContext` and `ClientContext`?

I'm sure there a more?!

**Comment by j055** [comment]
Continued in [discussions](https://github.com/MarimerLLC/csla/discussions/2008)
