### ISSUE TITLE
HttpProxy compression code doesn't work with custom HttpClient

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2075]
The compression code added in #1881 causes a problem when using a custom `HttpClient` object.

> This new code broke our code at runtime with exception "Specified argument was out of range of valid values. Parameter name: Unhandled CSLA Known type was found"
> 
> This is because we override GetHttpClient() to create an own HttpClient to pass along the client's AccessToken.
@rockfordlhotka Perhaps add a boolean property to add the compression headers or not?

@rfcdejong I don't understand the "fix" in your comment in #1881, can you explain more completely?

Also, I wonder if there is a better solution for compression (and the token stuff) by using DI in CSLA 6? My thought there is to require that the `HttpClient` instance be injected, so any customization of the client would occur during app initialization.

**Comment by rfcdejong** [comment]
Every request to the server has the following headers added

httpRequest.Headers.Add("Accept", "*/*");
httpRequest.Headers.Add("Accept-Encoding", "gzip,deflate,*");

Our custom HttpClient doing the request did not have "AutomaticDecompression" on
That being said, the Proxy should set AutomaticDecompression on to a custom HttpClient being injected by DI or in GetHttpClient().

This pull caused the nasty bug
https://github.com/MarimerLLC/csla/pull/1882/files

PS: My local IIS didn't dynamicly compress, but our hosting environment did so our dev and test both stopped working for a bit until I started digging into the CSLA commits ;)

I know it would be better to inject with something like this, but this will also go wrong because of missing AutomaticDecompression being on.

            builder.Services.AddHttpClient("MyCustomHttpClient", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

**Comment by rockfordlhotka** [comment]
I want to think through any change or fix before implementing it, as I want to make sure we still meet the needs of @BlagoCuljak, while also fixing the regression bugs that were introduced by the change.

I think there might be short-term (CSLA 5) and long-term (CSLA 6) fixes that are different.

In CSLA 5, the easiest solution might be to have a config flag, or a virtual method, where the request headers are set?

In CSLA 6, the more of this sort of config that can happen in Startup.cs (or equivalent) the better.

**Comment by rockfordlhotka** [comment]
I think the mistake in the #1881 implementation is that the compression stuff is hard-coded. In fact, it should be done via a subclass.

1. `GetHttpClient` is virtual, so there was no need to change this method, as a subclass could have configured the new HttpClient
2. `GetWebClient`  is virtual, so there was no need to change this method, as a subclass could have configured the new WebClient
3. The change should have been to provide a virtual method so the [HttpRequestMessage](https://github.com/MarimerLLC/csla/blob/a68e4998e93e9146ab6be1d87aa2fe4549ab50a2/Source/Csla.Shared/DataPortalClient/HttpProxy.cs#L429) can be altered by a subclass; though why this is necessary is confusing - does it not inherit the headers from the `HttpClient`? And if not, then what's the point of setting them on the client?

@rfcdejong and @BlagoCuljak, does this make sense to you? I think I'm on the right track here, at least for CSLA 5.

**Comment by rfcdejong** [comment]
Much in that pull request is hardcoded and cannot be configured back into the old behavior, also some weird code in DataportalController InvokePortal method setting the Content-type header.

1. True (the reason I wrote my comment)
2. True
3. Perhaps it should be fixed together by a boolean: UseCompression and use that to add the headers. Or perhaps introduce virtual methods that add headers to each request?
4. Same idea.

**Comment by rockfordlhotka** [comment]
The boolean idea would be (imo) a hack, because it is one of many things I could imagine someone might want to alter about the headers. This is why I think the virtual method approach is the right answer.

**Comment by BlagoCuljak** [comment]
We if you have some better suggestion, I can try out and test the new version of code. So far, compression really worked for us, but if we're about to introduce more security issues and configuration problems for other folks, I'm willing to revise the code and test once again.

**Comment by rockfordlhotka** [comment]
I've created a PR for CSLA 5 that uses subclassing to keep the original behavior, plus adds a new `HttpCompressionProxy` with the new behavior.

https://github.com/MarimerLLC/csla/pull/2085

Please review and let me know if you think this will work for both of your needs.

(I'm still working on a more elegant/modern solution for CSLA 6, hopefully relying more on DI and less on inheritance)

**Comment by rockfordlhotka** [comment]
I added an extensibility point to the `HttpPortalController` type, so the controller can override a `SetHttpResponseHeaders` method, in which someone would do this:

```c#
  protected override void SetHttpResponseHeaders(HttpResponse response)
  {
    response.Headers.Add("Accept-Encoding", "gzip,deflate");
  }
```

Or add any other headers necessary for things like security, etc.
