### ISSUE TITLE
Csla.Analyzers Solution Can't Be Compiled

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#2106]
**Describe the bug**
See the title :)

**Version and Platform**
CSLA version: Latest from GitHub
OS: any
Platform: any

**Code that Fails**
I got latest, tried to build Csla.Analyzers.sln, and two things pop up:

* It's still trying to load Csla.NetStandard2.0, which apparently doesn't exist anymore.
* Csla.Analyzers.Tests can't build because it's trying to load "..\..\Csla\Csla.csproj", which for whatever reason can't be found. The project does exist, but maybe the path is incorrect?

After talking to Rocky, apparently this stuff isn't being built by csla.test.sln, and it probably should.

**Comment by rockfordlhotka** [comment]
The problem is isolated to the csla.analyzers.sln, which still references the (now removed) csla shared netstandard code. With that project removed from the solution, the solution builds as expected.

**Comment by JasonBock** [comment]
I don't think this is fixed. I updated my fork with the fix, but I'm still getting this error:

```
Unable to find project information for 'C:\Users\jason\source\repos\csla\Source\Csla\Csla.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	Csla.Analyzers.Tests	C:\Users\jason\source\repos\csla\Source\Csla.Analyzers\Csla.Analyzers.Tests\Csla.Analyzers.Tests.csproj	1	
```

In `Csla.Analyzers.Tests`, there's this:

```
<ProjectReference Include="..\..\Csla\Csla.csproj" />
```

I think the path **is** correct (I originally thought it wasn't but I checked and it is there), but it's not part of the solution.
