### ISSUE TITLE
Blazor WASM Breakpoints Not Hit When Using HasPermission Attribute

### ISSUE THREAD

**Issue by saulyt** [MarimerLLC/csla#2110]
**Describe the bug**
Breakpoints not hit anywhere when using the HasPermission attribute.

**Version and Platform**
CSLA version: 5.4.1
OS: Windows
Platform: Blazor WASM

**Code that Fails**
If a CSLA HasPermission attribute is placed on any Blazor component, no breakpoints are hit in any Blazor components anywhere in the project (not just the one with the attribute.) They all say unbound breakpoint. It the attribute is removed, everything returns to normal.

I created a repository to demonstrate this. It is the ProjectTracker solution with only the projects necessary to run the Blazor Client app. I also updated it to .NET 5.0. The only place the HasPermission attribute is used in the app is on Roles.razor. I have it commented so that the breakpoints currently work. It you uncomment the attribute and rerun the app you should see the issue.

https://github.com/saulyt/CSLA_ProjectTracker

**Comment by rockfordlhotka** [comment]
Based on our conversation in gitter, @saulyt appears to have narrowed this down to an issue where debugging generally fails in Blazor wasm when any enum is passed to an attribute.

Given that, until (or if) Microsoft fixes that issue, it seems reasonable to think that the CSLA implementation needs to change the enum to a static class containing a set of static int const values - basically a low-tech replacement for an enum.

**Comment by saulyt** [comment]
Bug report files with MS
https://github.com/dotnet/aspnetcore/issues/30281

**Comment by saulyt** [comment]
They just closed the issue as duplicate.  [Someone else already reported it](https://github.com/dotnet/runtime/issues/47792). Fix is planned for 6.0.
