### ISSUE TITLE
Csla.ApplicationContext.User Not Automatically Set -Blazor Server

### ISSUE THREAD

**Issue by MarkOverstreet** [MarimerLLC/csla#2115]
On page 137 of your blazor book it indicates that the Csla.ApplicationContext should automatically be set but it is empty when I inspect it after using your example code in Project Tracker including the CredentialValidator class.

**Version and Platform**
CSLA version: 5.4.1
OS: Windows 10 (Development)
Platform: Blazor Server

**Code that Fails**
```
    [CascadingParameter] protected Task<AuthenticationState> AuthState { get; set; }
    protected async override void OnInitialized()
    {
        Console.WriteLine(Csla.ApplicationContext.User.Identity.Name);   // The user is not authenticated and no information was automatically picked up from the login process.  Blazor pages are working and I can get the user by using the cascading parameter as seen above.
    }

```
**Stack Trace or Exception Detail**
No errors are thrown.

**Additional context**
None.

**Comment by rockfordlhotka** [comment]
The way this is _supposed_ to work, is that `ApplicationContext.User` gets its value from `HttpContext` when running in an ASP.NET context.

That relies on the project referencing the `Csla.AspNetCore` package, and the correct application context manager being set. That context manager should be set automatically, but perhaps that's not happening?

**Comment by j055** [comment]
You can't use `HttpContext` and therefore `ApplicationContext` in a Razor Component

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state

**Comment by rockfordlhotka** [comment]
Digging into this today, and I think the only real answer is to revive #1068 - which is a major breaking change and must go into CSLA 6. This change would mean `Csla.ApplicationContext` becomes an instance type, not a static type, so all code relying on the type is affected, including _your code_.

@MarkOverstreet there is a sort-of-workaround, in that if you don't use `Csla.ApplicationContext.User` (or any of the context dictionaries) you can do something along the line of [this SO post](https://stackoverflow.com/questions/63911978/access-authenticationstate-in-blazor-server-to-update-components-in-a-single-pla).

That's basically what an instance-based CSLA `IContextProvider` will do as well - rely on DI to get the scoped `AuthenticationStateProvider` from Blazor.

**Comment by rockfordlhotka** [comment]
I'm closing this issue in favor of #1068
