### ISSUE TITLE
Business Rule executing a Command fails on Blazor with: System.Net.WebClient is not supported on this platform. Use System.Net.Http.HttpClient instead.

### ISSUE THREAD

**Issue by adrianwright109** [MarimerLLC/csla#2158]
I have created a `Command` object called `ClientExistsCommand`
```
    [Serializable]
    public class ClientExistsCommand : CommandBase<ClientExistsCommand>
    {
        public static readonly PropertyInfo<int> ClientIdProperty = RegisterProperty<int>(c => c.ClientId);
        private int ClientId
        {
            get => ReadProperty(ClientIdProperty);
            set => LoadProperty(ClientIdProperty, value);
        }

        public static readonly PropertyInfo<string> ClientNameProperty = RegisterProperty<string>(c => c.ClientName);
        private string ClientName
        {
            get => ReadProperty(ClientNameProperty);
            set => LoadProperty(ClientNameProperty, value);
        }

        public static readonly PropertyInfo<bool> ClientExistsProperty = RegisterProperty<bool>(c => c.ClientExists);
        public bool ClientExists
        {
            get => ReadProperty(ClientExistsProperty);
            private set => LoadProperty(ClientExistsProperty, value);
        }

        [Create]
        private void Create(int clientId, string clientName)
        {
            ClientId = clientId;
            ClientName = clientName;
        }

        [Execute]
        private void Execute([Inject] IClientRepository clientRepo)
        {
            ClientExists = clientRepo.Exists(x => x.CL_ClientID != ClientId && x.CL_ClientName.Equals(ClientName, StringComparison.OrdinalIgnoreCase));
        }
    }
```

This command is then executed with a custom `BusinessRule` I have created called `ClientNameIsUnique`
```
    internal class ClientNameIsUnique : BusinessRule
    {
        internal ClientNameIsUnique(IPropertyInfo clientIdProperty,
            IPropertyInfo clientNameProperty)
        :base(clientNameProperty)
        {
            ClientIdProperty = clientIdProperty;
            ClientNameProperty = clientNameProperty;
        }

        private IPropertyInfo ClientIdProperty { get; }
        private IPropertyInfo ClientNameProperty { get; }

        protected override void Execute(IRuleContext context)
        {
            var clientId = (int)ReadProperty(context.Target, ClientIdProperty);
            var clientName = (string)ReadProperty(context.Target, ClientNameProperty);

            if (ClientEdit.Exists(clientId, clientName))
            {
                context.AddErrorResult($"Client Name '{clientName}' already exists.");
            }
        }
    }
```

On the edit object `ClientEdit` I have added the business rule:
```
        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();

            BusinessRules.AddDataAnnotations();

            //check client name doesn't already exist in the database.
            BusinessRules.AddRule(new ClientNameIsUnique(ClientIdProperty, ClientNameProperty));
        }
```

On the Blazor edit page if I edit the ClientName so that matches a ClientName already in the database (e.g. 'DUPLICATE'), 

I'm expecting to see the error:
Client Name 'DUPLICATE' already exists.

Actual:
![image](https://user-images.githubusercontent.com/47532258/111314031-ee687800-8658-11eb-9d1e-eec3ddfc5681.png)

N.B. If I edit the record in the database so that it has a ClientName the same as another record and then load up the edit page the error message displays as expected.  The issue seems to be when editing the value in the `<input />` tag on screen.

**Comment by rockfordlhotka** [comment]
There must be some code path that causes `HttpProxy` to invoke the webclient method instead of the httpclient method.

Are you, by chance, trying to make a sync call in the data portal? I am pretty sure the webclient path occurs when someone tries to do a sync data portal call.

**Comment by adrianwright109** [comment]
It seems to be falling over on line 19 of the Async BusinessRule:
![image](https://user-images.githubusercontent.com/47532258/112159313-eff9e900-8be0-11eb-9bf2-da4e4d9e3a30.png)

`context.Target` is null

**Comment by adrianwright109** [comment]
Ok so I have fixed the null `context.Target` by setting `ProvideTargetWhenAsync = true;` in the constructor of the `ClientNameIsUnique` `BusinessRuleAsync`.

But after turning everything `Async` I'm still getting the error:
```
System.PlatformNotSupportedException: System.Net.WebClient is not supported on this platform. Use System.Net.Http.HttpClient instead.
```

When I search for the `WebClient` in the CSLA codebase I find that it is used in `Csla.DataPortalClient.HttpProxy.cs` class.

There looks to be logic in there that switches between `System.Net.WebClient` and `System.Net.Http.HttpClient` based on a `isSync` parameters.

```
    private async Task<byte[]> CallDataPortalServer(byte[] serialized, string operation, string routingToken, bool isSync)
    {
      if (isSync)
        serialized = CallViaWebClient(serialized, operation, routingToken);
      else
        serialized = await CallViaHttpClient(serialized, operation, routingToken);
      return serialized;
    }
```

To me it looks like this `isSync` parameter is always hardcoded to true - is that correct ?

How can I set `isSync` to `false` ?

**Comment by rockfordlhotka** [comment]
You don't manually set `isAsync` - it is set depending on whether you use a sync or async data portal call.

You do have a sync data portal call still

```c#
var cmd = DataPortal.Create<ClientExistsCommand>(clientId, clientName);
```

Maybe that's the trigger?

**Comment by adrianwright109** [comment]
Good spot.

Yes you're right I still had a sync `Create` call.  I have now changed it to `CreateAsync` and its working as expected.

**Comment by adrianwright109** [comment]
Just for my own learnings why are DataPortal `Sync` calls not support in Blazor?

**Comment by TheCakeMonster** [comment]
@adrianwright109 That's a good question. I think the problem is that HttpClient doesn't offer synchronous execution methods - so it's a limitation of networking in the underlying infrastructure, rather than that Blazor WebAssembly doesn't support it per se.

I've just run into the same problem, with a validation that uses a read-only list of data loaded from the database, and then heavily cached. It's called from a Data Annotations attribute that I have built, and as far as I know, Data Annotations cannot execute asynchronously. The caching means that the call will almost always execute locally, but just needs to perform data access on the first call. It's a pain to explain to users of my component that they need to work around this limitation, so I'm not in a great place.

Like you, I could change my validation rule to be an async business rule instead of a Data Annotations rule, but that's much less user friendly, and almost not necessary because of the caching that I perform.
