### ISSUE TITLE
Configuration UseCsla() change from HostBuilder to IHostBuilder

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#2171]
Please consider change in configuration the  UseCsla() extension from hostBuilder to IHostBuilder.

The next example don't work properly, because the CreateDefaultBuilder return IHostBuilder :
`

    IHost host = Host.CreateDefaultBuilder(args)
                    .UseCsla((config) =>
                    {
                        config
                            .PropertyChangedMode(Csla.ApplicationContext.PropertyChangedModes.Windows)
                            .DataPortal()
                                .DefaultProxy(typeof(Csla.DataPortalClient.LocalProxy), null);
                    })
                    
`
Thanks

**Comment by rockfordlhotka** [comment]
Thank you @adrianwright109 - glad you did this so fast!
