### ISSUE TITLE
Getting gRPC with Blazor configured to fix Request protocol 'HTTP/1.1' is not supported

### ISSUE THREAD

**Issue by richardbartley** [MarimerLLC/csla#2225]
What is the correct configuration for a Blazor client and server to us the gRPC protocol in the DataPortal in NET5?
I have the Microsoft samples working correctly to eliminate any machine specific/IIS 10.0 errors.

Currently my requests, debugging with VS2019 Preview 2.0 and running in IISExpress are failing with:

```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Request protocol 'HTTP/1.1' is not supported.")
   at Csla.Channels.Grpc.GrpcProxy.CallDataPortalServer(Byte[] serialized, String operation, String routingToken, Boolean isSync)
   at Csla.Channels.Grpc.GrpcProxy.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.<DoFetchAsync>d__18[[MB5.Shared.NVLists.UserEnvironmentNVList, MB5.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
```

Server is doing services setup

```
services.AddGrpc();
...
app.UseRouting();
            app.UseGrpcWeb();
            app.UseCors(BlazorClientPolicy);
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<Csla.Channels.Grpc.GrpcPortal>().EnableGrpcWeb();
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("index.html");
            });
```

Blazor client app sets the channel proxy.

```
builder.UseCsla(c =>
              c.DataPortal().DefaultProxy(
                typeof(Csla.Channels.Grpc.GrpcProxy), "https://localhost:44345"));
```

**What am I missing here?**

Request as shown with Fiddler.

```
POST https://localhost:44345/Csla.Channels.Grpc.GrpcService/Invoke HTTP/1.1
Host: localhost:44345
Connection: keep-alive
Content-Length: 1235
grpc-accept-encoding: identity,gzip
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
content-type: application/grpc
Accept: */*
Origin: https://localhost:44345
```

Response

```
HTTP/1.1 426 Upgrade Required
Transfer-Encoding: chunked
Upgrade: HTTP/2
Server: Microsoft-IIS/10.0
Grpc-Status: 13
Grpc-Message: Request protocol 'HTTP/1.1' is not supported.
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Grpc-Status,Grpc-Message,Grpc-Encoding,Grpc-Accept-Encoding
```

**Comment by richardbartley** [comment]
†IIS requires .NET 5 and Windows 10 Build 20241 or later.
‡HTTP.sys requires .NET 5 and Windows 10 Build 19529 or later.

Does this mean I effectively need to be running Insiders Preview latest Windows 10 OS builds?

**Comment by richardbartley** [comment]
Seems the Microsoft samples run on my home PC, Windows 20H2 but work is running Windows 10 Enterprise 1909 which does not work.

**Comment by rockfordlhotka** [comment]
fwiw, gRPC, for the data portal, is really not different from http. In both cases the MobileFormatter is used to create a byte stream that is transferred as binary (or text when on Blazor wasm) over the network transport.

As a result, the gRPC and http channels are essentially identical, in that they are the network transport, being used to flow the _exact same byte stream_.

**Comment by richardbartley** [comment]
OK, so performance is pretty much the same anyway, so I'm good.
Thanks.
