### ISSUE TITLE
The system cannot find the specified file

### ISSUE THREAD

**Issue by 455986780** [MarimerLLC/csla#2229]
Hello!
I have a published project in IIS. To add a new function, I need to add a new DLL file.

I use "projectTracker" as an example to describe the problem.

When I do not refer to the DLL in "projecttracker. Appservercore", I will be prompted with the following error message:

“"Could not load file or assembly 'Test1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the specified file。":"Test1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"}”

I tried to change the following code to run normally.

Csla.Reflection.MethodCaller

        public static Type GetType(string typeName, bool throwOnError, bool ignoreCase)
        {
            string fullTypeName;
            fullTypeName = typeName;
            return Type.GetType(fullTypeName, throwOnError, ignoreCase);
       }
       
        public static Type GetType(string typeName, bool throwOnError, bool ignoreCase)
        {
            string fullTypeName;
            fullTypeName = typeName;
            try
            {
                return Type.GetType(fullTypeName, throwOnError, ignoreCase);
            }
            catch (Exception err)
            {
                string[] astrTmp = fullTypeName.Split(',');
                if (astrTmp.Length > 2)
                {
                    var asm = AssemblyLoadContext.Default.LoadFromAssemblyPath(AppContext.BaseDirectory + astrTmp[1].Trim() + ".dll");
                    return asm.GetType(astrTmp[0].Trim());
                }
                else
                    throw err;
            }
        }

**Version and Platform**
CSLA version: 5.4.1
OS: Windows
Platform: WinForms

We need to copy and upgrade in some cases. We look forward to improving it. Thank you!

**Comment by rockfordlhotka** [comment]
This is the way aspnet works. For aspnet to find a dll, the dll needs to be in the bin folder on the web server.

It is your responsibility to make sure your dll files are in the bin folder.

If you reference a project from the aspnet web project, the dll is automatically placed in the bin folder. If you don't add a reference, that is OK, but you need to copy the dll files into the bin folder.

**Comment by 455986780** [comment]
Thank you very much!

My web project is "net core 3.1" target framework. There is no bin directory. 

I have copied the dll without reference to the same directory as the dll with reference. The dll with reference can be loaded, but the dll without reference failed to load. 

Using "AssemblyLoadContext.Default.LoadFromAssemblyPath" works well.

**Comment by rockfordlhotka** [comment]
Thank you, this makes sense. I've placed this into the backlog. If you would like to submit your change as a pull request that would be helpful, otherwise someone will get to it at some point I'm sure.

**Comment by rockfordlhotka** [comment]
@455986780 what package or assembly did you reference to gain access to the `AssemblyLoadContext` and `AppContext` types?

I've updated the code, and added references on my dev workstation, but they aren't available on the build server, so I suspect I'm pulling the wrong package or assembly.
