### ISSUE TITLE
Extension methods and CSLA0017 Business rules should use at least one Add() method on the context

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#2280]
Hi @JasonBock

**Describe the bug**
We have a bunch of extension methods for `IRuleContext` to easily `AddErrorResult` for things like min/max values, invalid characters, etc. The warning [CSLA0017](https://github.com/MarimerLLC/csla/blob/main/docs/analyzers/CSLA0017-BusinessRuleDoesNotUseAddMethodsOnContextAnalyzer.md#business-rules-should-use-at-least-one-add-method-on-the-context) is being shown, as we aren't calling any `Add()` method directly, but the extension method is.

**Version and Platform**
CSLA version: 5.4.2
OS: Windows
Platform: WinForms

**Code that Fails**
```cs
protected override void Execute(IRuleContext context)
{
    var guid = (Guid)context.InputPropertyValues[PrimaryProperty];

    if (guid == Guid.Empty)
        context.AddErrorResultRequiredRule(PrimaryProperty);
}
```

**Comment by rockfordlhotka** [comment]
Thank you @JasonBock, I appreciate you providing that context. I suspected that would be the answer.

I don't anticipate trying to walk the call path trying to find some deeply nested Add call, and disabling the rule is a valid workaround for a legacy codebase, so I'm going to close this issue.
