### ISSUE TITLE
CSLA0008 - Doesn't detect `static` missing from a backing field definition

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#2334]
**Describe the bug**
One of the analyzers isn't detecting a condition correctly for a backing field.

**Version and Platform**
CSLA version: 5.4.2
OS: Windows (but it shouldn't matter)
Platform: .NET 5

**Code that Fails**
If I write this:

```
public static PropertyInfo<Guid> IdProperty =
  Customer.RegisterProperty<Guid>(_ => _.Id);
```

I get the analyzer error as expected:
![image](https://user-images.githubusercontent.com/904213/122471143-804b8e00-cf84-11eb-800c-3b64ed2a6602.png)

But....if I change the code to this:

```
public readonly PropertyInfo<Guid> IdProperty =
  Customer.RegisterProperty<Guid>(_ => _.Id);
```

I don't get an error, because the property using the backing field is trying to use it as a static member, which is an error in and of itself:

![image](https://user-images.githubusercontent.com/904213/122471441-eb956000-cf84-11eb-85d4-ebfd182276d1.png)

The analyzer is looking to see if the field is being used within a property to check for the three conditions.

So the real question is....should the analyzer look to see if the field is set to the result of calling `RegisterProperty()`, even if it's not being used at all? Or is what the analyzer doing right now "acceptable" behavior?

**Comment by StefanOssendorf** [comment]
I'd say this is acceptable behavior. Once the property is either made `static` or not the `CSLA0008` will be raised for the `PropertyInfo`.

**Comment by rockfordlhotka** [comment]
I see what you are saying. Perhaps this isn't a bug, but it would be a nice enhancement if the analyzer were a little smarter?

**Comment by luizfbicalho** [comment]
@rockfordlhotka  do you have a table of valid/invalid options? I think I'll take a shot at this issue
Is this the same analyzer of the #1747 ?

**Comment by rockfordlhotka** [comment]
> @rockfordlhotka do you have a table of valid/invalid options? I think I'll take a shot at this issue Is this the same analyzer of the #1747 ?

It is the same analyzer, yes.

The only valid option is

```c#
public static readonly PropertyInfo<int> CustomerIdProperty = RegisterProperty<int>(nameof(CustomerId));
```

Obviously the code will _work_ without the `readonly` keyword, but `readonly` should be there and so should be required.

The code won't work without `static`, so that needs to be required.

The code must call `RegisterProperty`, so if we can detect and require that it would be ideal.

The `RegisterProperty` method has several overloads, all of which are valid, but use of `nameof` is ideal, and should be required.

**Comment by rockfordlhotka** [comment]
@luizfbicalho are you actively working on this? I know @kant2002 has been doing other analyzer work and might want to do this as well.

**Comment by luizfbicalho** [comment]
I'm working on the 4 issues that are assigned to me, but just outside working hours, I'm going to see this next saturday, it's OK?

**Comment by luizfbicalho** [comment]
> but it would be a nice enhancement if the analyzer were a little smarter?

@rockfordlhotka  I took a deep dive in this analyser and this is the result

```CSHARP

using Csla;

public class A : BusinessBase<A>
{
  public readonly PropertyInfo<string> DataProperty =
    RegisterProperty<string>(_ => _.Data); //doesn''t show warning because the property Data isn't connected to to the DataProperty yet
  public string Data
  {
    get;
    set;
  }
  public readonly PropertyInfo<string> DataProperty2 =
    RegisterProperty<string>(_ => _.Data2);// shows the warning
  public string Data2
  {
    get => GetProperty(DataProperty2);
    set;
  }
  public readonly PropertyInfo<string> DataProperty3 =
    RegisterProperty<string>(_ => _.Data3); // doesn't show the warning because the get isn't connected yet, even if the set is connected
  public string Data3
  {
    get;
    set => SetProperty(DataProperty3, value);
  }
  public readonly PropertyInfo<string> DataProperty4 =
    RegisterProperty<string>(_ => _.Data4);//shows the warning
  public string Data4
  {
    get => GetProperty(DataProperty4);
    set => SetProperty(DataProperty4, value);
  }
  public readonly PropertyInfo<string> ExpressionDataProperty =
    RegisterProperty<string>(_ => _.ExpressionData);//shows the warning
  public string ExpressionData => GetProperty(ExpressionDataProperty);
}
```
What is your expexted result in this case?

**Comment by rockfordlhotka** [comment]
Isn't there a different analyzer that checks to ensure that the get/set bodies are calling GetProperty/SetProperty/ReadProperty/LoadProperty?

I'd expect the two analyzers working together would get everyone to the right answer.

**Comment by luizfbicalho** [comment]
> Isn't there a different analyzer that checks to ensure that the get/set bodies are calling GetProperty/SetProperty/ReadProperty/LoadProperty?

this analyzer works only when the property is found
> 
> I'd expect the two analyzers working together would get everyone to the right answer.

Maybe there is another analyzer to check only the property, but this only checks methods with properties attached

**Comment by rockfordlhotka** [comment]
Hmm. The other analyzer I was thinking about is CSLA0007, which is supposed to ensure that a managed property getter and setter do nothing except call `GetProperty` and `SetProperty`.

I guess it isn't as strict as I thought it was, and so doesn't solve the invalid code scenarios you are considering.

For example, this is just invalid:

```c#
  public static readonly PropertyInfo<string> DataProperty = RegisterProperty<string>(_ => _.Data);
  public string Data
  {
    get;
    set;
  }
```

It is a managed property, and so I would have thought CSLA0007 would have flagged the get/set as being wrong.

As a result, I think the solution here is to write a _new_ analyzer that prevents these invalid property declarations.

A `get` must _always_ invoke `GetProperty` or `ReadProperty`.

A `set` must _always_ invoke `SetProperty` or `LoadProperty`.

CSLA0007 ensures the get/set doesn't have _extra_ code, but apparently doesn't make sure there's _enough_ code.

If we had this other analyzer, then the CSLA0008 one wouldn't need to worry about those other cases right?

**Comment by luizfbicalho** [comment]
Shoudn't we change the `CSLA0007` to prevent this ad keep the `CSLA0008` as is?
one other question, isn't the `set` optional? coudn't we have a read only property?

**Comment by rockfordlhotka** [comment]
Yes, I think CSLA0007 needs improvement, so we can keep CSLA0008 as is - I totally agree.

And yes, set is optional. But if it exists, it should be either `SetProperty` or `LoadProperty`.

Also, remember that we support both managed and private backing fields. Most properties in most code bases are using managed fields, but it is possible to use a private backing field by setting a flag on the static property and then using the private backing field in the `GetProperty` and `SetProperty` calls.

**Comment by luizfbicalho** [comment]
> Also, remember that we support both managed and private backing fields. Most properties in most code bases are using managed fields, but it is possible to use a private backing field by setting a flag on the static property and then using the private backing field in the `GetProperty` and `SetProperty` calls.

Is there any test or example of this? 


I only found this code with private on the tests and it doesn't look like it

 ```csharp
       using Csla;

        public class A : BusinessBase<A>
        {
          public static readonly PropertyInfo<string> DataProperty = RegisterProperty<string>(_ => _.Data);
          private string _x;
        
          public string Data { get { return null; } set { _x = "44"; this.SetProperty(DataProperty, value); } }
        
          public string GetX() { return _x; }
        }
```

**Comment by rockfordlhotka** [comment]
```c#
    public static readonly PropertyInfo<string> CityProperty = RegisterProperty<string>(nameof(City), RelationshipTypes.PrivateField);
    private string _city = CityProperty.DefaultValue;
    public string City
    {
        get => GetProperty(CityProperty, _city);
        set => SetProperty(CityProperty, ref _city, value);
    }
```

**Comment by luizfbicalho** [comment]
@rockfordlhotka  you gave me an amazing idea

after this issue I could create a source generator just like this

```csharp
public partial class Test
{	
    [AutoPropertyInfo]
    private string _city;

}
```
and generate this code 

```csharp
public partial class Test
{
	public Test()
	{
		_city = CityProperty.DefaultValue;
	}
	
	public static readonly PropertyInfo<string> CityProperty = RegisterProperty<string>(nameof(City), RelationshipTypes.PrivateField);
	public string City
    {
        get => GetProperty(CityProperty, _city);
        set => SetProperty(CityProperty, ref _city, value);
    }
}

```
this solves the point that I was looking for a way to remove all this extra code and also control the result class
If you like the idea you can create the issue and assign to me.

**Comment by StefanOssendorf** [comment]
> @rockfordlhotka you gave me an amazing idea
> 
> after this issue I could create a source generator just like this
> 
> ```cs
> public partial class Test
> {	
>     [AutoPropertyInfo]
>     private string _city;
> 
> }
> ```
> 
> and generate this code
> 
> ```cs
> public partial class Test
> {
> 	public Test()
> 	{
> 		_city = CityProperty.DefaultValue;
> 	}
> 	
> 	public static readonly PropertyInfo<string> CityProperty = RegisterProperty<string>(nameof(City), RelationshipTypes.PrivateField);
> 	public string City
>     {
>         get => GetProperty(CityProperty, _city);
>         set => SetProperty(CityProperty, ref _city, value);
>     }
> }
> ```
> 
> this solves the point that I was looking for a way to remove all this extra code and also control the result class If you like the idea you can create the issue and assign to me.

Yep. Was also looking how to get rid of that boilerplate. I'll probably fiddle with that and write one xD

**Comment by luizfbicalho** [comment]
I can put those 2 in high priority if you need in a hurry @StefanOssendorf

**Comment by StefanOssendorf** [comment]
No high priority for me necessary :) Thanks!
Furthermore if it's within the CSLA repo we will release it probably with v9 which is supposed to be released in november.

**Comment by luizfbicalho** [comment]
@rockfordlhotka  did you see the Generator idea that I put on this thread?
