### ISSUE TITLE
Add ability to more easily serialize DTOs via MobileFormatter

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2345]
![image](https://user-images.githubusercontent.com/2333134/124189758-d6412b00-da86-11eb-8f8c-a2b602c17487.png)

**Comment by TheCakeMonster** [comment]
My current thinking is that the best solution might be some combination of approaches 3 and 4. Adding type serializers would allow us to separate out the code associated with serializing the ClaimsPrincipal type, and offer a nice extension for developers. 

We certainly could use reflection to do POCO types, and it's possible to do this with a one-off performance hit by the creation of expressions. However, generating the required expressions probably isn't particularly straightforward. 

It feels to me like building a new solution using reflection might not be the best approach at this point; source generators offer an alternative, more modern approach, and one that might reduce the risk of arbitrary serialization security issues, as the implementation of serialization takes place as part of the build. Source generators are also not particularly straightforward, so this is not a simpler approach, but should offer the best serialization performance possible, in combination with a lower security risk.

**Comment by TheCakeMonster** [comment]
Closely related to issue #2148 (indeed it's arguably a duplicate)

**Comment by rockfordlhotka** [comment]
Oh, yes, it is a duplicate - let's work on #2148
