### ISSUE TITLE
Add support for unloading assemblies from memory (re: caching)

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2356]
Implement changes from #2095 into CSLA 6
---
There is no support for the concept of unloading an assembly and its types from memory during the lifetime of a process or AppDomain. It appears that in .NET Core it is now possible to unload an assembly and reload it, but when reloaded, that assembly no longer maps to the same types as the previous load.

This seems to imply that all locations in CSLA where type information is cached need to be updated to support a scenario where the "same type" can be loaded multiple times during the lifetime of an app.

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg I hope you are able to port your changes into the updated CSLA 6 codebase so they carry forward beyond CSLA 5. Thank you!

(also, did I get a contributor agreement from you? you aren't in the list of contributors here on GitHub, and you should be)

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka does classes with caching changed too much, that can not be auto-merged?) Or there are new concepts of ```CSLA``` behavior, in version 6?

Anyway - sure, but probably it will be in august. About contributing, i totally forgot :\ Will try to send it to you asap.

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg I don't think the _classes_ changed, but the directory structure has changed, because there's now only one `Csla` project in total that uses multi-targeting. So I automerge won't work, but cherry picking might?

**Comment by BaHXeLiSiHg** [comment]
@rockfordlhotka possible but better i will do it manually, not much changes. You can assign me, if it's alright to be done in august.

**Comment by rockfordlhotka** [comment]
@BaHXeLiSiHg that's perfect, thank you!

I think August is fine. I'll start doing pre-releases of CSLA 6 once v5.5.0 is out, but don't plan to finalize the CSLA 6 release until November when .NET 6 comes out.

**Comment by rockfordlhotka** [comment]
I'm closing this as it is a duplicate of #2095
