### ISSUE TITLE
Load CSLA v5.4.2 API docs into cslanet.com website

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2384]
For the most part the codebase includes decent API docs in comments. In the past I've used this (with ndoc and later sandcastle) to create chm or other help files.

These days what would be really nice is to use sandcastle or some other tool to generate static html content that we could add into the github repo under the `/docs` directory - maybe `/docs/api` or something?

This [SO thread](https://stackoverflow.com/questions/15316381/create-html-documentation-for-c-sharp-code) has some tooling options.

**Comment by Brannos1970** [comment]
I have begun the documentation of the API.

**Comment by Brannos1970** [comment]
An initial generation and preview of the documentation is uploaded and can be viewed at https://brannos1970.github.io/csla/5.4.2/html/. I am still working on this and would welcome any comments and suggestions to make it better.

**Comment by rockfordlhotka** [comment]
I like the look of this. Some thoughts

* As it generates actual html, it probably can't go into the /docs directory, and instead should go into https://cslanet.com - maybe in a /docs directory there?
* I would like to _not_ see the various unit test projects in the API docs, as I think they just add confusion
* Probably we should not see the analyzers either?

**Comment by Brannos1970** [comment]
I just released an updated preview of the API documentation. I removed the various unit test projects and the analyzers. The updated API is available at https://brannos1970.github.io/csla/5.4.2/html/. 

We can place the documentation anywhere. Right now, I have it set up to run from GitHub Pages which can be viewed at https://brannos1970.github.io/csla/. 

I am using Doxygen to generator the API documentation. If everyone is okay with that I will continue to do so as I work on the documentation.

**Comment by rockfordlhotka** [comment]
I think this is a lot cleaner, thank you!

I see from the doxygen site that they've customized other info in the nav pane. It would be nice to keep that minimal, but also to at least add links to https://cslanet.com and the github repo - maybe also a specific one for the Discussions tab?

I think it is perfect if you continue to work in your fork until it is ready to roll out.

That does also give time to think about where it'll end up once we do roll it out.

Versioning is the challenge I see. Something like https://cslanet.com/docs would be nice - but inadequate, since usually there are at least 2 "active" versions at any time - the released/bugfix version, and whatever is in `main`. So maybe what you are doing with the version in the URL is the answer. That does imply (in my mind) the need for an intermediate landing page though?

* cslanet.com/docs/5.4.2
* cslanet.com/docs/5.5.0
* cslanet.com/docs/6.0.0
* etc.

I imagine we can't keep _all_ of them, because that'll get huge over time.

**Comment by rockfordlhotka** [comment]
One thing I just noticed - the code links don't work. There are links to specific lines in various code files, but they don't go to a live location, just a 404.

**Comment by Brannos1970** [comment]
I notice the code links were not working after I pushed the update out. I am working on that. It is strange though; the files are there and visible through the code view but not being displayed in GitHub Pages at the moment.

I agree we need links to the main website and the GitHub repo and Discussions tab. I will get that integrated. 

As for the versioning, I figured that the current version and any supported versions should be available, which would keep it to a manageable group. But we can figure that out. Right now, I want to get the generation set up the way that is preferred. 

You mentioned that you would like to keep the nav pane minimal, I had reduced the listing down quite a bit, what additional information would you like to see removed?

**Comment by rockfordlhotka** [comment]
I don't think anything needs to be removed. I just want to be cautious about what we add.

**Comment by Brannos1970** [comment]
I have finished going through the generated pages. I think we need to add more information like examples and further explanations but I am not certain how much we should add or even if it is really needed. Any input would be appreciated.

If the current version is acceptable, I can go ahead and push the pages.

**Comment by rockfordlhotka** [comment]
Three things.

First, I think that looks fantastic!

Second, I don't want to go _too far_ down the road of examples. Some level is good, but will take time I'm sure. At the same time, I don't want to undermine my books and videos. I'm not sure the balance, but we should build _some examples_ over time for sure.

Third, this needs to be integrated into the [build process](https://github.com/MarimerLLC/csla/blob/main/docs/dev/Create-a-CSLA-.NET-release.md) such that I (or a CD task) can create/update the content. I would _like_ to switch to GitHub Actions or maybe ADO, at least for the CD build. Last time I tried (a while ago) to switch from appveyor to GH Actions it seemed overwhelming to get some of the older stuff to build. Now, in CSLA 6, we still build .NET Framework, code, so I don't know if all is well yet or not.

Right now I'm not trying to put a CD build on your plate!! I think we should take incremental steps, which means updating that build/release process doc, and maybe adding another doc (if necessary) what someone needs to install on their build machine to create the docs.

**Comment by Brannos1970** [comment]
I was thinking more along the lines of looking at the discussions and putting in information that is unclear, not documented, or providing at the very least links to the sample code or providing samples where needed, we could also reference the books. We can work on this as things move forward.

For the build is there another folder that I should be putting the files in?

**Comment by rockfordlhotka** [comment]
This second PR seems to have worked fine - it didn't prevent creation of index.html, and https://cslanet.com/5.4.2/html does seem to display the content.

The links to source files don't seem to be working in my quick test.

**Comment by Brannos1970** [comment]
That is something with GitHub Pages and I am not very good with Pages. I will look into their documentation to see if I can figure it out. If anyone has any ideas why linked code pages are not working please let us know.

**Comment by Brannos1970** [comment]
Found out a .nojekyll file needs to be created to link to the other pages. I don't see any issues with this, do you @rockfordlhotka?

**Comment by rockfordlhotka** [comment]
@Brannos1970 I don't know if you noticed, but I did update the https://cslanet.com and also the main GitHub landing page to have links to the API docs. It'll be fun to see what kind of feedback we get from folks.

Which does make me wonder - can you add arbitrary bits of script/html into the output? I use Google Analytics, and we could embed my analytics codes into the pages to track how much these docs get used.

**Comment by Brannos1970** [comment]
Yes, we can add Google Analytics. Send me HTML code and I will add it.
