### ISSUE TITLE
Should FieldManager expose an UpdateChildrenAsync method to avoid sync over async?

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2393]
**Area of Concern**
When writing asynchronous data portal methods for complex object graphs, it is troubling that the call to FieldManager.UpdateChildren is synchronous. If a child does asynchronous data access, this must have to be invoked from a synchronous method without awaiting it. That is sync over async, and must limit scalability of the system. 

However, it's important to note that I haven't actually experienced an issue with this as such; this is more theoretical than practical.

**Proposed Solution**
1. Add an asynchronous UpdateChildrenAsync method to FieldManager that can be used when async data portal methods are being written.
2. For safety, we should probably change the underlying dictionary that is used by FieldManager as part of the change to one that can handle multithreaded access, so that the async code doesn't cause threading issues (especially deadlocks.) I've had a number of deadlocks caused by the underlying Dictionary in the past; I don't want to make other people suffer them as a result of this change.

**Alternatives considered**
We could do nothing; after all, I haven't managed to trigger any problems in real life. However, I can't picture how this can be making best use of the available system resources for child objects, as awaits can't propagate through FieldManager.UpdateChildren.

**Additional context**
This is a theoretical issue; I have not suffered any noticeable problems as a result of using the synchronous method that exists at present.

**Comment by rockfordlhotka** [comment]
I'd rather "solve" this if there's a real problem to be solved.

Normally saving child objects occurs within the transactional context of the parent, and there are also (for collections) order of event issues where items need to be deleted, updated, inserted in the correct order to avoid unexpected behaviors.

If we make the update process async, then either the async update process would implement sync points to ensure correct order of events, or we'd be forcing the business developer to implement those sync points.

**Comment by TheCakeMonster** [comment]
I randomly get hangs in my application from complex object graphs where I have implemented async data access in the child objects. When I am in the debugger and I pause, I am at a FieldManager.UpdateChildren in one of those object graphs. I think there is some deadlocking going on, although I don't entirely understand why as I am on .NET Core 3.1, and I thought .NET Core didn't deadlock when using sync over async. So, I think there is both a theoretical, and a real, problem to be solved.

I'm not sure I understand your concern, yet. What I am suggesting is that we allow async all the way down - that a child object is able to await a call to a database, via an async dataportal method. If I understand async/await correctly - and it's possible I don't - there is no risk of a change to the order of events - as long as await is used.

What I am trying to achieve is this: UI calls await Parent.SaveAsync, which calls the data access method Parent.Dataportal_InsertAsync, which awaits database access, then calls Child.InsertAsync, which awaits database access.

At the moment, this doesn't happen, as the parent initiates saves of the children synchronously via FieldManager.UpdateChidren - thus "async all the way down" is broken.

There definitely might be a potential for threading to cause a problem, as the continuations may happen on different threads to the initiation of the async operation, but as far as I understand it, the order of execution is assured.

**Comment by TheCakeMonster** [comment]
OK, I think I've managed to create a fairly reproducible example of what I think I have been suffering in my application.

https://github.com/TheCakeMonster/Examples/tree/master/Issues/DeadlockingCSLADemo

If you run this solution in the debugger and enter a degree of parallelism of 1, the application works. This demonstrates that the code is fairly sound.

If you run it with a DOP of 2, it fairly consistently deadlocks.

The problem is being caused by thread starvation. If you break the debugger after it locks up, you will see that the line FieldManager.UpdateChildren is highlighted as the currently executing line (NestedChild.cs, line 218.) It's always this line.

Now comes the confession: it's a slightly contrived example. To make it consistently reproducible in a simple demo application I've had to _severely_ restrict the number of available threads. There would be enough threads to complete the work if the code were correctly implementing async - i.e. async all the way down - but not if it's doing sync over async.

Notice that it never deadlocks on the fetch operation, because the way fetch is implemented allows async all the way down the object graph. In contrast, FieldManager.UpdateChildren is a synchronous call, so it doesn't allow us to propagate the async operation to the children. As a result, saving an object graph is susceptible to this issue.

There is a chance that it won't deadlock on another machine. It does depend on the timings of the parallel operations coinciding for it to deadlock. If that happens, you can replicate the issue by restricting the max number of threads to 6, and running it with a DOP of 1.

Phew! That was hard to replicate!

**Comment by TheCakeMonster** [comment]
I've struggled all afternoon to make a few line change to the repo to resolve this, and failed.

The code on main doesn't currently work because of the changes that are in progress. I tried switching to branch v5.x but I can't get any of the tests to work to verify that the changes aren't causing a problem.

There are two classes that need to change:

Add these two methods to FieldDataManager.cs:

`
    /// <summary>
    /// Asynchronously invokes the data portal to update
    /// all child objects contained in the list of fields.
    /// </summary>
    /// <param name="parameters">Parameters for method</param>
    public async Task UpdateChildrenAsync(params object[] parameters)
    {
      foreach (var item in _fieldData)
      {
        if (item != null)
        {
          object obj = item.Value;
          if (obj is IEditableBusinessObject || obj is IEditableCollection)
            await Csla.DataPortal.UpdateChildAsync(obj, parameters);
        }
      }
    }

    /// <summary>
    /// Asynchronously invokes the data portal to update
    /// all child objects, including those which are not dirty,
    /// contained in the list of fields.
    /// </summary>
    /// <param name="parameters">Parameters for method</param>
    public async Task UpdateAllChildrenAsync(params object[] parameters)
    {
      Server.ChildDataPortal portal = new Server.ChildDataPortal();
      foreach (var item in _fieldData)
      {
        if (item != null)
        {
          object obj = item.Value;
          if (obj is IEditableBusinessObject || obj is IEditableCollection)
            await portal.UpdateAllAsync(obj, parameters);
        }
      }
    }
`

This is a pretty straightforward change. However, this doesn't fix it, by itself. There is also a change needed to BusinessBaseList to add an async update method.

`

    /// <summary>
    /// Asynchronously saves all items in the list, automatically
    /// performing insert, update or delete operations as necessary.
    /// </summary>
    /// <param name="parameters">
    /// Optional parameters passed to child update
    /// methods.
    /// </param>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [UpdateChild]
    protected virtual async Task Child_UpdateAsync(params object[] parameters)
    {
      using (LoadListMode)
      {
        foreach (var child in DeletedList)
          await DataPortal.UpdateChildAsync(child, parameters);
        DeletedList.Clear();

        foreach (var child in this)
          if (child.IsDirty) await DataPortal.UpdateChildAsync(child, parameters);
      }
    }

`

This feels like a much more significant change. I don't entirely understand how the dataportal method discovery works, so I'm not confident in this second change. As I can't get the tests to work to check it, I'm a bit stuck.

I'm going to have to give up at this point. There's some problem with the targeting of .NET assemblies on my machine that stops large swathes of the tests working, and I haven't managed to suss it in a sensible amount of time. I'll have to retire hurt.
