### ISSUE TITLE
Can't start Wcf DataPortal with Csla 5.5

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2409]
### Discussed in https://github.com/MarimerLLC/csla/discussions/2408

<div type='discussions-op-text'>

<sup>Originally posted by **amselem** August  5, 2021</sup>
Hi
When launching the WCF dataportal with Csla 5.5 in a .NetFW 4.8 project it gives me this error:

![image](https://user-images.githubusercontent.com/13227078/128359364-b14947f8-3327-489d-a96d-4b77150e0d1e.png)

It's weird because Csla 5.5 (Net46) takes a dependency on  v.3.1.9 of this package so why is it trying to load v3.1.0?:
`  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="3.1.9" targetFramework="net461" />
`

I found this link where it describes that Microsoft.Extensions.DependencyInjection.Abstractions is missing TargetFramework net461:   [https://github.com/dotnet/extensions/issues/434]()

I used Fusion logger and I think that what's happening here is that Microsoft.Extensions.DependencyInjection 3.1.9 package is trying to load Microsoft.Extensions.DependencyInjection.Abstractions 3.1.9 but can't load it (because of the previous bug) and it fallsback to 3.1.0 because 3.1.0 is the latest version that targets 4.6.1  (I guess)

I see that Csla 5.5 (net 5.0) already takes a dependency on both v5.0.0 Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.DependencyInjection.Abstractions.   Well, it happens that these v.5.0.0 packages also target net 4.6.1 !

![image](https://user-images.githubusercontent.com/13227078/128362878-3bca8ce5-f5e1-4ec4-b28b-cd0612cd1699.png)

So the fix is simply to update both Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.DependencyInjection.Abstractions packages to v5.0.0 in the csla net46 project

I tested it and Wcf Dataportal is running again with these changes

Does it make sense? Can these packages be upgraded for csla 5.5.1?

</div>

**Comment by rockfordlhotka** [comment]
@amselem This seems so simple on the surface, and yet it is not. As I'm updating the DI references in Csla.4.6, that causes a cascade of other dependency updates in other projects that reference Csla.4.6. I'm still working on resolving all of them to get a working build.

As I'm doing that, I'm starting to think that the risks are too high for this change, and that a different strategy is required.

In CSLA 6 the plan is to have a new _channel_ project for WCF, externalizing WCF entirely from the core of CSLA. This might allow, over time, the use of the open source WCF project for .NET Core and later, while isolating that dependency to a single project in CSLA.

Maybe the solution for CSLA 5 is to create an external WCF channel project too. Rather than risking breaking who knows how many projects by updating dependencies, it might be better to create an external WCF project and leave the core of CSLA 5 alone.

**Comment by rockfordlhotka** [comment]
@amselem I also wonder why DI is involved at all. WCF predates dependency injection, and so shouldn't be using it in any way.

**Comment by rockfordlhotka** [comment]
@amselem did you try adding a binding redirect instead of changing the referenced version?

```xml
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0"/>
			</dependentAssembly>
```

**Comment by amselem** [comment]
@rockfordlhotka  he bindingredirect also worked for me! 

Visual Studio added for me all these (when clicking on a specific warning):

```
	<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0"/>
			</dependentAssembly>
		</assemblyBinding>

```

**Comment by amselem** [comment]
@rockfordlhotka  I agree that isolating the Wcf channel in its own project / package would be much cleaner.
I really don't even plan to use the Wcf Channel in the long run, I'm just migrating my csla46 projects to csla55 and wanted to change one thing at a time!

**Comment by amselem** [comment]
> @amselem I also wonder why DI is involved at all. WCF predates dependency injection, and so shouldn't be using it in any way.
> 
> Do you get the same exception using the HttpProxy?

I managed to get some debug info of the failure, it looks like it's calling ApplicationContext.ServiceProviderScope  from the DataPortalProxyFactory and that is what is invoking DI.   Maybe I'm wrong but it doesn't look like a Wcf specific issue  (I didn't try the httpproxy).
Anyway I hope this help further debugging / refactoring:

![csla1](https://user-images.githubusercontent.com/13227078/130382587-c267bc25-121f-46c9-95c8-9a209c0422ed.jpg)

![csla2](https://user-images.githubusercontent.com/13227078/130382643-f76bdd02-0350-4ee2-945e-0ffa72bb1c29.jpg)

**Comment by rockfordlhotka** [comment]
Thank you for the help/research on this.

I have confirmed that a redirect solves the issue, and is a workaround for CSLA 5.

https://github.com/MarimerLLC/csla/issues/2409#issuecomment-903352606
