### ISSUE TITLE
Losing ClientContext when call dataportal_Execute from thread

### ISSUE THREAD

**Issue by RaviPatelTheOne** [MarimerLLC/csla#2436]
**Describe the bug**
When we are executing a background thread, values set in ClientContext are not available after calling the DataPortal_Execute method of the command object. 

In our application, we have implemented a schedular that executes jobs in the background. When execution of any job is started, few properties are set in Csla.ApplicationContext.ClientContext. Then, the job is calling the DataPortal_Execute method of the CommandBase object. In DataPortal execute method, values set in ClientContext are not available. It removes all the keys from ClientContext which are added before calling DataPortal_Execute method. Once execution of the DataPortal_Execute method is completed, ClientContext has populated again with previous values. It seems that ClientContext doesn't persist during the execution of the data portal method. 

NOTE: We have recently upgraded to 5.5.1.0 version from 4.3.13.0 version. Before the upgrade, we are using GlobalContext and it is working fine. After the upgrade, we have replaced GlobalContext with ClientContext and it doesn't persist values in ClientContext.

**Version and Platform**
CSLA version: 5.5.1.0
OS: Windows
Platform: ASP.NET
.Net Framework : 4.8

**Code that Fails**
**_default.aspx.cs_**

```c#
    public partial class Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Thread thread = new Thread(ExecuteJob);
            thread.Start();
        }

        private void ExecuteJob()
        {
            CreateGlobalContext();
            Debug.WriteLine("ClientContext Count after initialization: " + Csla.ApplicationContext.ClientContext.Count);
            HotelBookingCommand hotelBookingCommand = new HotelBookingCommand();
            HotelBookingCommand.Execute(hotelBookingCommand);
            Debug.WriteLine("ClientContext Count outsize DataPortal_Execute : " + Csla.ApplicationContext.ClientContext.Count.ToString());
        }

        private static void CreateGlobalContext()
        {
            Csla.ApplicationContext.ClientContext["Name"] = "Test";
            Csla.ApplicationContext.ClientContext["ID"] = "1";
            Csla.ApplicationContext.ClientContext["Person"] = "Dummy";
        }
    }
```

**_HotelBookingCommand_**

```c#
 public partial class HotelBookingCommand
    {
        public HotelBookingCommand()
        {
        }

        public static HotelBookingCommand Execute(HotelBookingCommand hotelBookingCommand)
        {
            HotelBookingCommand command = DataPortal.Execute<HotelBookingCommand>(hotelBookingCommand);
            return command;
        }

        protected override void DataPortal_Execute()
        {
            // Keys in Csla.ApplicationContext.ClientContext are cleared and only one key "__dataportaltimer" is available!!!
            Debug.WriteLine("ClientContext Count inside DataPortal_Execute : " + Csla.ApplicationContext.ClientContext.Count.ToString());
        }
    }
```

Output: 

ClientContext Count after initialization: 3
ClientContext Count inside DataPortal_Execute : 1
ClientContext Count outsize DataPortal_Execute : 3

Some additional Information: 
Csla.ApplicationContext.ContextManager.IsValid = true
Csla.ApplicationContext.WebContextManager.IsValid = false
Csla.ApplicationContext.ContextManager.GetType() = {Name = "
ApplicationContextManager" FullName = "Csla.Core.ApplicationContextManager"}

[CSLAUpgrade_TestApp.zip](https://github.com/MarimerLLC/csla/files/7009130/CSLAUpgrade_TestApp.zip)

**Comment by rockfordlhotka** [comment]
iirc, the workaround for this is to configure CSLA to use the [ApplicationContextManagerTls](https://github.com/MarimerLLC/csla/blob/v5.x/Source/Csla.Shared/Core/ApplicationContextManagerTls.cs) to manage context when HttpContext isn't available (like in background threads).

As I recall, we changed the default to use `AsyncLocal`, which is good for modern .NET, but classic ASP.NET doesn't work with it. That's my memory at least.

So in your app startup (global.asax.cs?) set the application context manager. Something like

```c#
CslaConfiguration.Configure().ContextManager(new Csla.Core.ApplicationContextManagerTls());
```

**Comment by RaviPatelTheOne** [comment]
We have applied suggested change in the sample. Still it is not working. Please find attached sample with suggested change.

We have added following code in global.asax.cs:

        protected void Application_Start(object sender, EventArgs e)
        {
            Csla.Configuration.CslaConfiguration.Configure().ContextManager(new Csla.Core.ApplicationContextManagerTls());            
        }

Please help.
[CSLAUpgrade_TestApp.zip](https://github.com/MarimerLLC/csla/files/7023294/CSLAUpgrade_TestApp.zip)
