### ISSUE TITLE
Could not load file or assembly 'System.Runtime.Loader, Version=4.0.1.0,

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#2470]
Describe the bug
Could not load file or assembly 'System.Runtime.Loader, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

Version and Platform
CSLA version: CSLA 5.5.1
OS: Windows
Platform: UWP etc.

Code that fails
calling any server side call
![image](https://user-images.githubusercontent.com/17121653/131337686-c38bf405-a3e2-4121-8cac-8f721f1b3377.png)

**Comment by SachinPNikam** [comment]
[ProjectTracker (2).zip](https://github.com/MarimerLLC/csla/files/7076646/ProjectTracker.2.zip)


Added Zip file of tested project tracker with uwp app

**Comment by rockfordlhotka** [comment]
Bummer that this didn't get caught during the test period for 5.5.1 😢

Originally reported here: https://github.com/MarimerLLC/csla/issues/2398

**Comment by SachinPNikam** [comment]
hi rocky ,
https://github.com/MarimerLLC/csla/commit/ab2602b890c8aac186f674fbd512ceea8f0e3b1d
also i given pull request which will fix compile time error related to csla.xaml of project tracker uwp

**Comment by SachinPNikam** [comment]
hi @rockfordlhotka there is error in sample Project Tracker uwp target while compile this will fix that issue . this check in not related to runtime loader issue ..
Thanks

**Comment by rockfordlhotka** [comment]
@SachinPNikam thank you, I appreciate the help. Unfortunately, the commit you reference isn't in a state where I can create a PR. Can you create a PR?

**Comment by SachinPNikam** [comment]
hii rocky ,
here is there PR https://github.com/MarimerLLC/csla/pull/2489
