### ISSUE TITLE
Could not find the resource "Csla.Properties.Resources.resources"

### ISSUE THREAD

**Issue by garethvdl2** [MarimerLLC/csla#2477]
**Describe the bug**
Could not find the resource "Csla.Properties.Resources.resources"

**Version and Platform**
CSLA version: 5.5.1
OS: Windows
Platform: Blazor

**Code that Fails**
[BlazorExample.zip](https://github.com/MarimerLLC/csla/files/7120323/BlazorExample.zip)

Steps to recreate
1) Login
2) Edit Person
3) Save

Incorrect
![5 5 1](https://user-images.githubusercontent.com/31724219/132318005-25130351-b654-476e-b310-05e9caeb111e.PNG)

Correct
![5 5 1-R21082202](https://user-images.githubusercontent.com/31724219/132318031-24753b74-831b-47fb-bd6d-589d13bce073.PNG)

**Stack Trace or Exception Detail**
Could not find the resource "Csla.Properties.Resources.resources" among the resources "" embedded in the assembly "Csla", 
nor among the resources in any satellite assemblies for the specified culture. 
Perhaps the resources were embedded with an incorrect name.

**Additional context**
Occurs when exception is thrown in dataportal update. Still works correctly in 5.5.1-R21082202.

**Comment by ashishsinha24** [comment]
Downloaded the sample
Doesnt happen on my end

**Comment by rockfordlhotka** [comment]
You might try cleaning and rebuilding the solution. This sounds like the build is using an old package from a cache.

**Comment by garethvdl2** [comment]
Hi

I deleted all nuget packages with ' dotnet nuget locals all --clear' and then cleaned and rebuilt above project with no luck.
Previous versions do work however ie 5.5.1-R21082202.
Anything else I could try?

**Comment by rockfordlhotka** [comment]
I was suggesting that, in Visual Studio, you do a Build-Clear and Build-Rebuild for the entire solution. The problem is likely to be old stuff in your `obj` folders.

**Comment by garethvdl2** [comment]
I cleaned the whole solution and built and still get it.
The nuget package csla.dll is 488KB
So I downloaded the 5.5.1 source and did a release build. The csla.dll is 500KB and if I copy this dll into the server and client of the test project above then it works correctly.
I will close this issue as I seem to be the only one who is getting the issue.
