### ISSUE TITLE
ClientContext regression bug in 5.5.1

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#2480]
**Describe the bug**

Use code example from here:
https://github.com/MarimerLLC/csla/issues/1875

Works with 5.5.0, breaks after update to 5.5.1

**Version and Platform**
CSLA version: 5.5.1
OS: Windows

**Code that Fails**
https://github.com/MarimerLLC/csla/issues/1875

This fails when you install these packages:

```
  <package id="Csla" version="5.5.1" targetFramework="net48" />
  <package id="Csla.AspNet" version="5.5.1" targetFramework="net48" />
```

**Comment by rockfordlhotka** [comment]
It appears that, in the server-side `DataPortal`, the `ClientContext` dictionary _does exist but is empty_ when the check is made to see if the context passed from the client should be used on the server. The code was just checking for a `null` value, but clearly also needs to see if the `ClientContext` is empty (`Count == 0`).
