### ISSUE TITLE
Issue with throwing System.Resources.MissingManifestResourceException rather than the expected Csla.DataPortalException

### ISSUE THREAD

**Issue by kurtgulden** [MarimerLLC/csla#2498]
**Describe the bug**
System.Resources.MissingManifestResourceException is returned rather than the expected Csla.DataPortalException

**Version and Platform**
CSLA version: 5.5.1
OS: Windows
Platform: .NET 5

**Code that Fails**
Within a Test Project targeting .NET 5, the test expects a certain exception as in the following:

`
Assert.ThrowsException<Csla.DataPortalException>(
...throw any kind of Exception in a method marked with DataPortal Attribute [Fetch], [Insert], [CreateChild], etc.
);`

**Stack Trace or Exception Detail**
Instead of the expected Csla.DataPortalException, this exception is returned:

`
System.Resources.MissingManifestResourceException: 'Could not find the resource "Csla.Properties.Resources.resources" among the resources "" embedded in the assembly "Csla", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.'`

**Additional context**
This is occurring in pre-existing tests which prior to release 5.5.1 have worked properly.

**Comment by rockfordlhotka** [comment]
Thank you @kurtgulden - someone else had a similar issue in UWP, and I was unable to replicate. 

Can I confirm:

1. You are running in en-US culture (the default)
2. This is an mstest project
3. The data portal is running in local mode
4. You are referencing the `Csla` NuGet package

**Comment by kurtgulden** [comment]
Yes that is all true. I appreciate your interest in resolving this issue.

(First-time Submitter, Long-time user.)

**Comment by adrianwright109** [comment]
Hi, I am now getting this same error in a Blazor WebAssembly project since upgrading from Csla `5.5.0` to `5.5.1`.

In version `5.5.0` I would get the following exception message:
```
DataPortal.Update failed on the server
```

Now in version `5.5.1` I get this exception message instead:
```
Could not find the resource "Csla.Properties.Resources.resources" among the resources "" embedded in the assembly "Csla", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
```

**Comment by MTantos1** [comment]
I'm also encountering this error after trying to update our project to latest CSLA and .NET 5.

**Version and Platform**
CSLA version: 5.5.1
OS: Windows
Platform: .NET 5 WPF

In response to @rockfordlhotka's questions:

> Can I confirm:
> 
>     1. You are running in en-US culture (the default)
>     2. This is an mstest project
>     3. The data portal is running in local mode
>     4. You are referencing the `Csla` NuGet package

1.  No, I'm using 'en-AU'.  I also tried 'en-US', this made no difference.
2. No, it's a .NET5 WPF app.
3. Yes
4. Yes

**Comment by rockfordlhotka** [comment]
I suspect it is an issue with the .NET 5 nuget package, but need to confirm.

**Comment by KC7465128305** [comment]
I have the same error after updating my project to CSLA 5.5.1 from 5.5.0.

Version and Platform
CSLA version: 5.5.1
OS: Windows
Platform: .NET 5 WPF

In my project, I have a global boolean to turn on and off N Level Undo.  If the boolean is true, all the BeginEdit, ApplyEdit, and CancelEdit methods will be executed.  If the boolean is false, all these methods will be skipped.  I use this to aid diagnosis because sometimes the N Level mismatch exception will throw first before the place that bombed have a chance to throw the exception.  This masks the real bug and makes it very hard to find the real culprit.  If this happens I will turn off the N Level Undo, fixes the bug, and turn back on the N Level Undo.  One thing I notice is that this 'System.Resources.MissingManifestResourceException' only throws when N Level Undo is turn on.

**Comment by KC7465128305** [comment]
I am running in en-US culture (the default)
The data portal is running in local mode
My project is referencing the Csla NuGet package

**Comment by rockfordlhotka** [comment]
Figured it out. I have to remember to entirely clear the target `bin` directory when I switch from working on CSLA 6 back to CSLA 5. Somehow Visual Studio (or msbuild?) gets confused when the CSLA 6 output is in that directory and doesn't seem to properly build all the output for CSLA 5.

Pushing a version 5.5.2 release to NuGet right now that addresses this issue.

**Comment by kurtgulden** [comment]
Wonderful news. Thank you.
