### ISSUE TITLE
MobileFormatter should serialize DateTimeOffset

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2523]
See https://github.com/MarimerLLC/csla/discussions/2522 for discussion.

The DateTimeOffset type is not normally serializable. `MobileFormatter` should be enhanced to serialize DateTimeOffset.

Also, the analyzer that checks for serializable types should be enhanced to understand that this type can now be serialized.

**Comment by swegele** [comment]
When whoever gets to coding this...they should probably .ToString the DateTimeOffset in the "O" round-trip format as talked about here, to preserve all original information contained therein.

https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings

**Comment by rockfordlhotka** [comment]
Maybe can be resolved once #2531 is complete?
