### ISSUE TITLE
PropertyInfo should have a way to display object level broken rules

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#26]
The `PropertyInfo` type in `Csla.Xaml` is attached to a specific property and it exposes bindable metastate values for that property (CanRead, IsBusy, etc.) for use within XAML data binding.

There should be an equivalent type (probably `ObjectInfo`) that can be attached to a business object. This would expose bindable metastate values for the object itself (IsValid, IsSaveable, IsBusy, etc.).

Needs to be implemented for Xamarin Forms, WPF, and UWP.

More info:
http://forums.lhotka.net/forums/t/9895.aspx

**Comment by halloween8** [comment]
I would like to help, is there a specific way you want it? how does this helping thing works anyway?

**Comment by rockfordlhotka** [comment]
I am going to close this issue, because over time the various "viewmodel" types (ViewModelBase, Controller, PageModel, etc.) have incorporated per-type methods to allow the UI to display this sort of information.

If anything is missing in terms of metastate that should be exposed we can open future work items to add those values to the various "viewmodel" types.
