### ISSUE TITLE
some dataportal unit test failed

### ISSUE THREAD

**Issue by niijyeni** [MarimerLLC/csla#2666]
1. Test method Csla.Test.DataPortal.DataPortalTests.TestTransactionScopeUpdate threw exception: 
Csla.DataPortalException: DataPortal.Update failed (Type is not resolved for member 'Csla.Security.UnauthenticatedPrincipal,Csla, Version=5.5.2.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30'.) ---> Csla.Reflection.CallMethodException: TransactionalRoot.DataPortal_Insert method call failed ---> System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Csla.Security.UnauthenticatedPrincipal,Csla, Version=5.5.2.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30'.
2. Test method Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Fetch_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Fetch_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters()

3. Test method Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Create_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Create_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters()

4. Test method Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Delete_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Delete_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters()

5. Test method Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Update_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at Csla.Test.DataPortal.AuthorizeDataPortalTests.DataPortal_Update_Calls_IAuthorizeDataPortal_Authorize_WithCorrectParameters()

6. Test method Csla.Test.DataPortal.LogicalExecutionDataPortalTests.Test_LogicalExecution_Values threw exception: 
System.AggregateException: One or more errors occurred. ---> Csla.Server.DataPortalException: DataPortal.Create failed on the server ---> Csla.Security.SecurityException: Principal must be of type BusinessPrincipal, not Nothing
    at Csla.Server.DataPortal.SetPrincipal(DataPortalContext context)

**Version and Platform**
CSLA version: 5.5.2
OS: Windows
Platform: WinForms

**Comment by rockfordlhotka** [comment]
Thank you for reporting these. I'm surprised that they are failing, as I _think_ they run correctly in the CI build. I guess they probably are not 😄
