### ISSUE TITLE
Add support for portable class libraries

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#267]

**Comment by rockfordlhotka** [comment]
At this point I'm pretty confident that I can create a PCL that supports .NET 4.6 and UWP targets, which means it would also support Xamarin targets. That seems worth doing to support people creating x-plat PCLs of their own that target that set of platforms.

**Comment by rockfordlhotka** [comment]
Turns out that there's no common way to set current culture values that spans .NET 4.5 up through .NET Core. As a result this PCL implementation really will rely on NuGet bait-and-switch to actually function - anyone trying to use the PCL at runtime will encounter issues - but that should never happen since NuGet should automatically ensure they are using per-platform assemblies.

For example, there's this code in `DataPortalT.cs`:

```c#
    private void SetThreadContext(DataPortalAsyncRequest request)
    {
      Csla.ApplicationContext.User = request.Principal;
      Csla.ApplicationContext.SetContext(request.ClientContext, request.GlobalContext);
      // set culture info for background thread 
#if !PCL46 // rely on NuGet bait-and-switch for actual implementation
#if NETCORE
      System.Globalization.CultureInfo.CurrentCulture = request.CurrentCulture;
      System.Globalization.CultureInfo.CurrentUICulture = request.CurrentUICulture;
#elif NETFX_CORE
      var list = new System.Collections.ObjectModel.ReadOnlyCollection<string>(new List<string> { request.CurrentUICulture.Name });
      Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Languages = list;
      list = new System.Collections.ObjectModel.ReadOnlyCollection<string>(new List<string> { request.CurrentCulture.Name });
      Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Languages = list;
#else
      Thread.CurrentThread.CurrentCulture = request.CurrentCulture;
      Thread.CurrentThread.CurrentUICulture = request.CurrentUICulture;
#endif
#endif
    }

```

**Comment by rockfordlhotka** [comment]
I solved the lack of WCF in all platforms by excluding `WcfProxy` from the PCL version of the framework. People wishing to use WCF will need to reference per-platform versions of CSLA, or use `HttpProxy`.

This makes sense anyway, because if they create a PCL that spans platforms that don't include WCF they weren't going to use it anyway.

**Comment by rockfordlhotka** [comment]
List of PCL targets for reference: http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY

**Comment by rockfordlhotka** [comment]
![snip_20151209113430](https://cloud.githubusercontent.com/assets/2333134/11693144/d85f3bee-9e68-11e5-9671-21f6e7f95b80.png)

**Comment by dazinator** [comment]
I'm super excited about this.. Thanks Rocky!

**Comment by rockfordlhotka** [comment]
Me too - I think it will be a very useful capability.

As I type this I'm pushing a refresh to the v4.6.300 beta into NuGet. I would love any help you (or others) can provide in terms of testing the utility of the new PCL.

The one thing I _do know_ is that it won't work with default Xamarin PCL projects, because the Xamarin PCL's also reference Silverlight and use NuGet 2.x instead of 3.x. I guess I was too quick to drop Silverlight support in CSLA .NET :disappointed:

**Comment by dazinator** [comment]
Haha.. the benefits of hindsight!
I am trying out this new release now as just starting to write a brand new business layer and eager to use PCL. I'll let you know if I hit any snags.
