### ISSUE TITLE
Should Csla 6.0 expose a client-side IDataPortalFactory interface and implementation?

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2676]
Discussion point.

Thinking about the code in my applications - Blazor is my mental go-to at the moment - it is not uncommon for a ViewModel or other UI control class to need to perform multiple data access operations, for multiple different types. For example, I may need to show a read-only list of items from which a user can pick. The UI then allows the user to load an existing editable or create a new instance of the editable object for editing, plus some read-only lists to populate drop-downs, perform validation and so on.

With Csla 6.0, each type that I need to instantiate requires a different instance of an IDataPortal<T> implementation - each is typed to support just a single type. If there are 4 or 5 different types in use, that's 4 or 5 different instances of IDataPortal<T> that need to be added to the constructor, constructed by the DI container and then kept in memory for the lifetime of my UI component. In some UIs that doesn't matter too much, but on shared infrastructure, such as a web server hosting a Blazor Server site, that might be a lot more memory being used than necessary (a little memory for each multiplied by a lot of users) - especially if the data portal instance is not used for most user scenarios.

**Possible Solution**
I am wondering if, instead of requesting IDataPortal<T> in the constructor for each and every type, I might instead express an interest in multiple data access operations by having an instance of a new interface - IDataPortalFactory - injected. This interface would expose a method from which I can instantiate an IDataPortal<T> or IChildDataPortal<T> if and when I need it, for any type in which I am interested.

**Potential Benefits**
- Simpler changes if an additional drop-down is added to the same edit form.
- Less memory usage on shared infrastructure
- Shorter lifetime of the object instances that are instantiated

**Counter Arguments**
From a pure architectural perspective, this may not be considered entirely correct. If a UI control class has multiple dependencies then those dependencies are more obvious if each is injected into the constructor as a separate parameter. Furthermore, the need to access multiple types might be considered an anti-pattern because it suggests that a component is too complex. However, from the pragmatic perspective, it feels like requiring every IDataPortal<T> to be injected is making things a bit more complicated than they need to be, and less efficient because I am having objects instantiated even if they are only used in a small subset of scenarios (only if a user presses a particular button for example, where that button is rarely used.)

If we were to add an IDataPortalFactory and DataPortalFactory for creating client-side data portal instances, we would give developers choice. It would be an additional option for when it is convenient - it doesn't force them to do something that is architecturally less perfect, as the current solution would also remain open to them.

**Additional context**
I have been having a go at reworking the Csla.Test unit test project. This has given me the opportunity to see the use of IDataPortal<T> in code I am working on, and I noticed that I'm creating a fair number of instances of IDataPortal<T> and sometimes, due to the peculiarities of the existing code, some IChildDataPortal<T> for the same types as well. Having the same object act as a root and a child should be rare in the real world, but that's not to say it won't ever happen.

It's quite possible that you have already had the same idea - possibly back in 2018. I can see that there is already an IDataPortalFactory interface in the solution. It only exposes the ability to get an IDataPortal<T> and not an IChildDataPortal<T> and I also can't see any references to this type - not within the projects in Csla.test.sln anyway. Maybe its existence is historical; should we resurrect it?

**Comment by rockfordlhotka** [comment]
I understand what you are saying. I have an app I'm building and sometimes there are quite a number of services injected into a page or other component.

The factory idea isn't a bad one. Technically we should all be getting our HttpClient objects from a factory apparently (though even Microsoft's examples rarely do that).

Normally a factory actually _does_ something though - more than just creating types. Like with the HttpClient factory, apparently it does some management of the instances as well (??).

I think you are right about the IDataPortalFactory - I was thinking along this line when I first started with CSLA 5, then abandoned the approach, and forgot to remove the type.

If we do create the factory type, I think there should be a separate factory type for the client-side data portal vs the child data portal (which is really only for use within a data portal operation method).

**Comment by TheCakeMonster** [comment]
Yeah, HttpClientFactory is an interesting beast. That's one area of .NET that has changed a _lot_ over the various iterations of .NET Core. In the early days there was a big, unseen problem with using HttpClient directly, and HttpClientFactory was introduced to help.

I think I have seen in a later release of .NET Core that the problem with direct usage has largely been mitigated, to the point where the recommendation might have changed again - but to be honest it's changed enough that I am just confused!

Yes, what you said about the child data portal makes perfect sense now that you mention it. I've been playing in the tests where usage of IChildDataPortal is necessary to perform some of the weird and wonderful tests that we have, so I've been using instances of that interface in uncommon ways. Some of those ways are very odd indeed, and I think that might be not only trying to cover unusual circumstances but also a few bad bits of code along the way.

**Comment by rockfordlhotka** [comment]
Now that the client-side data portal is an instance that is usually injected via DI, it is becoming apparent that in many cases (unit of work, root parent, and other types) _numerous_ data portal instances must be injected.

I am not sure this is _bad_ exactly, but it can make for a lot of typing. For example.

```c#
[Fetch]
private async Task FetchAsync(
  [Inject] IDataPortal<Type1> type1Portal,
  [Inject] IDataPortal<Type2> type2Portal,
  [Inject] IDataPortal<Type3> type3Portal,
  [Inject] IDataPortal<Type4> type4Portal,
  [Inject] IDataPortal<Type5> type5Portal)
{
  // use the various portal instances
}
```

I am thinking that, perhaps, it would be cleaner to allow the use of an `IDataPortalFactory` (and `IChildDataPortalFactory`) concept:

```c#
[Fetch]
private async Task FetchAsync(
  [Inject] IDataPortalFactory portalFactory)
{
  var type1Instance = await portalFactory.GetDataPortal<Type1>().FetchAsync(123);
  // use the portalFactory to interact with other portal instances
}
```

This shifts the data portal instance creation from the method declaration into the method. It _might_ improve readability. It certainly means that if a data portal instance is only used in some cases and not others, the data portal instance will only be created if needed.
