### ISSUE TITLE
Csla 6 fluent configuration - methods on the DataPortalServerOptions class should support method chaining

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2692]
During configuration using the Csla 6 AddCsla method, it's not possible to chain configuration using methods that are exposed by the DataPortalServerOptions class, as they do not expose the type on which they are placed.

The following is not supported, for example - this would not compile, as RegisterActivator is a void method:
```csharp
services.AddCsla(options => options
.DataPortal(options => options.AddServerSideDataPortal(cfg => cfg
.RegisterActivator<CustomActivator>()
.AddInterceptorProvider<CustomInterceptor>()
));
```

This:
```csharp
public void AddInterceptorProvider<T>() where T: IInterceptDataPortal
{
      InterceptorProviders.Add(typeof(T));
}
```
would become this:
```csharp
public DataPortalServerOptions AddInterceptorProvider<T>() where T: IInterceptDataPortal
{
      InterceptorProviders.Add(typeof(T));
      return this;
}
```
Optionally, I could also move the methods to a new file called DataPortalServerConfigurationExtensions and make them into extension methods if we'd prefer to make them a little more consistent with other parts of the codebase.

I can't see any downside to this suggestion, so I have created this directly as an issue because I think it likely that you will be happy with the change and want me to make it.

**Comment by rockfordlhotka** [comment]
I agree that the current implementation is lacking in consistency, and I really appreciate the thinking you (@TheCakeMonster and @swegele) are putting into this!

**Comment by TheCakeMonster** [comment]
I intend to hold off on this until we've got the big PR merged, or there is a danger I'll get myself confused!
