### ISSUE TITLE
Server-side data portal should use a single DI scope

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2695]
### Discussed in https://github.com/MarimerLLC/csla/discussions/2685

The server-side data portal _should_ create a DI scope on first call from the client. Subsquent data portal calls from _within the existing server-side context_ should run within that same DI scope.

Right now it appears that a new DI scope is created on each data portal call from within a server-side data portal operation method.

In other words, the client calls something like `FetchAsync`, resulting in code running on the server in a DI scope. The data portal operation method _then_ calls something like `FetchAsync`, which also runs on the server. But right now that second call is resulting in a new DI scope, which is not the correct behavior.

<div type='discussions-op-text'>

<sup>Originally posted by **swegele** January  8, 2022</sup>
I have a DI service which wraps an instance of my DAL db connection object.  I want this wrapper to be scoped to ensure that I have only one DB connection open at a time for this particular user's call to the DataPortal.  
```cs
public class JTDataAdapterManager
{
    private JTDataAccessAdapter _adapter;  //DAL connection
    private Guid guid = Guid.NewGuid();

    //Use DI
    public JTDataAdapterManager(ApplicationContext applicationContext, DBConfiguration dbConfigOptions)
    {
        //Set DAL Config options here with dbConfigOptions
        ...

            // open connection if we have crossed the logical and/or physical dataportal so it is safe to access the database
            if (applicationContext.LogicalExecutionLocation == ApplicationContext.LogicalExecutionLocations.Server)
            {
                _adapter = new JTDataAccessAdapter(true, connectionTimeoutInt);
            }
            else
            {
                throw new Exception("The Database can only be accessed on the server side of DataPortal");
            }
    }

```

The service is defined in my server side Blazor app as "Scoped"
```cs
builder.Services.AddScoped<LLBLGenDataUtilities.JTDataAdapterManager>();

```

I assumed since the service is defined as "Scoped" that the first call to this on the server side of the DataPortal would create a new one of these...but subsequent chained calls (still on the server side) would pick up the existing created one.  Example, here is an instance of a server side [Fetch] method that gets called first: 
```cs
public class TranslationRecordInfoList : BusinessBaseClasses.JTReadOnlyListBase<TranslationRecordInfoList, TranslationRecordInfo>
{
   ...

  [Fetch]
  private void DP_Fetch(
      LLBLGenDataUtilities.Criteria.LLBLGenFilterCriteria criteria,
      [Inject] LanguageInfoListFactory languageInfoListFactory,
      [Inject] TranslationRecordInfoFactory translationInfoFactory, 
      [Inject] LLBLGenDataUtilities.JTDataAdapterManager cxnManager)
{
      RaiseListChangedEvents = false;
      IsReadOnly = false;

      using (EntityCollection<TranslationEntity> list = new EntityCollection<TranslationEntity>())
      {
          // load values
          cxnManager.ActiveAdapter.FetchEntityCollection(list, criteria.Filter, criteria.MaxRecordsToReturn, criteria.SortExpression);

          if (list.Count > 0)
          {
              LanguageInfoList languages = languageInfoListFactory.GetAll();
              foreach (var language in languages)
              {
                  foreach (var entity in list.Where(ent => ent.LanguageId == language.Id))
                  {
                      Add(TranslationRecordInfo.Load(translationInfoFactory, entity, language));
                  }
              }
          }
      }

      IsReadOnly = true;
      RaiseListChangedEvents = true;
  }
```

This is the first method that gets called in a chain of calls...JTDataAdapterManager is injected so this is where one should get created.  A few lines into that method, I fetch another business object I need
```cs
    LanguageInfoList languages = languageInfoListFactory.GetAll();
```

That call ends up here in the LanguageInfoList object
```cs
public class LanguageInfoList : BusinessBaseClasses.JTReadOnlyListBase<LanguageInfoList, LanguageInfo>
{
  ...

[Fetch]
private void DP_Fetch(
    LLBLGenDataUtilities.Criteria.LLBLGenFilterCriteria criteria,
    [Inject] LanguageInfoFactory languageInfoFactory,
    [Inject] LLBLGenDataUtilities.JTDataAdapterManager cxnManager)
{
	RaiseListChangedEvents = false;
	IsReadOnly = false;

```

The problem is I check the "guid" property of the cxnManager in the second call and it is a new GUID (different than the one in the first fetch method.  I was not expecting that.  I thought once you cross the DataPortal, the LocalProxy had created a scope which would apply for DI until you end that original call into the DP.

I used have this class just like Rocky's where I did ref counting and stuck an instance of it inside the ApplicationContext.  That worked fine and I "could" keep doing that, but I figured I could get rid of all that extra stuff and really simplify this class by just defining it as scoped.
Obviously "scoped" is not behaving the way I expected so I'm missing something.  
</div>

**Comment by swegele** [comment]
Works like a charm!  Thanks for the fix.
