### ISSUE TITLE
LocalProxy creates a new instance of the built-in ApplicationContextManager, resulting in loss of context

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2702]
Whilst debugging the strange behaviour of a business object on which IsSavable was false despite IsValid and IsDirty both being true, I've discovered that the application context gets lost during the execution of a request through LocalProxy.

My object has the correct ApplicationContext - exposed by a custom ApplicationContextManager - until line 41 of LocalProxy.cs, at which point the default, AsyncLocal implementation of ApplicationContextManager is instantiated. At this point, the ApplicationContext is lost, because the new context manager doesn't have it.

It appears from the comment that the creation of a separate context manager is intentional. Should this new implementation of IContextManager be created from the scoped service provider created a few lines above rather than being created using the constructor of a specific type? Or is the use of a different and very specific context manager intentional, and therefore it should have its context set from the ambient/client-side instance at that moment, copying it from one place to another?

**Comment by rockfordlhotka** [comment]
iirc, the reason a new ApplicationContext is created is because it points to a new context manager, which has the scoped DI provider.

The LocalContext, ClientContext, and User should be coped to the new ApplicationContext (via reference, not serialized) - perhaps that is not happening?
