### ISSUE TITLE
Csla.Blazor needs its own ApplicationContextManager type

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2706]
Blazor relies on the `AuthenticationStateProvider` service to get the current user, not HttpClient, and so it needs an `ApplicationContextManager` type that uses this service to obtain the current user.

`ApplicationContextManager` is a scoped service, and so should maintain local/client context values as private properties.

Lots of discussion in #2687

**Comment by TheCakeMonster** [comment]
OK, great, thanks.

I think the code in my demo should pretty much cover it. The only thing I hadn't sussed was the separation between code that needed to go in Csla.Blazor, and code that was for SSB, which maybe should go in Csla.AspNetCore, as it references a type specific to AspNetCore.

**Comment by rockfordlhotka** [comment]
I don't think I'm using any types that are server-specific. The `AuthenticationStateProvider` type is the base type for all the state provider variations. The _server_ implementation adds a server-specific interface, but I don't think we need that dependency, as long as we forego the use of the `SetUser` method. I don't think `SetUser` should be supported, because devs should be using the Blazor/aspnetcore framework to change the current user.
