### ISSUE TITLE
Add IContextManager implementation for hybrid Blazor/WebAPI, Blazor/MVC or Blazor/Razor Pages scenarios

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2724]
We have a new Blazor ApplicationContextManager which plays very nicely with Blazor. However, if a Blazor Server-side site has any WebAPI controllers, MVC controllers or Razor Pages then the context manager will not work for those sections of the ASP.NET site. If someone needs to access anything via Csla from outside of Blazor then they will not be able to add authorization rules, as the context of the user would be unavailable in the non-Blazor sections - in other words, the GetUser() method of the context manager would return an unauthenticated principal to a WebAPI or MVC controller or Razor Page, even if a valid authentication cookie is presented with the HTTP request to the controller/page.

It is specifically - and almost exclusively - the behaviour of GetUser() that I think should behave better in hybrid scenarios. I am not suggesting that any state should be shared between Blazor and non-Blazor as such, but that all code in ASP.NET that is outside of Blazor should function as it always has - based on HttpContext, including/especially HttpContext.Current.User - whilst everything inside of Blazor should function as we have now placed into the new Blazor context manager.

**Proposed Solution**
I suggest we provide a hybrid context manager which determines whether it is within Blazor or outside of it, and within its constructor news up an instance of either the Blazor context manager (based on scoped objects from DI) or the ASP.NET one (based on HttpContext.) All of the IContextManager implementation is then delegated to the internal context manager that was created in the constructor.

The hybrid provider solely needs to make the determination of which other context manager to create, then delegate to it.

**Alternatives I Have Considered**
We could leave this out, and expect the end user to implement it. However, I think this would lead to more requests for help. I think it would be better to provide the implementation inside of the framework; then all we need do is point people to the correct implementation for their hybrid scenario.

**Additional context**
A full implementation of the solution was mocked up in a demo available at https://github.com/TheCakeMonster/Examples/tree/master/CSLA6/BlazorAuthentication

This demo includes the Blazor context manager and the hybrid one. The Blazor context manager has now been included in the framework, so the only thing remaining to be done that can be seen in the demo is the hybrid context manager.

**Comment by swegele** [comment]
Suggestion to test/try this out with minimal apis as well.  Much easier add some API functionality to a Blazor app without needing the full MVC ceremony?

**Comment by rockfordlhotka** [comment]
Good idea @swegele - though I think if it works in a controller it will also work in a minimal API b/c my understanding is that the pipeline is actually the same.

Really what matters is that the `User` value comes from either the `HttpContext` or an `AuthenticationStateProvider` as appropriate. All other state can now be maintained in the DI scope and it'll work.

**Comment by rockfordlhotka** [comment]
The previous commit should have been attached to #2676, not this issue.

**Comment by rockfordlhotka** [comment]
@TheCakeMonster I'm working on this, but can't figure out how to access the CircuitHandler and Circuit types outside an actual aspnetcore project. In other words, I have yet to find a package I can reference in `Csla.Blazor` (ns20, net5, net6) where I can access those types.

Also, to access `IHttpContextAccessor` I need to add an aspnetcore server package to `Csla.Blazor` - which might get deployed to a Blazor client too.

So I'm thinking some redesign is probably required, to try and keep some of these types isolated, and to access those that aren't available to a class library.

**Comment by TheCakeMonster** [comment]
Yeah, the references were my concern exactly, and that's why I felt it best not to dive in and do it until you'd had a look and a think.

I think the problem is the potential for a circular reference. I agree that the hybrid context manager could reside in Csla.AspNetCore - except it needs to instantiate the Blazor one, which would be in Csla.Blazor. Which, I think you said the other day, references Csla.AspNetCore. And that's a circular reference, which is not allowed :-(

I could see one solution being A Csla.Blazor.ServerSide package, but that seemed overkill.

Ah, it looks like you've maybe overcome it in the PR by copying the context manager into both places. Yes, that works too!

**Comment by rockfordlhotka** [comment]
In the end, the context manager is only in the Csla.AspNetCore package. The Csla.Blazor package has no context manager.
