### ISSUE TITLE
Allow use of data portal in AddObjectAuthorizationRules method

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2796]
Ok, I understand this will work with normal business objects. You can pass the DataPortalFactory to the static async method. 
On the other hand, the `AddObjectAuthorisationRules` static method is called by csla itself and it does not allow for any parameters at the moment.
What about allowing an optional IDataPortalFactory parameter for the AddObjectAuthorisationRules static method?
Something like this:
````
[ObjectAuthorizationRules]
private static void AddObjectAuthorizationRules(IDataPortalFactory factory)
{
    
}
````
I am not sure this will work, since the coder has no control to pass in the factory object.
It needs to be passed in by the csla framework and the coder needs to be able to use it.
Your thoughts on this?

_Originally posted by @JacoJordaan in https://github.com/MarimerLLC/csla/discussions/2790#discussioncomment-2233924_

**Comment by rockfordlhotka** [comment]
@JacoJordaan this might not be the final form we're going toward, but what I've done here is allowed an optional parameter to the `ObjectAuthorizationRules` method, which is an `ApplicationContext` instance.

We might want to abstract this a bit and pass in some sort of `context` parameter instead - like in a rule when it is executed.

The limitation here, and what _might_ be a breaking change, is that if someone were calling the `AddRules` method from _outside_ this method, then `applicationContext` would be `null` and that'd result in an exception. Prior to this change it was possible to externalize loading per-type authorization rules into a different class in your app, and this change prevents that.

I don't know if anyone actually _did_ such a thing - just observing that it was possible (mostly to enable scenarios where rules were loaded from a database as the app starts up).

If the very first attempt to interact with per-type authz rules is by a `HasPermission` or data portal call, then this change works as desired. I think that's the normal scenario, and so I _suspect_ this won't actually break anyone.

**Comment by JacoJordaan** [comment]
@rockfordlhotka, I am actually loading rules from a database through a different class by calling `BusinessRules.AddRule` with the required information from the database.

Your changes will allow me to  load the data from the database into my class and then call the `AddRule` method.
In my use case, I don't think your changes will break my implementation.  I will download the code and test.

If the application context is however required when calling `BusinessRules.AddRule`, is it not possible to overload the method
````
public static void AddRule(Type objectType, IAuthorizationRule rule, string ruleSet)
    {
      var typeRules = AuthorizationRuleManager.GetRulesForType(null, objectType, ruleSet);
      EnsureUniqueRule(typeRules, rule);
      typeRules.Rules.Add(rule);
    }
````
by adding a method 
````
public static void AddRule(ApplicationContext applicationContext, Type objectType, IAuthorizationRule rule, string ruleSet)
    {
      var typeRules = AuthorizationRuleManager.GetRulesForType(applicationContext, objectType, ruleSet);
      EnsureUniqueRule(typeRules, rule);
      typeRules.Rules.Add(rule);
    }
````
to allow the coder to pass in the application context?

**Comment by rockfordlhotka** [comment]
I see what you are saying. That is probably the right answer.
