### ISSUE TITLE
DI still giving wrong IContextManager within new scope in LocalProxy (IsStatefulRuntime=true)

### ISSUE THREAD

**Issue by swegele** [MarimerLLC/csla#2798]
@rockfordlhotka  @TheCakeMonster 
All testing good in preview 6 except one last issue - it's baaaack :-(   

AFAIK - this issue only shows up when
1.  LocalProxy is being used
2.  A new scope is in play (e.g. for ApplicationContextManager instances with `IsStatefulRuntime=true`)

As you know, in `LocalProxy,` if in a new scope, we now manually create `ApplicationContextManagerAsyncLocal`.  
But since DI doesn't create it, DI doesn't yet have a scoped instance of `IContextManager` to give others.  So the next time (while in that scope) any code uses DI to get an `IContextManager`, a new instance is given for whatever `IContextManager` type is registered.  (In BSS this ends up being a new instance of `ApplicationContextManagerHttpContext`)

**BUG:**  So you  end up with LocalProxy having an  `ApplicationContextManagerAsyncLocal` while my code gets a separate `ApplicationContextManagerHttpContext`

Two different IContextManagers on logical server side is a problem.  We need to devise a way where, **during the new scope in `LocalProxy`**, only one is used and it is always `ApplicationContextManagerAsyncLocal`.

Back to the chicken-egg scenario:  

Maybe you'll think of a better way, because this is rough, but I think it will work.  After brainstorming on this for hours, it's the only way I can think of that respects DI:

FIRST:
1. Create a new scoped service called "LocalProxyState" which has a bool property "NewScopeExists".
2. See about making an abstract base class called `ApplicationContextManagerFacade` which implements `IContextManager`.  This can then be used for 3 below.
2. Make each `IContextManager` implementation where `IsStatefulRuntime=true` be a class that inherits from `ApplicationContextManagerFacade`, and which is a facade wrapper with an `ActiveContextManager` just like the current  `Csla.AspNetCore.ApplicationContextManager` class.
3. Each of these facade context managers needs to use the `LocalProxyState` in their CTOR to know if they should create the  `ActiveContextManager` as a `ApplicationContextManagerAsyncLocal`

SECOND:
1. Immediately after LocalProxy creates the new scope, it will fetch a fresh instance of this service
    `var lpScopState = provider.GetRequiredService<LocalProxyState>()` 
    then it sets
    `lpScopeState.NewScopeExists= true`
2. LocalProxy should then use DI to get it's `IContextManager` and everyone gets one happy scoped instance

If you think it's a good idea, I could try it in a PR?

**Comment by rockfordlhotka** [comment]
This shouldn't be happening though, because LocalProxy only creates a new scope if it is running in a logical client, and when called by code that's already running in the logical server then no new scope should be created - regardless of the `IsStatefulRuntime` value.

So my question is how is code running in the logical server and still creating a new scope?

**Comment by swegele** [comment]
Right, LocalProxy creates the new scope (for BSS and WPF etc.)...then it manually creates an ApplicationContextManagerAsyncLocal.  But then the first subsequent call to DI to get an ApplicationContextManager will not get the one you manually created but it will create ANOTHER one.  Now you have two within that scope.

In the case of BSS, this is doubly bad because in the CTOR for it's AppContextManager, the new instance of the ActiveCircuitState reports that CircuitExists=false.  So you end up with an ActiveContextManager of ApplicationContextManagerHttpContext because HttpContext is present.

**Comment by swegele** [comment]
We need some flag that we can set...so that when DI calls a CTOR for a facade ApplicationContextManager it can know that it should create a ApplicationContextManagerAsyncLocal because it knows "I'm within the new scope of the LocalProxy".  If we figure that out then we can go back to LocalProxy creating it's IContextManager through DI.

**Comment by rockfordlhotka** [comment]
@swegele I see where you are going with the PR. However, I'm concerned that this issue exists in _all_ runtimes, not just aspnetcore and/or Blazor.

Or am I missing something and the PR is a solution for all runtimes?

**Comment by swegele** [comment]
Right, well partly.  AFAIK - the issue only shows up for those runtimes that are "stateful" (i.e. runtimes that would cause `IsStatefulRuntime=true` in `LocalProxy`).

I wanted to see if you like the idea before taking the time to apply the Facade pattern to the other stateful runtimes.

I think what remains TODO is to make a Facade ApplicationContext manager for those other runtimes (WPF etc.) just like what @TheCakeMonster did for AspNetCore.

**Comment by swegele** [comment]
If you want me to take a crack at it, I'll do it and add another commit to the PR.

**Comment by rockfordlhotka** [comment]
I'd like to think on it a bit. It seems like there should be a more elegant solution. What we're doing here largely bypasses the value of DI in a sense, and it just feels a little off to me. Like we're missing something, but I don't know what 😬

**Comment by swegele** [comment]
Yep.

I've chewed on this for hours going in circles, trying to figure out which comes first, the chicken or the egg.  This amounts to a "well it works" solution.  It felt like some "thing" was slightly askew, but what that "thing" is, is a bit over my head.  My gut says it might be something fairly core to the architecture. And this late in the game I'd be leary of that big a change unless really necessary.

The trick is that in the lowest layer we need LocalProxy (which doesn't know anything about higher layers) to know that it will get what it needs from the higher layers.  At the same time, the higher layers (which don't know anything about what's happening in LocalProxy) need to be able to adapt and return an AsyncLocal version of appcontextmanager.

The only risk I see (IMHO) is that someone makes their own ApplicationContextManager and that someone doesn't know how to make it properly respect the needs of LocalProxy.

We could add safety mechanisms (for example) 

1.  **within the new scope** of LocalProxy after the DI call for `IContextManager`, we could check to make sure that the returned instance inherits from `ApplicationContextManagerFacade`.   This would help ensure that anyone's custom ApplicationContextManager was implemented correctly to respect LocalProxy.  
2. Could also go one step further to ensure that the `ActiveContextManager` is of type `ApplicationContextManagerAsyncLocal`

This would, at run-time, give feedback to the developer "Hey dude, respect LocalProxy please".

**Comment by swegele** [comment]
One further thought related to your concern:

> What we're doing here largely bypasses the value of DI in a sense

Whatever is special about `ApplicationContextManagerAsyncLocal` that causes us to want to use that in the scoped stateful `LocalProxy` we could abstract into an interface such that we could test for the instance implementing it rather than demanding it be the concrete type when fetching `IContextManger`.  But TBH that could be overkill.

Anyway, I'm just getting my thoughts out of my head.

**Comment by swegele** [comment]
@rockfordlhotka I stewed this on the backburner for the last couple days...the more I think about it the better this looks.  IMHO it does NOT bypass DI.  Devs can make and register their own ApplicationContextManager implementing whatever they want.  
Simply, we are making the default ones handle the common behaviors/scenarios.

Pretty cool that our Blazor/AspNetCore one can inherit from facade (so pretty much it's only a CTOR) which makes it decide whether it needs to act like:
1. AspNet Razor/MVC
2. Blazor SS
3. HostedService
(and finally)
4.  Regardless of 1 2 or 3 - it can switch to AsyncLocal during new scope of LocalProxy

Same pattern would get applied to the other stateful types. They act like normal till they switch in new scope if that config option is enabled.

My point is, with DI anyone can feel free to roll their own and override almost all of what we do.  Obviously they must know what they are doing their stuff just won't work. But they can look at CSLA default implementations to see where the guideposts are.

True, feature 4 is a new behavior, but it flows naturally from the other cool new behavior of LocalProxy starting a new scope in stateful environments.  This is very powerful and convenient.  

I say we try it and see how it goes.  I'm ready to dive in and convert my huge CSLA 5 business business layer.

**Comment by rockfordlhotka** [comment]
I have a thought I'm going to try. Or at least type out the idea here to see if it falls apart as I describe it.

1. Each context manager has an IsValid property that should return true only if the manager can be used
    1. The HttpContext manager is only valid if it has an HttpContext
    1. The Blazor manager is only valid if it has a circuit
4. ApplicationContext could get a _list_ of registered context managers, and loop through them to use the first one it finds that is valid
    1. The HttpContext one would be valid in aspnetcore where there's no circuit
    2. The Blazor one would be valid in aspnetcore when there is a circuit
    3. Neither would be valid in a job where there's no HttpContext or circuit
    4. If the list of registered context managers doesn't have a valid option, then ApplicationContextManagerAsyncLocal would be used

I think this eliminates the need for that intermediate aspnetcore context manager that's really just a switcher, and makes it so the CSLA startup code for aspnetcore can just add the HttpContext manager, and the startup code for SSB can just add the Blazor manager. And WPF can add its manager, etc.

**Comment by swegele** [comment]
So here is the only problem with that...in Blazor Server Side, the moment you enter the new scope made by LocalProxy, the CircuitExists property now equals **false** (because it's a new scope).   HttpContext will be not null and thus that one will be errantly selected.  But that shouldn't be counted on or selected in that scenario.  

So, ONLY in BSS and ONLY in the new scope, I needed to create a flag (similar to ActiveCircuitState) that LocalProxy could set to true letting managers know the new scope was created and thus select appropriate one (AsyncLocal....).

**Comment by swegele** [comment]
Sorry, I meant to say that your number 2 idea is valid.  That might be cleaner.

...but you'd still need that flag to catch the scenario where circuit is no longer visible and yet you definitely should not use HttpContext just because it is present.

**Comment by rockfordlhotka** [comment]
In the model I'm trying, this means that the HttpContext context manager needs to know that just having an HttpContext isn't enough to be valid.

I think Microsoft is really messing with us here, by providing an "invalid" HttpContext. I'm not 100% sure we should be building a workaround for what seems to be a bug in aspnetcore itself.

Specifically, if they are saying that they'll provide us with an HttpContext, and then telling us not to use the very instance they created and provided - then they shouldn't be providing us with an instance that is invalid.

**Comment by swegele** [comment]
> I think Microsoft is really messing with us here, by providing an "invalid" HttpContext. I'm not 100% sure we should be building a workaround for what seems to be a bug in aspnetcore itself.
Specifically, if they are saying that they'll provide us with an HttpContext, and then telling us not to use the very instance they created and provided - then they shouldn't be providing us with an instance that is invalid.

**PREACH IT!!** I'm seeing the fallout of their weird decision play out over and over online in articles/examples/guidance and in 3rd party component developers too.  It's dangerous that they provided it as NOT NULL.  Either it shouldn't be available or it should be null.  The way it is just taunts newbs to try it and do bad things.  

I just implemented my SSO engine in Blazor.  I do complicated things and cannot use their middle-ware completely.  I noticed that the federated ClaimsPrincipal from AzureAD is present and perfect in the User property on the Razor side (_Host.cshtml) 
 Then immediately when you check it in Blazor (app.razor) the User property is unauthenticated.  Obviously their middle-ware does some magic to get it across.  But my point is HttpContext is truly untrustworthy in the circuit just like they say.  So to your point....WHY LEAVE A LOADED GUN LYING AROUND!  (eyeroll)

**Comment by rockfordlhotka** [comment]
@swegele please take a look at that most recent commit - I need to go to sleep now, as I have a super early meeting tomorrow, so this is untested - but I think it might be a workable and reasonably straightforward solution?

ApplicationContext selects the context manager that reports IsValid as true, or if none are available it uses the AsyncLocal manager (maybe that should always be added last in the list?).

The new Csla.Runtime.RuntimeInfo type maintains info about whether the current "runtime" is stateful and whether any HttpContext can be considered to be valid. LocalProxy explicitly sets these if/when it creates a new scope, so that new scope is not stateful and HttpContext is invalid.

**Comment by swegele** [comment]
Hope your meeting goes well!  
I've also got a 'Why .NET 6 and Blazor?" presentation to the company at lunch.

Will try this out ASAP and let you know.

**Comment by swegele** [comment]
OK I had a chance to sneak in some testing...two issues I see.

First the bigger issue:  These two conflict with eachother in setting `ApplicationContext.IsStatefulRuntime` property:
```cs
builder.Services.AddCsla(options =>
{
    options.AddServerSideBlazor();
    options.AddAspNetCore();
});

```
This new scenario works if it's all or nothing, but doesn't accommodate the fact that both .cshtml and .razor pages can be running in the same site and thus "sometimes" it is stateful and sometimes it is not.

Second issue - you throw a `NullReferenceException(nameof(HttpContext));` which blows up call to business layer in 
a HostedService.

**Comment by swegele** [comment]
As you and cake monster pointed out, we really can't have BSS without asp.net (example:  there will always be _Host.cshtml and _Layout.cshtml) so we will always need mixed stateful behaviors in Csla based on each call origin not based on universal config.

4 scenarios we must cover:
1. BSS HostedService (httpcontextexists = no / httpcontextuseable = no / circuit = no)
2. razor view calls business layer (httpcontextexists = yes / httpcontextuseable = yes / circuit = no)
3. blazor component calls business layer (httpcontextexists = yes / httpcontextuseable = no / circuit = yes)
4. new scope in LocalProxy for stateful environments (httpcontextexists = yes / httpcontextuseable = no / circuit = no)

**Comment by rockfordlhotka** [comment]
The thing I don't see how to solve is detecting when we have an invalid HttpContext. At least not without setting a scoped value at the start of each inbound request from a caller.

I agree that the aspnetcore and blazor configs conflict - Blazor should be called second to make most things work - and that order dependence where `AddAspNetCore` must occur _before_ the Blazor config is fragile.

My tentative thought is that a HostedService needs to inject the IRuntimeInfo service and set its properties correctly - before any real code runs as part of handling that client request or doing any work.

The _ideal_ would be some way to detect the invalid HttpContext within `ApplicationContextManagerHttpContext` - based purely on info from the aspnetcore runtime.

**Comment by rockfordlhotka** [comment]
| Index | Model | HttpContext exists | HttpContext valid | Circuit exists | ACHttpContext valid | ACSSB valid | ACAL valid |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | aspnetcore request (MVC, Razor Page) | yes | yes | no | yes | no | no |
| 2 | aspnetcore HostedService | no | no | no | no | no | yes |
| 3 | Server-side Blazor pages | yes | no | yes | no | yes | no |
| 4 | new scope within Server-side Blazor | yes | no | no | no | no | yes |

@swegele I think my latest update nearly addresses all four models.

`ApplicationContextHttpClient` is only valid if there is an HttpContext and RuntimeInfo.IsHttpContextValid=true - it shouldn't throw if HttpContext is null, it should just report invalid, thus supporting model number 2.

`ApplicationContextBlazor` is only valid if there is a circuit

`LocalProxy` explicitly sets its new scope so RuntimeInfo.IsHttpContextValid=false and IsStatefulRuntime=false - and so should cause ApplicationContext to select `ApplicationContextAsyncLocal` within the child scope.

Scenario number 2 would _also_ get `ApplicationContextAsyncLocal` because there's no HttpContext nor circuit, so neither of the registered context manager services will be valid.

**Comment by swegele** [comment]
@rockfordlhotka any chance of one more quick preview release?

I've finished converting our business layer to Csla 6 and .NET 6.   Now converting the automated tests so I can be ready next week for sharing with the team.  It would be helpful to have the latest Csla packages flow to the team via nuget rather than trying to figure out how to get them local temporary packages.

**Comment by swegele** [comment]
Actually, pause on that (if you were getting ready to hit the red button).  

I'm running my tests now and seeing some weird behavior with:
-  Child objects in `[UpdateChild]` method
-  Command objects in `[Execute]` method 
where the `ApplicationContext.LogicalExecutionLocation` is not being properly set to "Server".  Trying to see if I can pinpoint what is going on.

**Comment by swegele** [comment]
New issue #2808 entered, I hope it makes sense.
