### ISSUE TITLE
Wrong PropertyChangedMode in UI WPF?

### ISSUE THREAD

**Issue by bujma** [MarimerLLC/csla#2813]
https://github.com/MarimerLLC/csla/blob/dfaf1520e0e5acc05ee910b4f88703aafa137822/Samples/ProjectTracker/ProjectTracker.Ui.WPF/App.xaml.cs#L22

Shouldn't there be `Csla.ApplicationContext.PropertyChangedModes.Xaml` for WPF?

**Comment by rockfordlhotka** [comment]
The default (anything other than Windows) works for XAML scenarios. Windows Forms is a special case, different from everything else, and so it has its own propertychanged mode.

**Comment by bujma** [comment]
Yes, I understand Windows Forms has its own propertychanged mode, but why it is used in WPF application?

**Comment by rockfordlhotka** [comment]
Ahh, that seems like a bug in the sample.
