### ISSUE TITLE
'Visual hang' after selecting a resource in the Resources list

### ISSUE THREAD

**Issue by bujma** [MarimerLLC/csla#2815]
**Steps:**
- no configuration or code change after downloading the sources
- ProjectTracker.Ui.WPF and ProjectTracker.AppServerCore as startup projects
- run, login as 'manager'
- go to Project List
- press [Edit] on any project
- press [Add resource]
- select other than already selected resource in the Resources list
- => 'visual hang' with active Busy indication

**Version and Platform**
CSLA version: 5.5.1 as referenced in downloaded sources of v5.x branch (tried also with 5.5.2)
OS: Windows
Platform: WPF

**Potential fix**
Adding
```c#
Bxf.Shell.Instance.ShowStatus(new Bxf.Status { IsBusy = false });
```
as the last line of
https://github.com/MarimerLLC/csla/blob/dfaf1520e0e5acc05ee910b4f88703aafa137822/Samples/ProjectTracker/ProjectTracker.Ui.WPF/ViewModels/ProjectResourceEdit.cs#L63-L68
Is it OK and enough?

**Comment by rockfordlhotka** [comment]
Will be handled via #2551
