### ISSUE TITLE
Rule context objects should expose ApplicationContext

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/csla#2839]
**Describe the bug**

This relates to changes in CSLA 6 preview 7 for issue #2796

It will be helpful if the `AddObjectAuthorizationRulesContext`  can expose `ApplicationContext` directly. Since there is a public override method on `BusinessRule.AddRule` that takes a parameter of ApplicationContext, it makes sense to have the ApplicationContext available from the AddObjectAuthorizationRulesContext class.

Suggested changes in `AddObjectAuthorizationRulesContext`:
Change property: 
````
private ApplicationContext ApplicationContext { get; set; }
````
to:
````
public ApplicationContext ApplicationContext { get; private set; }
````

Suggested changes in `IAddObjectAuthorizationRulesContext`:
Add: 
````
    /// <summary>
    /// Gets the application context
    /// </summary>
    ApplicationContext ApplicationContext { get; }
````

**Version and Platform**
CSLA version: 6 prelease 7
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by JacoJordaan** [comment]
Ok, I am with you. Thanks for the clarification.

I do have a scenario where I check for the `ApplicationContext.ExecutionLocation` and skip the loading of rules from the database when the execution location = Server.
Let me first check if I can change my approach by rather loading the all the rules at app startup as you suggested.

**Comment by JacoJordaan** [comment]
I have tested loading rules outside the static method on app startup by calling the overload of `AddRule`, but the rules are **ignored** (not called).
From inside the `AddObjectAuthorizationRules`, it is working fine.

**Comment by rockfordlhotka** [comment]
Hmm. Maybe that scenario just isn't supported. I can't say I've ever considered it until we started making these changes. So in that case, that overload can be removed, as it is not necessary. Excellent!

**Comment by rockfordlhotka** [comment]
At the same time, I think you are right, in that the various rule context types should expose `ApplicationContext` rather than just properties of `ApplicationContext`.
