### ISSUE TITLE
In pure AspNet .NET 6 (razor or mvc only - no blazor)...Csla requires registration of AuthenticationStateProvider

### ISSUE THREAD

**Issue by swegele** [MarimerLLC/csla#2850]
Given an .NET 6 AspNet web site, 
using the Csla and the Csla.AspNetCore packages,
with this in program.cs `builder.Services.AddCsla(options => options.AddAspNetCore());`

When you use DI to get an ApplicationContext like so: 
`ServiceProvider.GetRequiredService<ApplicationContext>();`

You get an error from DI saying that it cannot 
resolve `Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider`

This is because of the following in Csla.AspNetCore
`config.Services.AddScoped(typeof(IContextManager), typeof(ApplicationContextManagerBlazor));`

If you register an instance then DI works:
`builder.Services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>()`

Having Csla users remember to register this should not be required.  Several ideas:
1.  Use some configuration to only register the `ApplicationContextManagerBlazor` when BSS is being used.
or
2.  Add a default to `AddAspNetCore` of `AuthenticationStateProvider`

Thoughts?

**Comment by rockfordlhotka** [comment]
I've been thinking the same thing.

In fact I did, quite some time ago, include a simple default implementation in CSLA, and as part of a bunch of our discussions about identity and everything I removed those types.

Probably should bring them back.

**Comment by swegele** [comment]
Would it work to move this line:

`config.Services.AddScoped(typeof(IContextManager), typeof(ApplicationContextManagerBlazor));`

from here  `Csla.AspNetCore.ConfigurationExtensions` 

to here `Csla.Blazor.ConfigurationExtensions.AddServerSideBlazor` ?


This would make it activate only when BSS is wanted/used.

**Comment by rockfordlhotka** [comment]
I think that's a good point - though I still need to re-add the simple implementation of the state provider, or people will be forced to reckon with the issue for all SSB apps too.
