### ISSUE TITLE
Backport More Secure Authorization, Revalidation and Sanitization Data Portal Protections to CSLA 5.x

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2852]
Issues #2650 and #2662 resulted in the addition of implementations for data portal extensibility points that provided additional security protections to remote data portal endpoints into CSLA 6. This addition avoids developers needing to create their own custom protection classes to reduce risk of invalid requests from threat actors being processed by those remote endpoints, making systems more secure.

I'd like to backport these implementations into the CSLA 5.x branch, allowing existing users of CSLA 5.x to enable the additional protections on their deployed systems without having to create custom code.

As this will be released as part of a patch or minor release, we need to decide whether to enable these protections by default. Whilst I would prefer the protections provided were on for everyone, it is probably most appropriate that they are not enabled by default, as people will not be expecting changes to the behaviour of the system in either a minor or bugfix release.

The first step is to create the code, which I am working on at the moment. Once we have the code we can then debate whether to enable them by default.

**Comment by rockfordlhotka** [comment]
I agree that this shouldn't be on by default. No breaking changes in CSLA 5 - at least not unless we publish a different versioning scheme for CSLA 5 going forward (not normal semver).
