### ISSUE TITLE
Command objects fail to execute under CSLA 6 - NullReferenceException from ObjectCloner

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/csla#2859]
**Summary**
Our unit tests show that an exception is thrown when attempting to execute a command object under CSLA 6 using the old usage pattern. 

Here is the usage pattern to which I refer:
``` csharp
CommandObject obj = new CommandObject();
// Set any properties on the object needed for execution
obj = dataPortal.Execute(obj);
```

An instance of a command object is created using its constructor, before being executed by passing it to the data portal. Under CSLA 6 an exception is caused internally when it attempts to clone the object prior to execution. This is caused by the ObjectCloner.GetInstance() method having been passed a null ApplicationContext from the command object, since the command object has not had an instance applied to it by anything before that point.

**Potential Solutions**

**Option 1**
We could instead create the instance of the command object using the data portal rather than its constructor, but as it stands at the moment this would have the unfortunate side-effect of forcing the addition of a data access method marked with the [Create] attribute added to all command objects, which I don't like.

We could perhaps get round the need to add a [Create] method by adding such a method to the base class, CommandBase. However, all of the consumer code that makes use of command objects would need more changes this way - it all needs to be changed to avoid use of the constructor.

``` csharp
CommandObject obj = dataPortal.Create();
// Set any properties on the object needed for execution
obj = dataPortal.Execute(obj);
```

**Option 2**
Alternatively, should/could the data portal internally take responsibility for setting the ApplicationContext property on the command object prior to execution of the data access method? This is probably a simpler change. However, is it less consistent for command objects to continue to be created using their constructor when nothing else works this way?

**Version and Platform**
CSLA version: 6.0
MSTest project Csla.Tests (in Csla.test.Csla6 solution)

**Exception Details**
TestCommandBase
   Source: BasicTests.cs line 84
   Duration: 113 ms

Message: 
  Test method Csla.Test.Basic.BasicTests.TestCommandBase threw exception: 
  System.NullReferenceException: Object reference not set to an instance of an object.

Stack Trace: 
  DataPortal_1.Update(T obj) line 476
  DataPortal_1.Execute(T command) line 592
  BasicTests.TestCommandBase() line 90

**Comment by rockfordlhotka** [comment]
I think option 1 is correct. Adding

```c#
  [Create]
  private void Create() { }
```

seems pretty straightforward, and makes command objects work like everything else.

**Comment by TheCakeMonster** [comment]
Thanks. Are you suggesting that we have users of the framework do that in their code, or that we add it to the base class inside of the framework?

I'll add RunLocal too; I didn't mention that in my original code, but I do intend to do that.

**Comment by rockfordlhotka** [comment]
Yes, I forgot RunLocal.

We don't have any data portal operation methods in the base classes anymore, and I hesitate to add them back.

**Comment by TheCakeMonster** [comment]
I can understand that, although I wonder how user-friendly that will seem for people. It seems unfortunate that people will have to learn to always include a method stub for creation that doesn't do anything.
