### ISSUE TITLE
Business layer code (using LocalProxy) is ~4x slower after preview 8

### ISSUE THREAD

**Issue by swegele** [MarimerLLC/csla#2885]
We have a huge automated test suite in the form of "Integration Tests" that run against an instance of LocalDB (SQL server) and test around 80% of our business layer.

Preview 7 - tests take around 6 minutes to run

Preview 8 - tests take around 20 minutes to run

Given our code didn't change, something fairly basic and significant changed related to performance in the framework.  Got any ideas what the culprits might be?
In this latest preview we added a loop in the `LocalProxy.SetApplicationContext` which might be a suspect just because it's more processing.  Not sure what else might be an issue.  Thinking off the top of my head, I'm wondering if we could add some parallelism in that to increase performance.  Thinking out-loud.

Not necessarily saying it's a problem since automated tests don't really mimic real live users who are not that fast and clicking :-)  But it's just note worthy at least.

**Comment by rockfordlhotka** [comment]
That's not good. I wouldn't expect traversing the tree to be so slow, but maybe?

**Comment by swegele** [comment]
We will do some testing here playing with that method and see if that is the issue or maybe it is somewhere else.  If your gut bubbles up another possible target area let me know.  Will report back asap.

**Comment by swegele** [comment]
OK @rockfordlhotka, sorry for the delay in getting back to you on this.   One of our developers dug into this and confirmed.  The performance hit is an average 10x slow down, all of which is from the `LocalProxy.SetApplicationContext` method.  The perf hit is obviously directly related to the level of recursion, the number of objects being passed across the portal, and the depth of their object graph. 

Example: One ReadOnly object with a handful of properties finishes very quickly (not human noticeable).  
But a complex editable object with many child properties, some of which are collections with many children, that 10X starts to become noticeable.  
Add that all up over a series of Automated Integration Tests and 10X literally takes us from what used to take 6 minutes is now pushing an hour.

**Confirmation:**
Here is how we confirmed the perf issue.  

1.  We commented out this section in LocalProxy constructor:
```cs
if (OriginalApplicationContext.LogicalExecutionLocation == ApplicationContext.LogicalExecutionLocations.Client 
  && OriginalApplicationContext.IsAStatefulContextManager)
{
  // create new DI scope and provider
  _scope = OriginalApplicationContext.CurrentServiceProvider.CreateScope();
  currentServiceProvider = _scope.ServiceProvider;

  // set runtime info to reflect that we're in a logical server-side
  // data portal operation, so this "runtime" is stateless and
  // we can't count on HttpContext
  var runtimeInfo = currentServiceProvider.GetRequiredService<IRuntimeInfo>();
  runtimeInfo.LocalProxyNewScopeExists = true;
}
```

2.  Then we commented out each of the calls to `SetApplicationContext` in the Create/Fetch/Update/Delete methods in LocalProxy.


Changing nothing else, running the automated tests went back to finishing quickly as they were before.


You will realize that our change is in essence the same thing that the option `LocalProxyOptions.CreateScopePerCall = false` used to do (but you removed that recently).  

Additionally:  We haven't made a deep dive into ways to speed it up yet, but we did do a quick try at adding "Parallel.ForEach" useage in that method, but as expected it didn't have that big of an effect because the amount of CPU processing per thread is quite low and thus the overhead of the parallelism isn't offset.


**Request 1 (big favor):**
Can we add that `LocalProxyOptions.CreateScopePerCall` option back in, and then do a quick pre-release 9 so our team can get back to productive (including running our automated tests without wanting to put a samurai sword in our bellies :-)
While we are looking forward to that new feature giving us the ability to make concurrent calls to the dataportal, we've never had that before so we don't miss it yet if we need to turn that off.


**Request 2**
Can we get our collective brain-trust focused on speeding that up somehow.  Seems like there must be some better way to have every object get a new reference, but I'm not coming up with anything yet on my own.  Seems like everything comes back to that reference to the ServiceProvider one way or another.

Thanks!

**Comment by rockfordlhotka** [comment]
I really appreciate the research.

I am on my way to Chicago for two full days of meetings, so probably won't be able to look at this until Friday or the weekend.

**Comment by rockfordlhotka** [comment]
And alternate implementation would be to have only the root object in the graph maintain a reference to `ApplicationContext`. The `ApplicationContext` property implementation would see if `Parent` was null and if so it would use its own value, otherwise it would as its parent for the value.

If we implement it this way, then `LocalProxy` wouldn't need to traverse the tree, and could just set the new value for the root object and the entire object graph would be happy.

(he says, while sitting on an airplane as they try to see if the engine will start)

**Comment by swegele** [comment]
OK got some data and I find the conclusions interesting.  We ran our test suite, tracking elapsed milliseconds for each of the three calls to SetApplicationContext in each of the LocalProxy CRUD methods.

- Total count of calls to SetApplicationContext is just over 3 million and 220K.
- That means our tests cause just over 1 million calls to a CRUD method through LocalProxy (wow)
- The max time taken to complete any one SetApplicationContext method was 20ms (there were only a few of those)
- There were a few more at 19ms, a few more at 18ms and so on down to several hundred that took 1ms.
- This means the almost 99% of the calls took less than 1ms!  That's not bad and what you expected.

If you round up the <1 values to just be one and then do this...(number of calls * 1ms / 3 / 1000 / 60) this yields ~58 which is close to the number of minutes it took run the tests once through.   Without the LocalProxy new scope, the tests take <10 min so the actual logic of the tests is almost immaterial here.  
This all shows a valid sanity check on the logic/methodology of our technique.


**So what does it mean?** 
As expected and stated in post above, our tests uniquely cause a cumulative performance hit given that they run as one continuous serial set of tasks (no parallelism) - integration tests doing CRUD operations with real data against a real SQL Server at the speed of compute.

1.  Normal scenarios of human testing would seriously negate this cumulative effect because humans do things slower thus the extra milliseconds here and there are not noticed.
2.  Normal scenarios of multiple humans testing would still not cause this cumulative effect because each concurrent user's actions are isolated from others and are not additive.
3.  Normal scenarios of automated processes would not show this cumulative effect because we just don't have any real life bulk scenarios like the bulk serial operation that our automated tests mimic.
4.  If, in future, we ever did have some bulk serial automated process popup, we'd need to design that process in an appropriate manner (likely would not use Csla for that at all...or some kind of specialized form).

**Final Conclusions:**
1.  The 10x perf hit is real using LocalProxy...but likely not noticeable in many/most scenarios given the sub-millisecond time frames involved.  It will be interesting to hear from other users of Csla to see if they noticed anything.  I guess keep your ears open.
2.  **If you put back in the option to turn off the create new scope feature**, then our tests will go back to running fast like before and we are fine because our tests don't need to run in parallel anyway.
3.  Since our Blazor UI users will not notice the perf hit given how humans work...we can leave the option on for production code which safely enables concurrent calls to LocalProxy.
4.  As a double safety mechanism, we will run our automated tests at least once a sprint **with the LocalProxyCreateScope option on** to ensure full code coverage addressing any concerns that we are testing the system similarly to how we are actually running it in production.

5.  Maybe you have some breakthrough insight into how to address this issue...and in future we can remove the step 4. 
 Depending upon how you look at this issue, it is serious to moderate to minor.  Curious what you think.


**Idea for a possible 3x to 5x improvement - not sure I like it but it's an idea**
Racking my brain for a couple days now thinking about what could be done.  I might have an idea:
1.  When entering the LocalProxy CRUD method you still call SetApplicationContext as it is currently.  This normalizes all refs for all objects crossing to the logical server side to use ONE reference of CurrentApplicationContext (regardless of what they were on the client).  This part would still suffer from the existing perf hit but I can't see any way around it (because of 3 below)
2.  During server side operations everything operates like normal in the new scope
3.  When exiting the LocalProxy CRUD method, instead of calling SetApplicationContext...you would instead simply pick ONE instance of the CurrentApplicationContext and do ONE replacement of it's gut child references with the gut references of the OriginalApplicationContext.  Boom - super fast and only done once effecting all instances in all object graphs.

But realize the technique in 3 leaves you in a situation where the ApplicationContext wrapper inside Csla objects can diverge into different references than others already on the client.  But maybe it doesn't matter because
1.  The actual references INSIDE the ApplicationContext are still one
2.  Any mix of these going back across the dataportal are sanitized and unified

Hope that makes sense and perhaps gets some creative juices flowing in your head.

All the other techniques I can think of fail unless you literally removed the internal reference to ApplicationContext AND it's embedded ServiceProvider from all objects.  Yikes - big change.  The cost of that architectural change at this late hour is pretty friggin high.
I muse that this kind of stuff is likely why some architects recommend using only POCOs.  But I'd argue that just shifts shells of effort around and you still must pay the pied piper somewhere!  But their arguments are definitely valid related to complexity and higher maintenance/education costs.

**Comment by rockfordlhotka** [comment]
I plan to spend some time today/tomorrow trying to find a better solution, because I don't want to accept this perf hit. I'd prefer not adding back in the option to not create a new scope, but if I can't figure out a solution I agree that's a workaround.

> I muse that this kind of stuff is likely why some architects recommend using only POCOs. But I'd argue that just shifts shells of effort around and you still must pay the pied piper somewhere! But their arguments are definitely valid related to complexity and higher maintenance/education costs.

No doubt! This is one of the things that makes CSLA unique with its support for mobile objects, and that architectural choice has its consequences (good and bad).

**Comment by swegele** [comment]
My co-worker suggested another way of looking at this...to focus on the sheer number of calls (+1M) to LocalProxy CRUD methods.  We do have a lot of automated tests but not THAT many :-)  I think that is because Csla says do not create an object directly through a CTOR (because of analyzers) when creating items for a list.  So if one of my tests is fetching a ReadOnlyList of whatever...then the Fetch method gets called once for each child item being added.  Of course this ensures all the plumbing and stuff is done correctly.  And the individual time for each of those is sub milliseconds....but that does add up.

And...
> This is one of the things that makes CSLA unique with its support for mobile objects, and that architectural choice has its consequences (good and bad).

Exactly.  The "Class-in-charge" approach is big reason why I love Csla so much.  But we realize, like everything, this has it's costs.   All architectures have their costs.  I'd say proudly that Csla has managed to stay modern and relevant while doing what it was fundamentally designed to do since 97....which is several lifetimes in technology.  It's looking like Csla 6 secures another 5 to 10 years if history is any guide.  It was the hardest upgrade of Csla yet, but worth it.

**Comment by swegele** [comment]
Finally got time to sit down and run tests to gather data for ya this morning.  Hopefully I'll have it for ya within the hour.

**Comment by swegele** [comment]
I picked a chunk from the beginning of the test suite (so I didn't have to wait the whole thing to run...good sampling of the whole though).  

Here are the somewhat surprising results of test runs in three different configurations:
1.  Preview 8 from nuget (run like normal)
2.  Your new code - pulled from your rockfordlhotka 2885 (post build copy of the dlls over nuget ones)
3.  Your new code - with the create new scope and Set/Replace parts commented out (post build copy of the dlls over nuget ones)



| Type | First Run Time | Second Run Time |
| --- | --- | --- |
| Preview 8 | 6.9 min | 6.5 min |
| Your new code | 6.6 min | 6.5 min |
| New Scope Disabled | 1.7 min | 1.6 min |

I'm surprised your technique didn't make a bigger impact.  I didn't expect that.

**Comment by rockfordlhotka** [comment]
I am also surprised. This makes me think that something else is generating overhead, though I don't know what that would be.

The new scope _does_ require creating new instances of all scoped services that are used - so maybe one or more services have a measurable startup cost or something?

**Comment by swegele** [comment]
I think the only way to really understand further and in depth would be to do some debugging adding some stopwatch instrumentation (down to the Ticks resolution <= ms measurements) for each action in that class...and then see where that leads.

Ultimately, I thank you for adding the UseLocalScope option, because the more I think about it the more I am convinced that my long string of automated tests running serially is artificially showing this as a large perf hit.  Turning off that option during my tests is completely fine because I do not use any concurrency.  If, at some point in the future, I come back and start breaking up the string of tests to run several groups concurrently then I will reenable that option.  But then by definition I would also see a perf _improvement_ directly related to the number of concurrent actions 👍  So I'm not worried.

Thanks Rocky!
