### ISSUE TITLE
BeginEdit thrown "out of memory" exception

### ISSUE THREAD

**Issue by 844235626Alex** [MarimerLLC/csla#2904]
**Describe the bug**
When i m trying to clone a SupportUndo model and call ing BeginEdit function, it thrown exception "out of memory"

**Version and Platform**
CSLA version: 4.3.13.0
OS: Windows
Platform:  WPF.

**Code that Fails**

```c#
private void SetModel(T oldValue, T newValue)
        {
            if (oldValue != null)
            {
                oldValue.PropertyChanged -= OnPropertyChanged;
                oldValue.ChildChanged -= OnChildChanged;
                oldValue.CancelEdit();
            }
            if (newValue != null)
            {
                newValue.PropertyChanged += OnPropertyChanged;
                newValue.ChildChanged += OnChildChanged;
                newValue.BeginEdit();
            }
        }
```

**Stack Trace or Exception Detail**

```
   at System.IO.MemoryStream.ToArray()
   at Csla.Core.UndoableBase.CopyState(Int32 parentEditLevel)
   at Csla.Core.UndoableBase.Csla.Core.IUndoableObject.CopyState(Int32 parentEditLevel, Boolean parentBindingEdit)
   at Csla.BusinessListBase`2.CopyState(Int32 parentEditLevel)
   at Csla.BusinessListBase`2.Csla.Core.IUndoableObject.CopyState(Int32 parentEditLevel, Boolean parentBindingEdit)
   at Csla.Core.FieldManager.FieldDataManager.Csla.Core.IUndoableObject.CopyState(Int32 parentEditLevel, Boolean parentBindingEdit)
   at Csla.Core.UndoableBase.CopyState(Int32 parentEditLevel)
   at Csla.Core.BusinessBase.BeginEdit()
```

**Additional context**

The parameter that need support edit and undo, if child objects is more than 15, this exception occurred 100%.

**Comment by 844235626Alex** [comment]
More than 15 child objects. It's a collection of vector graphics.
Parent object is graph info, include multiple vector graphics as the child for different status.
Such as a button, GraphInfo store the info such as graphic path or name. 
GraphStateInfo store the vector of different status, and it only store the point information but not a binary stream.

Now it crash when i create 15 GraphStateInfo object even there is no any point info inside.

**Comment by 844235626Alex** [comment]
> > if child objects is more than 15
> 
> More than 15 levels deep, or more than 15 child objects?
> 
> Also, do your objects contain large data, like images or massive string values?

More than 15 child objects. It's a collection of vector graphics.
Parent object is graph info, include multiple vector graphics as the child for different status.
Such as a button, GraphInfo store the info such as graphic path or name.
GraphStateInfo store the vector of different status, and it only store the point information but not a binary stream.

Now it crash when i create 15 GraphStateInfo object even there is no any point info inside.

**Comment by rockfordlhotka** [comment]
I'll probably need to see your code. Lots of people (including me) have a root object with a collection of more than 15 child objects.

**Comment by 844235626Alex** [comment]
> I'll probably need to see your code. Lots of people (including me) have a root object with a collection of more than 15 child objects.

Thanks, tt has been resolved, no need to call BeginEdit since it already under this state.
