### ISSUE TITLE
TextSeparator = ", " for concatenating errors

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#2925]
The standard validation error messages such as `[Required]` are proper sentences ending with a `.` and I think this is good practice. `Csla.Blazor.PropertyInfo` assumes error messages won't end with a `.` using `", "` to concatenate errors, so you end up with:

![image](https://user-images.githubusercontent.com/21806535/167091885-b5678283-f833-4d70-b977-8482e632cba2.png)

Should `TextSeparator = " "` or perhaps be a `public static string TextSeparator { get; set; }` instead?

**Comment by rockfordlhotka** [comment]
It seems like something someone could set, and perhaps the default should be `" "`.
