### ISSUE TITLE
Delete triggering ModelPropertyChanged for BusinessListBase but not BusinessBindingListBase in Blazor

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2954]
### Discussed in https://github.com/MarimerLLC/csla/discussions/2951

<div type='discussions-op-text'>

<sup>Originally posted by **michaelcsikos** May 23, 2022</sup>
I have two collections, one inherits from `BusinessListBase`, and the other from `BusinessBindingListBase`. Each collection is wrapped in a `ViewModel<T>`. The `PropertyChangedEventHandler` from the root edit page is passed down to all the children:
```cs
// Root edit page
private async void PropertyChanged(object? sender, PropertyChangedEventArgs e)
{
    await InvokeAsync(() => StateHasChanged());
}

// In each child collection
[Parameter]
public PropertyChangedEventHandler PropertyChanged { get; set; }

protected override void OnInitialized()
{
    VM.ModelPropertyChanged += PropertyChanged;
}
```

In the collection `ViewModel`, child items are deleted like this:
```cs
 public void Remove(WidgetVM context)
 {
     if (Model == null)
         return;

     Model    .Remove(context.Model);
     WidgetVMs.Remove(context);
 }
```

For the `BusinessListBase` deleting a child item triggers `PropertyChanged`, it bubbles up to the root edit page and the **Save** button becomes enabled, but it's not bubbling up for the `BusinessBindingListBase`. Ordinarily I would just use `BusinessListBase` to solve it, but we have some classes which are used in WinForms as well.

Am I approaching this correctly, i.e. making a VM to wrap each collection, and a VM to wrap each child item, and passing `PropertyChangedEventHandler` down?</div>

**Comment by luizfbicalho** [comment]
Is anyone working on this? If not you can assign to me

**Comment by rockfordlhotka** [comment]
I will assign it to you.

The real challenge here is to ensure that Windows Forms doesn't break with this change.

My view is that _if we can do this without breaking Windows Forms_, I'm happy to make `BusinessBindingListBase` work with Blazor. However, `BusinessBindingListBase` _only exists to support Windows Forms_, and that's the highest priority.

A good test for the WinForms binding is this:

https://github.com/MarimerLLC/csla/tree/main/Samples/RootChildGrandchildWinFormTest

**Comment by luizfbicalho** [comment]
I took a look at the inheritance tree of each class, 

BusinessListBase inherits from ObservableCollection<T>

BusinesBindingListBase inherits from BindingList<T>


this code compile

```cs
  public class GrandChildren : BusinessListBase<GrandChildren, GrandChild>
  {
    public GrandChildren()
    {
         this.PropertyChanged += GrandChildren_Child_PropertyChanged;
    }
    private void GrandChildren_Child_PropertyChanged(object sender, PropertyChangedEventArgs e)
    {
    }
  }
```
this code doesn't 

```cs
  public class GrandBindingChildren : BusinessBindingListBase<GrandBindingChildren, GrandChild>
  {
    public GrandBindingChildren()
    {
          this.PropertyChanged += GrandBindingChildren_Child_PropertyChanged;
    }
    private void GrandBindingChildren_Child_PropertyChanged(object arg1, PropertyChangedEventArgs args)
    {
    }
  }
```

there is no definition of PropertyChanged  in this class, I think that to control the binding or the BindingList have to control this events and can't allow us to add more code in it, or BindingList doesn't have the property changed control inside it.

Either way we would have to implement manually this.

**Comment by rockfordlhotka** [comment]
Right, `BindingList` is a very different base type from modern collection base types. I remember fighting with it a lot when WPF first came out, though I don't remember the specific issues.

I know that if a `BindingList` subclass implemented certain events, it would cause Windows Forms and/or WPF data binding to get very confused and not work correctly - especially in the context of data grid controls.

This is why I say that a lot of testing is required so we don't accidentally break people's existing code.

The thing to do is to implement `IPropertyChanged` in `BusinessBindingListBase` and raise the event. Then see if it breaks existing Windows Forms or WPF data binding scenarios.

**Comment by luizfbicalho** [comment]
I looked at the code from `ObservableCollection `, it implements two interfaces `INotifyCollectionChanged`, `INotifyPropertyChanged`

We have 2 ways to solve this, 

1. implement them in `BusinessBindingListBase` 

1.  the other that is "safer" is to inherit from `BusinessBindingListBase` in a new class that implement the interfaces, and then mark `BusinessBindingListBase `as obsolete or create a rule to change

We can also create tests to compare how the two events are triggered on both classes and see if they are the same.

which option do you like best @rockfordlhotka ?

**Comment by rockfordlhotka** [comment]
A third option, that is safest overall, is for @michaelcsikos to implement those two interfaces in his codebase, and to not change the core CSLA codebase at all.

@michaelcsikos, if you are using custom base types between CSLA and your business code, you can implement `INotifyCollectionChanged` and `INotifyPropertyChanged` in your custom `BusinessBindingListBase` base class.

I'm quite nervous about this, because I seem to remember that `INotifyCollectionChanged` is what cause some weird stuff to happen in WPF, because (iirc) WPF tried to use _both_ collection notification schemes and so the UI's data binding got very confused.

**Comment by michaelcsikos** [comment]
Yes, we're using our own base classes inheriting from CSLA. I ended up making our own class inheriting from `BusinessListBase<T>` our reproducing the other methods we were using from the binding list base class. Currently, we don't have a collection that needs to be edited in both WinForms and Blazor.

**Comment by luizfbicalho** [comment]
So this one will be closed?
