### ISSUE TITLE
Linux build fails because pt-BR not found

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2975]
This issue is back in version 5.5.3 (5.4.0 until 5.5.2 seems to be ok), breaking Linux / Docker builds.

![image](https://user-images.githubusercontent.com/43775697/171562011-0aa8a4e9-3225-403b-9957-4cc73c0c7933.png)
(screenshot from version 5.5.3 using the [NuGet Package explorer](https://nuget.info/packages/Csla/5.5.3))

In version 6 the issue is not present, but we can't upgrade to that version just yet. Can this be fixed in the v5 branch again?

_Originally posted by @PieterBoeren in https://github.com/MarimerLLC/csla/issues/1845#issuecomment-1144465833_

**Comment by rockfordlhotka** [comment]
@PieterBoeren I don't see how to fix this - the file in GitHub does have the proper casing.

https://github.com/MarimerLLC/csla/blob/main/Source/Csla/Properties/Resources.pt-BR.resx

**Comment by PieterBoeren** [comment]
The casing of the file (https://github.com/MarimerLLC/csla/blob/v5.x/Source/Csla.Shared.Resources/Resources.pt-BR.resx, the issue is in the 5.x branch, but the casing is correct here) was changed at some point. Isn't it just something like the casing is not updated since the NuGet package is being published from a Windows machine (where Git doesn't really "see" casing changes)?

**Comment by rockfordlhotka** [comment]
Hmm. On my local clone the casing looks right.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/2333134/185507933-8773fa8d-5d98-4714-a95c-8b2b787113a3.png">

**Comment by PieterBoeren** [comment]
Maybe check what happens if you pack it again (I guess the issue can be validated without actually pushing a new version)? I wanted to do it myself, but I gave up since my Visual Studio encountered a lot of not installed frameworks and workloads :(

**Comment by rockfordlhotka** [comment]
I can't really test this, as I don't use a Linux build agent, so I'm going to close it for now.
