### ISSUE TITLE
Provide manual way of triggering a check of business rules.

### ISSUE THREAD

**Issue by oatsoda** [MarimerLLC/csla#298]
To implement authorization checks on the server-side, it currently requires you to write your own code within your own implementation of IAuthorizeDataPortal to:

a) Map the Operation to AuthorizationAction
b) Call BusinessRules.HasPermission
c) If permission is not granted, raise a SecurityException (additionally mapping the Operation to a security action description such as "get", "create")

It would be better if CSLA provided methods for doing this - there could be a method on the AuthorizeRequest object to check the permissions and throw the relevant SecurityException if permission is not granted..

**Comment by rockfordlhotka** [comment]
Need to link new file into the other Csla.dll projects.
