### ISSUE TITLE
Logo not showing in v6 documentation

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2982]
@Brannos1970, when viewing the v6 docs (which are great btw, thank you!), the CSLA logo doesn't appear.

I think we had this with the v5 docs too, and you did something to fix it?

**Comment by Brannos1970** [comment]
Please double check that release. I had some issues getting over from my computer.

**Comment by rockfordlhotka** [comment]
Thank you @Brannos1970, the logo appears now.

btw, did you put in the google analytics link stuff?

**Comment by Brannos1970** [comment]
Should be already there. I will have to double check, will look into it as soon as I can. @rockfordlhotka .

**Comment by Brannos1970** [comment]
@rockfordlhotka the analytics link stuff is there.
