### ISSUE TITLE
FetchAsync in LocalProxy DeadLock

### ISSUE THREAD

**Issue by mbernard** [MarimerLLC/csla#300]
I'm having an issue when I'm using the Async dataPortal methods (FetchAsync(), etc...) at the same time as using a Local Server DataPortal

```
 public async Task Fetch(Type objectType, object criteria, DataPortalContext context, bool isSync)
    {
      if (isSync || Csla.ApplicationContext.LogicalExecutionLocation == ApplicationContext.LogicalExecutionLocations.Server)
      {
        return await _portal.Fetch(objectType, criteria, context, isSync);
      }
      else
      {
        var tcs = new TaskCompletionSource();
        var bw = new Csla.Threading.BackgroundWorker();
        bw.DoWork += (s, o) =>
        {
          o.Result = _portal.Fetch(objectType, criteria, context, isSync).Result;
        };
        bw.RunWorkerCompleted += (s, o) =>
        {
          if (o.Error == null)
            tcs.TrySetResult((DataPortalResult)o.Result);
          else
            tcs.TrySetException(o.Error);
        };
        bw.RunWorkerAsync();
        return await tcs.Task;
      }
    }
```
In my case I'm always falling the in "else" block which seems to dead lock on the ".Result" which for some reason never completes

I just don't get the "else" block and why this method cannot use the code inside the "if" block all the time.

When I change the code to always enter the "if" block no more dead lock and all my async code run just fine.

**Comment by rockfordlhotka** [comment]
@mbernard , there's a compiler warning in the code in WinRT that needs to be addressed so I am reopening this issue. Please take a look at the warning and address it, thank you!

**Comment by rockfordlhotka** [comment]
@mbernard - the warning also exists in the Android project, and I suspect in the iOS project (haven't got to that one yet)

**Comment by mbernard** [comment]
Here a new pull request that fixes the compilation warning
https://github.com/MarimerLLC/csla/pull/317

**Comment by JasonHardman** [comment]
DataPortal fetch no longer executes on a background thread for IOS, Android and .NET.  I have not tried the other DataPortal methods or platforms.

**Comment by rockfordlhotka** [comment]
Reverted the changes for now - obviously need to take another run at this.

**Comment by mbernard** [comment]
@rockfordlhotka I'm investigating the issue. I confirm that it doesn't seem to work properly at the moment

**Comment by rockfordlhotka** [comment]
Thank you @mbernard

**Comment by mbernard** [comment]
@rockfordlhotka I created a new pull request that fixes the issue found by @JasonHardman 

https://github.com/MarimerLLC/csla/pull/328

**Comment by JasonHardman** [comment]
@mbernard I thought a TaskFactory.StartNew() was required somewhere.  But why are you using await await? Shouldn't it be one await?
Also the IOS and Android projects are missing the file reference to CslaTaskScheduler.cs.
Thanks for the fix.

**Comment by mbernard** [comment]
@JasonHardman unfortunately we need to double await because the Action in the TaskFactory.StartNew returns a task<DataPortalResult>. So the return of the StartNew will be a Task<Task<DataPortalResult>>, we then need 2 await to unwrap the final result.

I don't have access to an environment that can open the Android and the iOs project at the moement. Could someone add the missing files in those projects for me please.

**Comment by rockfordlhotka** [comment]
It is also important to test this change in every environment because the whole thing relies on the synchronization context, and that is different in various runtimes.

This also must be tested in a cmd.exe window - where it probably won't 100% work (the original implementation didn't either) because there is *no* sync context. But in the original implementation the most common usage scenario had predictable and useful behavior.

ASP.NET is another outlier. The data portal must work in old-style non-async ASP.NET (Web Forms and MVC), and also in the newer style with an async controller.

Windows Forms and WPF are usually the same. Silverlight might be different, and WinRT might be different.

Thus far iOS and Android appear to work (generally) if Silverlight/WinRT work.

**Comment by mbernard** [comment]
I've been quite busy at work. But I'm planning on testing and fixing it for all platform soon. I'll let you know

**Comment by rockfordlhotka** [comment]
I merged this into the updated master branch (working toward targeting .NET 4.6, etc.) so you can ignore Silverlight and WinPRT (those projects are now gone).

**Comment by mbernard** [comment]
good to know, thank for the update

**Comment by rockfordlhotka** [comment]
btw, this does all build without warnings now (with Silverlight and WinPRT gone). You should test the changes on the CSLA 4.6 build, but I'm going to close this issue now because the changes are in and building.

**Comment by mbernard** [comment]
That's great news. I wrote a couple unit tests for this specific bug. I'll make sure they still pass on the 4.6 branch
