### ISSUE TITLE
MobileList<T> Requires Assembly Version of T on Client (WPF) to Equal Server (MVC)

### ISSUE THREAD

**Issue by crazyfox55** [MarimerLLC/csla#3021]
**Describe the bug**
When deserializing a ```MobileList<T>``` on the server if the type T has an assembly version later than that of the type on the server then it will fail. When deserializing a ```MobileList<T>``` on the client if the type T has an assembly version later than that of the type on the client then it will fail. This asymmetric requirement actually enforces that the assembly version of the client must equal that of the server.

This is my "biased" proposed solution:
https://github.com/crazyfox55/csla/pull/1

**Version and Platform**
CSLA version: 5.5.200
OS: Windows
Platform: WPF, MVC

**Code that Fails**
I don't have a repo with failing code but if needed I can write one up.

**Stack Trace or Exception Detail**
Its of the form below but this is not the exact text (obviously):
```"MobileList`1[[Type.T, version="4.5.6.7", keyToken=""]], csla=5.5.2 cant deserialize, make sure the type has the same name on the client as on the server"```

**Additional context**
We have a desktop application that will update itself however to do that it needs to talk to the server first. The desktop app is consistently one or two assembly versions behind the server. However the types that are used to update the client rarely change so they should serialize and deserialize without issues.

**Comment by crazyfox55** [comment]
I believe this is a bug because the behavior of SerializationInfo.AddValue(T) will have no issues about assembly version, but SerializationInfo.AddValue(MobileList<T>) will fail.

**Comment by rockfordlhotka** [comment]
Sadly it isn't a bug, it is a limitation.

If T is a child type you'll find the same result. It T is a system type we can resolve the type from dotnet itself without issue.

The solution is to version your data portal endpoint so that you can have two versions exposed until you upgrade all clients. This is a common thing in the mobile world, and as you note, can happen in desktop apps too.

**Comment by crazyfox55** [comment]
We actually don't use SerializationInfo.AddChild() anywhere in our code. Should we only be using AddValue() on system types?

Is the code below correct?
```
public AvailableMigrationPackageInfo Test { get; set; }

protected override void OnGetChildren(SerializationInfo info, MobileFormatter formatter)
{
	var si = formatter.SerializeObject(Test);
	info.AddChild(nameof(Test), si.ReferenceId);

	base.OnGetChildren(info, formatter);
}

protected override void OnSetChildren(Csla.Serialization.Mobile.SerializationInfo info, Csla.Serialization.Mobile.MobileFormatter formatter)
{
	if (info.Children.TryGetValue(nameof(Test), out var test))
	{
		Test = (AvailableMigrationPackageInfo)formatter.GetObject(test.ReferenceId);
	}

	base.OnSetChildren(info, formatter);
}
```
instead of 
```
protected override void OnGetState(Csla.Serialization.Mobile.SerializationInfo info, StateMode mode)
{
	info.AddValue(nameof(Test), Test);

	base.OnGetState(info, mode);
}

protected override void OnSetState(Csla.Serialization.Mobile.SerializationInfo info, StateMode mode)
{
	Test = info.GetValue<AvailableMigrationPackageInfo>(nameof(Test));

	base.OnSetState(info, mode);
}
```

**Comment by crazyfox55** [comment]
I agree, there are fundamental versioning decisions that need to be made when a type's properties aren't matching up. I can see that the assembly version is also important even if the type's properties match. Also assembly version doesn't auto increment so it is not a foolproof method.

I do want to point out that if scenario 2 happens on the client than scenario 3 will happen on the server, and vice versa. So my inclination would be that they both should throw exceptions. I think fundamentally this should be configurable.

In your example value B would get a default value in scenario 2 and dropped in scenario 3. This is where we could be creative in allowing configuration. Adding configuration for scenario 3 is tricky because the code would have to be too general. JSON solves this with a bucket aka the link below:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-handle-overflow?pivots=dotnet-6-0

What do you think of adding something like this to the ```MobileFormatter```?

**Comment by rockfordlhotka** [comment]
JSON has a much easier job that we do, because JSON isn't a full fidelity serializer. The output from deserializing a JSON stream is not guaranteed to be identical to the source object graph. Their job is easier in some ways.

We could have an option in `MobileFormatter` to do for _your_ types what we do for system types, which is to ignore signatures and versions - just rely on whatever assembly we can load that has a close match based on assembly and type name. This would leave dealing with mismatched fields from source/target entirely to the developer.

I'm not real keen on this, because I can see future discussion threads where people are trying to resolve really hard to find/debug issues. But I'm not 100% against it either, as long as it isn't the default configuration.

**Comment by crazyfox55** [comment]
I think the conclusion is as follows:
1. Add an option to turn on assembly/type matching somewhere in the CSLA options (default setting is off)
2. Change SerilizationInfo so it looks at the matching options
3. Change MobileList so it looks at the matching options
4. Change SerilizationInfo AddValue so it behaves like MobileList for IMobileObject types

I would like to see this change happen for CSLA 5.5 but step 4 is close to a breaking change.

**Comment by rockfordlhotka** [comment]
I'm not sure 3 is necessary. The instance creation code in `MobileFormatter` should be (I think) the only place where a change is required. I don't recall if this code is in `SerializationInfo` or `MobileFormatter` itself, as indicated by number 2.

I don't understand number 4 - if a child reference is being added, that's done in the set child code, not where values are set.

**Comment by crazyfox55** [comment]
Number 4: Apparently we are not using the SerializationInfo correctly. We add all of an object's properties using info.AddValue function regardless of if the value is a custom type or IMobileObject type or System type. 

1. Add an option to turn on assembly/type matching somewhere in the CSLA options (default setting is off)
2. Change MobileFormatter to look at the matching options

Should just be those two.
