### ISSUE TITLE
Analyzers Are Not Included in `6.0.0`

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#3025]
**Describe the bug**
Looks like the analyzers aren't being included with the latest version.

**Version and Platform**
CSLA version: 6.0.0
OS: Windows
Platform: Class Library

**Code that Fails**
I have a project that I use in a talk I do on analyzers. It was referencing `5.5.2`, so I updated it to `6.0.0` this morning. When I did this, none of the analyzers that I expected to fire showed up. For example, this code:

```csharp
public sealed class Customer
  : BusinessBase<Customer>
```

should show `CSLA0001` as it's not serializable.

**Comment by rockfordlhotka** [comment]
I think it is related to this issue:

https://github.com/dotnet/roslyn-analyzers/issues/5890
