### ISSUE TITLE
Binding Flags Declared Only Should Only Appear Once

### ISSUE THREAD

**Issue by crazyfox55** [MarimerLLC/csla#3034]
https://github.com/MarimerLLC/csla/blob/10ca30cee59095321481bda253b80075ab0a8aa6/Source/Csla/Reflection/ServiceProviderMethodCaller.cs#L29

Remove the duplicate ```| BindingFlags.DeclaredOnly``` at the end of the line.

**Comment by rockfordlhotka** [comment]
Thank you for finding this, @crazyfox55 !

**Comment by swegele** [comment]
When daily life presents a bit of humor, we should stop and appreciate it.
I chuckled at the irony in the title of this ticket "...Only Should Only Appear Once" 
:-)
