### ISSUE TITLE
Consider adding an option for MobileFormatter to ignore version/signing on deserialization

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3036]
Although very risky and unsafe for a user, it may be possible for `MobileFormatter` to have an option to allow deserialization into a type of the same name/assembly where the version and signing information doesn't match.

The referenced discussion thread contains info about why this is risky and may lead to people having hard-to-find and hard-to-solve issues in their app.

---

Number 4: Apparently we are not using the SerializationInfo correctly. We add all of an object's properties using info.AddValue function regardless of if the value is a custom type or IMobileObject type or System type. 

1. Add an option to turn on assembly/type matching somewhere in the CSLA options (default setting is off)
2. Change MobileFormatter to look at the matching options

Should just be those two.

_Originally posted by @crazyfox55 in https://github.com/MarimerLLC/csla/issues/3021#issuecomment-1196007880_

**Comment by kant2002** [comment]
I take a quick look at this. and I think this can be done in following way
1. Add methods `DisableStrongNamesCheck`/`EnableStrongNamesCheck`  here which enable/disable some configuration https://github.com/MarimerLLC/csla/blob/dde8da260c6df56063e0e0e0a1d560c71cf41e8d/Source/Csla/Configuration/Fluent/SerializationOptions.cs#L24-L28
2. Create property inside `ApplicationContext` which will be used for storing this configuration
3. During creation SerializationFormatter if it is MobileFormatter or derivative read this property and pass it to MobileFormatter. https://github.com/MarimerLLC/csla/blob/dde8da260c6df56063e0e0e0a1d560c71cf41e8d/Source/Csla/Serialization/SerializationFormatterFactory.cs#L20-L23
4. I would like to add some tests for this configuration in the SerializationTests, but I think I need to create couple simple test assemblies with same name, but different versions to check that real types are deserialized and do not play with mocks too much.

**Comment by rockfordlhotka** [comment]
I think you are correct. 

However, PR #4024 will change the implementation, because there will be a `MobileFormatterOptions` class where options specific to MobileFormatter are set and maintained. This will help enable other future formatters that people might create, and also provides a clear place for MF options.

Hopefully #4024 will be complete within the next day or two.
