### ISSUE TITLE
Use new Xamarin DataAnnotations implementation

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#306]
The latest version of Xamarin (at least Xamarin.Forms) appears to include a System.ComponentModel.DataAnnotations implementation. We'll need to change CSLA so it uses this implementation rather than the one built into CSLA.

**Comment by rockfordlhotka** [comment]
@tdyocum any chance you'll get to this in the next couple weeks?

**Comment by tdyocum** [comment]
Yes, I can get to this asap.  I had been putting together a sample app in Xamarin that I can use to begin testing changes.  I have that together now and can begin contributing on this one.  Is this needed as part of the bigger effort to support Apple's February deadline for conversion to the unified model?  Also, I did look on the Xamarin.Forms object model for the DataAnnotation implementation but didn't find it.  Do you know where it is in the model?
