### ISSUE TITLE
HttpProxy should not store HttpClient in a static field

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3148]
Oh crickey! Yeah, @saulyt, I think you've hit the nail on the head. I agree that the HttpClient being stored in a static variable is very odd. Well done, I think that might explain some of the problems we are seeing.

It's been a static variable for a very long time, but we are only now seeing it cause a problem. I think that is because we have changed the way things get disposed. If I recall, we did that as part of adding handling for the newish async disposal that has been added to .NET.

_Originally posted by @TheCakeMonster in https://github.com/MarimerLLC/csla/discussions/3128#discussioncomment-3936236_

**Comment by kcabral817** [comment]
I've been watching this thread via email.  You guys did an excellent job at tracking down this bug.   Awesome job guys.
