### ISSUE TITLE
Csla.Data.SqlClient Nuget Package Issue - 6.0.0 and Greater

### ISSUE THREAD

**Issue by bboney** [MarimerLLC/csla#3173]
The Csla.Data.SqlClient nuget package installs both Csla.Data.SqlClient.dll and Csla.Data.SqlClient.Fx.dll assemblies.  
This causes an issue in Visual Studio with referencing 2 identical versions of the SafeSqlDataReader in both assemblies.  Error CS0433.
Removing the Csla.Data.SqlClient.Fx.* files from my local Nuget folders resolved this issue after uninstalling/reinstalling the nuget package.

The installed .nuspec file also references
<dependency id="Microsoft.Data.SqlClient" version="4.1.0" />
instead of
<dependency id="Microsoft.Data.SqlClient" version="5.0.1" />

Correcting the csla.data.sqlclient.nuspec file on my local Nuget and uninstalling/reinstalling the package resolves that issue too.

**Version and Platform**
CSLA version: 6.0.0 and higher
OS: Windows
Platform: Class Library - .NET 6.0 AND NETSTANDARD 2.0

**Stack Trace or Exception Detail**
Visual Studio Error:
Error	CS0433	The type 'SafeSqlDataReader' exists in both 'Csla.Data.SqlClient.Fx, Version=6.2.2.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' and 'Csla.Data.SqlClient, Version=6.2.2.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30'	

**Additional context**
I have looked at the Csla repo for causes, but I cannot find the issue of installing both dll's.  However, the current nuspec file does reference "Microsoft.Data.SqlClient" version="4.1.0" in the repo.

**Comment by rockfordlhotka** [comment]
Ouch! Thank you for identifying this @bboney !!
