### ISSUE TITLE
Support parameter conversion in RuleContext.AddOutputValue

### ISSUE THREAD

**Issue by EricNgo1972** [MarimerLLC/csla#3251]
Currently, AddOutputValue in RuleContext does not support parameter conversion like SetPropertyConvert<F,P>.

`
    public void AddOutValue(Csla.Core.IPropertyInfo property, object value)
    {
      _outputPropertyValues.Value[property] = value;
    }
`

May be adding support for parameter conversion make it easier to use, especially  when the managed field is smart types (SmartDate)?

`
 public void AddOutValue(Csla.Core.IPropertyInfo property, object value)
            {
                if(value is not null)                
                    _outputPropertyValues.Value[property] = Csla.Utilities.CoerceValue(PrimaryProperty.Type, value.GetType(), null, value);                
                else
                    _outputPropertyValues.Value[property] = PrimaryProperty.DefaultValue;
            }
`

**Comment by rockfordlhotka** [comment]
That seems like a nice enhancement, thanks for the suggestion.
