### ISSUE TITLE
Issue with EditLevelAdded when undoing an edit in a cloned editablecollection with MobileFormatter

### ISSUE THREAD

**Issue by amselem** [MarimerLLC/csla#3291]
**Describe the bug**

1) I fetch an editable collection which already have some items in the collection
2) An edit is started in the collection: MyCollection.BeginEdit
3) Then the collection is cloned (I discard the original BO):  MyCollection=MyCollection.Clone
4) The cloned collection is then modified adding some items: MyCollection.AddNew()
5) Undo the changes:  MyCollection.CancelEdit.

The expected result is that MyCollection has restored the original items fetched in 1), but the actual result is that the collection is empty.

**Version and Platform**
CSLA version: 5.5.3
OS: Windows
Platform: WinForms

**Code that Fails**

Sample code:
[csla_undo_tests.zip](https://github.com/MarimerLLC/csla/files/11266940/csla_undo_tests.zip)

**Additional context**

- If we repeat these steps but using BinaryFormatter, the collection is restored as expected

- Is we repeat these steps but skipping 3), i.e.: using the same collection instead of cloning it, the collection is restored as expected.

I tracked the issue to an internal variable named EditLevelAdded which is not preserved after cloning the Collection. I think that's because EditLevelAdded is not a managed property but a classic one, so BinaryFormatter preserves this value but MobileFormatter does not. As the EditLevelAdded is not preserved all the items in the cloned collection are added as "new" items and discarded when calling CancelEdit.

**Comment by rockfordlhotka** [comment]
Thank you, this is very clear, I appreciate the well written issue!

The EditLevelAdded doesn't need to be a managed property (probably). Instead, the value should be put/retrieved from the serialization stream in the `IMobileObject` implementation. That's the way most of these internal/private fields are managed within the framework.

**Comment by amselem** [comment]
I found a workaround, it looks like that EditLevelAdded is correctly de/serialized when using MobileFormatter, but it gets messed up when adding the cloned children to the collection (I don't know why)

My workaround is to detect if we're cloning and in that case, after adding a child to a collection restore its EditLevelAdded value previous to the collection insert

```
    private const string cloningKey = "BusinessList_IsCloning";

    protected override object GetClone()
    {
      try
      {
        if (!Csla.ApplicationContext.ClientContext.Contains(cloningKey))
          Csla.ApplicationContext.ClientContext.Add(cloningKey, true);
        return base.GetClone();
      }
      finally
      {
        if (Csla.ApplicationContext.ClientContext.Contains(cloningKey))
          Csla.ApplicationContext.ClientContext.Remove(cloningKey);
      }
    }

    protected override void InsertItem(int index, PersonEdit item)
    {
      var ieditable = (Csla.Core.IEditableBusinessObject) item;
      if (ieditable != null &&
              Csla.ApplicationContext.ClientContext.Contains(cloningKey))
      {
        var ela = ieditable.EditLevelAdded;
        base.InsertItem(index, item);
        ieditable.EditLevelAdded = ela;
      }
      else
        base.InsertItem(index, item);
    }

```
