### ISSUE TITLE
Logical Execution Location can get stuck on Server for IOS and Android

### ISSUE THREAD

**Issue by JasonHardman** [MarimerLLC/csla#331]
If multiple calls to the local data portal occur at the same time Csla.ApplicationContext.LogicalExecutionLocation can get stuck on Server.  This occurs if the second data portal call starts before the first data portal has completed.  Subsequent data portal calls are then made on the main thread instead of a background thread.  This problem only occurs for IOS and Android.  .NET is ok since it uses an ApplicationContextManager that is thread aware.  Silverlight, Windows Phone and WINRT might also have this issue.

**Comment by rockfordlhotka** [comment]
The real solution to this is to implement #29

**Comment by rockfordlhotka** [comment]
I see what you did. So does iOS have thread local context? I wouldn't have expected that, but that's very nice!

**Comment by JasonHardman** [comment]
Yes, IOS is now mostly mono which is based on .NET45 (I think).  It was previously based on Silverlight but this changed about a year ago I think.  It has a lot more API than Silverlight :).  
I think #29 would definitely help solve this bug for Silverlight, Windows Phone and WinRT where I think it still exists.  My original solution was to add the thread ID to the __logicalExecutionLocation key which should solve it for all platforms.  However other areas would probably need to be addressed to make it thread aware and thread safe.  Then I realised than the bug did not occur for Windows Forms apps and discovered it was using a different ApplicationContextManager which also happened to work for IOS and Android.
