### ISSUE TITLE
Csla.ApplicationContext.User doesn't work in Blazor wasm

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3318]
After updating to CSLA 7 and .NET 7 the `ApplicationContext.User` property no longer returns the correct user identity within a Blazor wasm client app.

This can be found in the `BlazorExample` sample app in the `Login` page. The `AuthResult.Result.User` returns the correct user, and the Blazor authorization features see the correct user, but `ApplicationContext.User` does not return the correct value.

**Comment by joshhanson314** [comment]
I may have seen this in Blazor Server when I attempted to upgrade my projects to .NET 7 with using CSLA 6. I can check again tomorrow. Obviously it could have been any large number of things, but still, probably worth a double check.

**Comment by rockfordlhotka** [comment]
I'm now thinking it is an issue with the current identity not flowing through the data portal to the app server.

I did find and fix an edge case where `ApplicationContext.User` wasn't cached immediately from the `AuthenticationStateProvider` in Blazor wasm, but that didn't actually fix the bug I'm seeing - so I guess it is either an enhancement or a fix for a not-yet-discovered bug? 🙂

Now to debug the data portal and/or serialization issue.

**Comment by rockfordlhotka** [comment]
LOL! This wasn't really a bug in the framework, but rather in the BlazorExample project. 

@TheCakeMonster added the need to call `EnableSecurityPrincipalFlowFromClient` on client and server if you want the user identity to flow through the data portal. A very wise and good enhancement - and breaking change - that I totally forgot about until now when the sample app failed.
