### ISSUE TITLE
ReigsterProperty reuses default value

### ISSUE THREAD

**Issue by dvansteenburg** [MarimerLLC/csla#339]
When using a Csla read-only business class, I have a problem when I use a default value in the RegisterProperty.  Below is the "cleaned-up" code which should show the issue...

using Csla;
using System;
using System.Collections.Generic;

namespace MyApp
{
	[Serializable]
	public class Basis : ReadOnlyBase<Basis>
	{
		public Basis()
			: base()
		{
		}

        public Basis(IRepository repository) : base()
        {
            _Repository = repository;
        }

		public static readonly PropertyInfo<int> IDProperty = RegisterProperty<int>(c => c.ID);
		public int ID
		{
			get
			{
				return GetProperty(IDProperty);
			}
			private set
			{
				LoadProperty(IDProperty, value);
			}
		}

		public static readonly PropertyInfo<IList<IField>> FieldsProperty = RegisterProperty<IList<IField>>(c => c.Fields, "My Fields", new List<IField>());

		public IList<IField> Fields
		{
			get
			{
				return GetProperty(FieldsProperty);
			}
			private set
			{
				LoadProperty(FieldsProperty, value);
			}
		}

		#endregion

		#region Repository

		[NonSerialized]
		private IRepository _Repository;

		[Dependency]
		internal IRepository Repository
		{
			get { return _Repository; }
			set { _Repository = value; }
		}

		#endregion

		#region IFactory Members

		/// <summary>
		/// Get an instance for the given ID
		/// </summary>
		/// <param name="ID"></param>
		/// <returns>Instance for the given ID</returns>
		static public Basis GetBasis(int BasisID)
		{

			var crit = new BasisCriteria(BasisID);

			//Fetch rate from DataPortal
			var result = Csla.DataPortal.Fetch<Basis>(crit);

			return result;
		}

		#endregion

		#region CSLA DataPortal Create/Fetch methods for retrieving data out of the repository

		/// <summary>
		/// Server-side DataPortal Fetch populating from the database using the criteria specified
		/// </summary>
		/// <param name="crit"></param>
		private void DataPortal_Fetch(BasisCriteria crit)
		{
			var entity = Repository.GetBasis(crit.BasisID);

			this.ID = entity.BasisID;

			foreach (FieldEntity entField in entity.Fields)
			{
				this.Fields.Add(new Field(entField));
			}
		}

		#endregion
	}
}

When I then make the following calls...
   var firstCall = Basis.GetBasis(1);   // This returns a class which has 2 Fields entries
   var secndCall = Basis.GetBasis(99);   // This return a class which has 0 Field entries

The expected results are firstCall.Fields.Count == 2 and secndCall.Fields.Count == 0.

What I get is firstCall.Fields.Count == 2 and secndCall.Fields.Count == 2.

When I review the entries in secndCall.Fields, they are the same as in firstCall.Fields.  I had expected that each new instance of the class would have gotten its own empty List<IField> created.

I worked around this issue by not using the RegisterProperty default value option, and initialized the Fields list in the DataPortal_Fetch (this.Fields = new List<IField>()) before adding the values.

**Comment by dvansteenburg** [comment]
Here is a simplier example which exercises this same issue with the RegisterProperty, with a default value set...

using Csla;
using System;
using System.Collections.Generic;

namespace PropertyInfoIssue
{
         class Program
         {
                 static void Main(string[] args)
                 {
                          var testItemOne = TestItem.CreateTestItem();
                          testItemOne.MyList.Add(Guid.NewGuid());

                          OutputList(testItemOne);

 
                          Console.WriteLine("---------------------------");

 
                          var testItemTwo = TestItem.CreateTestItem();
                          testItemTwo.MyList.Add(Guid.NewGuid());
                          OutputList(testItemTwo);

 
                          Console.ReadLine();

                 }

                 private static void OutputList(TestItem testItem)
                 {
                          for (var i = 0; i < testItem.MyList.Count; i++)
                          {
                                   Console.WriteLine(testItem.MyList[i]);
                          }
                 }
         }

         [Serializable]
         public class TestItem : BusinessBase<TestItem>
         {
                  public static readonly PropertyInfo<List<Guid>> MyListProperty = RegisterProperty<List<Guid>>(c => c.MyList, "My List", new List<Guid>());
                 public List<Guid> MyList
                 {
                          get { return GetProperty(MyListProperty); }
                          set { SetProperty(MyListProperty, value); }
                 }

                 public static TestItem CreateTestItem()
                 {
                          return DataPortal.Create<TestItem>();
                 }
         }
}

**Comment by jonnybee** [comment]
Hi,

This is actually by design and described in the **Using CSLA 4 Creating Business Objects** ebook

*"The DefaultValue property should only be used for value types or immutable reference types such as the string type. The DefaultValue property is set when the RegisterProperty method is called, and that occurs exactly one time per AppDomain. This means the default value is shared across all instances of the business class."*
