### ISSUE TITLE
AddObjectAuthorizationRules is Not Invoked If Requested Type is Different Than Type Used in CreateInstace from IDataPortalActivator

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#340]
If I pass in a type to a DataPortal method where that type is not the one that will be used in the DP lifecycle, and the resolved type has the AddObjectAuthorizationRules method defined, it won't be called.

For example, let's say I have a BO called Person that implements IPerson. Person has the AddObjectAuthorizationRules() method defined. I also define my own implementation of IDataPortalActivator that, when CreateInstance() is called passing in a IPerson type, an instance of Person is returned. The problem is in AuthorizationRuleManager.InitializePerTypeRules(), the value of the type argument appears to be IPerson and not Person, so it won't find the AddObjectAuthorizationRules() and therefore won't call it.

One possible way to fix this may be that IDataPortalActivator adds a ResolveType() method with a Type argument that specifies the requested BO type, and returns a type (DataPortalActivator would default to returning the given type). Then CSLA could use ResolveType() to determine what type will really be used throughout the lifecycle of the DP operation.

**Comment by jjt212** [comment]
Hello, I would like to add that I am experiencing this issue as well, and was wondering if anyone knows of a workaround? Maybe triggering something within my custom IDataPortalActivator implementation?

Alternatively, is a proper CSLA fix on the roadmap? Thanks!

**Comment by rockfordlhotka** [comment]
**This is a breaking change for anyone who implements a custom `IDataPortalActivator`**

In that case you will need to add a new `ResolveType` method to your class that does the same mapping you currently do in your `CreateInstance` method. In fact, odds are good that your `CreateInstance` method can use the new `ResolveType` method to do all type resolution. For example:

```c#
  public class PerTypeAuthDPActivator : Server.IDataPortalActivator
  {
    public object CreateInstance(Type requestedType)
    {
      return Activator.CreateInstance(ResolveType(requestedType));
    }

    public void FinalizeInstance(object obj)
    {
    }

    public void InitializeInstance(object obj)
    {
    }

    public Type ResolveType(Type requestedType)
    {
      if (requestedType.Equals(typeof(IPerTypeAuthRoot)))
        return typeof(PerTypeAuthRoot);
      else
        return requestedType;
    }
  }
```
