### ISSUE TITLE
CSLA 7.0 and NetFrameWork 4.8 WebForms

### ISSUE THREAD

**Issue by Art666OTS** [MarimerLLC/csla#3409]
I have an old Web forms application that must be move to new hardware that does not support 3.5.1.

I have already converted two API to to NetCore6 and Csla 7.0.

I want to use the same business library for these API's in the web forms application.

I have updated the Frame Work to 4.8 and changed the code that references business object to the new style.
eg. ArticleEdit a1 = _dataPortalFactory.GetPortal<ArticleEdit>().Create();

This now compiles happily. However when I try to execute the code I get error messages

I assume this has something to do with the way the DI is established. For the API I do the following

            services.AddCsla();
            services.AddTransient<IDataPortalFactory, DataPortalFactory>();
            services.AddTransient<IArticle, ArticleDAL>();

I will also need to do something like this for the web forms. In looking this up I can see references to using Unity.

Do I need to use Unity? I recently saw an article (article may not be recent) quoting Rockford saying you do not have to use Unity.

Can anyone share an example of how DI is established in web forms with or without Unity.

**Comment by rockfordlhotka** [comment]
I haven't tried this in WebForms, but in other netfx48 (.NET Framework 4.8) UI scenarios you can reference the `Microsoft.Abstractions.DependencyInjection` NuGet package, and then you can initialize the standard .NET DI container to get the `services` field that you need.

Simple initialization of DI is covered in the [Upgrading to CSLA 6](https://github.com/MarimerLLC/csla/blob/main/docs/Upgrading%20to%20CSLA%206.md) document, though I suspect you'll actually want to use a web builder to create the services collection to fit into aspnet better.

**Comment by Art666OTS** [comment]
Rockford,

Thanks for pointing me in the right direction. I didn't get as elegant a solution as I would have liked but it is working so I can progress from here. 

I could not get the DI to work with the web forms. The page life cycle events did not appear to allow me to use Constructor injection so I came up with an alternative.

What I did was add public static properties to the Global class.

   public class Global : HttpApplication
    {

        public static ApplicationContext ApplicationContext { get; private set; }
        public static IDataPortalFactory DataPortalFactory { get; private set; }
        void Application_Start(object sender, EventArgs e)
        {
            // Code that runs on application startup
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
            var services = new ServiceCollection();
            services.AddCsla();
            services.AddTransient<IDataPortalFactory, DataPortalFactory>();
            services.AddTransient<IArticle, ArticleDAL>();
            services.AddTransient<IArticleList, ArticleListDAL>();
            services.AddTransient<ICategory, CategoryDAL>();
            services.AddTransient<ICategoryList, CategoryListDAL>();

            services.AddTransient<IDataBase, DataBase>();
            services.AddTransient<IBLSQL6Functions, BLSQL6Functions>();

            var provider = services.BuildServiceProvider();
            ApplicationContext = provider.GetService<ApplicationContext>();
            DataPortalFactory = provider.GetRequiredService<IDataPortalFactory>();
        }

and then for each web form in the code behind I added this.

       public IDataPortalFactory _dataPortalFactory { private get; set; }

        protected void Page_PreInit(object sender, EventArgs e)
        {
            _dataPortalFactory = web1.Global.DataPortalFactory;
        }

this allowed me then to use the IDataPortalFactory  on the web form like

ArticleEdit a1 = _dataPortalFactory.GetPortal<ArticleEdit>().Create();

Now I can do the changes the the web application to make the upgrade to CSLA V7.0 and then I can start my last project before I retire to convert the web application to a Blazor Server app/s.
