### ISSUE TITLE
Request for uk-UA compiler warning fix to be backported to v5.X

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/csla#3449]
Hi,

I'm wondering if it would be possible to backport the uk-UA casing issue to CSLA version 5 (5.4.2 is what we're using). I'm testing the transition to .NET 7 using that CSLA version and it APPEARS to do everything properly, but that particular compiler warning is somewhat annoying and I've tried suppressing it in the csproj file, but it has no effect.

https://github.com/MarimerLLC/csla/issues/3136

Thanks,
Jason

**Comment by rockfordlhotka** [comment]
If you submit a PR against the v5.x branch I will (try to) create a release.

(I say "try to" because I'm finding it harder and harder to build older versions of the framework as time goes on)

**Comment by GreatBarrier86** [comment]
We can actually skip this now. At the time, we had no plans to move to CSLA 7 but with the recent changes to use NET 7, it was a logical choice to go to CSLA 7
