### ISSUE TITLE
LocalProxy, HttpClient are kept alive in the root container (ServiceProvider), which causes a Memory Leak.

### ISSUE THREAD

**Issue by TanguyIngels** [MarimerLLC/csla#3491]
**Describe the bug**
When working as Local => Objects like LocalProxy are kept in the root containter, and never gets disposed.
When working as Remote => Objects like HTTPClient are kept in the root container, and never gets disposed.

**Version and Platform**
CSLA version: 6+
OS: Windows
Platform: WinForms, Blazor

**Comment by rockfordlhotka** [comment]
Also RabbitMqProxy needs to not implement `IDisposable`.
