### ISSUE TITLE
Serialization of type object is not supported while using property as complex type in Business model.

### ISSUE THREAD

**Issue by Hvishal88** [MarimerLLC/csla#3543]
Getting an error "Serialization of type object is not supported" while using property type as non-primitive datatype (e.g. Class).

Any solution to get this serialized or ignored during DAL operations.
    // POST: Person/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, PersonEdit person)
    {
      try
      {
        **person.ComplexClassProp = new ComplexClass() { FirstName = "Vishal" };**
        LoadProperty(person, PersonEdit.IdProperty, id);
       
        if (await SaveObjectAsync<PersonEdit>(person, true))
          return RedirectToAction(nameof(Index));
        else
          return View(person);
      }
      catch
      {
        return View(person);
      }
    }
-------------------------------------------------------------

 public class ComplexClass
  {
    public string FirstName { get; set; }
    public string LastName { get; set; }
  }
  [Serializable]
  public class PersonEdit : BusinessBase<PersonEdit>
  {

    public static readonly PropertyInfo<ComplexClass> ComplexClassPropProperty = RegisterProperty<ComplexClass>(nameof(ComplexClassProp));
    

    public ComplexClass ComplexClassProp
    {
      get { return GetProperty(ComplexClassPropProperty); }
      set { SetProperty(ComplexClassPropProperty, value); }
    }

.
.
.
.
.
Find the attached sample code for the issue reference. 
[MvcExample.zip](https://github.com/MarimerLLC/csla/files/13297132/MvcExample.zip)

**Comment by hurcane** [comment]
I think you need to add the Serialiazble attribute to ComplexClass.
