### ISSUE TITLE
.NET 8.0: Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#3583]
Out of interest, I switched a project over to .NET 8.0 and updated all NuGet packages, but still using CSLA 7.0.2. Nothing that requires an `IDataPortal<T>` seems to work anymore in Blazor. I checked [CSLA Version 8.0.0](https://github.com/orgs/MarimerLLC/projects/9/views/1) but it wasn't obvious if this was being tracked.

`Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component. Typically, this means you can call it only within a Razor component or inside another DI service that is resolved for a Razor component.`

The following is inside a razor component, using the appropriate Task<AuthenticationState>:

```cs
[CascadingParameter] protected Task<AuthenticationState> AuthenticationStateTask { get; set; }

protected async override Task OnInitializedAsync()
{
    var authState = await AuthenticationStateTask;

    ...

    var result    = await WidgetListFactory.GetAsync(); // This uses IDataPortal<WidgetList> and throws

    _ = base.OnInitializedAsync();
}
```

**Comment by rockfordlhotka** [comment]
It is being worked on, in that I'm still trying to figure out state management in dotnet 8.

CSLA 8 will support the new Blazor 8 render modes, I just don't yet know how.

The old render modes still work in Blazor 8.

**Comment by kcabral817** [comment]
If the database call is in the OnInitialized method, the database is hit every time the page loads.  I use :  protected override async Task OnAfterRenderAsync(bool firstRender)
 {
     if (firstRender)
     {
           ....csla.fetch()
     }
 }
 then, as I understand it, the prerendering is done but the access to resources is delayed.

**Comment by kcabral817** [comment]
I don't think that code up top will work.  The cascading parameter is passing a concrete object, and this would be a problem with the .net 8 release.  The only way to pass in AuthenticationState would be through an interface in the default constructor as a parameter as the [inject] will not work in this case.  Is that a possible solution or am I in way off the reservation?

**Comment by rockfordlhotka** [comment]
There's a built-in way to pass authentication state through a new Blazor 8 cascading type.

I'm at lunch in Prague, so don't have my computer to look it up.

**Comment by kcabral817** [comment]
Rocky,

I'm in Germany, Frankfurt.  If you need a place to crash, give me a call.

Have a nice day.

Kevin

https://rb.gy/syiuf


________________________________

**Comment by rockfordlhotka** [comment]
Part of #3308

**Comment by michaelcsikos** [comment]
Hmm, Microsoft says:

### Stateful reconnection after prerendering

When prerendering on the server, a component is initially rendered statically as part of the page. Once the browser establishes a SignalR connection back to the server, the component is rendered again and interactive. If the [OnInitialized{Async}](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#component-initialization-oninitializedasync) lifecycle method for initializing the component is present, the method is executed _twice_:

- When the component is prerendered statically.
- After the server connection has been established.

This can result in a noticeable change in the data displayed in the UI when the component is finally rendered. **To avoid this behavior, pass in an identifier to cache the state during prerendering and to retrieve the state after prerendering.**

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#stateful-reconnection-after-prerendering

**Comment by rockfordlhotka** [comment]
That technique may be problematic with CSLA, as the object graph would be hydrated on the server for pre-rendering, and then it is _required_ in interactive mode for data binding, etc.

Especially when you think of wasm interactive, the state needs to flow to the wasm client - though the solution is presumably the same either way - the "cache" they refer to, I assume, is like a hidden field on the page with the serialized object graph? Or maybe throw the serialized object graph into a REDIS cache and retrieve it?

Or use a variation on what I am trying to do in the Blazor8State solution.

It may be simpler, with CSLA, to just say that we only support non-pre-rendered modes.

`@attribute [RenderModeInteractiveAuto(prerender:false)]`

**Comment by michaelcsikos** [comment]
Microsoft used an `IMemoryCache` in their example:
```cs
using Microsoft.Extensions.Caching.Memory;

public class WeatherForecastService
{
    private static readonly string[] summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild",
        "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    public WeatherForecastService(IMemoryCache memoryCache)
    {
        MemoryCache = memoryCache;
    }

    public IMemoryCache MemoryCache { get; }

    public Task<WeatherForecast[]?> GetForecastAsync(DateTime startDate)
    {
        return MemoryCache.GetOrCreateAsync(startDate, async e =>
        {
            e.SetOptions(new MemoryCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow =
                    TimeSpan.FromSeconds(30)
            });

            var rng = new Random();

            await Task.Delay(TimeSpan.FromSeconds(10));

            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = startDate.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = summaries[rng.Next(summaries.Length)]
            }).ToArray();
        });
    }
}
```

**Comment by kcabral817** [comment]
I'm not clear on how using the Imemory cache addresses teh GetAuthentictationStateAsync issue?

Have a nice day.

Kevin

https://rb.gy/syiuf


________________________________

**Comment by michaelcsikos** [comment]
@kcabral817 It doesn't, it's just Microsoft's solution to not load things twice in `OnInitialized{Async}`.

**Comment by kcabral817** [comment]
Thank you.  I wasn't following that portion of the discussion.   Now that makes sense on why the reference.

Have a nice day.

Kevin

https://rb.gy/syiuf


________________________________

**Comment by rockfordlhotka** [comment]
For the authn part of this conversation, here are the docs:

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.cascadingauthenticationstateservicecollectionextensions.addcascadingauthenticationstate?view=aspnetcore-8.0

**Comment by rockfordlhotka** [comment]
I now have a #dotnet #blazor app that is able to maintain per-user state across server-rendered, server-interactive, and wasm-interactive pages in a single app. It still needs some refinement, but at least the concept is proven to work!

Blog post is the next thing on the agenda.

https://github.com/rockfordlhotka/Blazor8State

**Comment by michaelcsikos** [comment]
Hi @rockfordlhotka, we load some things in `Program.cs` before `app.Run()`. In **Exception Settings** if we have **Common Language Runtime Exceptions** selected we can see that this exception is being thrown when we call `GetRequiredService<T>()`. The data still loads, so I'm not sure if this means anything.

Is there a better way to do a once-only load of data as the app is starting up? Or, is there a way we can skip the auth check temporarily?
