### ISSUE TITLE
Custom ISerializationFormatter Feature Request

### ISSUE THREAD

**Issue by BrettJaner** [MarimerLLC/csla#361]
This is a feature request to allow providing your own ISerializationFormatter implementation via the app.config/web.config.

forum discussion here: http://forums.lhotka.net/forums/t/12881.aspx

**Comment by rockfordlhotka** [comment]
Please make sure to review the contributor doc and send a signed agreement before issuing a pull request.

https://github.com/MarimerLLC/csla/blob/master/CONTRIBUTING.md

**Comment by BrettJaner** [comment]
Signed contributor agreement sent.
