### ISSUE TITLE
Analyzer: Simplify Property Implementations

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#363]
If a property uses Get/Set/Load/ReadProperty, that's all the property should do. Any processing code should be handled as rules outside of the property getter and/or setter. This analyzer would flag properties that violate this idiom as a warning (probably without a code fix).

**Comment by jonnybee** [comment]
Except for when you have async LazyLoaded properties. These should call LoadPropertyAsync with a lambda to do the async fetch. Rules should do async load of property values.

**Comment by JasonBock** [comment]
I think these are all the methods that come into play with this analyzer. @jonnybee @rockfordlhotka let me know if this list is incorrect.

GetProperty
GetPropertyConvert
ReadProperty
ReadPropertyConvert
LoadProperty
LoadPropertyAsync
LoadPropertyConvert
LoadPropertyMarkDirty
ReadProperty
ReadPropertyConvert

**Comment by jonnybee** [comment]
Seems correct to me.

**Comment by rockfordlhotka** [comment]
The analyzer helped me find this code in ProjectTracker

```c#
    public static readonly PropertyInfo<ProjectResources> ResourcesProperty = 
      RegisterProperty<ProjectResources>(p => p.Resources);
    public ProjectResources Resources
    {
      get
      {
        if (!(FieldManager.FieldExists(ResourcesProperty)))
          LoadProperty(ResourcesProperty, DataPortal.CreateChild<ProjectResources>());
        return GetProperty(ResourcesProperty);
      }
      private set { LoadProperty(ResourcesProperty, value); }
    }
```
Lazy loading of a property value.

The analyzer needs to accommodate lazy loading of a property - or we need to devise another helper `GetXZY` method that simplifies how this is done and then the analyzer can look for that method.

**Comment by JasonBock** [comment]
My initial reaction would be to add a GetLazyProperty, which would do this for the developer. But there may be scenarios where not everyone wants to do this. 

Would a SetLazyProperty be needed as well? And Async versions of them as well? And Convert versions as well? :)

**Comment by JasonBock** [comment]
Also, would you need GetLazyCreateProperty, which would use DataPortal.CreateChild(), and GetLazyFetchProperty, which would use DataPortal.FetchChild()? And then allowing criteria to be passed in as well?

This could get out of hand! :)

**Comment by rockfordlhotka** [comment]
I have started playing with the `LazyGetProperty` concept. I don't know that this works entirely, but my current attempt allows the user to specify the code that generates (sync or async) the value to be loaded, so as to not have to do _too_ much work :smile: 

```c#
    protected X LazyGetProperty<X>(PropertyInfo<X> property, Func<X> valueGenerator)
    {
      if (!(FieldManager.FieldExists(property)))
      {
        var result = valueGenerator();
        LoadProperty(property, result);
      }
      return GetProperty<X>(property);
    }

    protected X LazyGetPropertyAsync<X>(PropertyInfo<X> property, Task<X> factory)
    {
      if (!(FieldManager.FieldExists(property)))
        LoadPropertyAsync(property, factory);
      return GetProperty<X>(property);
    }
```
The caller (getter) then does this:
```c#
      get { return LazyGetPropertyAsync(AssignmentsProperty, DataPortal.CreateAsync<ResourceAssignments>()); }
```
I don't think there's any 'lazy setter' concept - it is the triggering of a lazy load on get that is the requirement.

**Comment by rockfordlhotka** [comment]
@JasonBock: you should be able to have the analyzer now check for `LazyGetProperty` and `LazyGetPropertyAsync` as they are now also valid in a getter.

**Comment by rockfordlhotka** [comment]
I've added `LazyReadProperty` and `LazyReadPropertyAsync` methods now - in `BusinessBase` and `ReadOnlyBase` as well as the `IManageProperties` interface.
