### ISSUE TITLE
Analyzer: Capture Result of Save() to Variable

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#364]
Most of the time, when Save() is called on a business object, the intent is to do this:

obj = obj.Save();

However, it's easy to forget to do this, and it can lead to weird, unexpected states in the BO.

This analyzer would flag this as a warning, potentially with a code fix to add the assignment.

(Note: this may be a little more difficult if the result is set to a property or field, as that may be a valid intent by the developer, so need to ensure this case isn't flagged as an issue. I personally don't know of any time where I assigned the result of Save() this way, but it's possible.)

**Comment by JasonBock** [comment]
Jonny, I talked to Rocky about this, and we think that maybe it should be considered an error rather than just a warning if the return of `Save()` is ignored. However, we may be missing case(s) where this is valid. Do you know of any?

**Comment by jonnybee** [comment]
@JasonBock, I do not know or remember any case where I would not assign the result of save to a variable. 

Will you cover both Save and SaveAsync methods and also the overload with forceUpdate parameter?

**Comment by JasonBock** [comment]
OK, I'll make this an error :).

Forgot about SaveAsync, I'll add that too.
