### ISSUE TITLE
Support mobile/serializable collections (e.g. HashSet, SortedSet, and other classes from System.Collections.Generic)

### ISSUE THREAD

**Issue by praaline** [MarimerLLC/csla#3643]
In order to be able to use one of the collection classes offered by System.Collections.Generic in the CSLA property system, we need to ensure that MobileFormatter knows how to serialize/deserialize it. Currently CSLA offers MobileList that corresponds to a List and MobileDictionary that corresponds to a Dictionary.

See also: https://github.com/MarimerLLC/cslaforum/issues/534 

I would like to submit a pull request with code for mobile versions of HashSet, LinkedList, PriorityQueue, Queue, SortedDictionary, SortedList, SortedSet and Stack. My application is using SortedSet in business object properties, but the code was easy to write for the other types. 

That said, there is issue https://github.com/MarimerLLC/csla/issues/2531 (MobileFormatter should allow custom serializers for specific types) that could perhaps offer a cleaner solution: business object developers wouldn't have to use data structures that are specific to CSLA (MobileList, MobileSortedSet etc), but would be able to use the usual .NET data structures they're familiar with. Is any work being done on issue 2531? Can I contribute?

**Comment by rockfordlhotka** [comment]
> Is any work being done on issue 2531? Can I contribute?

No one has put work into that issue, and if you are interested in doing so that would be fantastic!

I'm happy to discuss design concepts around the issue. I just need a signed contributor agreement from you to accept any PR.

https://github.com/MarimerLLC/csla/blob/main/CONTRIBUTING.md

**Comment by rockfordlhotka** [comment]
To be resolved by #2531
