### ISSUE TITLE
Blazor ViewModel Save doesn't call begin edit after save.

### ISSUE THREAD

**Issue by russblair** [MarimerLLC/csla#3668]
**Describe the bug**
Blazor ViewModel Save doesn't call begin edit after save. We discovered this by changing an object then saving then changing again and cancelling. The result was that the cancel did not work.

**Version and Platform**
CSLA version: 7.0.3
OS: Windows
Platform: Blazor WASM

**Code that Fails**
Csla.Blazor.ViewModel.cs and Csla.Xaml.Shared.ViewModelBase.cs

**Stack Trace or Exception Detail**
EditLevel is zero after save.

**Comment by rockfordlhotka** [comment]
Related to https://github.com/MarimerLLC/csla/pull/3289
