### ISSUE TITLE
CSLA 7.0.4 release

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3672]

**Comment by rockfordlhotka** [comment]
@russblair @ProDInfo @StefanOssendorf 

I am unable to build CSLA 7 on my workstation. Well, to be clear, I can build all of it except the MAUI project - because they apparently have dropped support for the 7.0 target.

As a result, I don't see how I can push a 7.0.4 release.

Open to suggestions.

**Comment by ProDInfo** [comment]
I try to buid and compile from visual studio and works

========== Recompilar todo: 19 correcto, 0 con errores, 0 omitido ===========
========== Recompilar completado a las 14:21 y tardó 16,819 segundos ==========


My workstation has install...

> PS C:\Users\Euro5.EURO> dotnet --list-sdks
8.0.200 [C:\Program Files\dotnet\sdk]
PS C:\Users\Euro5.EURO> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
PS C:\Users\Euro5.EURO>

With this versions can compile on Visual Studio 2022 and Visual Studio 2022 Preview
![image](https://github.com/MarimerLLC/csla/assets/10604367/c0f7789d-2e39-4880-b9ae-01c49b439565)


Can I help you?

**Comment by StefanOssendorf** [comment]
I can't check it because I can't install the Android SDK 27.

**Comment by rockfordlhotka** [comment]
Interesting. I wonder why I can't?

And you are building the `csla.build.sln`?

**Comment by rockfordlhotka** [comment]
In short - if one of you can do a release build of `csla.build.sln`, then zip up the resulting `bin` directory tree and send it to me, I can package/push to nuget.

**Comment by StefanOssendorf** [comment]
[Csla-Release-v7.0.4.0.zip](https://github.com/MarimerLLC/csla/files/14971614/Csla-Release-v7.0.4.0.zip)

Version build from the PR commit from #3794
