### ISSUE TITLE
Add support for UWP

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#368]

**Comment by rockfordlhotka** [comment]
Need to update the NuGet and setup projects for the UWP assemblies.

**Comment by rockfordlhotka** [comment]
On further research it appears that at this time NuGet doesn't have any platform target for UWP - not that I can find in the NuGet source code at least.

**Comment by Jaans** [comment]
The recently released NuGet 3.0 RC2 doesn't seem to have anything either:
https://github.com/NuGet/NuGet.Packaging/blob/3.0-rc/src/NuGet.Frameworks/FrameworkConstants.cs

**Comment by niemyjski** [comment]
What's UWP?

**Comment by jonnybee** [comment]
UWP = Universal Windows Platform 

 

See: https://www.visualstudio.com/en-us/features/universal-windows-platform-vs.aspx 

And  <https://msdn.microsoft.com/en-us/library/dn894631.aspx> https://msdn.microsoft.com/en-us/library/dn894631.aspx 

 

Windows 10 Insider Preview introduces UWP apps and the Universal Windows Platform (UWP) which provides a guaranteed core API layer across devices. You can create a single app package that can be installed onto a wide range of devices. A single store makes it easy to publish apps across all device types.

**Comment by rockfordlhotka** [comment]
What I have learned is that if you create a UWP project and then use NuGet to add a package to that project what you get from NuGet are the elements in that package that target WinRT.

In other words, at the moment it appears that the way to create a "UWP" target in NuGet is to actually create a WinRT targetted assembly.

Due to this, CSLA already supported UWP before it even existed :)
