### ISSUE TITLE
Remove requirement for Serializable attribute

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3687]
Microsoft is removing support for BinaryFormatter in .NET 9, and presumably this means they might remove the `SerializableAttribute` type.

https://github.com/dotnet/runtime/issues/98245

CSLA never really _used_ this, but does require it as a vestige of when we used to support BinaryFormatter.

CSLA should no longer require the use of the `Serializable` attribute for serializable types.

**Comment by blowdart** [comment]
We can't remove the attribute, it would be too breaking :) It's just nothing will care about it.

**Comment by rockfordlhotka** [comment]
@blowdart agreed - though _Microsoft_ might remove the attribute (I don't know).

**Comment by blowdart** [comment]
In this case I am _Microsoft_. We don't have any plans to remove it as yet.

A much more detailed white paper will be coming soon, my issue in the dotnet repo is really just an overview. Hopefully that will set your mind to rest, but honestly removing the requirement is probably a decent idea if your serializers don't need it.

**Comment by rockfordlhotka** [comment]
That's excellent Barry, I wasn't really paying attention to the identity of the person doing the reply 🫢

I agree with the idea that _removing_ the attribute from .NET would be a massive breaking change. 

In the case of CSLA though, removing the checks that require it (I think) makes sense, because other serializers (including the one that's now default in CSLA) don't use it for anything - it was literally a vestige of the way CSLA was originally based on BinaryFormatter 20 years ago.
