### ISSUE TITLE
BusinessRule not executed when Input Property changes

### ISSUE THREAD

**Issue by ka-fim** [MarimerLLC/csla#3695]
**Describe the bug**
A BusinessRule is only executed when the PrimaryProperty changes but not when any property from the InputProperties changes.

**Version and Platform**
CSLA version: 7.0.3
OS: Should be OS independent, tested on Windows
Platform: Should be platform independent, tested with WPF, Console App

**Code that Fails**
https://github.com/ka-fim/CSLA-BusinessRules
BusinessRule is added with primary and additional input property (BusinessClass.cs):
```
        BusinessRules.AddRule(new Lambda(CustomRule)
        {
            PrimaryProperty = PrimaryProperty,
            InputProperties = { AdditionalInputProperty }
        });
```
Only when setting primary property rule is executed (Program.cs):
```
Console.WriteLine("Setting primary property");
bo.Primary = "test"; // rule will be executed
Console.WriteLine("Setting additional input property");
bo.AdditionalInput = "test2"; // rule will not be executed
```

Expected output of the console app is:
````
Setting primary property
Rule is executed
Setting additional input property
Rule is executed
````
Actual output is:
````
Setting primary property
Rule is executed
Setting additional input property
````

**Comment by rockfordlhotka** [comment]
This is intended behavior. If you want a rule to run because another property has changed, you need to set up dependent rules to trigger that behavior.

**Comment by ka-fim** [comment]
I just noticed that I used a LoadProperty instead of SetProperty for the AdditionalInput property - changing that actually leads to the behavior which I expected (I updated the linked repo accordingly).

So am I relying on a bug now to expect this behavior?!

**Comment by hurcane** [comment]
LoadProperty, by design, does not initiate running of rules. Typically, LoadProperty is used when initializing the properties from the data store.

**Comment by rockfordlhotka** [comment]
Not a bug, I misspoke and the info in this thread is good.
