### ISSUE TITLE
Project edit page stuck at "Loading Blazor wasm runtime..."

### ISSUE THREAD

**Issue by Tony20221** [MarimerLLC/csla#3741]
When the ProjectTracker runs for the very first time or when the page's browser storage is cleared of the wasm runtime and when going to a project details page, the editproject page is stuck at displaying the message "Loading Blazor wasm runtime...".

The page needs to be refreshed to display the page properly. 

Is the expectation that the page will dynamically display the contents when the page finishes downloading the Blazor wasm runtime in the background?

**Comment by rockfordlhotka** [comment]
Were you able to run it against the version of CSLA in main?

I clearly forgot to push that to NuGet 😳

**Comment by StefanOssendorf** [comment]
I got that message, too during fixing #1376 with the project references.

**Comment by Tony20221** [comment]
> Were you able to run it against the version of CSLA in main?
> 
> I clearly forgot to push that to NuGet 😳

I cloned CSLA which gets it from main.

**Comment by rockfordlhotka** [comment]
This doesn't happen on my machine. I wonder what is different?

**Comment by Tony20221** [comment]
Did you clear the application data and when you refresh the page, it downloads again the .NET runtime? Do you see .NET wasm files being downloaded in the network tab in devtools? Because if the runtime exists from before, this issue will not happen.

You seem to be running 8.0.0-R24031302 in your local machine and you mentioned in the Github discussion you forgot to push 8.0.0-R24031302 to Nuget and I still don't see it there. Assuming the new version touches the functionality we're discussing here.

**Comment by rockfordlhotka** [comment]
I just pushed 24031302 (got my starlink back online)

**Comment by Tony20221** [comment]
The page is still stuck at the 'Loading Blazor wasm runtime...' message when .net runtime are not available.

**Comment by rockfordlhotka** [comment]
I haven't had time to look into this yet, but as I was driving it occurred to me that the latest code does rely on the latest patch of .NET 8. Microsoft fixed a couple bugs with Blazor `InteractiveAuto` mode. Please make sure you are using the latest patch for .NET 8.

**Comment by Tony20221** [comment]
I am using 8.0.3 which is the latest.

**Comment by StefanOssendorf** [comment]
I can reproduce this issue with a fresh cloned main on my laptop.
Clear the site data and navigate to Projects -> Details. The first time going that route keeps you stuck at the loading screen. Second time works as expected.

**Comment by Tony20221** [comment]
The issue seems to be that the code in the razor page
```
@if (!IsInteractive)
{
    <h1>Edit Project</h1>
    <p>Loading Blazor wasm runtime...</p>
}
```

doesn't run after the OnAfterRender is fired when the .net runtime is not present?

**Comment by rockfordlhotka** [comment]
Is it that after render isn't being called, or am I missing a StateHasChanged call?

**Comment by StefanOssendorf** [comment]
Yes. A `StateHasChanged` in `OnAfterRender` after `IsInteractive = true;` in `EditProject.razor` solves the problem.

**Comment by Tony20221** [comment]
Probably missing a StateHasChanged call.

I placed a breakpoint in the OnAfterRender event and one on the if statement. Here are the sequences of breakpoints that got hit in each case.
You can see in the first case that after the second OnAfterRender, it didn't execute the if statement. That's when IsInteractive would be true by then.


(With no runtime loaded)
break at if statement - IsInteractive is false
break at if statement - IsInteractive is false
break at if statement - IsInteractive is false
break at if statement - IsInteractive is false
break at OnAfterRender (first render = true)
break at OnAfterRender (first render = false)
(page is rendered with 'Loading Blazor wasm runtime' line and stays at this state)


(Refresh the page and runtime should be loaded)
break at if statement - IsInteractive is false
break at if statement - IsInteractive is false
break at if statement - IsInteractive is false
break at OnAfterRender (first render = true)
break at if statement - IsInteractive is true
break at OnAfterRender (first render = false)
(page is rendered with project details)

**Comment by StefanOssendorf** [comment]
You have to change the `OnAfterRender` to 
```csharp
if (firstRender) {  
  IsInteractive = true;
  StateHasChanged();
}
```
Otherwise I get a StackOverflowException xD

**Comment by rockfordlhotka** [comment]
I _think_ that it should look like this:

```c#
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
      if (firstRender)
      {
        IsInteractive = true;
        if (Id.HasValue)
            await vm.RefreshAsync(() => projectEditPortal.FetchAsync(Id));
        else
            await vm.RefreshAsync(() => projectEditPortal.CreateAsync());

        RoleList = await roleListPortal.FetchAsync();
        StateHasChanged();
      }
    }
```

**Comment by Tony20221** [comment]
> I _think_ that it should look like this:
> 
> ```cs
>     protected override async Task OnAfterRenderAsync(bool firstRender)
>     {
>       if (firstRender)
>       {
>         IsInteractive = true;
>         if (Id.HasValue)
>             await vm.RefreshAsync(() => projectEditPortal.FetchAsync(Id));
>         else
>             await vm.RefreshAsync(() => projectEditPortal.CreateAsync());
> 
>         RoleList = await roleListPortal.FetchAsync();
>         StateHasChanged();
>       }
>     }
> ```
> 
> Moving the data portal calls out of initialized to after rendered so the data doesn't load during the server-side static render process.


This fix seems to have worked.
