### ISSUE TITLE
INotifyDataErrorInfo.GetErrors return BrokenRules when IsValid object.

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#3746]
**Describe the bug**
When use BusinessBase on WPF application, the INotifiyDataErrors implementation get errors when **IsValid** object.
For example rules that return **Information**, **Warning** and **Success** severity on rule engine.

**Version and Platform**
CSLA version: 7.0.3
OS: Windows
Platform: WPF

**Code that Fails**
```
IEnumerable INotifyDataErrorInfo.GetErrors(string propertyName)
{
  return BusinessRules.GetBrokenRules().Where(r => r.Property == propertyName).Select(r => r.Description);
}
```

**Additional context**

Implementation of INotifyDataErrorInfo should be only for  **RuleSeverity.Error** because the IsSelfValid it's only for RuleSeverity.Error 
See below the HasErrors implementation
```
 bool INotifyDataErrorInfo.HasErrors => !IsSelfValid;

 public virtual bool IsSelfValid => BusinessRules.IsValid;
```
```
  //
  // Resumen:
  //     Gets a value indicating whether there are any currently broken rules, which would
  //     mean the object is not valid.
  public bool IsValid => BrokenRules.ErrorCount == 0;
```

The code sould be:
```
IEnumerable INotifyDataErrorInfo.GetErrors(string propertyName)
{
  return BusinessRules.GetBrokenRules().Where(r => r.Severity == RuleSeverity.Error && r.Property == propertyName).Select(r => r.Description);
}
```

**Comment by rockfordlhotka** [comment]
@ProDInfo I suspect this will get fixed in 8.1.0 - if you want to fix it in 7.0.4 please submit a PR.
