### ISSUE TITLE
Data portal should call WaitForIdle on root object before returning

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3755]
Right now, if an object graph has async rules running on the logical server as the data portal operation completes, an exception is thrown because the graph is busy.

The data portal should, prior to the is busy check, await the root object's `WaitForIdle` method to wait until all async rules are complete (or the timeout). This is in `SimpleDataPortal`.

The `ObjectFactory` type should also expose a `WaitForIdle` helper method to make it consistent for factory code to explicitly wait for rule completion.

As per this thread: https://github.com/MarimerLLC/csla/discussions/3751#discussioncomment-8932459

**Comment by StefanOssendorf** [comment]
I'd argue this is a bug because a non valid/inconsistent state of an clsa object graph goes over the wire.
Furthermore the same holds for the client side which is about to send the object to the server. Shouldn't there also be ensured that all rules are finished?
