### ISSUE TITLE
CSLA 8.0.0 target framework not net8.0-windows

### ISSUE THREAD

**Issue by ProDInfo** [MarimerLLC/csla#3771]
**Describe the bug**
I try to update my libraries to CSLA 8.0.0, but the specification in nuspec links to net8.0-windows10.0.19041 and not to net8.0-windows, but CSLA projects are built for net8.0-windows. If not changed, all projects in my solution need to be upgraded to net8.0-windows10.0.19041, but I need net8.0-windows.

Can You switch from net8.0-windows10.0.19041 to net8.0-windows in the nuget specification?

**Version and Platform**
CSLA version: 8.0.0
OS: Windows
Platform: WPF

**Additional context**
To fix, although I am not an expert, I think that the following change in the nuspec files may be valid.
From:
```
 <group targetFramework="net8.0-windows10.0.19041">
      <dependency id="Csla" version="[4.6.3-Beta10]" />
      <dependency id="Microsoft.Extensions.Hosting" version="8.0.0" />
      <dependency id="Microsoft.Extensions.Hosting.Abstractions" version="8.0.0" />
    </group>

 <!-- net8.0-windows -->
    <file src="..\..\bin\Release\net8.0-windows\**\Csla.Xaml.*" target="lib\net8.0-windows10.0.19041.0" />

```
To:
```
 <group targetFramework="net8.0-windows">
      <dependency id="Csla" version="[4.6.3-Beta10]" />
      <dependency id="Microsoft.Extensions.Hosting" version="8.0.0" />
      <dependency id="Microsoft.Extensions.Hosting.Abstractions" version="8.0.0" />
    </group>

 <!-- net8.0-windows -->
    <file src="..\..\bin\Release\net8.0-windows\**\Csla.Xaml.*" target="lib\net8.0-windows" />

```

**Comment by ProDInfo** [comment]
CSLA 8.0.0

**Comment by ossendorf-at-hoelscher** [comment]
> CSLA 8.0.0 can’t use, now I use CSLA 7.0.3 but works fine with net8.0-windows

That somehow sounds weird. CSLA 7.0.3 also targets `net7.0-windows10.0.19041`. The difference is CSLA8 targets `net8.0-windows10.0.19041` in addtion 🤔

**Comment by ProDInfo** [comment]
Can affect this change in net8.0?

[https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list)

**Comment by rockfordlhotka** [comment]
The nuspec file can't just use `net8.0-windows`. That results in this error:

![image](https://github.com/MarimerLLC/csla/assets/2333134/e3025d53-5c99-4b83-8a89-328f6cef021c)

**Comment by rockfordlhotka** [comment]
Ahh, the TFM needs to be `net8.0-windows7.0` in the nuspec

```xml
      <group targetFramework="net8.0-windows7.0">
        <dependency id="Csla" version="[4.6.3-Beta10]" />
        <dependency id="Microsoft.Extensions.Hosting" version="8.0.0" />
        <dependency id="Microsoft.Extensions.Hosting.Abstractions" version="8.0.0" />
      </group>
```

and

```xml
     <!-- net8.0-windows -->
    <file src="..\..\bin\Release\net8.0-windows\**\Csla.Xaml.*" target="lib\net8.0-windows7.0" />
```

**Comment by rockfordlhotka** [comment]
@ProDInfo I pushed a v8.0.1 release with this fix so you can use CSLA 8.

https://github.com/MarimerLLC/csla/releases/tag/v8.0.1
