### ISSUE TITLE
Unable to read beyond end of stream from Android client

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3791]
Hi Folks,

I am currently working on an MAUI project using CSLA6 and CSLA7Preview  and I am facing an issue with the ntiers communication between android and the appserver.
Actually, the maui app windows works well with the ntiers communication but with android i got the following dataportal error :
**Unable to read beyond the end of the stream**.

Below, the github link to reproduce the issue  base on the Rocky MauiExample projet
https://github.com/sylum/MauiExample_NTiers

![FZfqwzHtYa](https://user-images.githubusercontent.com/15035848/235188387-3202f57b-337f-4084-9d3c-6a7afec32e16.png)

**Exception :**
```
Csla.DataPortalException
  Message=Unable to read beyond the end of the stream.
  Source=Csla
  Arborescence des appels de procédure :

   at Csla.DataPortalClient.DataPortalProxy.Fetch(Type objectType, Object criteria, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.<DoFetchAsync>d__19[[BusinessLibrary.PersonList, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Csla.DataPortal`1.<FetchAsync>d__24[[BusinessLibrary.PersonList, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MauiExample.Pages.PersonListPage.<>c__DisplayClass3_0.<<RefreshData>b__0>d.MoveNext() in C:\RFit\Developpement\Csla\SOURCE\MauiExample\MauiExample\MauiExample\Pages\PersonListPage.xaml.cs:line 31
--- End of stack trace from previous location ---
   at Csla.Xaml.ViewModelBase`1.<RefreshAsync>d__69`1[[BusinessLibrary.PersonList, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BusinessLibrary.PersonList, BusinessLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MauiExample.Pages.PersonListPage.RefreshData() in C:\RFit\Developpement\Csla\SOURCE\MauiExample\MauiExample\MauiExample\Pages\PersonListPage.xaml.cs:line 35
   at MauiExample.Pages.PersonListPage.OnAppearing() in C:\RFit\Developpement\Csla\SOURCE\MauiExample\MauiExample\MauiExample\Pages\PersonListPage.xaml.cs:line 20
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

Does someone has already encounter this issue ?

Thanks a lot for you feedback in advance,

Best regards,
Cedric

**Version and Platform**
CSLA : 6.2.2 and 7.0.0-R23042601
MAUI : WIN & DROID
VS2022
WINDOW11

_Originally posted by @sylum in https://github.com/MarimerLLC/csla/discussions/3325_

**Comment by rockfordlhotka** [comment]
I have replicated this issue and have spent some time debugging.

The issue is that the POST payload data (the serialized data portal request) is sent over the wire to the aspnetcore app server, but the server isn't putting the payload into `Request.Body` on the server.

I have the exact code running in Android and in a console app. The requests over the wire are the same. The console app works, the Android app fails - again, because on the server `Request.Body` has data from the console app and is an empty byte array from Android.

---

I am trying to post some binary data to aspnetcore using HttpClient PostAsync, and it works great on Windows and Blazor wasm, but fails from a MAUI Android client.

Is there a known bug with posting ByteArrayContent from Android?

On the server, the Request.Body contains the expected byte array in all cases, but not from Android. I can see the binary data in the payload on the wire in all cases - it just isn't getting put into the Request.Body when the endpoint is invoked from Android.

In all cases it is the exact same client and server code - the only difference is that the client code works from Windows or wasm, and somehow doesn't work from Android.

If I pass the same data as a base64 string it works fine in all cases.

This feels like the early limitation of Blazor wasm where binary data couldn't be posted to the server - a limitation that was long-since resolved.

**Comment by rockfordlhotka** [comment]
Continuing to work through this issue, I now believe it is a bug in the Android implementation of `HttpClient` in .NET itself.

In _theory_, the `content-type` header should be automatically set based on the type used to set the `Content` property of an http request. As a result, the `content-type` for a `ByteArrayContent` object should match up to some binary content type value.

```c#
      var content = new ByteArrayContent(serialized);
      var httpResponse = await client.PostAsync(
        "<server url>",
        content);
```

In _practice_ this is what happens:

| Platform | Behavior |
| --- |
| Windows | `content-type` is not set at all |
| Android | `content-type` is set to `application/x-www-form-urlencoded` |

The Windows behavior, while incorrect, at least _works_. 

The Android behavior doesn't even work, because the aspnetcore server doesn't properly take the binary payload and make it available in `Request.Body` like it should.

The result is that we can't post binary data from a MAUI app on Android to aspnetcore. Accounts of this exist on stackoverflow and in various CSLA forums - it seems to be a universal problem.

**Comment by rockfordlhotka** [comment]
Thanks to @dotMorten it looks like we have a much better workaround.

It turns out that the default `HttpClient` handler on Android is one that (according to the docs) is from .NET Core 2.0 and earlier: `HttpClientHandler`

My guess is that it is too old to understand the new `Content` property behaviors in .NET 8 - though that's just a guess.

The workaround is to configure the `HttpClient` service (or instance) to use a different handler. So in the `MauiProgram.cs` file define the `HttpClient` service like this:

```c#
  builder.Services.AddScoped<HttpClient>((p) => new HttpClient(new SocketsHttpHandler()));
```

This way the `HttpClient` injected into `HttpProxy` in the data portal will properly handle the `ByteArrayContent` content object type.

**Comment by dotMorten** [comment]
I do find it a little odd that you're not setting the content type of the content:
```cs
 var content = new ByteArrayContent(serialized);
 content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("text/html");
```
It is a bit messy to combine body content and querystring in a single request, rather than putting it all in the body.

**Comment by rockfordlhotka** [comment]
@dotMorten my understanding, and this is borne out when using `StringContent` is that `HttpClient` now automatically sets the content type of the content based on the type of content object used to set the Content property. 

As a result, we're not supposed to manually set the content type anymore.

https://github.com/dotnet/runtime/issues/97271

**Comment by filipnavara** [comment]
@dotMorten is right, setting the Content-Type on your *Content* is the right thing to do to get a consistent behaviour. .NET doesn’t have a way to infer it and some mobile platform handlers just happen to have different idea about what the default is for `POST` request.

> It turns out that the default HttpClient handler on Android is one that (according to the docs) is from .NET Core 2.0 and earlier: HttpClientHandler

That’s a wrong understanding. `HttpClientHandler` is still very much relevant. It delegates to a platform specific handler which can be configured. On desktop platforms it wraps `SocketsHttpHandler`. On mobile it depends on the project settings which are exposed as .csproj properties, among others places. The default is to use platform native handlers on mobile, due to size and also some background/foreground app behaviours that may only be relevant on mobile platforms.

**Comment by rockfordlhotka** [comment]
Basically what I'm finding from @dotMorten and @filipnavara is that the `PostAsync` method on `HttpClient` is so buggy as to be useless, and everyone needs to use `SendAsync` until either Microsoft fixes `PostAsync` or (maybe better) just removes it from the API.

**Comment by dotMorten** [comment]
> HttpClient is so buggy as to be useless,

@rockfordlhotka that was your takeaway? What we were saying was that you _should be explicitly_ setting the content type on your http contents - some platforms seem to let that slide, but Android is being stricter and not letting you get away with that.

**Comment by rockfordlhotka** [comment]
@dotMorten yes, but I'm finding - in the thread in the maui repo - that setting the content's content-type isn't reliable with `PostAsync`, but does work with `SendAsync`.

Also, the docs (to me) clearly imply that the correct content type will be set based on the type of content object you use (like `StringContent`, `ByteArrayContent`, etc.).

Maybe the docs are wrong, and all those explicit content types are the problem, as they are useless. I still think Android is broken because it doesn't behave like everything else.

**Comment by dotMorten** [comment]
> Also, the docs (to me) clearly imply that the correct content type will be set based on the type of content object you use (like StringContent, ByteArrayContent, etc.).

How though? How would code tell the difference between these two:
```
new StringContent("This is some text"); // text/plain
new StringContent("{'json':'this is json'}"); // application/json
```
For bytes that gets even trickier. Is it a zip file? An image and which kind? Or some custom byte type? Or maybe it's just text:
`new ByteArrayContent(Encoding.UTF8.GetBytes("This is some text"))`

**Comment by filipnavara** [comment]
> that setting the content's content-type isn't reliable with `PostAsync`, but does work with `SendAsync`.

`PostAsync` is literally just wrapper around `SendAsync`, nothing more, nothing less. In fact, the handlers implement only `SendAsync`.

> Also, the docs (to me) clearly imply that the correct content type will be set based on the type of content object you use (like `StringContent`, `ByteArrayContent`, etc.).

Not sure how you see that in the docs. It’s also literally impossible. Content-Type expresses a different concept than the in memory storage type of your data. There’s no way to infer a correct Content-Type from the data itself, you have to specify it.

One can argue that `application/octet-stream` would be a sensible default for `ByteArrayContent` but there’s no such sensible default for other `*Content` types. Likewise, one could argue that for browsers using the POST method the default is `multipart/x-www-…`.

**Comment by rockfordlhotka** [comment]
@dotMorten @filipnavara

I hear you. The issue is clearly that we're missing an analyzer that forces people to set the content.Header.ContentType explictly. Sure, the defaults are right on Windows and Linux, so 99.9% of people will never care. But for those who use MAUI and Android, this is a real issue.

**Comment by filipnavara** [comment]
> btw, the default for `StringContent` is (imo) correct - just plain text. And that is consistent across platforms.

Yes, and that's documented for that one specific constructor, and the other constructors take it as a parameter.

> The default for non-Android for `ByteArrayContent` is also correct - it is just Android that decided to be random.

There's no "default" for `ByteArrayContent` on any platform, and neither is there for `ReadOnlyMemoryContent` and `StreamContent`. If you don't specify it it's up to the handler to use something. You should absolutely specify a reasonable value though.

I agree that it may not be obvious from the documentation and it's a potential pit of failure.

The thing is that neither `AndroidMessageHandler` (Android) or `NSUrlSessionHandler` (Apple) impose any default either, they just happen to use whatever `HttpURLConnection` (Android) or `NSUrlSession` (Apple) inject as the default. I am not even sure if you could set it to an empty value on the platform-specific objects if you wanted, so it may literally be impossible to achieve the same behavior as `SocketsHttpHandler`.
