### ISSUE TITLE
Breaking change: Blazor StateManager does not use the provided timeout parameter

### ISSUE THREAD

**Issue by StefanOssendorf** [MarimerLLC/csla#3800]
https://github.com/MarimerLLC/csla/blob/881c262f695cfa02b7e936f123280aadd5fb867f/Source/Csla.Blazor/State/StateManager.cs#L46-L52

As shown the timeout parameter is not used in this method. The method is called by the two `InitializeAsync()` methods where one provides a timeout parameters as well.

I think we have two ways to correct this:
1. Remove the timeout parameter and remove the `InitializeAsync(TimeSpan)` method.
2. We extend `ISessionManager.RetrieveSession()` with an overload which also accepts a timeout and pass it along

I think option 2 would be the best so the user can decide whether he wants to wait or not.
In this regard: Should the `SaveState` also get a timeout parameter with passing along to `SendSession()`?

**Comment by rockfordlhotka** [comment]
This is left over from the original design before the final 8.0.0 release.

I suppose a timeout still is a valid concern. And for `SaveState` as well.

**Comment by luizfbicalho** [comment]
> This is left over from the original design before the final 8.0.0 release.
> 
> I suppose a timeout still is a valid concern. And for `SaveState` as well.

I'm working on this issue, shoudn't we  change ISessionManager to receive a cancellation token also?

```C#
public interface ISessionManager
{
  Task<Session> RetrieveSession(TimeSpan timeout);
  Task<Session> RetrieveSession(CancellationToken ct);
  Session GetCachedSession();

  Task SendSession(TimeSpan timeout);
  Task SendSession(CancellationToken ct);
}
```

**Comment by StefanOssendorf** [comment]
I woul say: no.
IIRC currently nowhere is a cancellation token supported. That would be a much greater change.
I think we should go with:
Change `ISessionManager` so `RetrieveSession` and `SendSession` now accept a `TimeSpan timeout` and populate it througout the calling chain to the top.
