### ISSUE TITLE
VersionToken and RoutingToken in HttpProxy/GrpcProxy

### ISSUE THREAD

**Issue by StefanOssendorf** [MarimerLLC/csla#3913]
I stumbled across this. Is the `if` in this form intended?
As far as I understand it looks like not.

https://github.com/MarimerLLC/csla/blob/bba09871f5c5dd04ba6764ab7d20021006b4f6d2/Source/Csla/DataPortalClient/HttpProxy.cs#L232-L237
The same holds for the GrpcProxy.

If exactly one satisfy `IsNullOrWhiteSpace` we could get some funny urls:
```
"create/    -VersionTokenValue"
"create/-VersionTokenValue"
"create/create-        "
"create/create-"
```
My questions are now:
1. Is this intended or a bug?
2. Is the `if` wrong?
3. Should the configuration (at application startup) prevent something like this, if possible?

Notes iff it must be addressed:
* VersionRoutingTag is supplied by `DataPortalOptions.VersionRoutingTag`

**Comment by rockfordlhotka** [comment]
See #1858

**Comment by StefanOssendorf** [comment]
Great. I'll close this as a duplicate then.
