### ISSUE TITLE
Make Templates NuGet package a Solution Level package?

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#396]
I noticed that the current templates package is is a project level package. Should probably be a solution level package?

**Comment by dazinator** [comment]
- The only reason the existing Package isn't treated as a Solution level package, is because of the Readme which is placed in the /Content folder of the package. If this readme was removed, this should then result in the NuGet package being treated a solution level one.

The readme file doesn't seem that important anymore as it just confirms that the templates were installed - it's not as if there are extra manual steps that the user has to carry out after the installation..

**Comment by dazinator** [comment]
I'll send a PR

**Comment by rockfordlhotka** [comment]
Two questions

1. Do I have a contributor agreement from you?
1. Did you test this locally to make sure the changes work as expected?

**Comment by dazinator** [comment]
1. No
2. To a degree but not fully. I did:

    - A manual `NuGet pack` on the `Templates.nuspec` file to produce a package.
    - Installed the package into a new solution to verify it was treated as a "Solution Level" package - and it was.

I have not fully tested it because I haven't physically checked that the templates were indeed copied to the correct locations on install. Let me verify that.

**Comment by dazinator** [comment]
Ok, it seems that for Solution Level packages - that is - packages without a `lib` or `contents` directory, NuGet does not fire the `Install.ps1` script upon install!

Instead it fires `init.ps1` - and it fires init.ps1 also every time the solution is initialised.

Therefore to fix this, I'd have to move the logic from `Install.ps1` into a new `init.ps1`. Would you be ok with such a change?

**Comment by rockfordlhotka** [comment]
I'm ok with such a change as long as the resulting functionality is correct.

**Comment by rockfordlhotka** [comment]
Before I accept a pull request I will need the contributor agreement. See here for details:
https://github.com/MarimerLLC/csla/blob/master/CONTRIBUTING.md

**Comment by dazinator** [comment]
Ok sure, I'll send an agreement across as soon as I get some more time.

As of my latest commit on the PR, I have tested the "solution level" nuget package - and it works.

Interestingly, NuGet doesn't seem to fire the uninstall.ps1 script for a solution level NuGet package, so this means this NuGet package will serve as a quick way to ensure the Templates / Snippets are installed (and due to init.ps1 firing when the solution is opened - even if another developer checks out the code and doesn't currently have the templates, init.ps1 will fire and install the templates automatically on their machine - which I think is nice) but if you wan't to remove the templates / snippets then simply uninstalling the NuGet package won't do it.

**Comment by rockfordlhotka** [comment]
Due to the nature of this package, it should really only run once on a machine for a user, then it has done its job. I'm personally unconcerned about ininstall, as all it does is put templates/snippets in place.

**Comment by rockfordlhotka** [comment]
This will probably be affected by #399 too, as I understand NuGet 3.0 makes some serious changes over 2.0.
