### ISSUE TITLE
Analyzer: No DataPortal Operations Exist

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#402]
If a class is a CSLA stereotype, and it doesn’t have at least one DP operation, flag this as a warning as it seems odd to not have any DP operations defined.

**Comment by jonnybee** [comment]
Except for when the solution uses ObjectFactory!!!! 
Then this is an "expected" condition for both "root" and "child" stereotypes and only "root" objects are expected to have the ObjectFactoryAttribute.

**Comment by ajj3085** [comment]
Also, we use compiler directives to compile out dataportal code for the client version of the business library that goes with our winforms ui, as our application only runs with a remote portal.

**Comment by JasonBock** [comment]
It isn't clear to me yet that this is a good idea for an analyzer. I'd like to get @rockfordlhotka's opinion on this, but I'm not sure this can be done in a straightforward fashion.

**Comment by rockfordlhotka** [comment]
I do not think it is a good idea. There are too many valid scenarios where people might create classes that don't persist.

**Comment by JasonBock** [comment]
Then let's close this out and not even try to do this :).
