### ISSUE TITLE
Fix analyzer for deployment via NuGet 3.0

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#404]
It looks like NuGet 3.0 requires that we be more explicit about dependencies for PCLs - the analyzer won't work after being deployed into a project because of a missing dependency.

```
Severity	Code	Description	Project	File	Line
Warning		An instance of analyzer Csla.Analyzers.IsBusinessObjectSerializableAnalyzer cannot be created from D:\Users\Rockford\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.3-Beta1\tools\analyzers\C#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	ProjectTracker.Dal	D:\Users\Rockford\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\ProjectTracker.Dal\CSC	
```

**Comment by JasonBock** [comment]
I talked to Rocky about this in e-mail. Initial steps are to get the nuspec and ps1 files updated to match what is gen'd when you create an analyzer project with VS2015 RTM (which is different than RC and before). If that doesn't fix things, we may need to look at adding project.json into the mix: http://blog.nuget.org/20150729/Introducing-nuget-uwp.html.

**Comment by JasonBock** [comment]
Seems like all of the following need to be updated:

* nuspec
* ps1 files
* packages.config
* csproj files

I believe we had fixed the first three, but the proj files themselves....not sure about that. But I did that locally with the latest code and that DOES fix the code fix issue we were having in VS2015.

**Comment by rockfordlhotka** [comment]
@JasonBock, master has been updated with the changes we just made to get the NuGet stuff working.

**Comment by rockfordlhotka** [comment]
@JasonBock I pushed 4.6.3-Beta2 into NuGet so you can do a final test from the actual server.

**Comment by JasonBock** [comment]
Just tested, everything works as expected, close this out! :)
