### ISSUE TITLE
Rework how the NuGet packages are created

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4058]
Right now the nuget packages are created using nuspec files and powershell scripts in the `csla/nuget` directory. This was necessary when we still had old-style project files, but starting with CSLA 9 all csproj files use the modern project syntax.

It should now be possible to create the nuget and symbol packages directly from the csproj files used in the `csla.build.sln` solution.

We need to make sure that the resulting nuget packages are identical to those being created by the nuspec files, at least in terms of package names, and target frameworks (TFMs).

Hopefully this change will allow the symbol packages to actually work as they are supposed to.

**Comment by luizfbicalho** [comment]
I used the [Nerdbank.Gitversioning](https://github.com/dotnet/Nerdbank.GitVersioning)

and this is what I use in my projects


```csproj
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AssemblyOriginatorKeyFile>..\signkey\XXXXX-key.snk</AssemblyOriginatorKeyFile>
    <LangVersion>latest</LangVersion>
    <OutputPath>..\NugetPackages\</OutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <Nullable>enable</Nullable>
```

what are your ideas besides that?

**Comment by rockfordlhotka** [comment]
@StefanOssendorf is working on the nullable stuff, so we shouldn't add that as part of _this_ change.

Does the Nerdbank.Gitversioning follow semver?

I assume most or all of this goes into the centralized build props file?

**Comment by luizfbicalho** [comment]
> Does the Nerdbank.Gitversioning follow semver?

Yes, it uses the git commit to generate an incremental nuget version based on a json file like this

```json
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/main/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0-beta"
}
```

about the others questions I just added what I used in other projects, after we get the idea then we can implement in a better way

**Comment by rockfordlhotka** [comment]
Sounds good to me!

**Comment by StefanOssendorf** [comment]
I'm using [MinVer](https://github.com/adamralph/minver) instead of Nerdbank.Gitversioning. It was easier for me to setup and maintain. But I have no hard feelings which tool we use to make the versioning work.

Do we want to include the symbols? IIRC that means our nuget package gets a lot bigger due to everything being packed into instead of "outsourced" into the snupkg. Or am I wrong here?

**Comment by luizfbicalho** [comment]
> Do we want to include the symbols?

I asked the nuget repository about this, [nuget issue](https://github.com/NuGet/Home/issues/9853)

**Comment by rockfordlhotka** [comment]
> Do we want to include the symbols? IIRC that means our nuget package gets a lot bigger due to everything being packed into instead of "outsourced" into the snupkg. Or am I wrong here?

I'd rather keep the core packages smaller, as people (one assumes) use them on build servers and probably other scenarios where time and bandwidth might cost extra. 

People using the packages on a dev box can access the symbol packages as necessary.

On the other hand, if there's no size difference, then whatever is simpler is better as a general rule.
