### ISSUE TITLE
BlazorExample Solution doesn't work with 8.2.4 - Error:Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component. Typically, this means you can call it only within a Razor component or inside another DI service that is resolved for a Razor component.

### ISSUE THREAD

**Issue by jmpotvin** [MarimerLLC/csla#4075]
I have upgraded the provided BlazorExample to CSLA 8.2.4

**Version and Platform**
CSLA version: 8.2.4
OS: Windows 10
Platform: ASP.NET Core

**Code that Fails**
Just start the solution and click on List People or Add Person.

**Stack Trace or Exception Detail**
The following error is displayed on the screeen:
**Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component. Typically, this means you can call it only within a Razor component or inside another DI service that is resolved for a Razor component.**

**Comment by rockfordlhotka** [comment]
I _think_ this is just a configuration issue. I'm pretty sure we fixed the underlying bug behind this exception, and probably didn't update the configuration of the sample app.

The solution should be to use a different application context manager, specifically:

https://github.com/MarimerLLC/csla/blob/v8.x/Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs

**Comment by rockfordlhotka** [comment]
I tested this against the 8.2.5 codebase and can't replicate, so the fix will be in the next release.

**Comment by jmpotvin** [comment]
Thanks! I'm upgrading my project from 7 to 8 and encountering the same error message. Do you have a planned release date for 8.2.5?

**Comment by rockfordlhotka** [comment]
We'll push the release as soon as possible, probably in the next few days.

**Comment by rockfordlhotka** [comment]
I take it back. Upon further testing today, I am still able to replicate the issue in the v8.x branch.

**Comment by kcabral817** [comment]
You have my prayers.

Have a nice day.

Kevin



________________________________

**Comment by rockfordlhotka** [comment]
@jmpotvin, @kcabral817 - the fix should be in NuGet now.
