### ISSUE TITLE
Rename Csla.Generators to Csla.Generator.AutoGenerator

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4085]
Now that the `Csla.Generators/cs` project works (#3068), I think we need to reconsider how it is named - including the resulting NuGet package.

We may create other generators over time, some that might not have to do with serialization. Difficult to see. Always in motion is the future.

To avoid confusion, I think the generator we now have should be renamed to `Csla.Generator.AutoSerializer` so it corresponds to the attribute an end developer uses to invoke it. That'll tie the behavior and names together - for our codebase and also for the NuGet package name.

**Comment by kcabral817** [comment]
Rocky,

Are you channeling a little Yoda?  “Difficult to see. Always in motion is the future.”

Have a nice day.

Kevin



________________________________
From: Rockford Lhotka ***@***.***>
Sent: Sunday, July 7, 2024 5:39 PM
To: MarimerLLC/csla ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MarimerLLC/csla] Rename Csla.Generators to Csla.AutoGenerator (Issue #4085)


Now that the Csla.Generators/cs project works, I think we need to reconsider how it is named - including the resulting NuGet package.

We may create other generators over time, some that might not have to do with serialization. Difficult to see. Always in motion is the future.

To avoid confusion, I think the generator we now have should be renamed to Csla.AutoSerializer so it corresponds to the attribute an end developer uses to invoke it. That'll tie the behavior and names together - for our codebase and also for the NuGet package name.

**Comment by StefanOssendorf** [comment]
I think we should include clearly in the name that the package is a source generator.
Maybe something like `Csla.Generator.<GenFunctionalty>` for example `Csla.Generator.AutoSerialization`?

**Comment by luizfbicalho** [comment]
Did anyone get this to do?

**Comment by rockfordlhotka** [comment]
No, would you like to do it?
