### ISSUE TITLE
Allow async Task<IRuleContext> rules

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#409]
Consider enhancing the rules engine to allow `Execute` methods that return `Task<RuleContext>`.

Right now async rules are `void` or `async void`, but it would be acceptable to have an overload of `Execute` that would be `async Task<RuleContext>`.

In such a scenario having the rule call `context.Complete()` would result in an exception, because completion of the rule would be indicated by `return context` instead. 

I don't think there'd be any other changes to the way rules are implemented - so this is basically a cosmetic change to the way rules are implemented to help avoid having people implement `async void` methods (which are normally a bad thing).

**Comment by JasonBock** [comment]
I'd name the new method "ExecuteAsync" to follow standard .NET patterns and to differentiate it from the old-school "Execute" way.

**Comment by rockfordlhotka** [comment]
The rule engine is interface-based, so adding a new method name would expand the interface - thus leaving the question of whether the engine should call `Execute` or `ExecuteAsync` given that both would have to be "implemented" by the rule.

**Comment by JasonBock** [comment]
Hmmm...is there a way this could be done so you have a AsyncBusinessRule class, and that's what's used for "new" async rules?

**Comment by rockfordlhotka** [comment]
Thinking about this more today. The rule engine is interface-based. So I suppose the answer is three interfaces.

```c#
  public interface IBusinessRuleBase {}

  public interface IBusinessRule
  {
    void Execute(IRuleContext context);
  }

  public interface IBusinessRuleAsyncBase
  {
    Task Execute(IRuleContext context);
  }
```
Update the existing `BusinessRule` base class, and add a new `BusinessRuleAsync` base class.

Rules would then look like this (sync, async-old, async-new):

```c#
  public class MyRule : BusinessRule
  {
    public override void Execute(IRuleContext context)
    {
      // sync rule goes here
    }
  }

  public class MyRule : BusinessRule
  {
    public MyRule() { IsAsync = true; }

    public override async void Execute(IRuleContext context)
    {
      // async rule goes here
      context.Complete();
    }
  }

  public class MyRule : BusinessRuleAsync
  {
    public override async Task Execute(IRuleContext context)
    {
      // async rule goes here
    }
  }
```
