### ISSUE TITLE
Remove ObjectContextManager

### ISSUE THREAD

**Issue by StefanOssendorf** [MarimerLLC/csla#4101]
Remove `Csla.Data.ObjectContextManager<C>` from CSLA.
In it's current form it's even unusable because you can't get hold of a reference due to changes back in 2021.

This is technically speaking a breaking change. But because it's not usable since 2021 I don't consider it breaking.

**Comment by luizfbicalho** [comment]
Can you assign this to me?

**Comment by StefanOssendorf** [comment]
Done
