### ISSUE TITLE
Rework Csla.Templates to be a dotnet CLI installed feature

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4119]
The `Csla.Templates` template files are in

https://github.com/MarimerLLC/csla/tree/main/Support/Templates

Prior to CSLA 9 we created and deployed these using a NuGet package - but really that was never the right solution.

I believe that now we can create a `dotnet` CLI command or package or tool (not sure of the name) that can install the templates for people. Perhaps this can also install the snippets found at

https://github.com/MarimerLLC/csla/tree/main/Support/Snippets

**Comment by kant2002** [comment]
The project template is dated. If take it as it is it not even compiles, since it uses `DataPortal` instead of `DataPortal<T>`. Do you think that particular template still has a value?

**Comment by rockfordlhotka** [comment]
> The project template is dated. If take it as it is it not even compiles, since it uses `DataPortal` instead of `DataPortal<T>`. Do you think that particular template still has a value?

I am skeptical that it has value. No one has complained about it not working, and it hasn't worked for years at this point.
