### ISSUE TITLE
ReadWriteTimeout in httpproxy.cs

### ISSUE THREAD

**Issue by amselem** [MarimerLLC/csla#4123]
**Describe the bug**

-When using HttpProxy I'm experiencing consistent timeouts in long running dataportal operations, specifically when > 5 minutes. I always get a TimeOut exactly 5:00 minutes after starting the call.

-Setting the HttpProxy.TimeOut property to a value > 5 minutes didn't help.

-I found that there's a default 5 minute timeout value in the ReadWriteTimeOut property of the HttpWebRequest class (https://learn.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.readwritetimeout?view=net-8.0). 
The ReadWriteTimeOut  is different from the  TimeOut (which is correctly set by the httpProxy timeout parameter), so please note that we have two timeouts in play here.

**Version and Platform**
CSLA version: 5.5.3

** To repro
Simply launch a long running dataportal call using the httpproxy, and wait 5:00.  The httpproxy TimeOut value won't help beyond 5:00

**Additional context**

I could subclass HttpProxy to fix it but since HttpProxy is allowing to manage the TimeOut value I thought that it would be interesting in adding this change to the main code

Suggested code change:

HttpProxy.cs , class DefaultWebClient  , change from :

```
protected override WebRequest GetWebRequest(Uri address)
      {
        var req = base.GetWebRequest(address) as HttpWebRequest;
        if (Timeout > 0)
          req.Timeout = Timeout;
        return req;
      }
```

to this  (For simplicity I used the same TimeOut property value for setting both TimeOut and ReadWriteTimeOut , but maybe a new separated property should be created in HttpProxy) :

```
protected override WebRequest GetWebRequest(Uri address)
      {
        var req = base.GetWebRequest(address) as HttpWebRequest;
        if (Timeout > 0)
        {
          req.Timeout = Timeout;
          req.ReadWriteTimeout = Timeout;  // <-- this
         }
         return req;
      }

```

**Comment by amselem** [comment]
Yes I'm in v5.5.3  under  .Net 8.0 but I think it is relevant in the current/future versions since the dependency with webclient is still there (look at the current httproxy.cs)

**Comment by rockfordlhotka** [comment]
I think we'll address this in v9. I am not even sure I can build v5 anymore, that's very old now 😄

**Comment by luizfbicalho** [comment]
Can it be the same timeout or we should have two properties to configure that?

Can you assign that to me?

**Comment by rockfordlhotka** [comment]
I think it should be its own timeout. That should be easier in v9 now that HttpProxy has its own options class.
