### ISSUE TITLE
Remove two obsolete/unused types

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4129]
@rockfordlhotka Could you please take a look at `Csla.DataPortalClient.DataPortalProxyDescriptor`. This class is no where referenced. Neither by type or as a magic string. Otherwise we can remove it.
And `Csla.DataPortalClient.IApplicationContextProvider` looks dead, too.

_Originally posted by @StefanOssendorf in https://github.com/MarimerLLC/csla/issues/1233#issuecomment-2259133951_

**Comment by rockfordlhotka** [comment]
@luizfbicalho do you want this one as well - same idea as the other two?

**Comment by luizfbicalho** [comment]
ok
