### ISSUE TITLE
Do not call GetAutnenticationState outside of DI.   BlazorExample project

### ISSUE THREAD

**Issue by kcabral817** [MarimerLLC/csla#4170]
**Describe the bug**
Do not call GetAutnenticationState outside of DI.  This happened with the latest download compiling the samples/blazorExample. 
https://[localhost:7210/listpersons](https://localhost:7210/listpersons)
https://[localhost:7210/editperson](https://localhost:7210/editperson)

Although Weather menu works:  https://localhost:7210/weather

**Version and Platform**
CSLA version:   8.2.5
OS: Windows
Platform: Blazor

**Code that Fails**
Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component. Typically, this means you can call it only within a Razor component or inside another DI service that is resolved for a Razor component.

**Stack Trace or Exception Detail**
14:52:07:094	'BlazorExample.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
14:52:07:094	'BlazorExample.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
14:52:07:354	'BlazorExample.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
14:52:07:354	Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
14:52:07:354	
14:52:07:354	System.InvalidOperationException: Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component. Typically, this means you can call it only within a Razor component or inside another DI service that is resolved for a Razor component.
14:52:07:354	   at Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider.GetAuthenticationStateAsync()
14:52:07:354	   at Csla.Blazor.WebAssembly.ApplicationContextManager.InitializeUser()
14:52:07:354	   at Csla.Blazor.WebAssembly.ApplicationContextManager..ctor(AuthenticationStateProvider authenticationStateProvider)
14:52:07:354	   at InvokeStub_ApplicationContextManager..ctor(Object, Span`1)
14:52:07:354	   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
14:52:07:354	   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
14:52:07:354	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
14:52:07:354	   at lambda_method73(Closure, IServiceProvider, Object[])
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
14:52:07:354	--- End of stack trace from previous location ---
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
14:52:07:354	   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
14:52:07:354	   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
14:52:07:354	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
14:52:07:354	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
14:52:07:354	crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
14:52:07:354	      Unhandled exception rendering component: Response status code does not indicate success: 500 (Internal Server Error).
14:52:07:354	System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
14:52:07:354	   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
14:52:07:354	   at System.Net.Http.Json.HttpClientJsonExtensions.<<FromJsonAsyncCore>g__Core|12_0>d`2[[Csla.Blazor.State.Messages.StateResult, Csla, Version=9.0.0.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30],[System.Text.Json.JsonSerializerOptions, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
14:52:07:354	   at Csla.Blazor.WebAssembly.State.SessionManager.RetrieveSession(CancellationToken ct)
14:52:07:354	   at Csla.Blazor.WebAssembly.State.SessionManager.RetrieveSession(TimeSpan timeout)
14:52:07:354	   at Csla.Blazor.State.StateManager.GetState(TimeSpan timeout)
14:52:07:354	   at BlazorExample.Client.Components.Pages.Counter.OnInitializedAsync() in C:\csla-main\Samples\BlazorExample\BlazorExample\BlazorExample.Client\Components\Pages\Counter.razor:line 27
14:52:07:354	   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
14:52:07:354	   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Additional context**
C:\csla-main\Samples\BlazorExample\BlazorExample\BlazorExample\bin\Debug\net8.0

![image](https://github.com/user-attachments/assets/7b8c8e85-9948-47a8-ab41-b08ee4407266)

**Comment by rockfordlhotka** [comment]
To be addressed as part of #2551
