### ISSUE TITLE
Address System.Data.SqlClient deprecation 

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4172]
https://github.com/dotnet/SqlClient/issues/2778

The CSLA package should follow the lead of Microsoft in the v9 and v10 releases.

**Comment by luizfbicalho** [comment]
Isn't System.Data.SqlClient?

**Comment by rockfordlhotka** [comment]
CSLA 9 will change this package to only target net462 so it continues to be available to .NET Framework users, but not to modern .NET users.
