### ISSUE TITLE
Remove `Csla.Security.PrincipalCache` and also `SecurityOptions.PrincipalCacheMaxCacheSize`

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4199]
Please take a look at `Csla.Security.PrincipalCache` this looks dead, too. If it's dead we also can remove the `SecurityOptions.PrincipalCacheMaxCacheSize` property.

_Originally posted by @StefanOssendorf in https://github.com/MarimerLLC/csla/issues/1233#issuecomment-2322976095_

**Comment by luizfbicalho** [comment]
Can you assign this to me?
