### ISSUE TITLE
Remove `ICslaIdentity`, `ICslaPrincipal`, `ICheckRoles` types 

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4200]
`ICslaIdentity`, `ICslaPrincipal`, `ICheckRoles.` also dead? 🤔

_Originally posted by @StefanOssendorf in https://github.com/MarimerLLC/csla/issues/1233#issuecomment-2322982672_

**Comment by luizfbicalho** [comment]
Can you assign this to me?
