### ISSUE TITLE
Analyzer not working

### ISSUE THREAD

**Issue by ossendorf-at-hoelscher** [MarimerLLC/csla#4269]
**Describe the bug**
The CSLA analyzer are not working. The following is in my project file (simple console):
`<PackageReference Include="Csla" Version="8.2.7" />`
But the analyzer do not show up in the VS analyzer view:
![image](https://github.com/user-attachments/assets/051425d2-2c98-424c-a928-2e3f42e5f32d)

Furthermore I have a business object `Foo` and using it with
`var foo2 = new Foo();`
As far as I know this should produce an analyzer warning. But nothing.

**Version and Platform**
CSLA version: latest 8.2.7
OS: Windows
Platform: Console

**Code that Fails**
```csharp
var foo = new Foo(); // Should trigger a warning

[Serializable]
public class Foo : BusinessBase<Foo>
{
  [Create, RunLocal]
private void Create()
{
}
}
```

**Comment by rockfordlhotka** [comment]
I am unable to replicate this issue. I recently worked with a new 8.2.7 project and the analyzers were working fine.

@ossendorf-at-hoelscher can you confirm the issue still exists?

**Comment by ossendorf-at-hoelscher** [comment]
Sorry I missed this. I think the problem was my test objects were not in a namespace. After moving them into a namespace and rebuilding i get the analyzers 👍
