### ISSUE TITLE
Blazor example broken on 9.0.0-R24070301

### ISSUE THREAD

**Issue by kant2002** [MarimerLLC/csla#4339]
**Describe the bug**
Open BlazorExample and change version in Directory.Build.packages to 9.0.0-R24070301. After running application you will see `.NET 8.0: Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component` on the List Person and Add Person pages. If go with 9.0.0-preview-g346ef21eb1, then everything would be working. It potentially related to #3583

**Version and Platform**
CSLA version: 9.0.0-R24070301
OS: Windows, Windows
Platform: Blazor

**Code that Fails**
BlazorExample

**Comment by rockfordlhotka** [comment]
Thank you @kant2002 - to be resolved in #3785
