### ISSUE TITLE
Standardize on Rocks for mocking in unit test projects

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#4346]
I would like CSLA to standardize on the use of the Rocks mocking framework for our unit tests.

@JasonBock has been a long-time contributor to CSLA, and often uses CSLA to test Rocks, and it makes sense to me that the CSLA project settle on Rocks within our tests.

**Comment by JasonBock** [comment]
Note: I'm currently waiting on Microsoft to publish the final version of their compiler-related assemblies, like [`Microsoft.CodeAnalysis.CSharp`](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/4.12.0-3.final), to push the `9.0.0` version of Rocks. Once that happens, then I can tackle this test.

**Comment by JasonBock** [comment]
Well....as I just found out, CSLA doesn't use **any** mocking frameworks in test projects. So, this is a nothing burger. I mean, if @rockfordlhotka wants to standardize on Rocks **if** mocking is needed in the future, I'm all for that :). But nothing seems to be needed right now.
