### ISSUE TITLE
Blazor.Example.Client  not run via VScode and C# Devkit due to missing

### ISSUE THREAD

**Issue by jhogan05** [MarimerLLC/csla#4388]
**Describe the bug**

- Open VSCode
- Pull the current GIT repository
- Navigate in the Explorer to Blazor Sample
- (CSLA --> Samples --> Blazor)
- Open Solution in VSCode (Samples\BlazorExample\BlazorExample.sln)

- Navigate in the Solution Explorer into Blazor.Example (BlazorExample --> BlazorExample)
- Open Program.cs
- [>] Build/Run --> works

- Navigate into Blazor.Example.Client
- [>] Build/Run --> Error (see below)

```
WasmAppHost --use-staticwebassets --runtime-config C:\Users\########\source\repos\csla\Samples\BlazorExample\BlazorExample\BlazorExample.Client\bin\Debug\net9.0\BlazorExample.Client.runtimeconfig.json

Error: Cannot find runtime config at C:\Users\########\source\repos\csla\Samples\BlazorExample\BlazorExample\BlazorExample.Client\bin\Debug\net9.0\BlazorExample.Client.runtimeconfig.json
```

**Version and Platform**
CSLA version: 9 Release
OS: Windows 11
Platform: ASP.NET Core

**Code that Fails**
as above

**Stack Trace or Exception Detail**
as above

**Additional context**
To allow it to run I have followed an example guided by CoPilot which it to create a runtimeconfig.template.json as below in the Blazor.Client.Example main project folder:

```
{
  "runtimeOptions": {
    "tfm": "net9.0",
    "framework": {
      "name": "Microsoft.AspNetCore.Components.WebAssembly",
      "version": "9.0.0"
    },
    "configProperties": {
      "System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport": true,
      "System.Runtime.TieredCompilation": false,
      "System.GC.Concurrent": false,
      "System.Globalization.UseNls": true
    }
  }
}
```
From CoPilot:
...
Summary:
Blazor WebAssembly: Microsoft.AspNetCore.Components.WebAssembly framework, version 7.0.0.

HTTP/2 Support: Enables unencrypted HTTP/2 for development.

Tiered Compilation: Disabled to prioritize startup time.

Garbage Collection: Server GC disabled (usually the default for WASM).

Globalization: Invariant mode enabled to reduce app size.

These settings help tailor the runtime environment to the specific needs and constraints of a Blazor WebAssembly application. Feel free to adjust or add additional settings based on your project's requirements.
...

**Comment by rockfordlhotka** [comment]
The `/Samples/BlazorExample` solution isn't a standalone wasm solution. It is a .NET 8 Blazor solution that demonstrates how to use the CSLA 9 features to use the new automatic render mode and hosting capabilities that came in Blazor 8.

I would not expect the `BlazorExample.Client` part to work by itself, as parts of the app are in the `BlazorExample` server project as well.
