### ISSUE TITLE
Translate name of business assemblies to short codes

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#442]
Similar to what was done in #435 for `mscorlib` and `Csla` assemblies, it should be possible to do the same thing for business assemblies.

Arbitrarily creating a unique code would be quite challenging (because the code must always be the same for any given assembly, yet unique across the set of assemblies used by an application). I think we can define an assembly-level attribute that can go into `AssemblyInfo.cs` so the developer can tell us the code to be used.

Or perhaps a translation map needs to be created at AppDomain initialization. Actually this might be required, as on a data portal server there'd be no way to ensure that any given assembly has been loaded into memory prior to its being needed - and therefore no way to ensure that an arbitrary code can be translated back into an assembly name.

In any case, then `MobileFormatter` can be enhanced to translate to that code during serialization and from that code during deserialization.

**Comment by JasonBock** [comment]
Could you have a default mapping strategy in place in case the developer doesn't care? For example, look at the EXE's referenced assemblies, and their referenced assemblies, and so on, until you have a complete list, and then just create unique names for them? I can't remember if you can get this list when an app starts up, but it may be worth doing the System.Reflection lookup on how referenced assemblies can be gathered, rather than forcing that on a dev (unless you have to).

**Comment by rockfordlhotka** [comment]
I think the server could dynamically create a list of known assembly names with associated short tokens as the server sees full assembly names come in from clients. The server could provide that dictionary of assembly name/token pairs to clients so in the future the client can use the tokens instead.

This would avoid the developer having to do any mapping by hand, because it would be entirely dynamic. In most cases the server would learn all the business assembly names within the first few data portal calls.

The only non-obvious parts of this is how/when the token dictionary would be returned to clients, and how to globally maintain the token dictionary on the server(s) because this would be server-side state that must be consistent across all app servers in any sort of cluster or farm.

My current train of thought is that the dictionary would be returned only when the client sends a non-tokenized assembly name (because the server then knows that the client is missing the current token list). The dictionary could be placed into `GlobalContext` so it flows to the client 'out of band'. The client-side data portal would then grab the dictionary out of `GlobalContext` and also remove the item from `GlobalContext` so that OOB data doesn't flow back and for to the server on future requests.

In terms of managing the shared server-side state, that's a harder nut to crack and I'm open to suggestions...

**Comment by JasonBock** [comment]
OK, here's my thoughts. I could be way off on this stuff, but ... just think about it :)

When you do deserialization of a type via `MobileFormatter`, keep a running dictionary of assembly names that you've seen before, and map those into unique integers. Put those integers into the `TypeName` property of the `SerializationInfo` to represent the assembly name. Once you have the object serialized, put the dictionary into the stream as well. On deserialization, find the map first, and use that to translate the shortened assembly name into full assembly names.

Here's pseudocode:

    // In AssemblyOne...
    public class CustomName
      : BusinessBase<CustomName> { }

    // In AssemblyTwo...
    public class Data
      : BusinessBase<Data> { }  

    // In AssemblyThree...  
    public class MyBusinessObject
      : BusinessBase<MyBusinessObject>
    {
      public static readonly IPropertyInfo<CustomName> NameOneProperty = 
        RegisterProperty(_ => _.NameOne);
      public CustomName NameOne { get ... set ...}

      public static readonly IPropertyInfo<CustomName> NameTwoProperty = 
        RegisterProperty(_ => _.NameTwo);
      public CustomName NameTwo { get ... set ...}

      public static readonly IPropertyInfo<Data> ValueProperty = 
        RegisterProperty(_ => _.Value);
      public CustomName Value { get ... set ...}
    }

If you'd serialize an instance of `MyBusinessObject`, the assembly name map would look something like this:

1, "AssemblyThree..."
2, "AssemblyOne..."
3, "AssemblyTwo..."

The names of the types in the serialization stream would contain these keys, e.g. "MyBusinessObject, /1".

This should hopefully reduce the size of the stream. You could theoretically do this with the type names as well, which may be helpful with serializing collections of objects.

**Comment by rockfordlhotka** [comment]
I agree, not a bad idea at all. I actually modeled this at one point and the savings are quite good. Almost as good as compression of the stream we already generate - and that's ultimately why I didn't try to implement it - I thought it was more effective/easier to just tell people to use compression.

(what is interesting is that _with_ a change like you are suggesting then compression doesn't do nearly so much, because the vast majority of the compression benefit seems to be du-duping repeat values in the byte stream)

So yeah, this is a really good idea - though I still think we can save even _more_ by just having developers put an assembly attribute in `PropertyInfo.cs` to give us a known key value.

Maybe do both? If they give us a key value use that, otherwise put the assembly name into a dictionary and use a generated key value?

**Comment by rockfordlhotka** [comment]
One comment on your thought - the scope of that dictionary has to be a single object graph's serialization. You can't guarantee the order in which any given client or server would encounter the various assemblies, so in a global sense you can't end up with a consistent master dictionary. But within the context of a single serialization operation you absolutely can generate a consistent dictionary.

**Comment by JasonBock** [comment]
I'm not necessarily thinking of a global master dictionary. Just the types and assemblies that are seen from the root object given in the `Serialize` call.

If you can auto-gen keys for each assembly name I don't see a need for a custom attribute to name the assembly.

I think we should talk about this in person :)

**Comment by JasonBock** [comment]
Aaaaaaand....work has begun.....

**Comment by rockfordlhotka** [comment]
In working on this @JasonBock found that the existing CSLA reader/writer components already do this work to a large degree, so there's nothing really to be done.
