### ISSUE TITLE
Allow null criteria to flow to nullable parameters

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#446]
I just noticed today that if I have this:

```
private void DataPortal_Fetch(int? id) { ... }
```

Calling the method via `DataPortal.Fetch(22)` will work, but if I call it with a value that's null, it fails. The simple fix is to make the criteria a `SingleCriteria` of that nullable type, but a dev won't know about this until it's run.

So....let's make an analyzer! It would look at any DP operation's parameter types, and if any are nullable types, flag it as a warning (I think an error would be too harsh, but I'm willing to listen to opinions on this). I could also offer a code fix to make that type a `SingleCriteria` as well. So the code fix would make my code sample into this:

```
private void DataPortal_Fetch(SingleCriteria<int?> id) { ... }
```

If I change the implementation such that it uses `id.Value` instead of `id` that would be really cool too (at least I think it would be).

Thoughts?

**Comment by rockfordlhotka** [comment]
I think having this as a warning is a good idea.

**Comment by tfreitasleal** [comment]
If I define a nullable type as a method parameter, it's because I  expect that sooner or later I will have to pass the method the value null. And it won't work. This is a problem that is hidden and only shows up on runtime.

The resulting issue is quite serious and the problem is well hidden. So I think we should use every availble mean to prevent the problem before it happens. Thus I think it should be flagged as an Error.

**Comment by JasonBock** [comment]
As a side note I wonder if this is really a bug in CSLA itself that should be addressed. I agree with @tfreitasleal in that, if I have an operation with an argument that is a nullable type, passing `null` should be a valid option. I wonder what CSLA does with a `null` value being passed to an argument of **any** reference type....

**Comment by JasonBock** [comment]
@rockfordlhotka will confirm if this still an issue with the latest bits of CSLA.

**Comment by rockfordlhotka** [comment]
Need to add some nullable parameter tests here:
https://github.com/MarimerLLC/csla/blob/master/Source/csla.netcore.test/DataPortal/ServiceProviderMethodCallerTests.cs

**Comment by rockfordlhotka** [comment]
@JasonBock no need for an analyzer. I enhanced the data portal to flow a `null` parameter value through to the server so it can be matched to a nullable parameter in a target method. So this work:

```c#
var obj = await DataPortal.CreateAsync<foo>(null);
```

against a type `foo` with this method:

```c#
[Create]
private void Create(int? c)
{ }
```

This'll go in with the #1228 PR.
