### ISSUE TITLE
Analyzer: Catch When Save() is Called on Itself 

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#458]
Doing something like this:

    public class x : BusinessBase<x>
    {
      public void Foo()
      {
        Save();
      }
    }

Doesn't seem right. If you try to save yourself, how can you assign the return value to `this`?

As @rockfordlhotka said here (https://github.com/MarimerLLC/cslaforum/issues/63), this will be an error. This may only make sense IF that value was returned from the method call. That may be somewhat tricky to do - I'll have to see if I can figure that out from the syntax tree. I may be restrictive here to say that if you call `Save()` or `SaveAsync()` on a BO within that same BO, and the method that it exists in is `void`, then flag it as an error.

**Comment by JasonBock** [comment]
@rockfordlhotka any reason this is still open? It's in the CSLA build.

**Comment by rockfordlhotka** [comment]
Should be closed then.
