### ISSUE TITLE
WcfProxy fails on Android

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#484]
```
"System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: 
Error in deserializing body of request message for operation 'Fetch'. OperationFormatter encountered an invalid Message body. 
Expected to find node type 'Element' with name 'Fetch' and namespace 'http://ws.lhotka.net/WcfDataPortal'. 
Found node type 'Element' with name 'FetchAsync' and namespace 'http://ws.lhotka.net/WcfDataPortal' 

(Fault Detail is equal to Error in deserializing body of request message for operation 'Fetch'. 
OperationFormatter encountered an invalid Message body. 
Expected to find node type 'Element' with name 'Fetch' and namespace 'http://ws.lhotka.net/WcfDataPortal'. 
Found node type 'Element' with name 'FetchAsync' and namespace 'http://ws.lhotka.net/WcfDataPortal')."

```

**Comment by ajj7060** [comment]
I wouldn't mind taking this up.  Is there some documentation on how to generate the proxy?  We're looking to use the Wcf proxy for android and ios, so getting this back for Android would be helpful to us.

**Comment by rockfordlhotka** [comment]
I'm happy to have help with this!

Master is currently 4.6.600 - and I think I'll start doing pre-releases next week on that branch. I'd prefer you work in master.

In terms of creating the proxy, the steps are relatively straightforward, but require a little care.

1. Stand up an app server that hosts the data portal endpoint you intend to use (not from a business object perspective - just from the perspective of whether you configure it for mobile or full WCF)
1. Open the Android CSLA project in Visual Studio (probably the whole csla.net.sln so it builds right)
1. Use the add service reference capability of VS to add a reference to your app server's WCF endpoint in the Android project (make sure to name it the same as the service references in the Csla.Net4 project(s))
1. Find all the #if directives that block the use of the WCF proxy in the Android codebase
1. The resulting code _should_ then build, because those #if directives where required because the WCF service reference wasn't present

**Comment by rockfordlhotka** [comment]
@ajj7060 I don't think I have a contributor agreement from you? I'd need that as well.

**Comment by ajj7060** [comment]
@rockfordlhotka Ok, I'll clear it with my employer and then get it back to you.  No way to fill out the form electronically?! :-)  Is it ok if I take a picture of the signed paper and send that?

**Comment by rockfordlhotka** [comment]
Yes a picture is fine - or you can use the Office Lens app to scan it with your phone (one of my favorite apps!).

**Comment by ajj7060** [comment]
@rockfordlhotka Ah, I have a Windows phone and I forget about that app (don't have many opportunities to use it).  I'll hopefully get you the form today.

**Comment by ajj7060** [comment]
Well, I think I might be missing something, because I don't seem to be able to get this working.  I can add Web Reference and it looks like it works fine, but it doesn't generate the IWcfPortal, IWcfPortalChannel, or WcfPortalClient classes.  I've tried generating the code with svcutil, but that actually seems to come out worse somehow.

**Comment by ajj7060** [comment]
I've tried several different things, and nothing seemed to work, including copying the Reference.cs and related files from the iOS project.

**Comment by rockfordlhotka** [comment]
I didn't think the iOS project had a working WcfProxy at this time?

I think this is unlikely, but maybe Xamarin doesn't have a working WCF implementation for Android?

Or maybe you need to ask on a Xamarin forum about what's going on?

**Comment by ajj7060** [comment]
Well the iOS Csla assembly leaves WcfProxy available in the DataPortalClient namespace, so I guess I was assuming it was working.  That's actually my next task, to get it setup in our project so I guess I'll find out :-)

**Comment by rockfordlhotka** [comment]
Fyi, that is issue #474

**Comment by dazinator** [comment]
I wonder if the fact that WCF is now available for `netstandard` changes anything? https://github.com/dotnet/wcf

I know that not all types of bindings are supported yet.

**Comment by rockfordlhotka** [comment]
It might, hadn't thought about that. I haven't had time to try WCF from the NS2.0 `Csla.dll` yet - so many moving parts these days, it is hard for me to get to all of them.
