### ISSUE TITLE
Token authentication in Web API project with CSLA Principal and Identity

### ISSUE THREAD

**Issue by josemyvision** [MarimerLLC/csla#489]
I'm sorry if this isn't the right place to ask but, where can I find an example of how to implement token authentication in a Web API project that uses Principal and Identity objects inheriting from CslaPrincipal and CslaIdentityBase?

I'm starting to read about this and I'm concerned about how this affect the authorization rules in the business objects.

**Comment by rockfordlhotka** [comment]
I think the MyVote project does this: https://github.com/Magenic/MyVote

I do know that you need a library to work with the token. For example, Magenic has a JWT token library: https://github.com/Magenic/JWTvalidator

**Comment by rockfordlhotka** [comment]
In terms of the 'right place to ask' - the forum repo is a better place for general discussion.
https://github.com/MarimerLLC/cslaforum
