### ISSUE TITLE
Investigate having CslaPrincipal subclass ClaimsPrincipal

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#496]
As per this discussion: https://github.com/MarimerLLC/cslaforum/issues/91

The two major considerations I can see right now are whether `ClaimsPrincipal`/`ClaimsIdentity` exists across all the platforms supported by CSLA, and whether it will be possible to implement `IMobileObject` over the Microsoft types.

**Comment by dazinator** [comment]
There is a [NuGet](https://www.nuget.org/packages/System.Security.Claims/) package for claims, which supports netstandard 1.3 and most platforms, however for full .NET it requires .NET 4.6.

Prior to .net 4.6, the claims types appear to be in mscorlib - for example for .net 452: // C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll

> whether ClaimsPrincipal/ClaimsIdentity exists across all the platforms supported by CSLA

Based on the above, a quick glance suggests that they do, but you would have to ensure that when compiling for .net 4.5.2 and below, it references mscorelib, where as the other platforms I think could all reference the NuGet package.

I did see you had some work around `netstandard`, perhaps it's best to revisit this once things are moved over to netstandard - depending on what your plans are.

**Comment by rockfordlhotka** [comment]
The solution I've settled on is to do the following:

1. Implement `Csla.Security.CslaClaimsPrincipal` as a simple wrapper around the normal `ClaimsPrincipal` so it implements `IMobileObject` (otherwise it can't be serialized via `MobileFormatter`).
1. Add special case code to `MobileFormatter` to handle the new `CslaClaimsPrincipal` type; necessary because deserialization must be handled via the constructor, it isn't possible to create the object then initialize, it must be created by passing in a binary stream to the ctor.

The result of this work is that anyone needing to use `ClaimsPrincipal` and CSLA can use `CslaClaimsPrincipal` and it should work universally.

**Comment by dazinator** [comment]
> The result of this work is that anyone needing to use ClaimsPrincipal and CSLA can use CslaClaimsPrincipal and it should work universally.

Great i'll give this a go!
