### ISSUE TITLE
Analyzer project is causing build to fail

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#510]
You can see details here:

https://ci.appveyor.com/project/rockfordlhotka/csla/build/4.6.83

**Comment by JasonBock** [comment]
Is it failing, or just producing a bunch of warnings?

**Comment by JasonBock** [comment]
OK, I dl'ed the log, it is an error:

[00:00:36] CSC : error AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.FixAnalyzers.CSharpFixerWithFixAllAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.FixAn
[00:00:36] alyzers.FixerWithFixAllAnalyzer`1' threw an exception.'. [C:\projects\csla\Source\Csla.Analyzers\Csla.Analyzers\Csla.Analyzers.csproj]

But this is an error with the analyzer referenced in the analyzer project, not the analyzer itself. This wasn't failing before, and I haven't made any changes in a while.

....

Did you change something with the build?

**Comment by JasonBock** [comment]
Talked to @rockfordlhotka about this last night, and we agreed the best approach right now is for @rockfordlhotka to talk to AppVeyor and see what the issue is, as this doesn't seem related to the analyzer project in any way.

**Comment by rockfordlhotka** [comment]
Appveyor thread: http://help.appveyor.com/discussions/problems/3756-build-failing-did-appveyor-change

**Comment by rockfordlhotka** [comment]
I was able to cause a failure on my dev workstation by re-cloning the repo to a clean directory structure. This leads me to believe the issue is probably due to some missing NuGet package that is (now) required by the analyzer project.

**Comment by rockfordlhotka** [comment]
Looks like a NuGet package update is needed: https://github.com/dotnet/roslyn/issues/7276
