### ISSUE TITLE
Provide Overloads for RegisterProperty to Make Default Value Initialization Easier

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#511]
Right now, if you want to set a default value in `RegisterProperty()`, the only overloads where you provide a default value force you to provide a friendly name, a lambda expression, and/or a relationship type (and I may be missing others). What I'd like is an overload where the property name is given along with the default value, and that's it, something like this:

```
public static readonly PropertyInfo<int> DataProperty = RegisterProperty(_ => _.Data, 22);
```

**Comment by rob-v** [comment]
PR #717
