### ISSUE TITLE
EF7 Support

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#518]
EF 7 RC 1 is released, I can see CSLA has support for EF 4,5 & 6 - is now a good time to consider adding EF7 support?

**Comment by dazinator** [comment]
I have just started work on a PR, will submit shortly.

**Comment by rockfordlhotka** [comment]
I suspect this new project will need to be a net46+dnxcore50 PCL so it supports full .NET and .NET Core.

**Comment by dazinator** [comment]
I'll check if EF7 is usable from a PCL project..

**Comment by dazinator** [comment]
Doesn't look like EF7 is compatible with DNX Core yet. Adding the NuGet package to such a PCL profile yields failure and many messages about: "some packages are not compatible with DnxCore, Version=v5.0."

Also issues like [this](https://github.com/aspnet/EntityFramework/issues/2336) seem to indicate the guidance for new ASP.NET projects that use EF7 is to comment out the DNX Core target from project.json

**Comment by jonnybee** [comment]
My biggest concern with EF7 RC1 is that it is very slow - even slower than EF6 - and has a lot of bugs. Looking forward to RC2 tho...

**Comment by dazinator** [comment]
@rockfordlhotka - I have a PR based on the shared project approach and a .NET 4.6 project. However would you prefer I move this to a PCL library, that just targets .NET 4.6 for the time being, until EF7 later supports DNX Core?

**Comment by rockfordlhotka** [comment]
No, we can make that change if/when it is necessary.

**Comment by dazinator** [comment]
Waiting on resolution of issue #521 - as this might inform the way forward with this a bit more.

**Comment by rockfordlhotka** [comment]
Something is causing this project to not flow through to the nuget output. I suspect the release mode output directory is not correct, so the assemblies don't end up in the same folder structure as all other projects - and so the nuspec doesn't find them to build the nuget package.
