### ISSUE TITLE
CSLA .NET 4.6, ASP.NET Core and IServiceProvider

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#521]
ASP.NET 5 provides two instances of a DI container (`IServiceProvider`)

- HttpContext.RequestServices
- HttpContext.ApplicationServices

RequestServices is created at the start of a request, and disposed of at the end.
ApplictionServices is created on app startup and remains for the duration of the application.

Within an ASP.NET application there is a `Startup` class where developers typically configure their services.

For example:

````
 public class Startup
    {        

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
        }    
    }
```
Those are extension methods being called, that make the service registration a bit easier. Services are actually registered with a lifetime (singleton, transient, scoped etc)

However, non ASP.NET applications could do something like:

```
 /// <summary>
    /// Application
    /// </summary>
    public class Program
    {
        public void Main(string[] args)
        {
            // Create service collection
            IServiceCollection services = new ServiceCollection();            

            // Add service descriptor for ICarService
            services.AddTransient<ICarService>(p => new LamborghiniService());            

            // Create a provider
            IServiceProvider provider = services.BuildServiceProvider();

            // Maybe store this IServiceProvider in CSLA Local Context?          
        }
    }
```

I would love if CSLA.NET 4.6 had a way to resolve an appropriate `IServiceProvider`. This would allow use of DI throughout an entire application / architecure.

The example that lead me in this direction would be that the `DbContextManager` for EF7 can resolve an instance of the DbContext as per how the developer configured in Startup.cs.

I can see it could also allow for DI if you use CSLA `ObjectFactory` approach

In fact you could start to configure CSLA services in startup.cs

```
 public class Startup
    {        

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

           services.AddCsla()
                .AddObjectFactory<IBusinessObjectFactory>(MyBusinessObjectFactory)
               // ?
        }    
    }
```

Do you have any thoughts / feelings around this type of thing?

**Comment by rockfordlhotka** [comment]
I have intentionally avoided binding CSLA to any specific IoC container framework. I know a lot of people like AutoFac, others use Unity, etc.

If CSLA binds to a specific framework then everyone using CSLA ends up with that dependency, even if they are already using (or prefer to use) another framework.

**Comment by rockfordlhotka** [comment]
@JasonBock: any thoughts on how or if we should handle this?

**Comment by dazinator** [comment]
@rockfordlhotka - Understood, although Microsoft have designed this to be used with your IoC container of choice, so if you want to you can still plug in Ninject, Autofac as your actual container implementation and it will override the default. I think this is more about allowing DI to be used throughout the codebase, by abstracting away from a particular implementation via this common `IServiceProvider` milarky..

**Comment by JasonBock** [comment]
I definitely do NOT want CSLA to ever take a dependency on a specific IoC. I like Autofac, and I would not be happy if I couldn't use that in CSLA.

There are ways to do DI in CSLA as I explain in this article: http://magenic.com/Blog/Post/43/Abstractions-in-CSLA. Side note: there are some things in there that I'd like to do differently (e.g. keep the scope out of the BOs) but this should be a start.

CSLA _could_ create an interface like what WebApi does and then an adapter could be created for the IoC of choice. But being able to create your own DataPortalActivator that knows about your container is good enough IMO, plus it's a reasonable choice for the composition root and it keeps knowledge of the container away from anyone else.

**Comment by rockfordlhotka** [comment]
If Microsoft is going to universally define an `IServiceProvider` abstraction in the BCL though, that might allow CSLA to use the _concept_ of IoC in a more direct way without dictating any specific container?

**Comment by dazinator** [comment]
@JasonBock - there is an adaptor for Autofac: http://alexmg.com/autofac-packages-for-visual-studio-2015-and-asp-net-5/

@rockfordlhotka 
>  that might allow CSLA to use the concept of IoC in a more direct way without dictating any specific container?

Yup, that aligns with my understanding!

**Comment by rockfordlhotka** [comment]
The issue I see at this point in time though, is that (if I understand correctly) all this stuff exists only in aspnet5, not in all the other platforms CSLA supports.

So to really go down this road we'd need to define our own IoC abstraction for full .NET, UWP, Xamarin, etc. that exactly mirrors aspnet5.

Basically the same thing we've done by reimplementing `DataAnnotations` on platforms where it doesn't exist.

**Comment by dazinator** [comment]
Oh Yikes, yeah I think you are right. So we'd have to define a common abstraction, for a common abstraction! Or a common abstraction, and our own Adaptor for plugging in `IServiceProvider` on aspnet platforms. 

This approach assumes we can implement a default IoC container on platforms that don't yet support Microsofts. [TinyIoC might be a good option here](https://github.com/grumpydev/TinyIoC) as it won't introduce any additional dependencies (It's source code is distributed via NuGet package so it get's directly compiled within your assembly) - so it means there would be no additional dependencies for anyone.

**Comment by dazinator** [comment]
@JasonBock - nice blog post.

Here are some of my thoughts for a way forward with this.

1. Define a common interface for CSLA to get registered services - i'll call it `ICslaServiceProvider` for now, to avoid confusion with aspnet5's `IServiceProvider`. 

This would look something like: 
```
public interface ICslaServiceProvider
{
   public T GetService<T>();
}
```

2. Expose this `ICslaServiceProvider` via a property: `Csla.ApplicationContext.ServiceProvider`.

3. Initialise `Csla.ApplicationContext.ServiceProvider` with a default implementation, that when used to resolve any services, could simply return null (or throw) because there is no container underlying anything by default.

With this in place, there would be a common mechanism for CSLA to "ask" for a particular service, in a container agnostic manner.

# Initialising a specific container

In your application, it would be a case of doing something like this on startup:

```
// initialise your container..
var container = new WhateverMyContainer();
container.Register<DbContextOptions>(new DbContextOptions())l

// set the csla service provider that knows to go to your container to ask for services..
var cslaServiceProvider = new WhateverMyContainerCslaServiceProvider(container)
Csla.ApplicationConext.ServiceProvider = cslaServiceProvider;

```

For an asp.net 5 / ef 7 application, you could bridge to Microsofts DI container by implementing one like this
```
public class CslaServiceProvider : ICslaServiceProvider
{
   public T GetService<T>()
{
  return CallContextServiceLocator.Locator.ServiceProvider.GetService<T>()
}
}
```

and then in startup.cs:

```
Csla.ApplicationConext.ServiceProvider = new CslaServiceProvider();

```

# Where would it be used?
Anywhere where CSLA creates an instance of a class where it might be nice to allow the use DI - typically business classes i'm guessing, and perhaps other places like within `DbContextManager` - CSLA could now "resolve" necessary constructor arguments for the instance it was creating, using the `Csla.ApplicationConext.ServiceProvider`.

## implications for DbContextManager ?

My understanding of DbContextManager is that it exists as a form of lifetime management for a `DbContext` - to allow the same instance to be re-used during nested data portal calls.

However, I know that many DI containers can manage lifetimes of object instances. So if you were injecting the `DbContext` directly into your business objects / object factories instead, and the container was managing its lifetime, then `DbContextManager` wouldn't be needed? However I appreciate you may not want to force the DI approach on people - so most likely `DbContextManager` would still remain useful in that scenario.

**Comment by dazinator** [comment]
@JasonBock 
> But being able to create your own DataPortalActivator that knows about your container is good enough IMO, plus it's a reasonable choice for the composition root and it keeps knowledge of the container away from anyone else.

Yeah I see what you are saying and agree to an extent, until you also want to allow the use of DI in other places - like on the DbContext that's created by DbContextManager. With this way, you can allow the use of DI anywhere you'd like in CSLA without having to ask the consumer to implement any more hooks / extension points.

**Comment by jonnybee** [comment]
Hi,

This is already available and has been for a long time!! 

But - it is called ObjectFactory approach and moves all data access out of the business object abd into a separate layer where you you can use whatever DI container you want to use. The key factor is to inherit from  ObjectFactoryLoader and use whichever DI container of you choice to build up tha data access layer. 

Seems like you are propsing a lot of bloat in CSLA to support this in the encapsulated invoke pattern where CSLA is responsible for the creation of objects in the DataPortal. 

There is also ways of injecting a DI container into the business layer and use property injection in the BOs.

As Rocky said - it has been key to keep CSLA without a dependency to a specific DI container.

**Comment by jonnybee** [comment]
And as for ContextManager it is a lifetime container. It keeps the DbContext so that you do do not have to pass the instance as a parameter to all children and controls the lifetime of the context object. 

To me - ContextManager and IoC containers are both lifetime containers and should be considered mutually exclusive. You use either - not both!

**Comment by dazinator** [comment]
Im aware of the object factory approach and injectable base classes! That doesnt solve allowing DbContext manager to use DI when it creates DbContexts though. So lets create another interface that consumers must implement to allow DI in that instance? We could go onwards in that direction whenever we come to a situation in which it might be nice to support DI, we can create an interface / extensibility point of some kind that people can use to take control of object instanciaton. This is what csla has done historically and it has workd, but it does mean each time you come accross a new situation for DI you have to add this extensibility point, and CSLA usere have more code to write to plugin their container at that location. This about having a central location in csla to bridge to your container of choice without having to implement all the other extensibility points for each scenario

Nothing about the suggestion ties CSLA to any container so rest easy on that front.

The bloat was adding one property, that provides a way for CSLA to resolve a type when it needs to perform DI on something. People can set that to plugin in their container of choice including the new aspnet 5 stuff.

So to respond.. this is more about bringing in DI more formally into the framework, rather than providing hooks in different places for people to achieve DI (ObjectFactory, IDataPortalActivator) , people could instead set this property and CSLA could resolve types from their container by default in all locations where allowing DI would be desirable. This should mean having to write less code to achieve DI in your own code base to get DI going with CSLA.

**Comment by dazinator** [comment]
I'll put this together in a branch to get some more feedback on something more concrete.

**Comment by rockfordlhotka** [comment]
Should be covered by #525

**Comment by dazinator** [comment]
As an update for this issue, `IServiceProvider` (Microsoft.Extensions.DependencyInjection) targets `NETStandard 1.1` which means it is compatible with the following platforms:

- .NET Core
- .NET Framework 4.5 or later
- Universal Windows Platform
- Windows 8
- Windows Phone 8.1
- Mono / Xamarin Platforms
- Mono

It is not available on:

- Windows Phone Silverlight 

I haven't looked at the full list of platforms that CSLA targets but if there is an alignment, then theoretically CSLA could leverage `IServiceProvider` as it's container abstraction.

**Comment by hoangcuongvn** [comment]
In Asp.net Core, I see nearly everything relies on RequestServices and ApplicationServices. To use Csla in Asp.net Core, there should be a way to retrieve those 2 service containers inside Csla context/domain. If not, we have to pass an hook object (i.e HttpContext) in every calls to DataPortal to create/fetch a business object or execute a command. 

I love the dazinator's idea about ApplicationConext.ServiceProvider but that seems impossible if ApplicationContext and DataPortal are still static classes. I cannot figure out how Csla authentication/authorization works in Asp.net Core if ApplicationContext.User is static?

**Comment by dazinator** [comment]
Even though ApplicationContext.User is accessed statically, it's value is held in thread local storage, or http context if httpcontext is available. In other words the User is always local to the current thread or the current http request (csla decides based on whether it thinks it's running within a web application or not). I highly recommend reading Rocky's book if you haven't already.

As of about 6 months ago, I used Csla with asp.net core. To achieve DI, I just implemented the standard hooks csla provides [IDataPortalActivator](https://magenic.com/thinking/abstractions-in-csla) and ObjectFactoryLoader (I was using object factories). I set these up on application startup, and they just wrapped the asp.net core IServiceProvider, which gets configured on startup. That fit my needs. I vaguely remember doing something where I had to check for http request services and resolve from that IServiceProvider if available, else use the application level IServiceProvider.

All you need to do AFAIK to authenticate with CSLA and allow CSLA authorization to work is just set the CSLA ApplicationContext.User property at the point your user logs in. If using Asp.net core cookie authentication, there are hooks you can implement when the cookie is accepted, and the claims identify is restored from the cookie. At this point I remember having to convert from Claims based Principle / Identity to standard one when setting ApplicationContext.User. 

Hope that helps.

**Comment by dazinator** [comment]
and here is an example of an object factory approach that works leverages the new asp.net core DI framework: 

You'd decorate your business object like this:

```csharp

    [ObjectFactory(typeof(IFooFactory))]
    [Serializable]
    public class Foo : BusinessBase<Foo>, IFoo
    {
    }

```

You'd implement an `IObjectFactory` loader like this:

```csharp

    public class ServiceProviderObjectFactoryLoader : IObjectFactoryLoader
    {

        private readonly IServiceProvider _serviceProvider;
        private readonly ConcurrentDictionary<string, Type> _cachedTypes;
      

        public ServiceProviderObjectFactoryLoader(IServiceProvider serviceProvider)
        {
            if (serviceProvider == null)
            {
                throw new ArgumentNullException(nameof(serviceProvider));
            }
            _serviceProvider = serviceProvider;
            _cachedTypes = new ConcurrentDictionary<string, Type>();
        }
      

        public object GetFactory(string factoryName)
        {
            Type type = GetFactoryType(factoryName);
            try
            {
                var serviceProvider = _serviceProvider; //?? _serviceProviderFactory();
                var httpContextAccessor = (IHttpContextAccessor)_serviceProvider.GetService(typeof (IHttpContextAccessor));
                if (httpContextAccessor != null)
                {
                    if (httpContextAccessor.HttpContext != null && httpContextAccessor.HttpContext.RequestServices != null)
                    {
                        serviceProvider = httpContextAccessor.HttpContext.RequestServices;
                    }
                }
                var implementation = serviceProvider.GetRequiredService(type);
                return implementation;
            }
            catch (InvalidOperationException ex)
            {
                throw new ObjectFactoryNotRegisteredException(factoryName, ex);
            }
        }

        public Type GetFactoryType(string factoryName)
        {
            Type type;
            if (_cachedTypes.ContainsKey(factoryName))
            {
                type = _cachedTypes[factoryName];
            }
            else
            {
                type = Type.GetType(factoryName);
                if (type == null)
                {
                    throw new TypeLoadException($"Could not load a type with name: {factoryName}");
                }
                _cachedTypes.AddOrUpdate(factoryName, (a) => type, (a, b) => type);
            }
            return type;
        }

        public void ClearCache()
        {
            _cachedTypes.Clear();
        }

    }

```

The loader will resolve services from the HttpRequest scoped service provider if it's available, with a fallback to application level scope.

Given the above, you could run a simple unit test to see this in action, something like so:

```csharp

       [Fact]
        public void Can_Get_Foo_By_Id()
        {
 var services = new ServiceCollection()
        .AddTransient<IFooFactory, FooFactory>();

 var serviceProvider = services.BuildServiceProvider();
 FactoryDataPortal.FactoryLoader = new ServiceProviderObjectFactoryLoader(serviceProvider);

var fooBusinessObject = Foo.Get(1);

}
```

When it comes to the asp.net core application proper, you will most likely want an extension method to fit in with the asp.net core style of registering services on startup, something like:


```csharp

   public static class ServiceRegistrationExtensions
    {
        public static IServiceCollection ConfigureBusinessLayer(this IServiceCollection services)
        {
            services.AddTransient<IFooFactory, FooFactory>();
             // register any other factories and services etc.
        }
   }

    public static class AppBuilderExtensions
    {
        public static IServiceCollection UseBusinessLayer(this IApplicationBuilder appBuilder)
        {
             Csla.Server.FactoryDataPortal.FactoryLoader = new ServiceProviderObjectFactoryLoader(appBuilder.ApplicationServices);            
        }
   }
```

Which you would then use in your applications `startup.cs` like so:

```csharp

 public class Startup
 {

       public void ConfigureServices(IServiceCollection services)
        {         
            services.ConfigureBusinessLayer();
        }

       public void Configure(IApplicationBuilder app)
        {                 

                app.UseBusinessLayer();   
                app.UseMvc() //etc etc..          
        }

}

```

**Comment by hoangcuongvn** [comment]
@dazinator: I have headache in finding a way to inject the HttpContext into BOs. Your sample code is very clear, it seems that using ServiceProviderObjectFactoryLoader will resolve my problem. Thank you so much.

**Comment by dazinator** [comment]
No problem. Yes the loader will work if you are using the CSLA object factory approach. If you are using object factories and the code I have posted above then you will find you can inject IHttpContextAccessor into your object factories and use that to access the current httpcontext - which of course might be null if using CSLA outside of a web request. If you are not / do not want to use object factories, and you instead want to inject services directly into your CSLA business objects, then you will most likely need to implement your own IDataPortalActivator that would behave similar to the code I posted for the object factory loader. I should really do a blog post about all this stuff for asp.net core, and I will eventually do so. Hope this has helped.
