### ISSUE TITLE
PCL and Templates

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#522]
Added the latest CSLA beta to a new PCL project.

Went to add a new project item - CSLA templates are nowhere to be found!

Even though I do have them installed:

![image](https://cloud.githubusercontent.com/assets/3176632/11752098/788e071c-a035-11e5-9dee-50aa761089c0.png)

Did some googling and found this: https://social.msdn.microsoft.com/Forums/vstudio/en-US/8ecb51d9-a53e-4078-a47f-0195ea98cf6d/create-item-template-for-portable-class-library-pcl?forum=vsx

It appears that you may need to add this new "AppliesTo" bit to the templates so that they show up for PCL projects:

```
 <AppliesTo>CSharp</AppliesTo>
```

**Comment by dazinator** [comment]
I am going to give the above a try and see If I can get them to show up.

**Comment by dazinator** [comment]
No joy - this still didn't fix it. Gonna try a repair on VS. If someone else can replicate this, let me know!

**Comment by rockfordlhotka** [comment]
I haven't done anything to the templates that would/wouldn't make them apply to .NET Core.

Really, the template package should only need to be installed on a computer one time ever, because what it does is install stuff into your Documents folder.

**Comment by rockfordlhotka** [comment]
Really what we _should_ do is consider eliminating the templates package from NuGet and going back to a VSIX model.

The reason being that NuGet 3 started the process of phasing out install scripts - or at least that's my understanding. And without scripting the templates package becomes useless because we rely on scripting to copy the various files into the user's Visual Studio 2015 directory structure.

**Comment by dazinator** [comment]
Yeah I think that probably makes more sense.
in VS2015 I created a new PCL project, and a new Library project. The templates show up for the library project, but not for the PCL project so I do think something might need to be done to the templates to enable them so show up for PCL.

**Comment by dazinator** [comment]
This issue doesn't seem to be just for the CSLA templates. I exported a new Item Template directly from a PCL project, and even this template doesn't show up for PCL projects, but shows up for Library projects. Makes me think this a bug in the VS PCL project system.

**Comment by rockfordlhotka** [comment]
I did report this to Microsoft, so I'm going to close this issue here because I think it is a problem with VS.

**Comment by dazinator** [comment]
Agreed!
