### ISSUE TITLE
unable to debug PT-WinRt sample, ver. 4.6.200 

### ISSUE THREAD

**Issue by AsadCheema** [MarimerLLC/csla#524]
Hi everyone, I download the Csla v.4.6.200, compile it and build ProjectTracker sample. Every thing went OK. So i tried to run PT-WinRT sample, and just stepping on line 

await ProjectTracker.Library.Security.PTPrincipal.LoginAsync("manager", "manager");

in app.xaml.cs file, getting exception 

An exception of type 'System.TypeLoadException' occurred in WinRTUI.exe but was not handled in user code

Additional information: Type 'Csla.ReadOnlyBase`1' in assembly 'Csla, Version=4.6.200.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.

Even i can not step into Csla code.

And in Csla code, Csla.ReadOnlyBase has method with signature

private void OnDeserializedHandler(StreamingContext context)

I don't know what is wrong here.

Regards.

**Comment by rockfordlhotka** [comment]
Can you try running the Windows Forms UI and see if you get the same result?

My guess is that the issue is occurring on the server side, because on the client the code must be using `MobileFormatter`, which wouldn't use the `OnDeserialized` attribute at all.

**Comment by rockfordlhotka** [comment]
btw, the ProjectTracker app uses NuGet to bring in the CSLA packages. So to walk through the actual CSLA code you'd need to set up your VS instance to use the symbolsource server, or remove the NuGet references and replace them with file or project references to your local compiled CSLA.

**Comment by rockfordlhotka** [comment]
I should also check - are you using ProjectTracker from the top-level Samples folder
https://github.com/MarimerLLC/csla/tree/master/Samples/ProjectTracker

Or from the `Samples\NET\cs` folder?

Only the top-level one is current. I haven't yet deleted the old `Samples\NET\cs` one because I'm using it as reference as I update it to current technologies (not just CSLA - but all the other stuff too).

**Comment by AsadCheema** [comment]
yes, i am usinf PT from Samples\Net\cs. And i created a new project, created PT libs in and created WinRT proj referencing my compiled Csla source folder. Even then while debugging, debugger is not jumping in the source code, giving same exception. I am looking into, since my machine does not have LocalDB, and i need to configure aspnetdb/PTracker db in my local Sql server, may be when IIS Express is starting WCF service, some time giving "Remote procedure call failed" exception, but await statement
await ProjectTracker.Library.Security.PTPrincipal.LoginAsync("manager", "manager");
is still giving same exception about OnDeserializedHandler with in incorrect signature.

I will try the root folder PTracker project as well, how it goes.
Regards.

**Comment by AsadCheema** [comment]
ok, attaching PTracker dbs to my local sql-server, that "Remote procedural call failed" exception goes away. But still unable to step into my code, having same exception
{"Type 'Csla.ReadOnlyBase`1' in assembly 'Csla, Version=4.6.200.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.":"Csla.ReadOnlyBase`1"}

regards.

**Comment by AsadCheema** [comment]
I also created WpfUI project in my Test solution, WfpUI is using WcfPortal.svc, and it is working fine, no exception. I can dedug into PTracker classes as well as Csla source code. But for WinRT proj. getting same error
{"Type 'Csla.ReadOnlyBase1' in assembly 'Csla, Version=4.6.200.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.":"Csla.ReadOnlyBase1"}
All these testing is doing on PTracker project under Sample/Net/cs folder.
Regards.

**Comment by rockfordlhotka** [comment]
The sample in Sample/Net/cs is old. I would _expect_ that to fail, because it hasn't been updated to work with current CSLA.
