### ISSUE TITLE
Ensure config settings used by CSLA all work in ASP.NET Core

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#525]
In ASP.NET 5 there is a new configuration system where settings are stored in json files, and are accessed using different classes, not `ConfigurationManager`.

Looking at the code, it looks as though CSLA doesn't provide a way for an `ObjectFactoryLoader` to be configured at present on particular platforms due to no `ConfigurationManager`:

https://github.com/MarimerLLC/csla/blob/d3a2b0707f56b619d6ad46a517a572f3fdeb729d/Source/Csla.Shared/Server/FactoryDataPortal.cs#L40

Sadly, I rely on a custom ObjectFactoryLoader at present in order to achieve DI in my object factories and other things. But it looks as though I won't be able to use it at present in an ASP.NET 5 application because of this issue, unless I create an old style web.config file.

Even if I do this, I don't think it will address the issue on Android / IoS.

For my present scenario (hosting an ASP.NET 5 application under IIS), a web.config file is actually still necessary as its used to configure IIS with the HttpPlatformHandler which will forward traffic through to the ASP.NET 5 Kestrel server. But really, my application is not actually meant to use it for anything, its meant to use the new style configuration system. 

It would be good if CSLA could find away to be agnostic of any concrete configuration system, or at the least, allow things like the `CslaObjectFactoryLoader` to be configured through code so we can still use it on Android / iOS etc?

**Comment by dazinator** [comment]
Edit: I'm talking rubbish - Think I can set it in code after all!

**Comment by rockfordlhotka** [comment]
I think you may be correct though - and I think it is worth looking through the various config settings used by CSLA to make sure they all work in ASP.NET 5.

**Comment by rockfordlhotka** [comment]
Article with useful info: http://developer.telerik.com/featured/new-configuration-model-asp-net-core/

**Comment by Olorin92** [comment]
I know this has just recently been updated, so is it fair to say this is being looked at? We're trying to create an ASP.NET 5 Web API, but finding it difficult due to the change in where configuration is stored (i.e. no more web.config for CSLA to automatically read DB connections out of).

Any recommendations on how to do this?

**Comment by rockfordlhotka** [comment]
.NET Core and ASP.NET Core are my next major priority, yes. However, my focus in terms of config will be entirely around the CSLA .NET config settings, not things like database connection strings.

This is the link to the relevant doc page: https://docs.asp.net/en/latest/migration/configuration.html

**Comment by Olorin92** [comment]
Thanks for the speedy reply. I did see the page you linked earlier. It seems that CSLA tries to read out the DB connection strings using ConfigurationManager or something similar, which obviously fails when using ASP.NET Core.

Have you got any suggested workarounds for this in the time being?

**Comment by rockfordlhotka** [comment]
I assume you are using one of the db connection manager types from Csla.Data? The `GetManager` method has an overload where you can indicate that the string you are passing is not the database name, but rather is the connection string. The idea has always been that if you are using an alternate configuration scheme, this is how you'd pass the connection string to the connection manager.

For the time being, this is the workaround I'd recommend.

**Comment by Olorin92** [comment]
Ah yep, that works! Thanks again for your help!

**Comment by rockfordlhotka** [comment]
This may be the answer: https://www.nuget.org/packages/CoreCompat.System.Configuration/4.2.3-r4

**Comment by rockfordlhotka** [comment]
Some info on .NET Core configuration access: https://blogs.msdn.microsoft.com/fkaduk/2017/02/22/using-strongly-typed-configuration-in-net-core-console-app/
