### ISSUE TITLE
PCL - compilation Issues with 4.6.300.0

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#526]
Have a compilation issue that I haven't been able to solve, i'll list replication steps:

![image](https://cloud.githubusercontent.com/assets/3176632/11896321/5ce48e4e-a57d-11e5-8996-e4af04ec04e2.png)

1. Create a new PCL project  (.net 4.5, asp.net core 5.0, windows 8, xamarin android, ios, ios classic)
2. Create a new ms unit test project (.net 4.5)
3. Add the lastest CSLA Core NuGet package (pre release 4.6.300) to both projects.
4. In the PCL project, create this class:

```
public class ObjectFactoryLoader : IObjectFactoryLoader
    {
        public object GetFactory(string factoryName)
        {

            throw new NotImplementedException();
        }

        public Type GetFactoryType(string factoryName)
        {
            throw new NotImplementedException();
        }
    }
```

5. In the unit tests projects, add a project reference to the PCL project.
6. Add a unit test:

```

 [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {

            Csla.Server.FactoryDataPortal.FactoryLoader = (IObjectFactoryLoader)new ClassLibrary1.ObjectFactoryLoader();

            // var orgFactory = new BusinessObjectFactory<IOrganisation>();
            // var org = orgFactory.Fetch(new SingleCriteria<int>(1));


        }
    }

```

Now try and compile:

![image](https://cloud.githubusercontent.com/assets/3176632/11896347/9a189a12-a57d-11e5-9fde-d1153fb47699.png)

Any ideas?

**Comment by dazinator** [comment]
Have a feeling this may be something to do with bait and switch and missing typeforwarding perhaps? will take a look into that aspect.

**Comment by dazinator** [comment]
To fix, had to remove the reference to the net 4.5 CSLA assembly, from Unit test project, and manually add a reference to the PCL CSLA assembly.

**Comment by dazinator** [comment]
This makes me wonder, can the CSLA nuget package, just add the PCL version of the assembly as a reference to all the supported project types (.net 4.5, android, ios etc), instead of adding the platform specific version?

**Comment by dazinator** [comment]
Referencing the PCL csla assembly from my .net 4.5 project seemed to work for a while, until I started using `CrtieriaBase<T>` which lead to this weird error:

![image](https://cloud.githubusercontent.com/assets/3176632/11899393/7234f5f4-a596-11e5-9d10-39be95b19004.png)

So stuck at this point, i'll wait to see if someone can verify any of these issues.

**Comment by rockfordlhotka** [comment]
The actual PCL assembly won't work - it doesn't contain all the code from the framework, because there are some differences between the platforms that can't be reconciled.

If we want to have people really reference the PCL at runtime then I'll have to restrict the set of supported platform targets to ones that are truly common - which will basically make the PCL useless.

This is why bait-and-switch is so important (and why if we can't get it to work we'll just have to drop the PCL entirely).

**Comment by rockfordlhotka** [comment]
For example, the PCL uses the `NETFX_CORE` compiler directive (so it can build in a way that WinRT/UWP targets are valid), which means that it includes some implementation code that is totally incompatible with full .NET (I suspect that includes the `OnDeserialized` method).

It also has the code for setting the culture and UI culture totally removed, because there is not a common way to set those values that includes .NET 4 or 4.5 (or WinRT) along with 4.6 and .NET Core (UWP, etc.).

**Comment by dazinator** [comment]
Ok, understood. We need this bait and switch to work then, but at present it appears the compiler won't resolve types referenced in the PCL assembly to types referenced in the platform specific assembly - atleast thats my best guess as to whats going on based on those replication steps i posted.

I thought when I last read about the bait and switch technique that you had to put typeforwarded attributes in somewhere to get this to work - i'll do some further research if i get any more time

**Comment by dazinator** [comment]
This wasnt the original article I read - but it shows the use of the typeforwardedto attribute when doing bait and switch: http://dotnetbyexample.blogspot.co.uk/2014/05/writing-behaviors-in-pcl-for-windows.html

**Comment by dazinator** [comment]
One reason that the bait and switch approach may not work is if the method signatures do not match exactly. Given what you have said above, I think its likely that the `NETFX_CORE` compiled assembly has different method signatures to the `.NET 4` or `4.5` versions of the assembly - leading to this situation where bait and switch doesn't work - as the runtime is can't find a compatible method signature.. The error message specifically mentions the `OnDeserializedHandler` causing an issue.

Not sure of a solution for this..

**Comment by rockfordlhotka** [comment]
What is strange is that the code we're talking about is not platform-specific:

```csharp
    [OnDeserialized]
    private void OnDeserializedHandler(StreamingContext context)
```

I think this is the code in question, and it is the same on every platform, including the PCL.

**Comment by rockfordlhotka** [comment]
It might be as simple as inconsistent implementations. Looking through the code I see a lot of inconsistency in the use of compiler directives around deserialization. I'm doing some cleanup via #527 - perhaps that'll help.
