### ISSUE TITLE
Clean up deserialization handler code

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#527]
Several base classes implement deserialization handler methods, and they are not consistent in terms of compiler directives, etc. Clean up the code and make all implementations consistent.

**Comment by tiitk** [comment]
PCL version does not work.
Handler functions are decorated:
#if !NETFX_CORE || PCL46 || WINDOWS_UWP
    [System.Runtime.Serialization.OnDeserialized]
#endif

but PCL assembly has compilation symbols set:
PCL46;NETFX_CORE
