### ISSUE TITLE
Additional information: Type 'Csla.Core.ExtendedBindingList`1' in assembly 'Csla, Version=4.6.300.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the 

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#535]
hi I added the following class in CSLA dll (4.6.300) and compile it's works for WPF not for Android and WinRT

using System;
using System.ComponentModel;
using Csla.Properties;
using Csla.Core;
using Csla.Serialization.Mobile;

namespace Csla
{

    /// <summary>
    /// This is the base class from which readonly name/value
    /// collections should be derived.
    /// </summary>
    /// <typeparam name="K">Type of the key values.</typeparam>
    /// <typeparam name="V">Type of the values.</typeparam>
  /// <typeparam name="C">Type of the values.</typeparam>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
  [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
  [Serializable]
  public abstract class NameCodeValueListBase<K, C, V> : 
    Core.ReadOnlyBindingList<NameCodeValueListBase<K, C, V>.NameCodeValuePair>, 
    ICloneable, Core.IBusinessObject, Server.IDataPortalTarget
  {

    #region Core Implementation

    /// <summary>
    /// Returns the value corresponding to the
    /// specified key.
    /// </summary>
    /// <param name="key">Key value for which to retrieve a value.</param>
    public V Value(K key)
    {
      foreach (NameCodeValuePair item in this)
        if (item.Key.Equals(key))
          return item.Value;
      return default(V);
    }

    /// <summary>
    /// Returns the code corresponding to the
    /// specified key.
    /// </summary>
    /// <param name="key">Key value for which to retrieve a value.</param>
    public C Code( K key )
    {
      foreach( NameCodeValuePair item in this )
        if( item.Key.Equals( key ) )
          return item.Code;
      return default( C );
    }

    /// <summary>
    /// Returns the key corresponding to the
    /// first occurance of the specified code
    /// in the list.
    /// </summary>
    /// <param name="code">Value for which to retrieve the key.</param>
    public K Key( C code )
    {
      foreach( NameCodeValuePair item in this )
        if( item.Code.Equals( code ) )
          return item.Key;
      return default( K );
    }
    
    /// <summary>
    /// Returns the key corresponding to the
    /// first occurance of the specified value
    /// in the list.
    /// </summary>
    /// <param name="value">Value for which to retrieve the key.</param>
    public K Key(V value)
    {
      foreach (NameCodeValuePair item in this)
        if (item.Value.Equals(value))
          return item.Key;
      return default(K);
    }

    /// <summary>
    /// Gets a value indicating whether the list contains the
    /// specified key.
    /// </summary>
    /// <param name="key">Key value for which to search.</param>
    public bool ContainsKey(K key)
    {
      foreach (NameCodeValuePair item in this)
        if (item.Key.Equals(key))
          return true;
      return false;
    }

    /// <summary>
    /// Gets a code indicating whether the list contains the
    /// specified code.
    /// </summary>
    /// <param name="code">Value for which to search.</param>
    public bool ContainsCode( C code )
    {
      foreach( NameCodeValuePair item in this )
        if( item.Code.Equals( code ) )
          return true;
      return false;
    }
    
    /// <summary>
    /// Gets a value indicating whether the list contains the
    /// specified value.
    /// </summary>
    /// <param name="value">Value for which to search.</param>
    public bool ContainsValue(V value)
    {
      foreach (NameCodeValuePair item in this)
        if (item.Value.Equals(value))
          return true;
      return false;
    }

    /// <summary>
    /// Get the item for the first matching
    /// value in the collection.
    /// </summary>
    /// <param name="value">
    /// Value to search for in the list.
    /// </param>
    /// <returns>Item from the list.</returns>
    public NameCodeValuePair GetItemByValue(V value)
    {

      foreach (NameCodeValuePair item in this)
      {
        if (item != null && item.Value.Equals(value))
        {
          return item;
        }
      }
      return null;

    }

    /// <summary>
    /// Get the item for the first matching
    /// key in the collection.
    /// </summary>
    /// <param name="key">
    /// Key to search for in the list.
    /// </param>
    /// <returns>Item from the list.</returns>
    public NameCodeValuePair GetItemByKey(K key)
    {

      foreach (NameCodeValuePair item in this)
      {
        if (item != null && item.Key.Equals(key))
        {
          return item;
        }
      }
      return null;

    }

    /// <summary>
    /// Get the item for the first matching
    /// key in the collection.
    /// </summary>
    /// <param name="code">
    /// Key to search for in the list.
    /// </param>
    /// <returns>Item from the list.</returns>
    public NameCodeValuePair GetItemByKey( C code )
    {

      foreach( NameCodeValuePair item in this )
      {
        if( item != null && item.Code.Equals( code ) )
        {
          return item;
        }
      }
      return null;

    }

    #endregion

    #region Constructors

    /// <summary>
    /// Creates an instance of the object.
    /// </summary>
    protected NameCodeValueListBase()
    {
      Initialize();
    }

    #endregion

    #region Initialize

    /// <summary>
    /// Override this method to set up event handlers so user
    /// code in a partial class can respond to events raised by
    /// generated code.
    /// </summary>
    protected virtual void Initialize()
    { /* allows subclass to initialize events before any other activity occurs */ }

    #endregion

    #region NameValuePair class

    /// <summary>
    /// Contains a key and value pair.
    /// </summary>
    [Serializable()]
    public class NameCodeValuePair : MobileObject
    {
      private K _key;
      private C _code;
      private V _value;

#if (ANDROID || IOS) || NETFX_CORE
      /// <summary>
      /// Creates an instance of the object.
      /// </summary>
      public NameCodeValuePair()
      { }
#else
            private NameCodeValuePair() { }
#endif

            /// <summary>
            /// The Key or Name value.
            /// </summary>
            public K Key
      {
        get { return _key; }
      }
      
      /// <summary>
      /// The Code or Name value.
      /// </summary>
      public C Code
      {
        get { return _code; }
      }

      /// <summary>
      /// The Value corresponding to the key/name.
      /// </summary>
      public V Value
      {
        get { return _value; }
      }

            /// <summary>
            /// Creates an instance of the object.
            /// </summary>
            /// <param name="key">The key.</param>
            /// <param name="code">The code.</param>
            /// <param name="value">The value.</param>

            public NameCodeValuePair(K key, C code, V value)
      {
        _key = key;
        _code = code;
        _value = value;
      }

      /// <summary>
      /// Returns a string representation of the
      /// value for this item.
      /// </summary>
      public override string ToString()
      {
        return _code.ToString() + ":" + _value.ToString();
      }

      /// <summary>
      /// Override this method to manually get custom field
      /// values from the serialization stream.
      /// </summary>
      /// <param name="info">Serialization info.</param>
      /// <param name="mode">Serialization mode.</param>
      protected override void OnGetState(SerializationInfo info, StateMode mode)
      {
        base.OnGetState(info, mode);
        info.AddValue("NameCodeValuePair._key", _key);
        info.AddValue("NameCodeValuePair._code", _code);
        info.AddValue("NameCodeValuePair._value", _value);
      }

      /// <summary>
      /// Override this method to manually set custom field
      /// values into the serialization stream.
      /// </summary>
      /// <param name="info">Serialization info.</param>
      /// <param name="mode">Serialization mode.</param>
      protected override void OnSetState(SerializationInfo info, StateMode mode)
      {
        base.OnSetState(info, mode);
        _key = info.GetValue<K>("NameCodeValuePair._key");
        _code = info.GetValue<C>("NameCodeValuePair._code");
        _value = info.GetValue<V>("NameCodeValuePair._value");
      }

    }

    #endregion

    #region ICloneable

    object ICloneable.Clone()
    {
      return GetClone();
    }

    /// <summary>
    /// Creates a clone of the object.
    /// </summary>
    /// <returns>A new object containing the exact data of the original object.</returns>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    protected virtual object GetClone()
    {
      return Core.ObjectCloner.Clone(this);
    }

    /// <summary>
    /// Creates a clone of the object.
    /// </summary>
    public NameCodeValueListBase<K, C, V> Clone()
    {
      return (NameCodeValueListBase<K, C, V>)GetClone();
    }

        #endregion

        #region Criteria

        /// <summary>
        /// Default Criteria for retrieving simple
        /// name/value lists.
        /// </summary>
        /// <remarks>
        /// This criteria merely specifies the type of
        /// collection to be retrieved. That type information
        /// is used by the DataPortal to create the correct
        /// type of collection object during data retrieval.
        /// </remarks>
        //[Serializable()]
        //protected class Criteria: CriteriaBase
        //{
        //    /// <summary>
        //    /// Creates an instance of the object.
        //    /// </summary>
        //    /// <param name="collectionType">
        //    /// The <see cref="Type"/> of the business
        //    /// collection class.
        //    /// </param>
        //    public Criteria(Type collectionType)
        //      : base(collectionType)
        //    { }

        //    /// <summary>
        //    /// Creates an instance of the type.
        //    /// </summary>
        //    public Criteria() { }
        //}

        #endregion

        #region Data Access

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "criteria")]
    private void DataPortal_Create(object criteria)
    {
      throw new NotSupportedException(Resources.CreateNotSupportedException);
    }

    /// <summary>
    /// Override this method to allow retrieval of an existing business
    /// object based on data in the database.
    /// </summary>
    /// <param name="criteria">An object containing criteria values to identify the object.</param>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", MessageId = "Member")]
    protected virtual void DataPortal_Fetch(object criteria)
    {
      throw new NotSupportedException(Resources.FetchNotSupportedException);
    }

    private void DataPortal_Update()
    {
      throw new NotSupportedException(Resources.UpdateNotSupportedException);
    }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "criteria")]
    private void DataPortal_Delete(object criteria)
    {
      throw new NotSupportedException(Resources.DeleteNotSupportedException);
    }

    /// <summary>
    /// Called by the server-side DataPortal prior to calling the 
    /// requested DataPortal_XYZ method.
    /// </summary>
    /// <param name="e">The DataPortalContext object passed to the DataPortal.</param>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", MessageId = "Member")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    protected virtual void DataPortal_OnDataPortalInvoke(DataPortalEventArgs e)
    {

    }

    /// <summary>
    /// Called by the server-side DataPortal after calling the 
    /// requested DataPortal_XYZ method.
    /// </summary>
    /// <param name="e">The DataPortalContext object passed to the DataPortal.</param>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", MessageId = "Member")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    protected virtual void DataPortal_OnDataPortalInvokeComplete(DataPortalEventArgs e)
    {

    }

    /// <summary>
    /// Called by the server-side DataPortal if an exception
    /// occurs during data access.
    /// </summary>
    /// <param name="e">The DataPortalContext object passed to the DataPortal.</param>
    /// <param name="ex">The Exception thrown during data access.</param>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", MessageId = "Member")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    protected virtual void DataPortal_OnDataPortalException(DataPortalEventArgs e, Exception ex)
    {

    }

    #endregion

    #region IDataPortalTarget Members

    void Csla.Server.IDataPortalTarget.CheckRules()
    { }

    void Csla.Server.IDataPortalTarget.MarkAsChild()
    { }

    void Csla.Server.IDataPortalTarget.MarkNew()
    { }

    void Csla.Server.IDataPortalTarget.MarkOld()
    { }

    void Csla.Server.IDataPortalTarget.DataPortal_OnDataPortalInvoke(DataPortalEventArgs e)
    {
      this.DataPortal_OnDataPortalInvoke(e);
    }

    void Csla.Server.IDataPortalTarget.DataPortal_OnDataPortalInvokeComplete(DataPortalEventArgs e)
    {
      this.DataPortal_OnDataPortalInvokeComplete(e);
    }

    void Csla.Server.IDataPortalTarget.DataPortal_OnDataPortalException(DataPortalEventArgs e, Exception ex)
    {
      this.DataPortal_OnDataPortalException(e, ex);
    }

    void Csla.Server.IDataPortalTarget.Child_OnDataPortalInvoke(DataPortalEventArgs e)
    { }

    void Csla.Server.IDataPortalTarget.Child_OnDataPortalInvokeComplete(DataPortalEventArgs e)
    { }

    void Csla.Server.IDataPortalTarget.Child_OnDataPortalException(DataPortalEventArgs e, Exception ex)
    { }

    #endregion
  }
}

**Comment by rockfordlhotka** [comment]
This may be related to #526 

However, it is also _critical_ to understand that you can **NEVER** directly reference the PCL assembly, because we are using the bait-and-switch technique where the PCL doesn't contain implementation (or not complete/working implementation) because there is no way to reconcile differences across all the platforms.

You _must_ use NuGet and reference the CSLA packages. If you are creating a PCL that will result in your code using the CSLA PCL _at design time_, but at runtime you'll end up always using the appropriate per-platform CSLA assembly that does have a complete implementation.

As noted above though, #526 may be the problem you are seeing, and I'm still trying to figure out how to reconcile some remaining issues. Any help figuring out answers/solutions is very much appreciated!!

**Comment by SachinPNikam** [comment]
Thank you very much for the reply

**Comment by Nilzor** [comment]
I'm getting the same with CSLA-UWP 4.6.500 on a Win 10 UWP app targeting 10586 . The CSLA reference is in a UWP Class Library project. The error shows when I'm using the designer and added a ListView which binds to CSLA objects.

Is this related - some configuring I can do to fix it, or should I open a separate issue?
