### ISSUE TITLE
Could not load file or assembly '\/c' or one of its dependencies

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#537]
[CSLA 4.6.200]
[WPF UI]

  <add key="CslaDataPortalProxy" value="Csla.DataPortalClient.MobileProxy, Csla" />
<add key="CslaDataPortalUrl" value="http://localhost:11170/WcfMobilePortal.svc" /> --get the result of customers

but same Service not working with following service
 <add key="CslaDataPortalUrl" value="http://t21.gainz.com/WcfMobilePortal.svc" />----we got the error while fetching the customers

**Comment by rockfordlhotka** [comment]
It sounds like your client or server does not have 4.6.200 installed, but is using an older version of `Csla.dll`.

A number of [serialization-related changes](https://github.com/MarimerLLC/csla/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A4.6.200+serialization) were made in 4.6.200, including some that change the format of the byte stream transferred between client and server.

So if the client and server don't have the same version of `Csla.dll` they won't be able to communicate.
