### ISSUE TITLE
4.6 .msi

### ISSUE THREAD

**Issue by attora** [MarimerLLC/csla#538]
Hi,

Why we don't have csla 4.6.3 .MSI!!

**Comment by jonnybee** [comment]
Csla is now only distributed by NuGet.
The MSI installers are deprecated and no longer produced. 

See: https://github.com/MarimerLLC/csla/issues/376

**Comment by jonnybee** [comment]
Leave a comment

**Comment by attora** [comment]
Thanks. I downloded the last package 4.6.3 and try to test the projecttraker but still have a lot of error when I compile a project in visual studio 2012 even I install from nuget, still have error like uknown bxf.dll or unkown projecttraker.library.dll?

**Comment by IndraneelKurane** [comment]
If list of instructions for up and running ProjectTracker is available, it would be quite helpful.
