### ISSUE TITLE
Csla.Xaml.ViewModelBase throws serialization error when save is called if ManageObjectLifetime is true and Model implements INotifyCollectionChanged.

### ISSUE THREAD

**Issue by royog** [MarimerLLC/csla#545]
A bug in **Csla.Xaml.ViewModelBase** exists where if a ViewModel derived from _ViewModelBase_ sets **ManageObjectLifetime** to **true** AND if the Model class that's contained in that ViewModel implements either (or both) _INotifyCollectionChanged_ or _INotifyChildChanged_, then when any of the Save methods are called on the ViewModel, a Serialization error is thrown at line 867 in _ViewModelBase_ (if _SaveAsync()_ is the particular Save method that is invoked):

 867   **savable = (Csla.Core.ISavable)clonable.Clone();**

The serialization error indicates that the ViewModel is not marked as Serializable. But the ViewModel should not and cannot be marked as serializable (it's the Model that needs to be serializable of course).

**The fix is to add the following line at the top of each of the Save methods in ViewModelBase:**

**UnhookChangedEvents(Model);**

The cause of the exception is that in method _ViewModelBase.OnModelChanged(T oldValue, T newValue)_, the method _HookChangedEvents(newValue)_ is called (long before any Save methods are invoked) which finds the underlying Model's _INotifyCollectionChanged_ and _INotifyChildChanged_ implementation and wires those events to the ViewModel. When any Save method is subsequently called on the ViewModel, the implementation in _ViewModelBase_ clones the Model (if ManageObjectLifetime is True), but the _INotifyCollectionChanged_ and _INotifyChildChanged_ events **are still wired up**. Those wired-up events cause the serializer in the  Model.Clone() call attempt to suck in the ViewModel along with the Model's serialized object graph. The _OnModelChanged_ method does automatically unhook these events, but _OnModelChanged_ does not get called **until after** the Save operation completes, which is too late with respect to the Save operations.

If each Save method in ViewModelBase first calls _UnhookChangedEvents(Model)_ **the problem is resolved**. After the Save completes, _OnModelChanged_ is fired and the events get hooked back up again automatically, which is good.

I'm not sure if this would be a side effect or not, but if this fix is implemented, if the Save call on the Model throws an error for any reason, _OnModelChanged_ won't be called, and the _INotifyCollectionChanged_ and _INotifyChildChanged_ events will have been unhooked, so perhaps **_HookChangedEvents(Model)_ should be called in the catch block of the _ViewModelBase_ Save methods as well** so that events are wired back up as they were before the error occurred.

See the _ViewModelBase.DoCancel()_ method as currently implemented ... it unhooks and re-hooks the contained model's ChangedEvents.  Each Save method in _ViewModelBase_ needs to do the same thing basically.

I would **also propose** that both methods _UnhookChangedEvents(T)_ and _HookChangedEvents(T)_ should be changed from **private** to **protected** in _ViewModelBase_. Without this change a ViewModel derived from _ViewModelBase_ cannot itself call these methods because they are not accessible. Right now, even if I were to override the Save methods in my ViewModel (that derives from _ViewModelBase_), my implementation of Save cannot properly unhook those events before the save by simply calling the base class _ViewModelBase.UnhookChangedEvents_ method because of the private accessibility setting in _ViewModelBase_.

Roy Ogborn
Denver, Colorado

**Comment by rockfordlhotka** [comment]
Which platform are you using when you see this - WPF?

**Comment by royog** [comment]
Yes, WPF.

**Comment by tfreitasleal** [comment]
I'm interested on this issue's progress as I will have to replicate the fixes on CslaContrib.Caliburn.Micro.XXX modules.
