### ISSUE TITLE
Alternatives to Csla framework?

### ISSUE THREAD

**Issue by amselem** [MarimerLLC/csla#546]
Hello there

First let me be clear: I'm a fully advocate of Csla.Net and I've been applying it succesfully to my projects. 

However now I'm writing some papers (for management) and I'd like to compare cost and features of Csla vs other similar current frameworks. Can you point me to any modern framework which achieves (fully or partially) the same things than csla (even if it isn't .NET based)? What are "non-cslaers" using as business layer today?

Thank you!

**Comment by rockfordlhotka** [comment]
Please post this in the forum: https://github.com/MarimerLLC/cslaforum
