### ISSUE TITLE
Analyser - CommandBase - and "Csla objects must have public constructor "

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#559]
Was wondering if the code analyser should exclude classes that derive from `CommandBase` in it's "should have a public constructor with no arguments" check?

i.e - isn't the below valid? 

```
      
        [Serializable]
        public class DoSomethingCommand : Csla.CommandBase<DoSomethingCommand>
        {

            private SomeState _something;

            public DoSomethingCommand(SomeState something)
            {
                _something = something;
            }

            protected override void DataPortal_Execute()
            {
                // todo
                base.DataPortal_Execute();
            }

            public static void DoSomething(SomeState somestate)
            {
                Csla.DataPortal.Update(new DoSomethingCommand(somestate));
            }
        }

```

**Comment by JasonBock** [comment]
This may be an exceptional case, but I'd like @rockfordlhotka to chime in before I move on it.

**Comment by rockfordlhotka** [comment]
Scenarios involving `MobileFormatter` always require a default ctor, which is what the analyzer is intended to do - make sure everyone provides a default ctor so deserialization works.

**Comment by dazinator** [comment]
Ah ok. Thought i'd double check, as I thought commandbase might be a special case - obviously not though ;-) thanks for responding!
