### ISSUE TITLE
Bad favicon.ico reference path on Csla.Net4.6 project.

### ISSUE THREAD

**Issue by rxelizondo** [MarimerLLC/csla#561]
Project **Csla.Net4.6** file **CslaPrivate.resx** has **favicon.ico** reference path of:

`..\Csla.Net4.5\Resources\favicon.ico;System.Drawing.Icon.`

The correct reference path (I believe) should be:

`..\Csla.Net4.6\Resources\favicon.ico;System.Drawing.Icon`

Basically, replace **Csla.Net4.5** with **Csla.Net4.6**.

**Comment by rockfordlhotka** [comment]
@rxelizondo does this cause any actual issue? I think I did this on purpose to reuse the existing ico file.
