### ISSUE TITLE
CSLA ProjectTracker Sample Missing DbContext Example

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/csla#562]
I've recently started a new project that is going to target CSLA 4.6.3 (was going to use 4.5.701 but decided to use latest).  Using the CSLA 4 eBooks, I've been able to take my previous knowledge using 3.8 and 4.1 and move the version up.  

However, in previous projects we used LINQ to SQL so EF is completely new to me.  Having said that, the eBook is built off of 4.1 using what appears to be an older EF since its using `ObjectContextManager`.  I've been able to use `ObjectContextManager `with my current EF implementation using the `DalManager` described in the eBook BUT the `IDispose `interface was not implemented.  It was just there and empty.

I tried to implement it today using the example in the book and the differences between `ObjectContextManager` and `DbContextManager` seem to be breaking for me.  By this I mean I can replace `ObjectContextManager` with `DbContextManager` usring `Csla.Data.EF6` but when my 
DalManager hits the `return Activator.CreateInstance(type) as T;` line the code throws the following error: `System.MissingMethodException: Constructor on type 'OLTP.DalEf.OltDbEntities' not found.`

Is there an updated sample project someone can point me to that implements the `DalManager` using `DbContextManager` instead?  I've been stuck here all day so any help is appreciated.  Code available if needed.

Some info that might help:

1. EF Code Generation Strategy is **T4**
2. This was Database First since we already had the tables
3. Looking at the code that is generated by my templates, I do not have any constructors.  There is only `OnModelCreating` which is used to throw an `UnintentionalCodeFirstException`

**Comment by jonnybee** [comment]
I have moved this question to the forum: https://github.com/MarimerLLC/cslaforum 
It is not an issue within the CSLA.NET framework.
