### ISSUE TITLE
Unnecessary png files on Csla.Shared.Resources project.

### ISSUE THREAD

**Issue by rxelizondo** [MarimerLLC/csla#563]
Perhaps I am wrong about this but if you take a look inside folder "Csla.Shared.Resources" you will see three png files:

Error.png
Information.png
Warning.png

I don't think those files belong in that folder, I think png files only belong on UI projects but I may be missing something.

Not a big deal but just though I bring it up.

Thanks.

**Comment by rockfordlhotka** [comment]
The `CSLA.Shared.Resources` directory is just a storage place for some files that are linked into other projects - it isn't directly _part_ of any other projects.

Or, perhaps you are right, and it is a left-over from when I was figuring out what files did and didn't actually work via Shared Projects.

But I do recall that image resources don't work when brought in via a Shared Project - they need to be linked individually on a per-file basis.

**Comment by rxelizondo** [comment]
My source of confusion is that the same png files exists in multiple folders. For example, they exist on the `Csla.Shared.Resources` and `Csla.Xaml.Resources` folders (i did not check other folders).

Should't those png files be shared from a single folder so that things are easier to maintain?

**Comment by rockfordlhotka** [comment]
I agree - but (and my memory is hazy) - I kind of think that file linking didn't work for at least one of the Csla.Xaml project types, so copying the files in was required.

However, I am unwilling to cross-link from one project to another anymore. That's what we were doing prior to my massive cleanup effort last year - and I never want to go through that process again! 😷

**Comment by rxelizondo** [comment]
No problem, I am good with that. This is really just a trivial issue and only brought it up just in case you guys misplaced those files during the cleanup.

Thanks.
