### ISSUE TITLE
Add Interception to the DataPortal

### ISSUE THREAD

**Issue by BrettJaner** [MarimerLLC/csla#564]
Add the ability to plug in a custom implementation of IDataPortalServer into the DataPortal.

**Comment by donnybrasco** [comment]
Is it possible to get samples for this new functionality? I find it difficult getting tutorials on how to use a lot of the new things that have been added in the framework, since the CSLA 4 book came out.

**Comment by BrettJaner** [comment]
If you haven't read the pull request thread yet #547, there is some good stuff there.  I did spin up a quick example found [here](https://github.com/BrettJaner/Csla.ScratchPad).  The implementation has changed slightly since, but the concept is still the same.  I'll update the sample project with the final pull request version as soon as I can.

**Comment by BrettJaner** [comment]
Updated the [example](https://github.com/BrettJaner/Csla.ScratchPad).
