### ISSUE TITLE
Issue with FindSaveAssignmentIssueAnalyzerAddAsyncAssignmentCodeFix and ConfigureAwait

### ISSUE THREAD

**Issue by BrettJaner** [MarimerLLC/csla#567]
When I ConfigureAwait an async business object save, it doesn't seem to pass code analytics.  I get the following error:  Do not ignore the result of SaveAsync().  I remove the ConfigureAwait and it passes.

company = await company.SaveAsync().ConfigureAwait(false);

Also this pops up in VS2015:  'FindSaveAssignmentIssueAnalyzerAddAsyncAssignmentCodeFix' encountered an error and has been disabled.

**Comment by rockfordlhotka** [comment]
Sounds like a scenario we didn't consider. @JasonBock - this one is probably for you :smile:

**Comment by JasonBock** [comment]
Yeah, probably for me (grumble, grumble)

:)

**Comment by JasonBock** [comment]
I think I figured it out....still need to add some tests....

**Comment by JasonBock** [comment]
PR 663 should fix this: https://github.com/MarimerLLC/csla/pull/663
