### ISSUE TITLE
[Idea] - Fody weaving

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#573]
I have recently looked at Fody: https://github.com/Fody/Fody/

I was wondering if there are cases for CSLA where a Fody Weaver could be helpful / desired.

Just to chuck an idea out there (One i really haven;t thought through fully) - how about an "Attribute" based CSLA property system.

For example an auto property like this

```
 [CslaProperty]
 public string Foo { get; set; } 

```

Could be turned by the CSLA fody weaver into this::

```
 public static readonly PropertyInfo<string> FooProperty = RegisterProperty<string>(c => c.Foo);
 public string Foo 
        {
            get { return GetProperty(FooProperty); }
            set { SetProperty(FooProperty, value); }
        }

```

Or rather than an opt in for that (via the attribute) you could "opt out". So these properties on a CSLA class:

```

 public string Foo { get; set; } 

 [CslaPropertyExclude]
 public string Bar { get; set; } 

```

would be processed by a weaver into this:

```

 public static readonly PropertyInfo<string> FooProperty = RegisterProperty<string>(c => c.Foo);
 public string Foo 
        {
            get { return GetProperty(FooProperty); }
            set { SetProperty(FooProperty, value); }
        }

 public string Bar { get; set; } 

```

Just chucking ideas out there..

**Comment by dazinator** [comment]
In terms of loading / setting properties:

You could then set the above properties normally like this:

```
businessObject.Foo = "something";
```

And the Fody Weaver  could perhaps change that into:

```
  LoadProperty<string>(businessObject, businessObject.FooProperty, "something");
```

**Comment by rockfordlhotka** [comment]
I haven't looked at this tool, it sounds like a code generator of some sort?

I wonder if the attribute you suggest could just take a parameter (optional) that allows you to indicate which of the property patterns to use (read-write, readonly, type converter, lazy loaded child, etc.)?

**Comment by dazinator** [comment]
Good decision. Fody doesn't support netcore yet, if it ever adds support for netcore I'll revisit.
