### ISSUE TITLE
Replace `Csla.Reflection.MethodCacheKey` with `System.Reflection.MethodInfo.ToString()`

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#602]
Replace `Csla.Reflection.MethodCacheKey` with `System.Reflection.MethodInfo.ToString()`

**Comment by JasonBock** [comment]
Why not use the metadata value for `MethodInfo`?

**Comment by JasonBock** [comment]
Actually, if you used a structure that uses the assembly, type and method metadata tokens, that should be unique and a lot more efficient than `ToString()`

**Comment by rockfordlhotka** [comment]
This is really a solution in search of a problem, and I'm going to close the issue.
