### ISSUE TITLE
CancelEdit() Appears to be broken on Android.

### ISSUE THREAD

**Issue by BradChase2011** [MarimerLLC/csla#615]
On Android the CancelEdit on the object appears to be broken. I take a simple object and call beginedit, change a decimal value, call CancelEdit(). At this point the object still retains the decimal value. This is happening with all of our objects on Android.

This is using 4.6.400

Here are the stats on the object after begin edit:
Csla.Core.IUndoableObject.EditLevel = 1
EditLevelAdded= 0
FieldManager.EditLevel = 0

Here are the stats on the object after cancel edit:
Csla.Core.IUndoableObject.EditLevel = 0
EditLevelAdded= 0
FieldManager.EditLevel = 0

**Comment by rockfordlhotka** [comment]
Related to this forum post: https://github.com/MarimerLLC/cslaforum/issues/219

**Comment by BradChase2011** [comment]
@rockfordlhotka Have you had a chance to take a look at this?  It still seems broken on mobile.

**Comment by tiitk** [comment]
Are there plans for fixing this? Does not work on netstandard 2.0 UWP neither. Works on android with latest 4.5 but not with 4.6 nor 4.7.

**Comment by rockfordlhotka** [comment]
This issue is no longer valid now that Android support has been rolled into netstandard.
