### ISSUE TITLE
Issue with ValidationContext.MemberName assignment for DataAnnotation rules

### ISSUE THREAD

**Issue by TheSquirrelKing** [MarimerLLC/csla#616]
While creating a custom `ValidationAttribute`-based validation rule, I noticed that CSLA is setting the rule’s `ValidationContext.MemberName` property to the `FriendlyName` value of the property being validated. From `Csla.Rules.CommonRules.DataAnnotation`:

``` C#
    protected override void Execute(RuleContext context)
    {
#if NETFX_CORE
      var ctx = new System.ComponentModel.DataAnnotations.ValidationContext(context.Target);
#else
      var ctx = new System.ComponentModel.DataAnnotations.ValidationContext(context.Target, null, null);
#endif
      if (PrimaryProperty != null)
        ctx.MemberName = PrimaryProperty.FriendlyName;

      System.ComponentModel.DataAnnotations.ValidationResult result = null;
      try
      {
        if (PrimaryProperty != null)
        {
          object value = context.InputPropertyValues[PrimaryProperty];
          result = this.Attribute.GetValidationResult(value, ctx);
        }
        else
        {
          result = this.Attribute.GetValidationResult(null, ctx);
        }
      }
      catch (Exception ex)
      {
        context.AddErrorResult(ex.Message);
      }
      if (result != null)
        context.AddErrorResult(result.ErrorMessage);
    }
```

This behaviour appears to have been added because, for `DataAnnotation` rules, the `BrokenRules` messages were otherwise using the type name of the business object being evaluated instead of the property name being validated (http://www.lhotka.net/cslabugs/edit_bug.aspx?id=755). However, if the name of the property being validated differs from its `FriendlyName`, then any `ValidationAttribute`-based rules that use `ValidationContext.MemberName` will not function as expected, especially if they’re doing something like this in `IsValid`: `validationContext.ObjectType.GetProperty(validationContext.MemberName)`

As such, it seems as though `FriendlyName` should instead be assigned to `ValidationContext.DisplayName`, while `ValidationContext.MemberName` should be set to `RuleContext`’s `OriginPropertyName` value like so:

``` C#
    protected override void Execute(RuleContext context)
    {
#if NETFX_CORE
      var ctx = new System.ComponentModel.DataAnnotations.ValidationContext(context.Target);
#else
      var ctx = new System.ComponentModel.DataAnnotations.ValidationContext(context.Target, null, null);
#endif
      if (PrimaryProperty != null)
        ctx.DisplayName = PrimaryProperty.FriendlyName;

      ctx.MemberName = context.OriginPropertyName;

      System.ComponentModel.DataAnnotations.ValidationResult result = null;
      try
      {
        if (PrimaryProperty != null)
        {
          object value = context.InputPropertyValues[PrimaryProperty];
          result = this.Attribute.GetValidationResult(value, ctx);
        }
        else
        {
          result = this.Attribute.GetValidationResult(null, ctx);
        }
      }
      catch (Exception ex)
      {
        context.AddErrorResult(ex.Message);
      }
      if (result != null)
        context.AddErrorResult(result.ErrorMessage);
    }
```

Has anyone else run into this and/or would like to weigh in?

**Comment by rockfordlhotka** [comment]
Hi @TheSquirrelKing - just running through the backlog and doing some grooming.

Do you have an example of where this is an issue? Basically looking for a repro.

**Comment by rockfordlhotka** [comment]
Might also have some relation to this issue: https://github.com/MarimerLLC/csla/issues/344

**Comment by TheSquirrelKing** [comment]
It's been a while but I believe this was independent of localization and that it could be reproduced by any annotation rule that references RuleContext.MemberName running on a property whose name differs from its FriendlyName. I'm out of the office this week but I can dig into this again when I get back if that helps.
