### ISSUE TITLE
Analyzer possibly incorrectly flagging CSLA0010: argument should be serializable?

### ISSUE THREAD

**Issue by richardbartley** [MarimerLLC/csla#623]
Version 4.6.401

I have Child_Fetch methods taking parameter class objects which have been marked as [Serializable] but the analyzer is warning that this should be serializable.

In my case, the AccountDto class is defined in a separate project/assembly.  Not sure if I've done something wrong, or a real issue.  Either way, it's a minor thing.

```
private void Child_Fetch(AccountDto item)
        {
            Id = item.Id;
            Name = item.Name;
            Tags = item.Tags;
            SortOrder = 999;
        }
```

```
[Serializable]
    public class AccountDto : BaseDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tags { get; set; }
    }
```

BaseDto is [Serializable] too.

Thanks,
Richard.

**Comment by rockfordlhotka** [comment]
I thought @JasonBock put in a fix for this - maybe this is yet another scenario? Or maybe the fix will be in 4.6.500.

**Comment by richardbartley** [comment]
Maybe this is it https://github.com/MarimerLLC/csla/issues/598 and it's targeted for the 4.6.500 milestone as you suggest.

**Comment by rockfordlhotka** [comment]
I don't think so - there was another issue where @JasonBock reimplemented the code to detect the concept of being "serializable".

**Comment by rockfordlhotka** [comment]
@JasonBock: can you double-check that this was fixed? I can't find the issue/PR containing the fix, though I recall you showing me the changed code at some point.

**Comment by JasonBock** [comment]
I'm not getting this issue with the current code. Here's a screen shot:

![image](https://cloud.githubusercontent.com/assets/904213/18749137/13deaf3c-809b-11e6-89db-107abe0944b6.png)

Notice that the only DP operation with arguments getting flagged is the one with the non-serializable type. The one using `AccountDto` isn't flagged with a warning.

**Comment by JasonBock** [comment]
Just to be clear, if the operation was `Child_Fetch` the warning doesn't show up either.

**Comment by toddhughes1** [comment]
Any word on this? I'm using the newest version of CSLA-Core 4.6.500

![image](https://cloud.githubusercontent.com/assets/12050268/20182362/85e21a14-a72f-11e6-9a81-3bb227409095.png)

**Comment by JasonBock** [comment]
So, some rather unfortunate news :(

This won't be fixed until the 2.1 version of the Compiler API. This talks about this issue in detail: dotnet/roslyn#3898

So, until then, there really is no way to fix this problem :( Until then, you can disable the analyzer:

![image](https://cloud.githubusercontent.com/assets/904213/20184683/60885bb8-a71e-11e6-96cf-89202b9b02ec.png)

**Comment by JasonBock** [comment]
Sigh....seems like this fix for Roslyn is never going to get in. Latest update has it targeted for 15.6 or 15.7, but this has languished for over a year now. Ugh :(

**Comment by JasonBock** [comment]
Woot! When 15.7 ships this will finally be fixable :)

**Comment by rockfordlhotka** [comment]
In a .NET Core or ASP.NET Core project the current workaround is to add a GlobalSuppressions.cs file to the root level of the project with this line:

```
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CSLA0010:Find Operation Arguments That Are Not Serializable", Justification = "<Pending>")]
```

**Comment by JasonBock** [comment]
Today may be the day when this **finally** gets fixed .... :)
