### ISSUE TITLE
Consolidate NuGet dependencies

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/csla#645]
Microsoft.Bcl.Build 1.0.4/1.0.14 to 1.0.21
Microsoft.Bcl 1.0.19 to 1.1.10
Microsoft.Bcl.Async 1.0.16 to 1.0.168
System.Collections.Immutable 1.1.36/1.1.37 to 1.2.0
NewtonSoft.Json 6.0.8/8.0.2 to 9.0.1
System.Runtime 4.0.0 to 4.1.0
System.Threading 4.0.0 to 4.0.11

**Comment by rockfordlhotka** [comment]
Is this something you suggest should occur in the upcoming 4.5.600 release?
