### ISSUE TITLE
DataPortal_XYZ methods - plug in a container?

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#647]
I have been using `ObjectFactories` for a while - and it's easy to achieve DI, but as it increases the complexity of the solution quite a bit (in terms of number of classes etc) I was considering not using them for my next project.

So - when **not** using ObjectFactories - and therefore just putting `DataPortal_XYZ` methods directly in business classes, is there any "point of extensivity" I can leverage in CSLA so that I could plug in my container to achieve method injection? i.e I would like for some of the arguments to be injected into the DataPortal_XYZ methods, as opposed to being supplied by the initial `DataPortal.Fetch<>()` args, or having to be resolved within the method itself using a `ServiceLocator`.

I.e I'd like to achieve this:

```

        private void DataPortal_Fetch(int someCriteria, ISomeService someService)
        {         

          var data = someService.GetStuff();        

        }

```

Where `ISomeService` would be injected by me somehow.

As opposed to this:

```

        private void DataPortal_Fetch(int someCriteria)
        {

           var service = ServiceLocator.Current.GetService<ISomeService>();
           var data = someService.GetStuff();          

        }

```

**Comment by rockfordlhotka** [comment]
You can use the provider model I demonstrate in the _Using CSLA 4_ ebook. It isn't a DI scheme, but it is a simple/nice abstraction.

If you want to use an IoC container it is important to remember that the data portal server is stateless, so each client request needs to restore (or create) the IoC container to the thread on which the request is being handled. Current versions of CSLA have hooks in the server-side data portal specifically for this purpose via the `IDataPortalActivator` interface.

https://github.com/MarimerLLC/csla/issues?utf8=%E2%9C%93&q=is%3Aissue%20ioc%20is%3Aclosed%20initializeinstance
