### ISSUE TITLE
Implement ASP.NET Core permission requirement handler

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#649]
As per https://github.com/MarimerLLC/cslaforum/issues/254

**Comment by johntco** [comment]
Would you think that a new Project + Namepsace for "Csla.Web.Http" would be required, so that those HasPermissionAttribute classes can be more directly targeted?

**Comment by johntco** [comment]
![capture](https://cloud.githubusercontent.com/assets/12813917/19196677/11ed5fa6-8c7c-11e6-91cc-014dfc356825.PNG)
