### ISSUE TITLE
Broken wiki link for CSLA Whitepaper

### ISSUE THREAD

**Issue by coverband** [MarimerLLC/csla#654]
http://magenic.com/Resources/WhitePapers/OverviewofCSLA returns a 404.

**Comment by rockfordlhotka** [comment]
They just did a major revamp of the web site, I suspect it got moved or something. I'll check when I get some time. Thanks for the heads-up.

**Comment by jonnybee** [comment]
Check; https://magenic.com/media/1843/magenic-white-paper-overview-of-csla.pdf 

Or just google it:  **csla site:magenic.com**
