### ISSUE TITLE
csla objects can not save into localfolder using Microsoft.Toolkit.Uwp.LocalObjectStorageHelper

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#658]
: Self referencing loop detected for property 'Parent' with type 'e2.SOM.Lib.SalesOrder'. Path 'SalesInvoice

hi want to use Microsoft.Toolkit.Uwp.LocalObjectStorageHelper

```
      e2.SOM.Lib.SalesOrder salesOrder = await e2.SOM.Lib.SalesOrder.GetSalesOrderAsync("122200002421");
```

  var helper = new Microsoft.Toolkit.Uwp.LocalObjectStorageHelper();
      string keyLargeObject = "large";
      if (await helper.FileExistsAsync(keyLargeObject))
      {
        var result = await helper.ReadFileAsync<e2.SOM.Lib.SalesOrder>(keyLargeObject);
      }

```
  // Save complex/large objects 

  await helper.SaveFileAsync(keyLargeObject, salesOrder);
```

**Comment by SachinPNikam** [comment]
An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: Self referencing loop detected for property 'Parent' with type 'e2.SOM.Lib.SalesOrder'. Path 'SalesInvoice'.

**Comment by rockfordlhotka** [comment]
It is not possible to directly serialize a CSLA object. This wiki page has more info: https://github.com/MarimerLLC/csla/wiki/WCF-Services

**Comment by SachinPNikam** [comment]
Thank you so much rocky for valuable reply...!!

**Comment by tfreitasleal** [comment]
Hi Rocky,

The wiki page [https://github.com/MarimerLLC/csla/wiki/WCF-Services](https://github.com/MarimerLLC/csla/wiki/WCF-Services) points to [https://github.com/MarimerLLC/csla/wiki/ObjectsAsServiceContract](https://github.com/MarimerLLC/csla/wiki/ObjectsAsServiceContract) but it seems the later doesn't exist on the wiki.
