### ISSUE TITLE
Custom Principal and Identity

### ISSUE THREAD

**Issue by Brannos1970** [MarimerLLC/csla#659]
I don't know if this is by design or I did something wrong but I thought I would ask. When I access Csla.ApplicationContext.User.Identity or (CustomIdentity)Csla.ApplicationContext.User.Identity the properties of the custom identity are not available. I noticed in one post that they accessed the custom identity properties by entering ((CustomIdentity)Csla.ApplicationContext.User.Identity).CustomProperty. 

Is this by design or some limitation that the Csla.ApplicationContext.User.Identity does not emulate the custom identity?

Could my configuration somehow not telling the system to use the CustomPrincipal and CustomIdentity? I followed the basic set-up as it was in the Project Tracker sample and the extended my custom identity, so I would expect that this should work.

**Comment by fujiiface** [comment]
Have you tried declaring a variable and initializing it to your custom identity, then accessing the property?

```
//Example 1
Csla.ApplicationContext.User.Identity.CustomProperty //Error: you only have access to the IIdentity interface properties here

//Example 2
(CustomIdentity)Csla.ApplicationContext.User.Identity //this is just a type cast

//Example 3
((CustomIdentity)Csla.ApplicationContext.User.Identity).CustomProperty //type casts and makes your CustomIdentity properties available; not sure if this is a good practice but I'm guilty of it sometimes.

//Example 4
CustomIdentity _identity = (CustomIdentity)Csla.ApplicationContext.User.Identity;
_identity.CustomProperty //should work
```

**Comment by fujiiface** [comment]
Also, I assume Csla.ApplicationContext.User.Identity is actually your CustomIdentity type?  If so, you're good.  You have to do something like Example 3 or 4 above to get access to the custom properties since you will only get the IIdentity interface properties by design.  That's a .NET thing, not CSLA.

**Comment by Brannos1970** [comment]
That helps. Coming from VB to C# has been a little frustrating. I am used to certain behaviors and C# and .NET does not have them.
