### ISSUE TITLE
[Question] - Root BO property - dependent upon property in all items of a child list

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#667]
Is anyone able to enlighten me or point me to a sample showing the correct way to implement a parent that has a property, where that property is dependent upon properties within a child list item..

For example, an editable root BO called "Order" that as a child editable list of "OrderLine"'s - I'd like the root order to BO to expose an OrderTotal property which should basically be a calculated value, which will Sum the total of the OrderLines (then minus order level discount etc)

My thinking is the order total property need to be a CSLA property info so that it can raise appropriate change notifications, and so that I can use the business rule system with it (I.E orders below 0 are invalid).

However the property needs to re-calculate each time a dependent property changes on a child item - and its that bit I am not sure what the correct way is to wire that up.

**Comment by rockfordlhotka** [comment]
Please repost this in the cslaforum GitHub rather than this one, which is intended to be work items for the framework itself.

**Comment by dazinator** [comment]
Ah ok - apologies - cheers
