### ISSUE TITLE
Re-add HttpProxy support for Windows Phone 8.1

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/csla#668]
See forum thread: https://github.com/MarimerLLC/cslaforum/issues/275#issuecomment-263359987

**Comment by rockfordlhotka** [comment]
@ajj7060 do you think this remains relevant? 

Starting in 4.6.600 there's no longer any support for WP 8.1, so addressing this issue would require creating a maintenance branch off an older version of CSLA.

**Comment by rockfordlhotka** [comment]
No longer supporting Windows Phone
