### ISSUE TITLE
 JsonConvert.DeserializeObject is not working with CSLA Object JsonConvert.SerializeObject is working

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#669]
hi,
## I have a small query I need to save csla object in to file in any format and retrieve back object from that file . if in case app crashed 

CSLA 4.6.500
UWP 

string SalesOrderObjectFile="SalesOrderObjectFile";
  e2.SOM.Lib.SalesOrder so = await e2.SOM.Lib.SalesOrder.GetSalesOrderAsync("122200016602");
   string json = JsonConvert.SerializeObject(so, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            await helper.SaveFileAsync("SalesOrderObjectFile", json); ==>**Object Save in to File**

            if (await helper.FileExistsAsync(SalesOrderObjectFile))
            {
            var result = await helper.ReadFileAsync<string>(SalesOrderObjectFile);=> # **Object in to string**
                so = JsonConvert.DeserializeObject<e2.SOM.Lib.SalesOrder>(result); ## ==>**Error Point**
             }

while JsonConvert.DeserializeObject I am getting Below error

at Csla.Core.ReadOnlyBindingList`1.InsertItem(Int32 index, C item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.Add(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader,

**Comment by rockfordlhotka** [comment]
Please direct support questions like this to the CSLA .NET forum (https://github.com/MarimerLLC/cslaforum).

**Comment by SachinPNikam** [comment]
Okay Rocky
