### ISSUE TITLE
Best way to handle Authorization Rules that behave differently on different pages?

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/csla#675]
Before I start off, if there is a better forum to see examples / code, please point me to it.

So here's the problem I'm running into...  My authorization rules are basically need to be a bit different for my "Admin" role based on what page they are on.  I'm not sure the best way to do this, reading the HttpContext.Current page seems like an ugly way of doing things in the business layer.

Here is my fictitious example:
Let's say I have a list of "CriminalCases", where once an "Officer" selects a case to work, it becomes assigned to him/her.  In other words, they can Get/Edit the CriminalCase object on their "WorkCases.aspx"

Now, I also have an "Admin" role.  Now this "Admin" is not allowed to edit any CriminalCase entities on this "WorkCases.aspx" page, however in the Admin area, they are able modify certain properties on this CriminalCase entity in the "Admin" page.    **What would be a clean way of handling such a scenario?**  Would love to find more built out example applications if there are any, I just see the following samples when I got the ebook "Dependencies, EncapsulatedInvoke, EncapsulatedInvokeDto, ExceptionInspector, and FactoryImplementation, and Library.NET (Some sort of category / order project"

**Comment by JustinBourlier** [comment]
Basically it's like I need 2 different rules for GetObject, but the framework doesn't support that type of scenario.

**Comment by JustinBourlier** [comment]
Nevermind, I found the area around RuleSets in the documentation, that seems to have worked out for me.

**Comment by dazinator** [comment]
So only certain properties are editable for "Admin" user, where as all properties are editable for the assigned user? 

Not seeing where the page is at all relevant in this, just sounds like it's a decision based on whether the current user has the admin role, or the assigned user id.

I know this probably isn't helpful, and you've found rulesets now anyway.. but I'd definitely try to keep page name out of business layer like you suggested. If you have different rulesets based on current page name that doesn't sound quite right to me. Rulesets were more for multi tenant applications. However whatever works for you is the answer! :-)
