### ISSUE TITLE
4.6.5 ProjectTracker for UWP

### ISSUE THREAD

**Issue by crussi** [MarimerLLC/csla#677]
Hi Guys,
I downloaded the latest 4.6.5 samples and fired up ProjectTracker (found in ... \csla-4.6.500\Samples\ProjectTracker\ProjectTracker.Ui.UWP\).  I'm a little confused, the WPF project seems fully functional, but, the UWP project does not.  For example, there is no login process and the amount of code seems much less when compared to the WPF app.  Am I accessing the incorrect sample?  If I am accessing the right solution AND the UWP project is still a work-in-progress; does anyone have a working sample from which I could learn?  Many thanks!  :-)
Chris

**Comment by rockfordlhotka** [comment]
ProjectTracker for UWP needs to be completed.

**Comment by rockfordlhotka** [comment]
Tracked by #507
