### ISSUE TITLE
VS2015 analyzers CSLA0007 deletes #region directives when auto-fixing managed backing fields

### ISSUE THREAD

**Issue by kmreid** [MarimerLLC/csla#680]
```
#region Properties 

private static readonly PropertyInfo<Guid> MyGuidProperty = RegisterProperty<Guid>(c => c.MyGuid);
...
#endregion
```

becomes:

```
public static readonly PropertyInfo<Guid> MyGuidProperty = RegisterProperty<Guid>(c => c.MyGuid);
...
#endregion
```

giving

"Unexpected preprocessor directive

Unmatched region"

**Comment by jonnybee** [comment]
You are missing the first line of

    #region Properties 

And what the compiler says is that #endregion is an unexepected directive

**Comment by kmreid** [comment]
@jonnybee I think you misunderstand. I have `#region Properties`. When I click on "Fix managed backing field declaration" -> "Document", it changes the managed backing field to public - which is great. What isn't great is that it also deletes the region `#region Properties`. I'm guessing that the regex it is using is searching for the previous '}'.

Not a big deal, I can work around it, but just thought I would point this out.

**Comment by jonnybee** [comment]
@JasonBock is this something you could look into?

**Comment by JasonBock** [comment]
I'm guessing this has to do with how I'm handling trivia before the modifiers - I'll check in a bit.

**Comment by JasonBock** [comment]
Confirmed this is a bug....now....to fix it :)

**Comment by JasonBock** [comment]
OK, once someone like @rockfordlhotka accepts the PR this should be fixed :)
