### ISSUE TITLE
Rule conundrum

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/csla#686]
Really been struggling, used to think I was quick learner!   I need assistance with an authorization rule.
Let me give a basic example
`
class Person
{
     int PersonId;
     int Age;
     Customer customer;
}

class Customer
{
    string Name;
}
`

Now...   let's say I only want the user to edit the Customer's name if they are older than 18, oh and it's very possible that Person.Customer is null.

How would you go about wiring this rule up?  I've tried using a static method, but I get an error around ensureunique rule if I call it more than once.
static Customer GetCustomerByPerson(int personId) {
var person = GetPersonByPersonId(personId);
BusinessRules.AddRule(typeof(Customer), new CustomerAuthorization(AuthorizationActions.WriteProperty, person.Age, _nameProperty);
return person.Customer;
}

I can't add it in the static AddObjectAuthorizationRules() function, because I don't have the person object available.
I can't make it a typeof(Person) rule, because then I can't pass the properties of the Customer object into it.   Simply stumped on  something that on the surface would seem pretty straight forward.

Thanks in advance,
Justin

**Comment by jonnybee** [comment]
There are some limitations to the authorization rule system. 

- There can only be one-1 Authorization rule per Type, AuthorizationAction and MethodInfo/PropertyInfo. 
- The per-property authorization rules must be added in the AddAuthorizationRules method and the per-object authorization rules in AddObjectAuthorizationRules. 

Also remember that CSLA only has per-type rules - there is no support for per-instance rules. IE: you cannot add an authorization rule for only a given instance (which is what it seems you are doing here). You should regard each registered authorization rule as a Singelton and the rule cannot store anything related to a given instance of a business object except for PropertyInfo's..

So you should register the rule in AddAuthorizationRules. THen inside your rule you can use the context.Target to get to the actual object that the rule is running on (Customer). I assume age is a property related to the logged in user so you could either add this property to a custom IPrinipal/IIdentity or use one of the ApplicationContext

**Comment by tfreitasleal** [comment]
Havng only per-type rules is a limitation, but you can force the rule system to re-evaluate the rule on each iteration by make the rule result non-cacheable like this

`public new bool CacheResult
{
    get { return false; }
}`

**Comment by jonnybee** [comment]
This type of questions should be posted on the CslaForum repo. Not in the Csla repo itself. 

So please post this type of questions here: 
https://github.com/MarimerLLC/cslaforum

**Comment by JustinBourlier** [comment]
Sorry if this is a silly question, been overworked and the noodle is a bit cooked, but that link takes me back to the same place.  (Basically the first tab here)  And if I click on "CSLA .NET forum", I land back on issues.

**Comment by jonnybee** [comment]
Follow my link above and select issues. Questions should be posted as issues in the cslaforum repository.

This is noe an issue in the csla repository.

**Comment by JustinBourlier** [comment]
Ohh okay, NOW I see the url is slightly different :).   Thanks.
