### ISSUE TITLE
Look into Principal/User is managed in Windows Forms

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#701]
It appears that the way Windows Forms manages the current principal has changed to be more like WPF.

In other words, what appears to be happening is that the current principal on the UI thread is no longer maintained over time, so ApplicationContext.User becomes incorrect when WinForms (at some point) resets the current principal on the thread.

I am not 100% sure this is what's going on, but at first glance it appears that Microsoft changed the behavior to work more like WPF (which imo is broken).

This probably means that the ApplicationContext provider for Windows Forms needs to be altered to maintain the current principal (the `User` property) in a static field instead of on the current thread.

**Comment by MaceySoftware** [comment]
Just reading through the issue list and spotted this.

I haven't come across this issue myself, is there a certain circumstances that make it occur? I know we are not using the latest version of CSLA, so would that have a knock on effect as to if we could experience the issue?

**Comment by rockfordlhotka** [comment]
I don't have any information. A couple CSLA users reported this issue, and I've been able to confirm it by rebuilding existing WinForms apps in .NET 4.6, so I am convinced it is an issue.

It seems like the behavior of the CurrentPrincipal has changed to match how it is handled in WPF, which basically makes it useless for scenarios where the user logs into the app, rather than relying on the underlying Windows OS login.

Fortunately I know how to solve this within the context of CSLA, because I can use the same solution I did for WPF - which is to store the User property value in a static so it is consistent and global.

**Comment by rockfordlhotka** [comment]
In other words, I don't think it is a CSLA issue as such - I think it is a change in Windows Forms in more recent versions of .NET.

**Comment by MaceySoftware** [comment]
Thanks for the update. 

I will inform the developers here so we know if the issue crops up through the helpdesk.

**Comment by MaceySoftware** [comment]
Sorry to bug you again, you had to rebuild the app to 4.6 to get the issue yeah?

I know sometimes just having the framework installed some features are changed.

**Comment by rockfordlhotka** [comment]
My observation is that I saw the problem after I rebuilt with a newer version of .NET. If you (or others) see something different I'd love to hear about it!

**Comment by MaceySoftware** [comment]
Thanks! 

Will let you know if we encounter any issues, hopefully we won't, might just mean we may not be able to move to 4.6 for a little while longer.

**Comment by rockfordlhotka** [comment]
If it is time sensitive for you, the code to manages the CSLA `User` property is managed by a pluggable provider, so there's an easy workaround that doesn't require modifying CSLA.

**Comment by MaceySoftware** [comment]
I don't think it is. However if there is a workaround it would be nice to know.

**Comment by rockfordlhotka** [comment]
Here's the `ApplicationContextManager` used by WPF (and other XAML platforms):
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Xaml.Shared/ApplicationContextManager.cs

Implement the `IContextManager` code and on app startup tell CSLA to use your custom implementation and you can do anything you'd like.

Basically, the fix for this in CSLA will be to create a comparable class in the Windows Forms support library.

**Comment by MaceySoftware** [comment]
Seems simple enough.

Thanks for your help.

**Comment by rockfordlhotka** [comment]
I have confirmed that this is a real issue - Microsoft changed the way they manage the principal in Windows Forms to match how it works in WPF.

Personally I think this is entirely broken, as it eliminates the use of Windows Forms apps (and WPF apps) in kiosk scenarios where the underlying Windows identity doesn't change between users.

However, it is solvable from a CSLA perspective by changing the framework to use a custom `IContextManager` for Windows Forms just like it does for WPF.

This means that the principal/identity will now be stored in a `static` field (global to the AppDomain) rather than in thread-local storage. 

**This is a breaking change**, but then so was Microsoft's change - so we're kind of stuck.
