### ISSUE TITLE
Microsoft.Threading.Task.dll 1.0.12.0 not found

### ISSUE THREAD

**Issue by ramanbansalfis** [MarimerLLC/csla#702]
Hi, 
I upgraded to CSLa version 4.6.5, and I have Microsoft.Threading.task.dll 1.0.1.65. But now runtime error for Microsoft.Threading.Task.dll 1.0.12 not found coming. Can anyone suggest the solution.

**Comment by rockfordlhotka** [comment]
Are you on .NET 4.0?

**Comment by rockfordlhotka** [comment]
No response from OP, so closing this issue.
