### ISSUE TITLE
Add .editorconfig file for CSLA

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#707]
CSLA loves spaces. I don't. But now that the master for CSLA has been updated for VS2017, I think it's time to put an .editorconfig file at the root that enforces that the code should uses spaces (and 2 at that!). Then I don't have to keep doing the "change my VS settings dance" when I start and stop with adding code for CSLA. There's other settings you can put into .editorconfig but at least put the "spaces" setting in there. That is all :)

**Comment by rockfordlhotka** [comment]
I absolutely think you should do this! 😈

**Comment by JasonBock** [comment]
I think the benevolent dictator that has started this project from day 1 should put those configurations into place ;)
