### ISSUE TITLE
CSLA-Core 4.6.500 Unsigned

### ISSUE THREAD

**Issue by rabidkitten** [MarimerLLC/csla#709]
When referencing the CSLA-Core NuGet packaged in a signed assembly (within a .NET Core project), the following error occurs:

CS8002	Referenced assembly 'Csla, Version=4.6.500.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.			1	Active

This does not happen in my non-.NET core projects.

**Comment by rabidkitten** [comment]
No longer using the CSLA.

**Comment by rockfordlhotka** [comment]
For other's reference, this has been fixed in master and will be in the next release.
