### ISSUE TITLE
Operation Argument Types Should Be Serializable in DataPortal_XYZ Methods in .NET Core

### ISSUE THREAD

**Issue by rabidkitten** [MarimerLLC/csla#711]
Using CSLA-Core v4.6.500 within a .NET Core application, I get the error in the subject line. I do not get this error in a non-.NET Core application.

**Comment by rabidkitten** [comment]
No longer using the CSLA.

**Comment by rockfordlhotka** [comment]
For other's reference, this is a known issue and is tracked in #705
