### ISSUE TITLE
Issue in calling Dataportal_Execute method asynchronusly

### ISSUE THREAD

**Issue by vsinghal7** [MarimerLLC/csla#719]
Hi,

I am trying to call DataPortal_Execute method asynchronously from WebApi. It works perfectly fine if I make it a synchronous call. CSLAApplicationContext is getting changed in a single WCF call if I am calling DataPortal_Execute method asynchronously from WebAPI. 

If I briefly explain the scenario, It would be something like this : There are multiple business object inside a object graph, for some of the BO's CSLAApplicationcontext is behaving as per the expectations, but for some it is not bringing the desired values. So, I am unable to get the desired user identity out of CSLAApplicationContext in case of asynchronous call.

Please comment on this.

Thanks
Vinod

**Comment by rockfordlhotka** [comment]
You should post this question in the forum: https://github.com/MarimerLLC/cslaforum
