### ISSUE TITLE
Loosing CSLA ApplicationContext in Async Calls 

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/csla#721]
We are making async DataPortal Execute Calls and we store user idenity in ApplicationContext.  This identity is getting lost on Dataportal server side. Please suggest how to use ApplicationContext with asynchronous Dataportal calls.

**Comment by rockfordlhotka** [comment]
More people follow the form at https://github.com/marimerllc/cslaforum - you should probably ask this question there.
