### ISSUE TITLE
Add support for PCL Profile259

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#723]
The latest Xamarin PCLs target Profile259 instead of Profile111, and sadly the Profile111 support doesn't extend to Profile259 automatically.

**Comment by rockfordlhotka** [comment]
Moving this out - there's a realistic workaround, which is to change the Xamarin project to target Profile 111.

In fact, the existing Class Library PCL for Xamarin still targets Profile 111 - and they updated only the client app project templates to Profile 259, so even within the context of the Xamarin templates we have to do this reconciliation...

**Comment by dazinator** [comment]
Or... step 1: drop PCL completely in favour of NETStandard.
Step 2: watch the world burn.
Step 3: profit

**Comment by rockfordlhotka** [comment]
I'm going to take @dazinator's (probably not serious) suggestion and close this without implementation.

Given that netstandard 2.0 is available as of today, and given that I no longer have a VS install that has the old Silverlight and Windows Phone SDKs installed (the ones required for profile 259), I think we'll just look to the future :)

**Comment by rockfordlhotka** [comment]
As you can probably see - I changed my mind again and **I did make this change** so there is now direct support for Profile259.

Otherwise it is just a pain for Xamarin developers, because some Xamarin templates create Profile111 and others Profile259 projects, and the workaround was to manually edit the csproj files. Tedious, so this avoids that frustration.
