### ISSUE TITLE
Dependency Property (ResolutionScope.ClientAndServer) Issue in 3-tier

### ISSUE THREAD

**Issue by ashishaon** [MarimerLLC/csla#727]
I have application running on 3-tier and Autoface is being used for IoC.
In a Business Class there is one property marked as dependency with ResolutionScope set as ClientAndServer (hence this property is serializable). While creating this BO, I am getting below exception on ObjectPortal’s Create method.

> Exception thrown: 'System.ServiceModel.CommunicationException' in Csla.dll
> Additional information: An error occurred while receiving the HTTP response to http://localhost/Aon.Arbt.Security.CslaDataPortalv2/SecurityAPI_Portal.svc. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.

After looking at the service log I got below exception details:

> There was an error while trying to serialize parameter http://ws.lhotka.net/WcfDataPortal:CreateResult. The InnerException message was 'The use of type 'Csla.Core.ContextDictionary' as a get-only collection is not supported with NetDataContractSerializer.  Consider marking the type with the CollectionDataContractAttribute attribute or the SerializableAttribute attribute or adding a setter to the property.'.  Please see InnerException for more details.

Please suggest if somebody also encountered such exception.
Thanks

**Comment by rockfordlhotka** [comment]
You should post this in the forum repo to get more input.

https://github.com/MarimerLLC/cslaforum
