### ISSUE TITLE
DbContextManager<C> and DbContext inheritance

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#728]
I have two products which share a common base `DbContext`. The two products are compatible and can co-exist, so it was important for me to have some base tables and classes which they could build upon. Each project inherits from the base `DbContext` and this works exceptionally well.

The only problem I have is when I need to do some data access within a
`using (var ctx = DbContextManager<...>.GetManager(...))`
block in both the inheriting project and the base project.

The inheriting `DbContext` _is a_ `DbContextBase`, but of course the `DbContextManager<C>` doesn't match, so it throws:

```
System.InvalidCastException
Unable to cast object of type
Csla.Data.EF6.DbContextManager<Example.Inherited.DbContext>
to type
Csla.Data.EF6.DbContextManager<Example.Base.DbContextBase>
```

Can you think of a workaround for this?

Kind regards
Michael

**Comment by jonnybee** [comment]
You just use named context to separate these DbContexts by specifying label.

If you do not use label the internals of DbContextManager will use a default ("default") name.  

But won't this also make each context use separate connections and hence require distributed transactions (if you use both connections for updates). 

So use the overload that accepts label and always specify another label name for at lest one of the contexts.  

    public static DbContextManager<C> GetManager()
    {
      return GetManager(string.Empty);
    }
    public static DbContextManager<C> GetManager(string database)
    {
      return GetManager(database, "default", null);
    }
    public static DbContextManager<C> GetManager(string database, string label)
    {
      return GetManager(database, label, null);
    }

**Comment by michaelcsikos** [comment]
I actually want the common core project to use the `DbContext` created by the other project. As far as the common core project is concerned, everything is there that it requires. The inheriting `DbContext` classes just add more tables and relationships to the common tables.

In business classes that inherit from the common generic base classes defined in the common core business library, the inheriting class passes a `DbContextBase` instance through, which works fine. But if it's a concrete class which is being used in the common business library, I'd like to get any live `DbContextBase` which is available in the current context via the `DbContextManager`.

**Comment by jonnybee** [comment]
The issue as such is not with DbContextManager, it is more about casting the inherited instance to  the base DbContext type. 

I have an application with a:
DbContext 
    ==> TrackerContext (non generic) 
             ==> MyContextBase<T> 
                     ==> MyContext 
and there is no exception when casting an instance of MyContext to TrackerContext.

**Comment by michaelcsikos** [comment]
Do you use the `DbContextManager` in this scenario?

**Comment by jonnybee** [comment]
No, I don't. I tried with DbContextManager and it is the generic constraint on DbContextManager that blows up. And it needs the generic constraint to make this safe and do the reference counting. 

Not quite sure how to get around this. I assume you must create your own version of DbContextManager and a new way of handling the reference counting.

**Comment by michaelcsikos** [comment]
OK, I'll have to brainstorm it. Thanks for your input, Jonny.
