### ISSUE TITLE
SafeDataReader, ConnectionManager both not in net core library

### ISSUE THREAD

**Issue by Olorin92** [MarimerLLC/csla#730]
Hi all,

I'm sure there's an obvious answer as to why this is the case, but I noticed when trying to convert our .NET 4.5 DAL and BO classes over to a .NET Core implementation, the CSLA library seems to exclude both SafeDataReader and ConnectionManager.

I've looked into implementing these myself and it seems doable, but was wondering why these were excluded in the first place? I'm assuming there's some compatibility reason that I'm not aware of which explains this.

Alternatively, are there similar classes which are implemented in the .NET Core library? We've got a very old version of CSLA (3.6), so for all I know there might be newer implementations present!

Thanks,

Olorin92

**Comment by rockfordlhotka** [comment]
To my knowledge ADO.NET won't be in .NET Standard until 2.0, so it isn't available today - which is why those data-related types don't exist in .NET Core right now.

**Comment by Olorin92** [comment]
Great thanks for that information, I wasn't aware!
