### ISSUE TITLE
 "SerializationInfo.GetValue: _bindingEdit" error - UWP

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#745]
CSLA 4.6.602

hi 
while calling the commandBase Class Async method I am getting below error
**SerializationInfo.GetValue: _bindingEdit**

"The given key was not present in the dictionary."
ExceptionType    System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Csla.Serialization.Mobile.SerializationInfo.GetValue[T](String name)

**Comment by rockfordlhotka** [comment]
This is an issue @Bowman74 reported late last week too - but neither of us had time to get it into GitHub - so I'm glad you reported it - thank you!
