### ISSUE TITLE
Incorrect Async BusinessRule timeout value comment

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/csla#754]
tl;dr - update the invalid comment in BusinessRuleTest.cs

The `ExecuteRule` summaries in [RuleTutorial.Testing.Common.BusinessRuleTest](https://github.com/MarimerLLC/csla/blob/master/Samples/NET/cs/RuleTutorial/RuleTutorial.Testing.Common/BusinessRuleTest.cs) states that the Async BusinessRule timout should occur after 3 seconds but the timeout value is 30 seconds.

**Comment by jonnybee** [comment]
This sample is rather from my own experience where a test of an asynchronous rule should not take more than 3 seconds. 

The actual timeout in CSLA at runtime could wery well be as high as 30 or 60 seconds.

**Comment by fujiiface** [comment]
I figured as much when I was looking at it.  I wasn't sure if the comment or the code was correct (or maybe both).  In this case, it sounds like it is both.  This can be a little confusing so I propose adding additional wording to the summary stating this explicitly.

**Comment by rockfordlhotka** [comment]
@tfreitasleal is this resolved as part of #763?

**Comment by tfreitasleal** [comment]
No.
