### ISSUE TITLE
Normalize base interfaces between netstandard and Xamarin

### ISSUE THREAD

**Issue by Bowman74** [MarimerLLC/csla#757]
When using business classes in net standard libraries they don't work in some instances.

If an object inherits from BusinessBase and implements an interface that in turn inherits from IBusinessBase, some dataportal methods will fail (tested with calling Create and CreateAsync and Android and iOS Xamarin projects).

The same class and interface in a native library and referenced by the project will work fine. It is only if it is a net standard library (tested with 1.6) where the error will occur. Also removing the interface that inherits from IBusinessBass from the concrete implementation will resolve the issue.

A simple test project to re-create the issue can be found here:

https://github.com/Bowman74/CslaNetStandardBug

The error received is:

System.TypeLoadException: VTable setup of type CSLANetStandardTest.SomeBusinessClass failed
  at Csla.DataPortal`1[T].Create (System.Type objectType, System.Object criteria) [0x00032] in <d7f5b9a1247143dd87364bb686741b63>:0
  at Csla.DataPortal`1[T].Create (System.Object criteria) [0x00000] in <d7f5b9a1247143dd87364bb686741b63>:0
  at Csla.DataPortal.Create[T] (System.Object criteria) [0x00005] in <d7f5b9a1247143dd87364bb686741b63>:0
  at Csla.DataPortal.Create[T] () [0x00000] in <d7f5b9a1247143dd87364bb686741b63>:0
  at CSLANetStandardTest.Droid.MainActivity+<OnCreate>d__1.MoveNext () [0x0008f] in /Users/kevinford/Projects/CSLSNetStandardTest/CSLANetStandardTest.Droid/MainActivity.cs:29
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d855bac285f44dda8a0d8510b679b1e2>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0
  at at (wrapper dynamic-method) System.Object:9e5df153-cbe8-4f06-be5e-a9d05e41f917 (intptr,intptr)

**Comment by JasonBock** [comment]
Since .NET Standard 2.0 was released today let's just use that, it should magically fix this because it's newer, right? :)

**Comment by rockfordlhotka** [comment]
I believe I captured the essence of the sample from @Bowman74 in this .NET Core 2.0 console app:

```c#
using System;
using Csla;

namespace netcore_csla_serialization
{
  class Program
  {
    static void Main(string[] args)
    {
      var obj = Csla.DataPortal.Create<SomeBusinessClass>();
      obj = obj.Clone();
      Console.WriteLine("Hello World!");
      Console.ReadLine();
    }
  }


  [Serializable]
  public class SomeBusinessClass : BusinessBase<SomeBusinessClass>, ISomeBusinessClass
  {

  }

  public interface ISomeBusinessClass : IBusinessBase
  {

  }
}
```

Unfortunately there's no failure creating the object or cloning it, so the failure must be unique to mono and/or Android 😞

**Comment by rockfordlhotka** [comment]
Hmm. This code (basically the same thing) also works in Android:

```c#
using Android.App;
using Android.Widget;
using Android.OS;
using System;
using Csla;

namespace AndroidApp
{
  [Activity(Label = "AndroidApp", MainLauncher = true)]
  public class MainActivity : Activity
  {
    protected override void OnCreate(Bundle savedInstanceState)
    {
      base.OnCreate(savedInstanceState);

      // Set our view from the "main" layout resource
      SetContentView(Resource.Layout.Main);

      var obj = Csla.DataPortal.Create<SomeBusinessClass>();
      obj = obj.Clone();

    }
  }

  [Serializable]
  public class SomeBusinessClass : BusinessBase<SomeBusinessClass>, ISomeBusinessClass
  {

  }

  public interface ISomeBusinessClass : IBusinessBase
  {

  }
}

```

**Comment by Bowman74** [comment]
I found the problem. It has to do with classes that inherit from IReadOnlyBase in a .Net Standard library (probably a PCL too). The version of this interface in the .Net Standard library and the version in the Xamarin iOS/Android projects are not the same. 

If you create a class that inherits from this interface in the .Net Standard library it will be compiled with the version of that interface from the Csla .Net Standard implementation in the nuget package. If you then reference that .Net Standard library from an iOS or Android project (perhaps some other clients) with it getting the iOS/Android version of the interface, the problem will show up. The version of the dataportal in the iOS/Android CSLA app will try and create and instance of that class expecting the IReadOnlyBase to look a certain way but find the very different shape compiled into the .NetStandard library. 

This is why we haven't seen this error since the old interop days. Nuget forces us to use bait and switch and bait and switch requires that the external interfaces look the same.The implementation can be different but the shape of the public interfaces have to be the same.

**Comment by rockfordlhotka** [comment]
From @Bowman74's testing it looks like the changes to `IReadOnlyBase` worked, but other base interfaces have comparable issues and need normalization as well.
