### ISSUE TITLE
Update samples

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/csla#763]
1. Update solutions to VS2017
2. Update projects to NET 4.5
3. Fix analizer errors (leave `SingleCriteria `warnings untouched)
4. Add `ErrorLog.txt` file on solutions with compile time or run time errors
5. Add `How to run.txt` instructions file
6. All samples should NuGet Csla packages
7. Fix `NuGet.config` files so all samples use the same packges folder
8. Leave Silverlight solutions untouched
9. Identify broken samples and ask for help in CslaForum

Plus
- small fixes /enhancements to ProjectTracker, including removing LazyLoad
- add LazyPropeties demo

**Comment by rockfordlhotka** [comment]
@tfreitasleal do you consider this complete now?

**Comment by tfreitasleal** [comment]
No. I'm having some issues creating resources and projects on ProjectTracker. I'm working on it and expect to close very soon.

**Comment by rockfordlhotka** [comment]
No problem!

**Comment by tfreitasleal** [comment]
It's the LazyGetProperty issue. I think I mis-fixed it last time. I'm reverting it and retesting.
