### ISSUE TITLE
ProjectResources bug?

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/csla#775]
Should the linked line of code be a DataPortal_Fetch instead of Child_Fetch?  ProjectEdit.cs is lazy loading  the ProjectResources but ProjectResources.cs does not have a DataPortal_Fetch.

https://github.com/MarimerLLC/csla/blob/a326747904970a85e7de3370e3503f5904c22826/Samples/ProjectTracker/ProjectTracker.BusinessLibrary.Shared/ProjectResources.cs#L52

**Comment by rockfordlhotka** [comment]
@tfreitasleal is working on this and has been changing related code, so he'll know.

**Comment by tfreitasleal** [comment]
After thorough investigation I found out ProjectTracker isn't using LazyLoad to fecth or assign the child collections. It just uses  LazyLoad to replace the create child collection statement that should be done in the root's `DataPortal_Create`
There is a PR at https://github.com/MarimerLLC/csla/pull/774 that removes LazyLoad from ProjectTracker and adds the 
`LoadProperty(ResourcesProperty, DataPortal.CreateChild<ProjectResources>());` declaration in `DataPortal_Create`
It was tested using the local AppServer but after commiting the PR, @rockfordlhotka must update the azure AppServer.

I'm working on a replacemnte project based on https://github.com/tfreitasleal/CslaExtremeDemos/tree/master/LazyProperties but it's a bit rough on the UI side and I'm polishing it. Anyway the LazyLoad logic is correct, on three layers: DAL, BO and UI.

**Comment by rockfordlhotka** [comment]
btw @tfreitasleal, do you want me to accept the current PR and you'll do another for your new sample?

**Comment by tfreitasleal** [comment]
That's the idea.

**Comment by fujiiface** [comment]
Thanks for the update.  I had seen emails going back and forth and updates but thought those were already live when I was looking at the code.  Apologies for the extra issue opened.
