### ISSUE TITLE
How to prevent CSLA for generating Csla.Resources.dll file on deployment?

### ISSUE THREAD

**Issue by itgoran** [MarimerLLC/csla#778]
I'm using CSLA framework with dot net core 2.0.

When I do publish (dotnet publish -c Release -r ...) using Release configuration additional folders (tr, sv, sr) to name few of them, contains Csla.Resources.dll and they are copied in output publish folder ( ~/bin/Release/netcoreapp2.0/centos.7-x64/publish).

How to exclude these folders (with the file) or delete them from publish folder, once when dotnet publish finish executing?

**Note** 
File "Csla.resources.dll" doesn't exist before deploy process start. It will be generated when dotnet publish started.

**Comment by rockfordlhotka** [comment]
The CSLA-Core NuGet package includes all the resource files that localize CSLA itself for quite a few languages. I imagine the `dotnet publish` process must pick up on the fact that they exist, so it creates those folders when you create your project (which depends on CSLA).

I've never tried to suppress that behavior, so I'm not sure how or if it can be suppressed.

Certainly it is the case that the .NET runtime discovers those resources dynamically at runtime. So if you don't want to support anything beyond en-us (the default for CSLA) you should be able to just delete, or not deploy, those language-specific folders and then only the default resources will be discovered at runtime.

**Comment by itgoran** [comment]
Thank you @rockfordlhotka
