### ISSUE TITLE
Update samples to CSLA .NET 4.7.100

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/csla#788]
Update CSLA .NET dependencies.
Make each solution use its own packages folder.

**Comment by rockfordlhotka** [comment]
@tfreitasleal do you want to run through the demos now that I've pushed the latest 4.7.100 pre-release to NuGet? I suspect some may need changing/updating because I split out the netstandard platforms from full .NET as a platform.

**Comment by tfreitasleal** [comment]
I'm on it.
