### ISSUE TITLE
FindSaveAssignmentIssueAnalyzer creating compile errors after upgrading CSLA

### ISSUE THREAD

**Issue by pssewell21** [MarimerLLC/csla#791]
Hello.  We are attempting to upgrade from CSLA 4.5.601 to 4.6.603.  I'm trying to understand what negative effects calling the Save method with assigning the result could have.  We often use the Save method in way similar to this

```C#
var foo = fooFactory.NewFoo(arg1, arg2);
if (foo.IsSavable)
{
    foo.Save();
}
```

In many of our cases like this, we are creating an object that is not necessarily displayed in the UI anywhere, and is saved in the database.  Upgrading has caused a number of compile errors in our product due to changes contained in #421.  Of course, an easy solution for us would be to assign the result of the Save call to a local variable that is never used, but that would be a sloppy solution.  

I do see in the issue discussion that you guys said nobody should ever refrain from using the return value from Save, so do you have any suggestions about what should be done with the returned objects in situations like these?  Thanks for the assistance.

**Comment by GillesBer** [comment]
My understanding is that the expected behavior would be:
```
var foo = fooFactory.NewFoo(arg1, arg2);
if (foo.IsSavable)
{
    foo = foo.Save();
}
```
As using the 'foo' variable after the save is unexpected.
In my uses cases (a rich client application), not handling this correctly is a major source of bug.
And the 'foo' object has visibility on a much wider scope. So this is impossible to guarantee that no code is using it once the Save() method is called.
Gilles

**Comment by pssewell21** [comment]
Thanks for the reply.  We understand that the DataPortal returns a new copy of the object after a save, so if the newly saved object is not assigned to a variable, operations performed on the object which are saved later will fail or at least leave the business object in an unexpected state.  So the following code

```C#
private void CreateRelatedRecord()
{
    var foo = fooFactory.NewFoo(arg1, arg2);
    if (foo.IsSavable)
    {
        foo.Save();
    }

    foo.Property = "newValue";
    foo.Save();
}
```

would instead need to be corrected to do this:

```C#
private void CreateRelatedRecord(arg1, arg2)
{
    var foo = fooFactory.NewFoo(arg1, arg2);
    if (foo.IsSavable)
    {
        foo = foo.Save();
    }

    foo.Property = "newValue";
    foo = foo.Save();
}
```

So since we can see that the foo variable only exists within the scope of CreateRelatedRecord method, what does assigning the output of the same to foo the second time do for us?  Our code quality tool (Resharper) flags this as a value that is unused in any execution path because it isn't used for anything after the second save.  So typically we have not assigned the output of the Save in these situations since we would not use it for anything.  We understand that this protects those using CSLA that may not know that a new object is returned by the DataPortal on a Save from running into behavior they might not expect, but it means that we have a number of code quality issues now.  I would expect to be able to do the following and still have my code compile, but I also understand that it would be difficult or impossible to make the analyzer smart enough to tell when not assigning the result of the save is acceptable.

```C#
private void CreateRelatedRecord(arg1, arg2)
{
    var foo = fooFactory.NewFoo(arg1, arg2);
    if (foo.IsSavable)
    {
        foo = foo.Save();
    }

    foo.Property = "newValue";
    foo.Save();
}
```

So here is what I understand to be true here.  Please let me know if any of this is incorrect.

- The new code analyzer was put in place to protect users from saving an object and not assigned the result, which could result in unexpected behavior
- The protection put in place come at the cost of assigning variables containing the results of save operations that may not be used in cases like mine.  

Your help is appreciated.

**Comment by pssewell21** [comment]
Also, there is the option of disabling the CSLA0005/CSLA0006 rules in the Analyzers for our projects.  I mostly just want to make sure that we are not neglecting to follow a pattern that we should be in some cases.  Thanks.

**Comment by royog** [comment]
Code should be self documenting where possible. If in a couple years from now a less experienced developer was assigned a task to modify your code, it would be fairly easy for that person to overlook the fact that "foo.Save();" would need to be rewritten as "foo = foo.Save();" assuming that the change required the examination/modification of the business object post save. For this reason, I'd strongly recommend sticking with the CSLA guideline of always accepting the returned reference to a saved business object, even if you never use that reference in your current code. You may not have any control over who's in control, when, or how that method is modified in the future. To put up with being flagged for assigning a variable that's never used would be far less annoying than having a difficult to find logic bug in some future revision of your code project in my opinion.

**Comment by royog** [comment]
The other thought I had while looking at your example code, is perhaps what you should do for this type of scenario is use the CSLA stereotype Command Object instead of a read-write Business Object to perform the work needed.  The Command Object sounds like it may possibly be the right stereotype to use to do the work of "CreateRelatedRecord" sever side.

For just doing server side work, the Command Object is your friend, and may eliminate your concerns regarding the Analyzers' results. So, perhaps you are using a Business Object where you aught to be considering the use of a more efficient Command Object to perform the desired action?

**Comment by rockfordlhotka** [comment]
This is a good thread, I like the suggestion of command object. It is also the case that not using the result of `Save` is the exception, and so suppressing the warning is valid, because we assume you know what you are doing when you suppress it.

**Comment by pssewell21** [comment]
Thanks for the feedback guys.  I will look into the Command Object to see if it is more appropriate to use for the work we are doing in these situations.  We already use them frequently in our product, but I had not thought about using them for cases such as these.  I was able to upgrade to the new framework version after disabling the two code analysis rules and reworking a couple static classes that use the Data Portal.  Perhaps I can turn them back on after some rework since we do follow the recommended pattern the majority of the time.
