### ISSUE TITLE
Split platform-specific code into satellite assemblies

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#793]
Support for netstandard 2.0 really means having _exactly_ one Csla.dll that targets netstandard 2.0. All per-platform functionality needs to be in per-platform satellite assemblies.

As of Feb 19, 2018, all platforms already meet this requirement except for full .NET. Some aspects of full .NET (COM+, WCF, etc.) need to be split out into a brand new satellite assembly that supports full .NET.

--

Original description:

Right now the NuGet package includes output for numerous platforms, including:

* netstandard 2.0
* iOS 
* Android
* UWP

The problem we appear to be facing is that the iOS, Android, and UWP `Csla.dll` outputs are _actually_ platform-specific, which is causing some issues when an iOS or UWP app references a business DLL built using netstandard 2.0.

This is because the `Csla.dll` used at runtime is set by the app, so that business class library ends up trying to use the platform-specific assembly, not the netstandard assembly. Because these assemblies are not identical, this is a problem.

**Comment by ddobrev** [comment]
When is this bug going to be fixed? Xamarin.Forms is dropping PCL in its next release and it's vital that CSLA can work with .NET Standard 2.0 instead.

**Comment by rockfordlhotka** [comment]
I'm experimenting with some options.

The challenge is that this is probably a _major_ breaking change for anyone not running the latest VS (15.5) and using NS2.0 for Xamarin and UWP.

The solution I've been testing (with success) is to change the CSLA-Core package so it only contains
* netstandard 2.0
* .NET 4.0
* .NET 4.5

All the other targets (.NET 4.6, Xamarin, UWP, ns 1.5, ns 1.6) are technically superseded by NS2.0 - but only for people running the latest and greatest.

As a result, if I go down this road (and I think it is the only option) the CSLA 4.7.100 release will not work for anyone running on older versions of Xamarin or UWP.

**Comment by rockfordlhotka** [comment]
Note to self: NS2.0 is pretty awesome, but people _do still use full .NET_ and so we can't actually eliminate support for full .NET 4.6.1 - that's where a lot of interesting Windows-only things around security, COM+, and so forth all exist...

**Comment by rockfordlhotka** [comment]
Now encountering this issue:

https://github.com/dotnet/standard/issues/300

It doesn't appear that there is currently a solution to this problem, at least until a bug gets fixed in full .NET (4.7.2?).

I may have to switch tactics in the meantime, releasing a NuGet package for full .NET as a separate thing from the standard NuGet package that'll now target netstandard 2.0.

**Comment by rockfordlhotka** [comment]
What I've done in these last couple commits is to

1. Make the Csla-Core NuGet package contain all the non-netstandard versions of `Csla.dll` - so NET 4, 4.5, 4.6, PCL111, PCL259
1. Make a new Csla-Core-NS NuGet package that contains the netstandard 2.0 version of `Csla.dll`
    1. Update the Android, iOS, Xamarin Forms, UWP, and .NET Core NuGet packages to have a dependency on the new Csla-Core-NS package
    1. Leave the "legacy" Windows Forms, WPF, EF, and ASP.NET NuGet packages with a dependency on the original Csla-Core package

If you are running your code in any of the full .NET platform scenarios (Windows client or server w/o .NET core) then you'll end up using the full .NET version of `Csla.dll`.

If you are running your code in any of the modern .NET platform scenarios (Xamarin, UWP, .NET Core) then you'll end up using the netstandard version of `Csla.dll`.

Where you'll be left in the lurch at the moment, is if you have (for example) a netstandard client (like Xamarin) and a full .NET server. In that case your _business assembly_ will need to be compiled once for the client and once for the server.

This is because of the previously referenced issue with full .NET where BinaryFormatter/NDCS serialization doesn't work for types built using netstandard 2.0.

What I haven't tested, is whether this problem exists with MobileFormatter. I strongly suspect it does not exist, and so _maybe_ you can get away with using a business library built for NS2 on a netstandard client and a full .NET server. But I'm dubious, as I suspect there are other inconsistencies between the two sets of assembly bindings.
