### ISSUE TITLE
warning PRI263: 0xdef01051

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#794]
I am getting the warning PRI263: 0xdef01051 after added the  csla core in uwp project

 eg: 
3>GENERATEPROJECTPRIFILE : warning PRI263: 0xdef01051 - No default or neutral resource given for 'Csla.Properties.Resources/FailedOnServer'. The application may throw an exception for certain user configurations when retrieving the resources.

**Comment by rockfordlhotka** [comment]
Just to clarify, this is in CSLA 4.6, not the 4.7 prerelease?

**Comment by rockfordlhotka** [comment]
A further note on this. It appears that the problem exists when using the old style csproj file for UWP and is related to this thread:
https://developercommunity.visualstudio.com/content/problem/82838/uwp-resource-handling-fails-when-baseintermediateo.html

One workaround suggested by Microsoft is to remove the `baseintermediateoutputpath` element.

Another workaround is to update the project to use the more modern csproj format.

**Comment by rockfordlhotka** [comment]
This remains an issue 😢

**Comment by rockfordlhotka** [comment]
@sachinpnikam did you close this because the problem no longer exists? I was encountering the issue and to my knowledge it still is a problem?
