### ISSUE TITLE
How to migrate from Local to WcfProxy on a subset of my business objects

### ISSUE THREAD

**Issue by GillesBer** [MarimerLLC/csla#796]
Dear all, 
I'm running and maintaining a large 2-tier application that is using CSLA 4.6.600.
We would like to migrate this application to 3-tier, but in several phases.
Is there any 'best practice' to migrate only a subset of my business objects?

Our plan was to migrate: 'one form at a time', and their business objects.

I imagine that I can also add the [RunLocal] attribute on all my legacy objets to 'opt-out' them from 3 tier. But ideally, I would like to 'opt-in' my new forms (and related business objects) and migrate my business objects 'form' by 'form'.

I found this old 2008 thread on http://forums.lhotka.net/forums/p/4413/21609.aspx#21609 which proposed to choose to which Proxy it redirects. I imagine this is still valid solution.
Has someone any experience doing so? Are there any pitfall I should anticipate.
Regards,
Gilles

**Comment by rockfordlhotka** [comment]
Sorry, didn't see this until now. Please post questions like this in the forum

https://github.com/MarimerLLC/cslaforum/issues
