### ISSUE TITLE
Authorization Rule with description message.

### ISSUE THREAD

**Issue by sashkr** [MarimerLLC/csla#797]
Why Authorization rule does not support description message? Something like PropertyRule with "MessageText"?
I've found only one reference to this problem:
[http://cslanet.com/old-forum/12159.html](url)

JonnyBee recommended to throw exception inside Execute method. But this is bad idea.
Why we can't add "MessageText" property to AuthorizationContext class?
Implementing it should be easy.

**Comment by jonnybee** [comment]
If you want a message then it is not an authorization rule - it is a business rule that may set Error/Warn/Info level on a message text. 

An authorization rule only returns true/false as to whether the user has permission or not.

**Comment by sashkr** [comment]
I'm sorry but I don't understand.
What exectly do you mean?
How to achieve my goal?

I would like to prevent object editing depend to some properties values. For example:
 1. If "Property1" = true && "Property2" = "sometext" - description message should let's say "Editing disabled becouse of problem1".
 2. If "Property1" = false && "Property2" = "somemegatext" - description message should let's say "Editing disabled becouse of problem2".

**Comment by sashkr** [comment]
> An authorization rule only returns true/false as to whether the user has permission or not.

But I stiil don't understand why we can't implement message to authorization rule.
We need just add string property to AuthorizationContext class and use it inside modified HasPermission method (add one more parameter 'bool throwOnFalse'). Like this:

```c#
private static bool HasPermission(AuthorizationActions action, object obj, Type objType, string ruleSet, bool throwOnFalse)
{
	if (action == AuthorizationActions.ReadProperty || action == AuthorizationActions.WriteProperty || action == AuthorizationActions.ExecuteMethod)
	{
		throw new ArgumentOutOfRangeException("action");
	}
	bool result = true;
	string resultMessage;
	IAuthorizationRule rule = AuthorizationRuleManager.GetRulesForType(objType, ruleSet).Rules.FirstOrDefault((IAuthorizationRule c) => c.Element == null && c.Action == action);
	if (rule != null)
	{
		AuthorizationContext context = new AuthorizationContext
		{
			Rule = rule,
			Target = obj,
			TargetType = objType
		};
		rule.Execute(context);
		result = context.HasPermission;
		resultMessage = context.MessageText;
	}
	if (!result && throwOnFalse)
	{
		if (!string.IsNullOrEmpty(resultMessage))
			throw new SecurityException(resultMessage);
		else
		{
			switch (action)
			{
				case AuthorizationActions.WriteProperty:
					SecurityException ex = new SecurityException(string.Format("{0} ({1})", Resources.PropertySetNotAllowed, property.Name));
					throw ex;
				case AuthorizationActions.ReadProperty:
					SecurityException ex = new SecurityException(string.Format("{0} ({1})", Resources.PropertyGetNotAllowed, property.Name));
					throw ex;
				case AuthorizationActions.ExecuteMethod:
					break;
				case AuthorizationActions.CreateObject:
					break;
				case AuthorizationActions.GetObject:
					break;
				case AuthorizationActions.EditObject:
					break;
				case AuthorizationActions.DeleteObject:
					break;
				default:
					throw new ArgumentOutOfRangeException(nameof(action), action, null);
			}
		}
	}

	return result;
}
```

**Comment by jonnybee** [comment]
Your mindset should be 
- The user is only allowed to get or set the properties that he/she is allowed to 
- When a property is not valid there should be a message saying why (from a Business rule)
- The BrokenRules collection should at any time reflect the state of the object.

What is the state of you object when a user has already edited property Property3 before  Property1 and Property2 enters the given state? 

My preference is to disable the UI control when the user is not allowed to set the value. 

Also remember
- there can only be one-1 authorization rule per type, property and AuthorizationAction 
- authorization for ReadProperty/WriteProperty are automatically called by the framework when using DataBinding in a RichClient or WebApplication (CslaModelBinder will not check per property) 
- the default setting is to cache the result (WriteProperty/ReadProperty/ExecuteMethod) 

In BusinessBase the code is as follows: 

```
    /// <summary>
    /// Returns true if the user is allowed to write the
    /// specified property.
    /// </summary>
    /// <param name="property">Property to write.</param>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public virtual bool CanWriteProperty(Csla.Core.IPropertyInfo property)
    {
      bool result = true;
      VerifyAuthorizationCache();

      if (!_writeResultCache.TryGetValue(property.Name, out result))
      {
        result = BusinessRules.HasPermission(AuthorizationActions.WriteProperty, property);
        if (BusinessRules.CachePermissionResult(AuthorizationActions.WriteProperty, property))
        {
          // store value in cache
          _writeResultCache.AddOrUpdate(property.Name, result, (a, b) => { return result; });
        }
      }
      return result;
    }

    /// <summary>
    /// Returns true if the user is allowed to write the
    /// calling property.
    /// </summary>
    /// <returns>true if write is allowed.</returns>
    /// <param name="property">Property to write.</param>
    /// <param name="throwOnFalse">Indicates whether a negative
    /// result should cause an exception.</param>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public bool CanWriteProperty(Csla.Core.IPropertyInfo property, bool throwOnFalse)
    {
      bool result = CanWriteProperty(property);
      if (throwOnFalse && result == false)
      {
        Csla.Security.SecurityException ex = new Csla.Security.SecurityException(
          String.Format("{0} ({1})", Resources.PropertySetNotAllowed, property.Name));
        throw ex;
      }
      return result;
    }
```


I guess you could throw a SecurityException directly inside the AuthorizationRules Execute method. It should have the same effect.

**Comment by sashkr** [comment]
> My preference is to disable the UI control when the user is not allowed to set the value.

Yes. But only if you edit object on form. But when you edit in DataGridView that's another story. I would like to handle CellBeginEdit event. And check permission there. If user does not have permission to edit object or property I would like show MessageBox with apropriate description and set e.Cancel = false.

I don't understand how to achive it. So, I close an issue. I will modify CSLA framework.

**Comment by tfreitasleal** [comment]
Hi sashkr,

On one hand, changing a given version of CSLA. NET isn't a good idea because CSLA is permanently being updated/upgraded. Some of these updates/upgrades are pretty useeful and to benefit from them, you are forced to repeat the change.

On the other hand, it looks like you have a problem you can't solve with the current implementation of business rules/authorization rules. Maybe your problem isn't just yours and it might be interesting to share it.

I'd like to ask you to give us some more details like UI platform (WinForms, WPF, Web) and maybe a small sample so one can understand the "real issue". The "real issue" is clear to you but not for us (not for me at least). If a picture is worth a thousand words, a sample is worth a million words.

Thanks for your colaboration.

**Comment by jonnybee** [comment]
If you throw a SecurityException directly inside the AuthorizationRules Execute method it should have the same effect as the proposed changes.

**Comment by sashkr** [comment]
> If you throw a SecurityException directly inside the AuthorizationRules Execute method it should have the same effect as the proposed changes.

Maybe you are right. I have not used CSLA for a long time. And I forgot it.
I just don't know if throwing a SecurityException inside Execute method will not break something inside CSLA framework.

**Comment by sashkr** [comment]
Throwing exception looks unnatural inside AuthorizationRule.
CSLA has method:
public bool CanWriteProperty (IPropertyInfo property, bool throwOnFalse)

So when the user calls this method with "throwOnFalse = false" he don't expect to get an exception.
So I propose to add this parameter (throwOnFalse) to HasPermission method. And when "throwOnFalse = true", CSLA will throw SecurityException with a user defined message instead of CSLA default message.
