### ISSUE TITLE
Cancel FetchAsync.

### ISSUE THREAD

**Issue by sashkr** [MarimerLLC/csla#798]
Is there any way to cancel FetchAsync operation?
Task class has support of CancellationTokenSource. But CSLA seems has no support of it.
I would like to get the user ability to cancel operation.

**Comment by jonnybee** [comment]
Please post these questions on the forum instead. 

https://github.com/MarimerLLC/cslaforum/issues

**Comment by sashkr** [comment]
I didn't know about forum on github.
Thanks!
