### ISSUE TITLE
Update Analyzers to be .NET Standard 1.3-Based

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#804]
According to [this article](https://andrewlock.net/creating-a-roslyn-analyzer-in-visual-studio-2017/), when you create analyzers for VS2017, they're now targeting .NET Standard 2.0. This means they're not longer PCL-based, which is great. However, this also sounds like this would mean the analyzers would only work in VS2017. But I talked to @rockfordlhotka and he said this is OK. So....when I get the time I'll make the update.

**Comment by JasonBock** [comment]
Couple of notes:

* Because the analyzer will target .NET Standard, it can reference CSLA directly now. Before, being a PCL, it couldn't, because I don't think there was a PCL version of CSLA when I started doing the analyzers (there may have been or there may be now, but not sure about that). This should be advantageous because I no longer have to use constants to ensure the member I'm looking at is the "right" one from CSLA.
* I may end up putting in new tasks to refactor some of the analyzers. I believe all of them use syntax trees and in some cases using semantic models can make the code a little easier to read.

**Comment by JasonBock** [comment]
Slight disappointment....I looked at what the VS template generates for a new analyzer project, and it's targeting `netstandard1.3`. That kind of sucks, I was hoping for 2.0 :(

**Comment by rockfordlhotka** [comment]
That's a bit of an issue too, as starting with 4.7 CSLA only supports NS2.0 (and .NET 4.0/4.5). It never did support NS1.3 though, because of various limitations - the furthest back we ever went was 1.4.

**Comment by JasonBock** [comment]
Well, it's only an issue if I want to reference CSLA directly. I just wouldn't be able to do that. So, it's still somewhat of a "gain" in that the analyzer gets away from being a PCL.

FYI I tried to update the generated analyzer from VS 2017 to be .NET Standard 2.0, and that doesn't work.
