### ISSUE TITLE
Statics and DI

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#810]
The configuration method that I created a while back for asp.net core, here: https://github.com/MarimerLLC/csla/blob/3ec0b5030560c078b2458b0dbd39217ec0c15a74/Source/Csla.Web.Mvc.Shared/WebConfiguration.cs#L22

is a bit of a hack, and I realised it at the time, because it implies that you are configuring CSLA inside a container.

But under the hood, it's actually just setting stuff at an AppDomain level (statics):

```
                Csla.Server.FactoryDataPortal.FactoryLoader = ObjectFactoryLoader;
                Csla.DataPortal.ProxyFactory = DataPortalProxyFactory;

```

For example if you did this:

```
        
        [Fact]
        public void PassingTest()
        {

            var services = new ServiceCollection();           
            services.ConfigureCsla((a, b)=>{ a.ObjectFactoryLoader = Foo; });
            var sp = services.BuildServiceProvider();

            DoSomeAssertsWithCsla(sp);
            
        }

        [Fact]
        public void FailingTest()
        {
            var services = new ServiceCollection();
            services.ConfigureCsla((a, b) => { a.ObjectFactoryLoader = Bar; });
            var sp = services.BuildServiceProvider();

            DoSomeAssertsWithCsla(sp);
        }


```

Both methods are configuring CSLA at a global level, so If you run tests in parallel they will therefore interfere with eachother.

It would be just grand, if we could find a way, to allow CSLA to operate purely within the confines of a container (all global configuration (like `Csla.Server.FactoryDataPortal.FactoryLoader`) would be scoped to the configuration instance provided / resolved via that container).

Not a simple one I appreciate though :-)

**Comment by rockfordlhotka** [comment]
Did the change in #525 help?

Probably not, because the dictionary containing the AppSettings is still global.

Though perhaps it is a step in the right direction, as it could be maintained in an `AsyncLocal`, and that might give it some isolation? We'd also have to go through the `ApplicationSettings` class and remove all the caching that's in there for performance reasons - so it always re-reads and re-creates values on every call (which doesn't sound like a _great_ idea).

**Comment by dazinator** [comment]
@rockfordlhotka was this closed because its now solved? Or was it determined its not faesible?
