### ISSUE TITLE
dataPortal_Update error - save method not available to override in businessBindingListBase

### ISSUE THREAD

**Issue by DevinderMCA** [MarimerLLC/csla#811]
I have upgrade my code from csla 3.6.3 to csla 4.6.5

I was overriding save method of BusinessListBase class. After upgrade I am using BusinessBindingListBase class. But now I can't override save method of BusinessBindingListBase class as it is not marked as virtual.

Now dataPortal_Update error is coming when I call save method in BusinessBindingListBase

Please let me know where to move my code written in save method or how to override save method so that existing working does not get affected.

**Comment by rockfordlhotka** [comment]
You now need to override SaveAsync, because the data portal supports all the new async/await concepts in .NET, and internally it is all async, even if you are using it by calling one of the old sync methods.

**Comment by DevinderMCA** [comment]
Even SaveAsync is not marked as virtual so not able to override it too.

Method declared in **BusinessBindingListBase<T, C>** as      **public Task<T> SaveAsync();**.

following error coming when try to override it

cannot override inherited member 'BusinessBindingListBase<POrders, POrder>.SaveAsync()' because it is not marked virtual, abstract, or override

**Comment by GillesBer** [comment]
@DevinderMCA  You are not overriding the correct method.

Try using this one (this code is in VB.NET):
 Protected Overrides Async Function SaveAsync(forceUpdate As Boolean, userState As Object, isSync As Boolean) As Task(Of T)

**Comment by DevinderMCA** [comment]
Thanks for the help. 
Now I able to apply the fix to the issue
