### ISSUE TITLE
Unable to find version '4.7.100-R18022202' of package 'CSLA-WPF'

### ISSUE THREAD

**Issue by digitalsummit** [MarimerLLC/csla#819]
After cloning the latest CSLA repository from Github, which includes the Merge pull request #817, I'm getting the error Unable to find version '4.7.100-R18022202' of package 'CSLA-WPF'.  I can run most of the Xamarin-Android demo from the Project Tracker Solution  with little issue but am having issues getting the WPF demo within Project Tracker to run at all.  Please offer advice...

**Comment by rockfordlhotka** [comment]
I've been using ProjectTracker to test the updates to CSLA's NuGet packages, mostly using local packages that don't get pushed to NuGet (it gets messy to push dozens of intermediate non-functional packages to a public location).

This sounds like a basic oversight where the WPF package didn't get updated to the prerelease that _is_ in NuGet. You should be able to solve this by upgrading the package to the latest prerelease.
