### ISSUE TITLE
OnDeserialized attribute from NS2 causes runtime error in full .NET

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#822]
Several CSLA base classes use the `OnDeserialized` attribute to be notified when the BinaryFormatter or NDCS has completed deserializing the object graph.

Unfortunately at the moment there's a conflict between this attribute in netstandard 2.0 and full .NET. So if you use this attribute in an NS2 assembly and then try to reference and run that assembly from within a full .NET runtime (ASP.NET, Windows Forms, WPF, etc.) you'll get a runtime exception because the types don't match.

Until this issue is resolved within full .NET CSLA needs to maintain a set of NuGet packages (and assemblies) that target full .NET separately from netstandard.

This is documented by https://github.com/dotnet/standard/issues/300 in the Microsoft .NET repo.

**Comment by j055** [comment]
This isn't just full .NET which is affected. If you create an Azure Function project targeting .NET Core and install CSLA-Core-NS, you cannot build the project because `TypeLoadException` is thrown. 

```
System.TypeLoadException: Type 'Csla.Core.ManagedObjectBase' in assembly 'Csla, Version=4.7.100.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler' with an incorrect signature for the serialization attribute that it is decorated with.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
```

As far as I can tell you can't use CSLA in any flavour of an Azure Function Project if you want to use the `DataPortal` (local or otherwise).

**Comment by rockfordlhotka** [comment]
Azure Functions use full. NET so an NS assembly won't work. I don’t know why the full. NET version is having issues.

**Comment by rockfordlhotka** [comment]
I haven't used the latest. The key with CSLA at this point is that you use CSLA-Core when running in full dotnet and CSLA-Core-NS when running in netcore.

**Comment by rockfordlhotka** [comment]
Sounds like the issue has been resolved in .NET 4.7.2.
https://github.com/dotnet/standard/issues/300#issuecomment-412860753

Which now begs the issue of whether I can unravel the mess of NuGet packages I've created such that when everyone eventually starts using 4.7.2 we can get back to simply using `CSLA-Core`...

**Comment by rockfordlhotka** [comment]
Upon further review, and the changes made in #927, no work is required to resolve this issue.

For the next several years the `CSLA-Core` package will contain one or more .NET Framework assemblies along with .NET Standard assemblies. At no point in the foreseeable future will any .NET Framework app end up using the NS2 assembly.

Once all CSLA .NET users are on at least .NET Framework version 4.7.2 many years will have passed. But at that time perhaps the `CSLA-Core` package can contain just the NS assembly(ies).
