### ISSUE TITLE
CS043 :The type 'SerializableAttribute' exists in both ..

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#823]
hi,

after Updating the CSLA to 4.7.100 I am getting below error to uwp lib classes 
Error	CS0433	The type 'SerializableAttribute' exists in both 'Csla, Version=4.7.100.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' and 'System.Runtime.Serialization.Formatters, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Csla, Version=4.7.100.0,

**Comment by rockfordlhotka** [comment]
You updated to the new CSLA-UWP package of the 4.7.100 release (not preview)?

**Comment by SachinPNikam** [comment]
previously  I only used CSLA_Core for all uwp dll and Project .after the CSLA_UWP ..installing this issue is resolve..thanks
