### ISSUE TITLE
Azure Function App throws SerializationException: Unable to find assembly

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#824]
Azure Function App throws `SerializationException: Unable to find assembly` at `DataPortal.Execute`. I’m using `CSLA 4.7.100` but if seems to be a problem in previous versions too. 

![csla-serializationexception](https://user-images.githubusercontent.com/6011428/37921092-af46f826-3120-11e8-9589-7641e733ded9.png)

Stack Trace:
```
   at Csla.DataPortal`1.Update(T obj)
   at Csla.DataPortal.Update[T](T obj)
   at Csla.DataPortal.Execute[T](T obj)
   at ClassLibrary1.CommandObject1.Execute() in C:\Users\andre\source\repos\FunctionApp1\ClassLibrary1\CommandObject1.cs:line 23
   at FunctionApp1.Function1.Run(TimerInfo myTimer, TraceWriter log)
   at lambda_method(Closure , Function1 , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__9.MoveNext()
```
This does NOT seem to occur when running a WebJobs project.

Any ideas?

**Comment by rockfordlhotka** [comment]
You are referencing the CSLA-Core package, not CSLA-Core-NS?

**Comment by j055** [comment]
Yes `C:\Users\andre\.nuget\packages\csla-core\4.7.100\lib\net46\Csla.dll`.

I'm targeting .NET Framework 4.7. I think it might the same with NS too. But I will have to double check.

**Comment by rockfordlhotka** [comment]
CSLA-Core-NS won't work in a full .NET runtime due to #822 - so I was just ruling that out as a possible issue for you.

**Comment by rockfordlhotka** [comment]
So is the Function calling a remote data portal, a local data portal, or is it _hosting_ the data portal?

**Comment by j055** [comment]
Local data portal. To repro: Open VS2017, New Azure Function project, new function class with timer trigger, new CSLA `CommandObject`, as above. Call `CommandObject` from `Run` method. Run in debug. Throws `SerializationException`.

**Comment by j055** [comment]
Don't know if this helps but I've observed the following:

When I use a WebJob project CSLA Serialization works. Use a Function project and the `SerializationException` is thrown in both dev environment and hosted on an Azure App Service. WebJobs are obsolete for new projects as far as I can tell.

`Assembly.GetExecutingAssembly()`

WEBJOB (Azure) [success]
Location - `D:\local\Temp\jobs\continuous\WebJob1\r4hdjetb.rli\WebJob1.exe`
CodeBase - `file:///D:/local/Temp/jobs/continuous/WebJob1/r4hdjetb.rli/WebJob1.exe`

FUNCTION (Azure) [fail]
Location - `D:\local\Temporary ASP.NET Files\root\0ef9c0fd\eaa3d11e\assembly\dl3\a46468d1\0ef3cee5_c0c5d301\FunctionApp1.dll`
CodeBase - `file:///D:/home/site/wwwroot/bin/FunctionApp1.dll`

FUNCTION (Dev) [fail]
Location - `C:\Users\andre\source\repos\FunctionApp1\FunctionApp1\bin\Debug\net47\bin\FunctionApp1.dll`
CodeBase - `file:///C:/Users/andre/source/repos/FunctionApp1/FunctionApp1/bin/Debug/net47/bin/FunctionApp1.dll`

**Comment by jonnybee** [comment]
Do you have assembly redirects in your web.config/app.config? 

See: https://stackoverflow.com/questions/38093972/azure-functions-binding-redirect/38101488

**Comment by j055** [comment]
The package manager adds some to the app.config in the webjob project. Nothing for CSLA. I removed them and the webjob still works.

**Comment by j055** [comment]
I'm attaching the VS2017 Solution because it's so tiny.
[FunctionApp1.zip](https://github.com/MarimerLLC/csla/files/1852011/FunctionApp1.zip)

**Comment by j055** [comment]
Impressive! Yes that does fix the problem, after one simple test at least. Do you think I should report it to the Function dev team? I suppose I could at least ask the question: 'why is it necessary'? 

Thanks for digging out the fix.

**Comment by rockfordlhotka** [comment]
Ask away 😄 

I rather suspect the answer is lost to the mists of time though, since this issue has existed since the very inception of .NET itself, and so the people who made and implemented the design decision are almost certainly on to other things (or even other employers).

**Comment by wShaw** [comment]
Wanted to comment that @rockfordlhotka SerializationWorkaround() method also fixed the exact same issue I was having. Thanks so much!
