### ISSUE TITLE
NullReferenceException when calling RuleContext.Complete() & add IRuleContext

### ISSUE THREAD

**Issue by klk103** [MarimerLLC/csla#827]
If you initialize an async **RuleContext** with a null _completeHandler_ parameter (I have a few unit tests for custom rules that don't need a callback), the context will throw a **NullReferenceException** when the rule calls Complete:
```csharp
public void Complete()
{
  if (Results.Count == 0)
    Results.Add(new RuleResult(Rule.RuleName, Rule.PrimaryProperty));
  _completeHandler(this);
}
```
as __completeHandler_ was never set.

**Comment by rockfordlhotka** [comment]
Either we should check the parameter provided and throw an exception if it is null, or we should allow it to be null and fix the code in `Complete`.

What is the scenario where you don't care when/if the rule completes? I'm not sure that should be a supported scenario?

**Comment by ajj7060** [comment]
I hit this issue too, in the same context.  In a unit test for a business rule, we new up an instance of a RuleContext.  When we weren't creating async business rules, passing null for the completeHandler was fine.  But once we tried to test async rules, where you have to call context.Complete, our unit tests were blowing up, and it took a while to figure out it was within the Complete call.  We worked around it by always providing a () => {} for the completeHandler.

In unit testing, we typically only used RuleContext to send in the input properties we wanted, and then verified that any expected output properties were added.

At the time I was trying to find this error, I was actually wishing for an IRuleContext interface that business rules would use, so I could just Moq the instance given to the rule.

**Comment by rockfordlhotka** [comment]
@ajj7060 You'll be happy to see that I did choose to add an `IRuleContext` interface as part of this backlog item 😄

**Comment by rockfordlhotka** [comment]
**Adding `IRuleContext` turns out to be a breaking change for all custom rule classes.

**Comment by ajj7060** [comment]
@rockfordlhotka  Hurray, thank you!  

I just saw your subsequent message about the interface being a breaking change; are you still going to keep the interface, or do you think its not worth breaking things?

**Comment by rockfordlhotka** [comment]
I'm keeping the interface - it makes testing rules easier, and that is a big deal.

**Comment by ajj7060** [comment]
Glad to hear it!  It should be a fairly easy breaking change to overcome as well too.
