### ISSUE TITLE
Update Analyzer Documentation

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#828]
Two things:

* [This wiki entry](https://github.com/MarimerLLC/csla/blob/master/docs/Analyzers.md) needs some polish.
* Analyzers can have help links associated with them. Right now we don't have that, and we should add entries into the wiki here that describe the analyzers and code fixes in more detail.

**Comment by rockfordlhotka** [comment]
I'm thinking about moving the wiki content into a folder within the main repo. That way the content versions with the framework, which should make it more valuable.

**Comment by JasonBock** [comment]
So, after talking to @rockfordlhotka, here's what I'll do:

* Create an "analyzers" folder off of "docs"
* Move the currently analyzers.md doc into the subfolder and rename it to "index.md".
* Put an "images" directory underneath "analyzers".
* Create the screenshots for the "analyzers.md" doc, put them into "docs/analyzers/images" directory, and then link them into "analyzers.md"
* Create .md files for each rule/descriptor within an analyzer in the "analyzers" folder. Follow this convention: {ID}-{Name}.md - ex: CSLA0003-CheckConstructorsAnalyzer.md
* Update each `DiagnosticDescriptor`'s `helpUrl` constructor parameter.

I think that covers everything.
