### ISSUE TITLE
Get CSLA working with Blazor

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#829]
Get CSLA to work with [Blazor](https://github.com/aspnet/Blazor).

Right now if you reference CSLA 4.7.100 (netstandard 2.0) in Blazor the result is a linker error when Blazor attempts to compile to wasm. I think this is because some of the Microsoft assemblies used by CSLA aren't supported in the version of mono on which Blazor is based.

The short-term strategy might be to pare down the dependencies on those system assemblies (even if that means removing some CSLA functionality) to see if it is possible to get a `Csla.dll` that can be linked into a Blazor app.

**Usage note**
Based on the _very experimental_ work so far on this issue, you can play around with it too by following these instructions:

1. Get yourself all set up with Blazor so you can run their starting template project
1. Pull the experimental CSLA code from here: https://github.com/rockfordlhotka/csla/tree/blazor
1. Add the `Csla.Shared` project to your solution
1. Add the `Csla.Wasm` project to your solution
1. Reference the `Csla.Wasm` project from your Blazor project

At this point you should be able to create CSLA business classes in your Blazor project and interact with them from your views.

**Comment by rockfordlhotka** [comment]
The strategy appears to be largely successful. I was able to get the dependencies down to just these:

```
  <ItemGroup>
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.3.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.3.0" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
  </ItemGroup>
```
Without removing any functionality from CSLA - at least to get it compiled.

It may be however, that some functionality is now broken. For example, the data portal doesn't currently work in Blazor, due to an exception with `System.Linq.Expressions`. I'm not yet sure if that's a limitation of mono-wasm, or a missing dependency from CSLA.

Ignoring the data portal however, it is possible to create and interact with a CSLA business object in Blazor.

**Comment by rockfordlhotka** [comment]
Further experimentation establishes that the offending reference is 
```
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
```
All other dependencies are fine with Blazor.

**Comment by rockfordlhotka** [comment]
Further experimentation seems to establish that the linker issue is with two of the serialization assemblies:

```
    <PackageReference Include="System.Runtime.Serialization.Xml" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
```
I've been able to restore all the other assembly references and still have a Blazor app link and run against `Csla.dll`. 

The data portal continues to fail with the `System.Linq.Expressions` issue, so I think that is a mono-wasm issue, not a system reference issue (because neither of the now-removed assembly references have anything to do with Linq).

**Comment by rockfordlhotka** [comment]
Removing the usage of `System.Linq.Expressions` wasn't as hard as I'd feared, because I never got around to removing the old `IOS` compiler directives that used to be necessary for this same reason. Added new `WASM` directives, rebuilt, and now the data portal works!

**Comment by fujiiface** [comment]
This is some exciting news!

**Comment by royog** [comment]
Just awesome!  I’m as excited about Blazor as you are Rocky … I’m thinking it’ll have huge potential as well. Thanks for jumping on it so quickly! CSLA still rocks after all these years.

Can’t wait to see if MS makes a solid commitment announcement for Blazor at Build this year.

Roy

**Comment by tfreitasleal** [comment]
Hi all,

I have some notes/questions/doubts about WASM/Blazor. I started a thread about this at [What is WASM/Blazor good for?](https://github.com/MarimerLLC/cslaforum/issues/514)

**Comment by rockfordlhotka** [comment]
CSLA appears to work in Blazor at this point, except that the data portal is encountering an issue with the DataContractSerializer - which doesn't appear to be working.

https://github.com/aspnet/Blazor/issues/511

Ideally this would be resolved by mono-wasm or Blazor, but in the meantime I'm considering exploring other options (if Json.Net works in Blazor that'd be a nice workaround).

**Comment by rockfordlhotka** [comment]
**SUCCESS!!**

Well, mostly anyway. There's now a `Samples\BlazorExample` that (on the counter page) successfully gets a simple business object via the data portal from the ASP.NET Core web server.

The only issue at the moment is that the button click handler is an `async` method, and that appears to mess up how Blazor does data binding. So after you get the object, click the other button to increment the counter (and thus refresh data binding) to see the value.

This is extremely cool imo!

(the other current limitation is that I'm 99% sure any sort of list objects won't go through the data portal - I need to replace the one spot I'm using Json.Net with something else - probably have to write my own low-level serializer 😢 )

**Comment by rockfordlhotka** [comment]
There's a `StateHasChanged` method that refreshes data binding if you call it at the end of an `async` method, so that issue is resolved.

**Comment by rockfordlhotka** [comment]
It looks like the DCS/Json.Net dependency can be avoided with simpler code: https://github.com/MarimerLLC/cslaforum/issues/515#issuecomment-379801420

So valuable to have other eyes on the work!!

**Comment by rockfordlhotka** [comment]
The solution to the `System.Linq.Expressions` issue might be to somehow detect at runtime that we're running on MonoWasm and branch to the reflection code, while branching to the Linq implementation on all other platforms.

Messier than my current use of compiler directives, but I suppose it would allow a single assembly that supports both platforms.

**Comment by rockfordlhotka** [comment]
The solution to the `HttpClient` limitations around passing only text is to create a new data portal channel such as `HttpTextProxy` or something along that line - thus allowing MonoWasm devs to set up a proxy/host that works for Blazor, while allowing other platforms to choose the existing `HttpProxy` that uses binary.

**Comment by rockfordlhotka** [comment]
**Starting at this point my plan is to disregard the initial PR and create a new PR with a cleaner implementation.**

**Comment by rockfordlhotka** [comment]
**THE CHANGE TO MOBILELIST IS A BREAKING CHANGE**

`MobileList` _used_ to be able to serialize any type that could be serialized by the `DataContractSerializer`. With the change made for wasm, there's no longer a DCS dependency, which means that `MobileList` can not only serialize primitive types.

**Comment by tfreitasleal** [comment]
> `MobileList` can not only serialize primitive types.

I supposed this means that from now on, `MobileList` can serialize all kinds of types (including primitive types). Is this correct?

**Comment by rockfordlhotka** [comment]
Prior to this change `MobileList` could contain any items that could be serialized by the DCS.

Because we no longer use the DCS, `MobileList` can now _only_ contain primitive types (string, date, number, etc.). 

It can no longer contain complex items like it could before.

**Comment by tfreitasleal** [comment]
Oh, I see. This a breaking change indeed, and a big one. I foresee people not upgrading versions because of this limitation.

This means not even SmartDate is allowed... 

Is there a way to keep the `MobileList` as it is now and introduce a `PrimitiveMobileList` with the primitives-only limitation?

**Comment by rockfordlhotka** [comment]
Anything that implemented `IMobileObject` continues to work - so `SmartDate` should be fine.

What stops working are arbitrary non-primitive, non-CSLA types.

**Comment by tfreitasleal** [comment]
I retract my previous statement. If `MobileList` can serialize CSLA objects, the breaking change isn't that big, unless someone was using it on non-CSLA projects.

In these circumstances I don't think we need a new type.
