### ISSUE TITLE
When using nullable parameter within BusinessObject marked Serializable, I'm getting CSLA0010 warning...

### ISSUE THREAD

**Issue by digitalsummit** [MarimerLLC/csla#831]
When using nullable parameter within BusinessObject marked as serializable, I get the following warning: Operation Argument types should be serializable.  I wasn't aware that I couldn't use a nullable parameter type when the class is marked as serializeable.

I can remove warning by adding the following to a global suppression file but would rather determine if I should just stay away from nullable parameters when dealing with seriablizeble classes...

System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CSLA0010:Find Operation Arguments That Are Not Serializable", Justification = "<Pending>", Scope = "member", Target = "~M:AssemblyTypeList.DataPortal_Fetch(System.Nullable{System.Int16})")]

I guess I can just use a custom criteria because that doesn't seem to have issues with nullable properties and pass that in as a parameter to my fetch methods.

**Comment by rockfordlhotka** [comment]
Thank you for opening this issue. 

In this case the issue is known, and a fix has become possible, though iirc the fix will updating the analyzers to netstandard and everyone using VS 2017.

https://github.com/MarimerLLC/csla/issues/623
