### ISSUE TITLE
Did you remove .netcore support in 4.7.100

### ISSUE THREAD

**Issue by realzhaorong** [MarimerLLC/csla#851]
It's said you add .netcore 2.0 & efcore 2.0 in 4.7.100 in release notes, but it was removed since 4.7.100-R18031402 in nuget package. what's wrong?

**Comment by rockfordlhotka** [comment]
From the release notes in 4.7.100:

Right now there are two "families" of CSLA .NET packages in NuGet. One that supports full .NET and one that supports all other runtimes.

The full .NET family must be used for the following types of app:
* Windows Forms
* WPF
* ASP.NET (other than Core)
* Console apps (other than Core)
* Azure Functions
* Any other runtime hosted by full .NET 4.6.1+

The netstandard family must be used for the following types of app:
* Xamrin
* UWP
* .NET Core
* ASP.NET Core
* Any other runtime _not_ hosted by full .NET 4.6.1+

What this means for you is that if your n-tier app is 100% full .NET or full netstandard then you can live within one of those families. BUT if your server is full .NET and your client is Xamarin (for example) then your _business library_ assemblies need to be compiled twice: once for full .NET and once for netstandard.

The `Samples\ProjectTracker` app shows how this is done by using a Shared Project to contain the code, and two concrete class library projects that compile the code for full .NET and netstandard respectively.
