### ISSUE TITLE
Create ProjectTracker ASP.NET Core app

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#852]

**Comment by rockfordlhotka** [comment]
My plan was to use the new Razor Pages model to create a web ProjectTracker UI. The underlying tech is MVC, but with (I think) a better level of abstraction than manually coding controllers over and over again.

The idea is to bind the view directly to the domain objects, using the existing NS2 business library project - it already supports all the other UI types, and shouldn't need alteration. This same business library supported the ASP.NET MVC UI a few versions back - I just haven't had time to recreate the web UI with modern ASP.NET.

**Comment by itgoran** [comment]
Thanks for info

**Comment by StefanOssendorf** [comment]
@rockfordlhotka isn't this already done or outdated?

**Comment by rockfordlhotka** [comment]
Given that I totally restarted ProjectTracker with only Blazor, I think this issue remains valid.
