### ISSUE TITLE
ProjectTracker broken

### ISSUE THREAD

**Issue by shawndewet** [MarimerLLC/csla#864]
I just downloaded a zip of the Code, and opened ProjectTracker solution in VS2017.
It builds and runs, but after entering login credentials, I get this error:

> Csla.DataPortalException: Could not load file or assembly 'Csla, Version=4.7.101.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>    at Csla.DataPortal`1.Fetch(Type objectType, Object criteria) in E:\src\rdl\csla\Source\Csla.Shared\DataPortalT.cs:line 472
>    at Csla.DataPortal`1.Fetch(Object criteria) in E:\src\rdl\csla\Source\Csla.Shared\DataPortalT.cs:line 457
>    at ProjectTracker.Library.Security.PTIdentity.GetPTIdentity(String username, String password) in D:\Learning\CSLA\csla-master\Samples\ProjectTracker\ProjectTracker.BusinessLibrary.Shared\Security\PTIdentity.cs:line 25
>    at ProjectTracker.Library.Security.PTPrincipal.Login(String username, String password) in D:\Learning\CSLA\csla-master\Samples\ProjectTracker\ProjectTracker.BusinessLibrary.Shared\Security\PTPrincipal.cs:line 33
>    at PTWin.LoginForm.OK_Click(Object sender, EventArgs e) in D:\Learning\CSLA\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\LoginForm.cs:line 23
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.PerformClick()
>    at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
>    at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
>    at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
>    at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
>    at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
>    at PTWin.MainForm.DoLogin() in D:\Learning\CSLA\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\MainForm.cs:line 330
>    at PTWin.MainForm.<MainForm_Load>d__4.MoveNext() in D:\Learning\CSLA\csla-master\Samples\ProjectTracker\ProjectTracker.Ui.WinForms\MainForm.cs:line 39
> ------------------------------
> System.IO.FileLoadException: Could not load file or assembly 'Csla, Version=4.7.101.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
>    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
>    at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
>    at System.Type.GetType(String typeName)
>    at Csla.Core.FieldManager.FieldDataManager.Csla.Serialization.Mobile.IMobileObject.SetState(SerializationInfo info) in C:\src\rdl\csla\Source\Csla.Shared\Core\FieldManager\FieldDataManager.cs:line 857
>    at Csla.Serialization.Mobile.MobileFormatter.DeserializeAsDTO(List`1 deserialized) in C:\src\rdl\csla\Source\Csla.Shared\Serialization\Mobile\MobileFormatter.cs:line 285
>    at Csla.Serialization.Mobile.MobileFormatter.Deserialize(Stream serializationStream) in C:\src\rdl\csla\Source\Csla.Shared\Serialization\Mobile\MobileFormatter.cs:line 232
>    at Csla.Serialization.Mobile.MobileFormatter.Deserialize(Byte[] data) in C:\src\rdl\csla\Source\Csla.Shared\Serialization\Mobile\MobileFormatter.cs:line 415
>    at Csla.Server.Hosts.Mobile.WcfPortal.<Fetch>d__1.MoveNext() in C:\src\rdl\csla\Source\Csla.Shared\Server\Hosts\Mobile\WcfPortal.cs:line 0

**Comment by shawndewet** [comment]
If I change the app.config file to use the localhost:11170 address for the CslaDataPortalUrl then the sample runs fine.
So I think it's just a case of the version deployed at http://ptrackerserver.azurewebsites.net has not yet been updated to the latest.

**Comment by tfreitasleal** [comment]
@shawndewet there is a version mismatch as you said. Have a look at [Gitter CslaForum](https://gitter.im/MarimerLLC/cslaforum). Rocky had to deploy 4.7.200 for testing purposes.
