### ISSUE TITLE
Version Tolerance for BusinessBases

### ISSUE THREAD

**Issue by BrettJaner** [MarimerLLC/csla#867]
Hey Rocky & Contributors,

I'm interested in getting a little bit of version tolerance with BusinessBases.  At my company, our slns' are getting too big and we are experimenting with publishing our Csla business layers to a private NuGet feed for our more completed/inactive projects.  Client applications will then consume from the NuGet feed.  For this to work in a robust fashion, we need some version tolerance between client and server.  Basically I'd like to deploy my DataPortal service before deploying my client when I'm only adding Properties to my BusinessBases.  It looks like the root of my restriction is in the FieldDataManager.cs, and how it indexes its array of FieldData.  Before I get too deep into solution mode, I'd like to get some other thoughts on the matter.  I appreciate your feedback.

Thanks,
Brett

**Comment by rockfordlhotka** [comment]
This would be better discussed on the forum at https://github.com/MarimerLLC/cslaforum
