### ISSUE TITLE
Dependency Injection in CSLA

### ISSUE THREAD

**Issue by Vin1206** [MarimerLLC/csla#871]
Hi, 

Please let me know whether the way i implemented the interface in CSLA is correct way.

 [Serializable]
    public class LineOfBusinessList : ReadOnlyListBase<LineOfBusinessList, LobInfo>, ILineOfBusiness
    {

        public static IRepository<ICD_LineOfBusiness> lobRepository { get; set; }
        public LineOfBusinessList(IRepository<ICD_LineOfBusiness> _lobRepository)
        {
            lobRepository = _lobRepository;

        }
       

        public LineOfBusinessList GetLineOfBusiness()
        {
            var returnValue = DataPortal.Fetch<LineOfBusinessList>();
            return returnValue;
        }

        

        private void DataPortal_Fetch()
        {
            var rlce = RaiseListChangedEvents;
            //RaiseListChangedEvents = false;
            List<LobInfo> response = new List<LobInfo>();
            IsReadOnly = false;
            var list = lobRepository.GetAll().Select(x => new LobInfo { LineOfBusinessId = x.LineOfBusinessId, LoBName = x.LoBName }).ToList();

            this.AddRange(list);
            // this.AddRange(list);
        }

     

        public LineOfBusinessList()
        {
            // this.AllowNew = true;
        }
    }
}

**Comment by rockfordlhotka** [comment]
Please direct this sort of question to the forum at https://github.com/marimerllc/cslaforum
