### ISSUE TITLE
CSLA ASP.NETCORE_MVC =>Unable to cast object of type 'Csla.Security.UnauthenticatedPrincipal' to type 'e2.SLM.Lib.Security.SLMPrincipal'

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#874]
CSLA ASP.NETCORE_MVC 4.7.100
CSLA Core NS 4.7.100

hi  I am getting above issue in asp.net core application
even Csla.ApplicationContext.User is there in asp.net Core application but server side i am getting above error

            LoginValidate = await e2.SLM.Lib.Security.SLMPrincipal.LoginAsync("info", "1475", appinfo.AppID);
            var CustomerBOSelected = await e2.BDM.Lib.Customer.GetCustomerAsync("110300000258");
//here  Customer Info is fetching but after this if i make any call to server like below it will fail 
    
            var InfoConsigne = await e2.BDM.Lib.Consignees.GetConsigneesAsync("110300000258");//failing

in previous release it was working fine.I was login only one time. now i need to login for every server call other wise above error i am getting.

**Comment by rockfordlhotka** [comment]
Please direct this sort of question to the forum at https://github.com/marimerllc/cslaforum
