### ISSUE TITLE
Implement WcfProxy for Xamarin

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#876]
Prior to the switch from native Xamarin support to .NET Standard 2.0, the WcfProxy type had stopped working in Xamarin. Originally my thought was to re-implement it after going to NS2, but it turns out that NS2 doesn't have WCF support.

More recently, my plan has been to create a separate Xamarin project/package for the WCF proxy code because it can't be included in CSLA-Core-NS. 

But perhaps the best answer is to put the WcfProxy type into the existing UI-specific projects/packages – so maybe in the Xamarin version of Csla.Xaml?

**Comment by tfreitasleal** [comment]
As far as I understand [.NET Core 2.0 supports WCF in client scenarios](https://github.com/dotnet/wcf/issues/2405).

Can you please give some more details about the issue or issues?

**Comment by alfredorevilla** [comment]
Hi @tfreitasleal, well CSLA NS or Xamarin does not expose a WcfProxy which is needed to connect to the portal.

**Comment by rockfordlhotka** [comment]
@tfreitasleal it is a little confusing right now, because the CSLA-Core package has `Csla.dll` that _does_ directly include the `WcfProxy` type.

In this new netstandard world that is no longer a good approach. Now the `WcfProxy` type _should_ be in the different platform (UI) support assemblies. So yes, the `Csla.Xaml` project for Xamarin is where `WcfProxy` should now be implemented.

Eventually (with any luck) the CSLA-Core package can completely go away - as soon as Microsoft fixes the bug in full .NET regarding the `OnDeserialized` attribute...

**Comment by rockfordlhotka** [comment]
From @alfredorevilla 

_Hi Rocky, got some progress here. Fixing some ns2 method not supported exceptions so the calls can (finally) be made to the MobileProxy. 

The thing is I'm initially compiling the ms wcf client lib as ns2 due that being the fastest route for me. Now I know you suggested to make the WCF client implementation specific to Xamarin in this:

>the CSLA-Core package has Csla.dll that does directly include the WcfProxy type.
>in this new netstandard world that is no longer a good approach.

Why is not a good approach to keep the WcfProxy in the CSLA Core? Because it belongs more to the client apps side? Maybe I can create a ns2 csla client library that can be referenced by xamarin? Finally what should be the criteria to follow to choose between porting ms wcf client library to ns2 or implementing it inside csla (ala system.componentmodel classes for platforms that did not supported it)._

**Comment by rockfordlhotka** [comment]
@alfredorevilla - so there's enough WCF support in ns2 to implement the proxy directly in `Csla.dll`?

In that case the simplest and best solution is to put `WcfProxy` directly into the ns2 `Csla.dll` - that is very nice!

**Comment by alfredorevilla** [comment]
@rockfordlhotka seems so, but still need more testing. now on the xamarin side i'm getting some errors, could be a thing of dll hell or... that xamarin being based on mono android (correct me if i'm wrong on any of the previous assumptions) choses its own system.servicemodel implementations which are not perfect.

**Comment by JacoJordaan** [comment]
Thanks Rocky, appreciate pointing me in the right direction.

**Comment by rockfordlhotka** [comment]
This is a redundant issue with #1183, so I'm closing it.
