### ISSUE TITLE
CSLAMVC project: CheckObjectRules warning

### ISSUE THREAD

**Issue by grahamblandford** [MarimerLLC/csla#889]
Any idea how I resolve this warning?:

![image](https://user-images.githubusercontent.com/28442774/40559827-09542daa-6026-11e8-88f7-c7bd39f8e338.png)

I don't seem to be able to override it, as it's protected?:
![image](https://user-images.githubusercontent.com/28442774/40559863-2cc903aa-6026-11e8-9244-4d84c6e48e2c.png)

Thanks!

**Comment by tfreitasleal** [comment]
Hi Graham,
I think this kind of questions should be asked in [CslaForum](https://github.com/MarimerLLC/cslaforum/issues)

**Comment by grahamblandford** [comment]
My apologies! Will do!
