### ISSUE TITLE
DataMapper should have a way to ignore metastate properties

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#902]
**Is your feature request related to a problem? Please describe.**
Right now it can be difficult to use `DataMapper` to copy values from a `BusinessBase` type to a DAL type, because it attempts to automatically copy the metastate properties. The result is that you need something like this:

```c#
DataMapper.Map(this, data, new string[] { "Parent", "BrokenRulesCollection", "IsValid", "IsSelfValid", "IsNew", "IsDirty", "IsDeleted", "IsSelfDirty", "IsBusy", "IsSelfBusy", "IsSavable", "IsChild" });
```

**Describe the solution you'd like**
There should be some simpler way to tell `DataMapper` to ignore metastate properties without having to manually list them.

**Comment by kcabral817** [comment]
Rocky,
I'm using AutoMapper by Jimmy Bogard to map to and from my DAL to CSLA.  It works pretty well and ignores the metastate information.  It might be something to consider.

**Comment by rockfordlhotka** [comment]
Closing due to lack of interest.
