### ISSUE TITLE
Property rule did not fire when changed via data binding

### ISSUE THREAD

**Issue by rodneyworkman291** [MarimerLLC/csla#920]
**Describe the bug**
We have a property rule that was tested and used to work but suddenly stopped working.  I loaded a debug version of CSLA to learn why the rule would not fire.  I found a unexpected condition in BusinessRules.CanRunRule().  In the CanRunRule method the variable canrun was set to false when evaluating (rule.RunMode & RunModes.DenyOnServerSidePortal).  This was unexpected since the value changed as part of a bound control.  The property was not changed in a DataPortal method.  Upon this discovery I set my property rule CanRunOnServer to true.  Now my rule fires when the value is updated via a bound control in a form.  

**Version and Platform**
CSLA version: 4.7.200
OS: Windows 10 Pro
Platform: WinForms, .net 4.6.2

**Code that Fails**
I do not have a shareable solution at this point but will see if I can create one in the near future. 

**Stack Trace or Exception Detail**
N/A

**Additional context**
When this rule was originally built and tested we were running 4.6.603

**Comment by rockfordlhotka** [comment]
@jonnybee is the expert in this area.

**Comment by jonnybee** [comment]
What is the value of rule.RunMode?  

It would appear as the BusinessObject believes it is on the server side of the data portal. 
Are you able to create a gist or sample that recreates the issue?

**Comment by rodneyworkman291** [comment]
I went back to 4.6.603 where it was not an issue for us.  I have not been back to 4.7 yet.  In the next couple of weeks I will try 4.7 again.  If it is still an issue I will have the time to submit a small sample project.

Thanks,

Rodney

**Comment by rodneyworkman291** [comment]
I did recently discover that our CslaPropertyChangedMode was not set for Windows.  I have since fixed that.  Would that have caused the issue I saw?

**Comment by rockfordlhotka** [comment]
That is very possible, yes. Data binding in WinForms expects different event handling from WPF, so if that value isn't set correctly the results could be unexpected.
