### ISSUE TITLE
Remove all old conditional symbols in the CSLA codebase

### ISSUE THREAD

**Issue by Troncho** [MarimerLLC/csla#923]
Throughout the codebase there are a lot of older compiler symbols. The only [current symbols](https://github.com/MarimerLLC/csla/blob/master/Support/CompilerDirectives.md) are

* NET40
* NET45
* NET46
* NETSTANDARD2_0

All the other symbols should be removed from the codebase. This must be done with care though, to preserve the behavior represented by the current symbols, while removing all the legacy/dead code wrapped by the other symbols.

**Comment by rockfordlhotka** [comment]
I have been slowly removing the old compiler directives from the code, and would love any help!

If you'd like to submit a pull request with the changes I would appreciate it!

**Comment by Troncho** [comment]
Sure Rocky, I'll generate a pull request. Glad to participate and help.

**Comment by rockfordlhotka** [comment]
This is slowly but surely happening as code gets updated for other issues, so I'm going to close this overarching issue.
