### ISSUE TITLE
Github organisation access

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#924]
Hello,
I am a member of the CSLA github org (due to past contributions), however I was recently setting up Team City integration at work for another GitHub org, and I noticed this:

![image](https://user-images.githubusercontent.com/3176632/44340187-f4cfec80-a47b-11e8-8b57-76f638bc0979.png)

i.e by default, when I authenticated with my github account, the application was granted full read and write access to the CSLA org's repositories too.

I am not comfortable about a tool being set up in a work capacity for my employer, being granted cart blanche access to CSLA repositories, so I thought I would stall for now and raise it. Is there anyway my membership could be tweaked such that, similar to the other organistations shown in the screenshot, this kind of access requires a "Request" to be granted / authorised by some CSLA repo admin?

**Comment by rockfordlhotka** [comment]
I don't think that's what this is saying.

I just double-checked, and you are in a group that has _Read_ access to the repo, nothing more. So I think you have access - but only read access.

**Comment by dazinator** [comment]
@rockfordlhotka ah ok, perhaps I was interpreting it wrong :-)

**Comment by rockfordlhotka** [comment]
I appreciate you checking!!
