### ISSUE TITLE
Create analyzer to flag use of new keyword

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#925]
Developers should not use the `new` keyword to create an instance of a business domain class. 

The only place the `new` keyword should be allowed is in a server-side factory class, where the factory is responsible for all creation and initialization of the domain object.

**Comment by JasonBock** [comment]
@rockfordlhotka, can you give some specifics about what "a server-side factory class" is? Need to make sure I get the context of calling `new()` correctly.

**Comment by rockfordlhotka** [comment]
A server-side factory class is when you create an `ObjectFactory` subclass to create a factory class that creates/initializes/updates/deletes the business object's data.

Inside an `ObjectFactory` subclass _you_ are responsible for creation of the business object instance in the create/fetch operations. The idea here is that you might use `new`, `Activator.CreateInstance`, or a DI framework to create that instance.

**Comment by JasonBock** [comment]
OK, that's doable.

This will be an analyzer with no code fix. Can't think of what I could offer to rectify the situation other than removing the constructor call, but that could lead to other problems. Seems like the best thing to do is to flag it and let the developer figure out what to do.
