### ISSUE TITLE
Update samples to Csla 4.8.1

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/csla#949]

**Comment by rockfordlhotka** [comment]
@tfreitasleal if you plan to do this, please hold off for a day or two, as I'm fixing a bug and plan to push 4.8.1 very soon.

**Comment by tfreitasleal** [comment]
I was almost done. But wil restart after 4.8.1

**Comment by rockfordlhotka** [comment]
Sorry about that!

**Comment by rockfordlhotka** [comment]
I'm pushing 4.8.1 to NuGet right now, so in 5 mins you should be able to redo the work. Sorry again!!!!
