### ISSUE TITLE
no suitable method found to override	-Execute(Csla.Rules.RuleContext context)

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#954]
**Describe the bug**

Customer.CheckDupicatePrimaryAddress.Execute(RuleContext)  no suitable method found to override	

protected override void Execute(Csla.Rules.RuleContext context)

above method available in Netstandard but not in Server Lib  .Net Framwork 4.7.1
**Version and Platform**
CSLA version: 4.8.1
OS: Windows 10
Platform: UWP,Xamrin

**Comment by rockfordlhotka** [comment]
In 4.8 the parameter for Execute changed to IRuleContext.

**Comment by SachinPNikam** [comment]
Thanks rocky  for early reply ..I will check with your suggestions. . Look like CSLA-Core-NS is still 4.7.200

**Comment by tfreitasleal** [comment]
Csla-Core-NS was discontinued under 4.8.x. Use Csla-Core instead.
[https://github.com/MarimerLLC/csla/issues/927](https://github.com/MarimerLLC/csla/issues/927)

**Comment by SachinPNikam** [comment]
Ohh okay ..!
