### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by ktngoykalolo** [MarimerLLC/csla#958]
Hello,
CSLA is one of the oldest and mature frameworks for .net. 
does it support multitenancy or can it be included ?

**Comment by itgoran** [comment]
@ktngoykalolo 
I'm using CSLA in all multitenancy projects already.
What would you like to see as multitenancy support?

**Comment by ktngoykalolo** [comment]
@itgoran that is nice. 
how does it work exactly with CSLA ?

**Comment by rockfordlhotka** [comment]
@ktngoykalolo the biggest feature for supporting multitenancy is that the rules engine supports a concept called _rule sets_, so each tenant can have its own rule set, allowing different business rules to be applied on a per-tenant basis.

Beyond that, CSLA recommends and is designed to work in a stateless server environment, providing isolation between users (and therefore between tenants).
