### ISSUE TITLE
Mark RelationshipTypes.Child as obsolete

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#963]
Mark `RelationshipTypes.Child` as obsolete, as it is not used by the framework any longer (confirm this first!).

This change would help avoid confusion such as in this thread: https://github.com/MarimerLLC/cslaforum/issues/650

**Comment by tfreitasleal** [comment]
I raised this question long long time ago, I think in the old forum and @jonnybee confirm it wasn't used. More recently I re-check the sources to make sure it's not used. Nevertheless, a re-re-check might be useful,

**Comment by fujiiface** [comment]
Isn't `RelationshipTypes.Child` part of the lazy loading property declaration?  I believe a lot of the recent examples I've seen reference this type of implementation.  Page 27 in the Using CSLA 4 Objects book also shows it.

**Comment by tfreitasleal** [comment]
[CslaGenFork](https://github.com/CslaGenFork/CslaGenFork) generates `RelationshipTypes.Child` just in case it would be used by CSLA sometime in the future. The fact is you just can't find it in CSLA source code.
