### ISSUE TITLE
Add fluent config types to CSLA

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#966]
It would be easier to configure CSLA if we had a set of fluent configuration types in `Csla.Configuration`, following the model of config types used in ASP.NET Core and other scenarios.

Something like
```c#
    Csla.Configuration.ConfigureCsla()
        .DefaultDataPortalProxy("proxyTypeName", "serverUrl")
        .Authentication("Windows")
        .SerializationFormatter("MobileFormatter")
```

**Comment by rockfordlhotka** [comment]
Also add an extension method for ASP.NET Core as per this doc.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1

**Comment by itgoran** [comment]
@rockfordlhotka 
Should CSLA have his own configuration section in the appsettings.json file for this and further configurations?

Example (just a few of them):

```
{
   "csla": {
      "proxyType":"name",
      "authentication":"windows",
      "serializationFormatter":"MobileFormatter"
    }
}
```

Beside fluent interface, existing configuration mechanism implemented in the .net core can be used.

**Comment by rockfordlhotka** [comment]
Yes, it should.

A couple versions ago I switched everything inside the framework to use `Csla.Configuration` instead of `System.Configuration` to decouple from the .NET Framework.

So if you are running on .NET Framework then you get the legacy behavior from app.config/web.config unchanged.

I didn't implement any of the new behaviors from .NET Core, as I didn't have time - but that should absolutely happen!

Not just for appsettings.json, but the higher level abstractions, because .NET Core's config subsystem is smart enough to pull from ENV variables or other locations common in cloud scenarios (where config files are a bad idea in general).

**Comment by rockfordlhotka** [comment]
@itgoran - interested in helping?

**Comment by itgoran** [comment]
@rockfordlhotka 
I would like to help.

**Comment by rockfordlhotka** [comment]
Need to add a few more unit tests.

**Comment by rockfordlhotka** [comment]
Need to clean up some of the method names, especially in the `CslaDataPortalConfiguration` type, as the names seem messy.

Also, the configuration sub-types for data/dataportal/security/serialization should be attached to the base config type by extension methods, not as explicit methods. Using extension methods allows other/future subareas of CSLA to add themselves to the fluent config API.
