### ISSUE TITLE
Read CSLA config values from .NET Core config subsystem

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#967]
CSLA should have its own configuration section in `appsettings.json` file for this and further configurations.

Example (just a few of them):
```
{
   "csla": {
      "proxyType":"name",
      "authentication":"windows",
      "serializationFormatter":"MobileFormatter"
    }
}
```
Beside [fluent interface](https://github.com/MarimerLLC/csla/issues/966), existing configuration mechanism implemented in .NET Core can be used to read from `appsettings.json` and other sources supported by .NET Core.

**Comment by rockfordlhotka** [comment]
My understanding is that the .NET Core config subsystem takes the names of your settings (like you have in the json @itgoran) and flattens them for use in ENV variables or other scenarios. I don't know the exact algorithm, but something like `csla-proxyType` I think.

They use a precedence scheme (I don't remember the specifics) so they'll read the value from the config file, ENV variables, and maybe other sources, and there are rules as to which values ultimately "win" - which overrides the others.

In the end, the code throughout CSLA itself uses `ConfigurationManager.AppSettings` to access all the values, using hard-coded config value names.

So it seems to me that what we need to do is load the values from the .NET Core config subsystem, then map those values into the pre-defined `AppSettings` dictionary for use by all the existing code.

That doesn't seem too difficult.

**Comment by rockfordlhotka** [comment]
I assembled a list of the settings keys:

CslaAuthentication
CslaAuthorizationProvider
CslaAutoCloneOnUpdate
CslaDataPortalActivator
CslaDataPortalExceptionInspector
CslaDataPortalInterceptor
CslaDataPortalProxy
CslaDataPortalProxyFactory
CslaDataPortalReturnObjectOnException
CslaDataPortalUrl
CslaDefaultTransactionIsolationLevel
CslaDefaultTransactionTimeoutInSeconds
CslaIsInRoleProvider
CslaMobileFactoryLoader
CslaObjectFactoryLoader
CslaPrincipalCacheSize
CslaPropertyChangedMode
CslaPropertyInfoFactory
CslaReader
CslaSerializationFormatter
CslaWriter
dbProvider

**Comment by itgoran** [comment]
Great @rockfordlhotka , I was doing exactly the same thing.
Do you agree with the idea to use json like syntax, without CSLA prefix, since it will be in csla section?
Example:
1. 
```
"csla": {
    "Authentication":"windows",
    "AuthorizationProvider":"...",
    "AutoCloneOnUpdate":"..."
}
```

or 
2. we should proceed with the same key names under "csla" section?

**Comment by itgoran** [comment]
Yes, it is.

Also, additional 'grouping' for 'PropertyChanged' and 'DefaultTransaction' can be performed.
1. Should we do this?

"csla": {
   "DefaultTransaction": {
        "IsolationLevel":"..."
        "TimeoutInSeconds":"..."
    },
    "Property": {
      "ChangedMode":"..",
      "InfoFactory":"..."
    }
}



2. Additionally, where a limited set of values can be applied (such as _SerializationFormatter_), should we log a warning and use the default value?

**Comment by rockfordlhotka** [comment]
Again, I'd like the fluent API and this json model to line up. Right now I've broken the fluent API into fairly coarse groups

![image](https://user-images.githubusercontent.com/2333134/48028622-924ccb00-e111-11e8-817b-648b00ba6847.png)

https://github.com/MarimerLLC/csla/tree/master/Source/Csla.Shared/Configuration

The groups are based on the subsystem of CSLA that uses/needs the config setting value.

**Comment by rockfordlhotka** [comment]
> Additionally, where a limited set of values can be applied (such as SerializationFormatter), should we log a warning and use the default value?

This is a good idea, though unfortunately some of the config values are overloaded in their meaning.

For example, `CslaSerializationFormatter` can be one of:

* BinaryFormatter
* MobileFormatter
* NetDataContractSerializer
* MyProject.MyFormatter, MyProject (assembly qualified type name)
