### ISSUE TITLE
Move System.Data.SqlClient reference out of CSLA core

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#981]
**Describe the bug**
Hello rocky,
I created sample App having issue Windows App Certification Kit-FAILED 
when i Used Csla 4.8.1 and 4.9.0 Pre Release.however same App if decrease the version of CSLA 4.6.603 Windows App Certification Kit-PASSED.
I attached sample App.
[App1.zip](https://github.com/MarimerLLC/csla/files/2573299/App1.zip)

[ValidationResult.zip](https://github.com/MarimerLLC/csla/files/2573306/ValidationResult.zip)

Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements. 

not sure but look like System.Data.SQLClient causing the issue which is referred in latest release  
https://github.com/dotnet/corefx/issues/26847

**Version and Platform**
CSLA version: 4.8.1
OS: Windows 10
Platform: UWP

**Comment by rockfordlhotka** [comment]
If it is the System.Data.SqlClient reference that's the issue, fixing it will require some breaking changes.

Specifically this would/will mean moving all the Csla.Data functionality into a separate assembly and NuGet package so it is only optionally brought into your solution when used.

For people who use Csla.Data (I suspect the majority) this will mean adding a new NuGet reference before their existing code will continue to build.

**Comment by SachinPNikam** [comment]
Thanks rocky
I will wait for update ..

**Comment by rockfordlhotka** [comment]
Here's what I'm doing with this change.

1. I'm only changing code in .NET Standard - so .NET Framework 4.0, 4.5, 4.6 should remain unchanged
1. I'm creating a new `Csla.Data.SqlClient.Fx` project that will contain `ConnectionManager` and a new `SafeSqlDataReader`
   1. The reason for the `.Fx` at the end is that Microsoft is working on a whole new SqlClient implementation and I want to ensure we can use that without name conflicts
   1. This will be in a new NuGet package, which will be required for anyone using `System.Data.SqlClient` types
1. `ConnectionManager` for NS2 will only exist in this new project/package (breaking change)
1. The old/existing `SafeDataReader` for NS2 will no longer contain any SQL Server specific types or members (breaking change)
1. The new `SafeSqlDataReader` for NS2 will extend `SafeDataReader` by adding SQL Server specific types and members
   1. This is really how these members should have been added the first time - I view this as an opportunity to clean up some tech debt
