### ISSUE TITLE
DataPortal Problem - Business Object Can't Find Data Layer class in Data Layer DLL

### ISSUE THREAD

**Issue by MarkOverstreet** [MarimerLLC/csla#996]

**Comment by MarkOverstreet** [comment]
Hi, we just did a WPF app using CSLA.NET 4.8.1 and have a small problem that I am assuming that someone familiar with this framework could answer pretty quickly.  

Our business classes are in one DLL (ex: BusinessLayer.DLL) and in the DataPortalXXX methods we reference data access classes in a different DLL (DataLayer.DLL).  The problem is when we run this app and login, all works correctly but as soon as we add the config entries to use the WCFproxy service, it crashes when you try to login and the error message indicates that it cannot find the data access class (i.e. the DataLayer.dll).  Yes, both DLLs are referenced by the wcf service project in the solution and are in the bin directory.

So my question is this:  Are there any known issues when using business objects in one DLL that reference another DLL when using serialization and the remote data portal?

Thanks for any help.

Mark

**Comment by rockfordlhotka** [comment]
Please direct this sort of support question to the forum at http://github.com/marimerllc/cslaforum
